### ISSUE TITLE
Migration documentation / migration tool (Add existing repos to Redmine)

### ISSUE THREAD

**Issue by micah** [jbox-web/redmine_git_hosting#141]
Hello,

I have a gitolite configuration and a redmine setup already. I've installed your great plugin and I'm now trying to figure out how I should migrate things, and it isn't clear to me how to:

 . associate existing repositories to existing projects
I can add the repository in the redmine configuration, but it seems like the redminegitolite.repositoryid needs to be set somehow, and I need to associate existing users with the repository.

 . associate existing gitolite keys to ones managed by redmine_git_hosting
I can go into gitolite and rename all the keys, for example 'foo.pub' -> 'redmine_foo.pub' so that they can be properly managed by the plugin, for the user 'foo', but perhaps that isn't the right thing to do?

 . I am sure there are other pieces I haven't yet discovered! Your documentation on the wiki here is very helpful, but maybe there should be a section for migrating things to make it more clear for people in my use case?

thanks!

**Comment by jamasi** [comment]
Coming from an older version of the redmine_git_plugin I also wonder about the migration path. Is there any update on this?

**Comment by n-rodriguez** [comment]
> Coming from an older version of the redmine_git_plugin I also wonder about the migration path.

Which version are you running?

**Comment by jamasi** [comment]
Before it was 0.6.2 but I've updated to 0.7.9 branch (+redmine 2.6.1 + sidekiq) now.

**Comment by n-rodriguez** [comment]
> Before it was 0.6.2 but I've updated to 0.7.9 branch (+redmine 2.6.1 + sidekiq) now.

Great! So what do you want to know?

**Comment by jamasi** [comment]
When running git push on a repository I also get this

   remote: Repository does not have 'redminegitolite.projectid' set, exiting...

How would I set/add the missing projectid attribute?

The config-test page lists everything as "green"
Git version 1.7.10.4
gitolite 2.3-1 (Debian)
sudo 1.8.5

**Comment by n-rodriguez** [comment]
Weird... This should not happen... Can you please open a new issue for this one with some logs from ```git_hosting.log``` file?

**Comment by gituser** [comment]
>How would I set/add the missing projectid attribute?

most likely redmine's new version of the hook wasn't installed properly for each repository.

check ~git/repositories/<repo>.git/hooks/post-receive symlink

it should point to post-receive -> /home/git/.gitolite/hooks/common/post-receive and contents of it is some ruby script.

**Comment by jamasi** [comment]
@gituser those links and the ruby script look OK. It looks like those variables are simply not set as 

    $ git config --get redminegitolite.projectid
    
    $ git config --get core.bare
    true

inside the repository returns nothing.

I'll open a new issue on this.

**Comment by gjroelofs** [comment]
> You can do that by setting ':gitolite_redmine_storage_dir' in plugin settings to something like 'redmine'. This will create a subdirectory 'redmine' in Gitolite and move Redmine repositories into it. This will prevent conflicts as described above.

As a check; does this imply that migration pre-existing git repositories in Redmine is supported?
So not gitolite git repo's; just simple git repo's.

If so, how does one trigger this migration?

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
