### ISSUE TITLE
Redmine database not updated after a commit

### ISSUE THREAD

**Issue by sdinot** [jbox-web/redmine_git_hosting#209]
I recently installed Redmine (2.5.1) and the Redmine Git Hosting plugin (0.7.2) on a Debian testing system, using three different accounts for Apache (www-data), Redmine (redmine) and Gitolite (git) and RVM to manage Ruby environments.

I can create an empty repository through the Redmine interface; this repository is immediately created and added in the Gitolite configuration. I can clone this repository on my PC. I can push a couple of changes on the remote repository managed by Gitolite and after this, clone this remote repository elsewhere : my changes appear on the last clone.

But these changes never appear in the Redmine interface. The repository page always displays the message "Repository is empty. Get started by following the instructions below." followed by the setup instructions.

The following informations are displayed (with a green background) in the "Config Test" tab of the Redmine Git Hosting administration interface:

```
*Required Permissions*
Scripts directory writeable?    /opt/redmine/redmine-2.5.1/plugins/redmine_git_hosting/bin/
Temp directory writeable?       /opt/redmine/tmp/redmine_git_hosting/git/
Script for Gitolite Admin command installed?    /opt/redmine/redmine-2.5.1/plugins/redmine_git_hosting/bin/gitolite_admin_ssh
Script for Git command installed?       /opt/redmine/redmine-2.5.1/plugins/redmine_git_hosting/bin/run_git_cmd_as_gitolite_user
Script for Shell command installed?     /opt/redmine/redmine-2.5.1/plugins/redmine_git_hosting/bin/run_shell_cmd_as_gitolite_user
Redmine username        redmine
Gitolite username       git
Sudo version    1.8.9
Git user is able to sudo to Redmine user?       True
Redmine user is able to sudo to Git user?       True
Hooks parameters installed?     True redmineurl
                                True debugmode
                                True asyncmode
Hooks installed?                True post-receive.d
                                True post-receive.redmine_gitolite.rb
                                True post-receive.git_multimail.py
                                True post-receive.mail_notifications.py
Mirrors keys installed?         True
Git version     2.0.0
Gitolite version        2

*Gitolite banner*
hello admin, this is gitolite 2.3-1 (Debian) running on git 2.0.0.rc2

the gitolite config gives you the following access:
    #R  #W      @all
    &R_ &W_     testing
    #R_ #W_     zoinx-release
    #R_ #W_     zoinx/zoinx-homepage

*PATH directories*
/opt/redmine/.rvm/gems/ruby-2.0.0-p481/bin
/opt/redmine/.rvm/gems/ruby-2.0.0-p481@global/bin
/opt/redmine/.rvm/rubies/ruby-2.0.0-p481/bin
/usr/local/bin
/usr/bin
/bin
/usr/local/games
/usr/games
/opt/redmine/.rvm/bin
```

After the push, the following messages appear in the Gitolite log:

```
2014-06-02.21:50:04     redmine_sdinot  AA.AA.AA.AA  git-receive-pack '/zoinx/zoinx-homepage.git'
2014-06-02.21:50:04     redmine_sdinot  AA.AA.AA.AA  git-receive-pack '/zoinx/zoinx-homepage.git'    W       00000000000000  f580edac885c13  zoinx/zoinx-homepage    refs/heads/master       refs/.*
```

and the following messages appear in the Redmine Git Hosting plugin log:

```
2014-06-02 21:51:54 +0200 DEBUG [GitHosting] Lookup for git_cache_id with repository path 'repositories/zoinx/zoinx-homepage.git' ... 
2014-06-02 21:51:54 +0200 DEBUG [GitHosting] Found git_cache_id ('zoinx/zoinx-homepage'), call cache... 
2014-06-02 21:51:54 +0200 DEBUG [GitHosting] Send GitCommand : '/opt/redmine/redmine-2.5.1/plugins/redmine_git_hosting/bin/run_git_cmd_as_gitolite_user' '--git-dir' 'repositories/zoinx/zoinx-homepage.git' '-c' 'core.quotepath=false' '-c'
 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2014-06-02 21:51:54 +0200 DEBUG [GitCache] Probing cache entry
2014-06-02 21:51:54 +0200 DEBUG [GitCache] '/opt/redmine/redmine-2.5.1/plugins/redmine_git_hosting/bin/run_git_cmd_as_gitolite_user' '--git-dir' 'repositories/zoinx/zoinx-homepage.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2014-06-02 21:52:01 +0200 DEBUG [GitHosting] Lookup for git_cache_id with repository path 'repositories/zoinx/zoinx-homepage.git' ... 
2014-06-02 21:52:01 +0200 DEBUG [GitHosting] Found git_cache_id ('zoinx/zoinx-homepage'), call cache... 
2014-06-02 21:52:01 +0200 DEBUG [GitHosting] Send GitCommand : '/opt/redmine/redmine-2.5.1/plugins/redmine_git_hosting/bin/run_git_cmd_as_gitolite_user' '--git-dir' 'repositories/zoinx/zoinx-homepage.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2014-06-02 21:52:01 +0200 DEBUG [GitCache] Probing cache entry
2014-06-02 21:52:01 +0200 DEBUG [GitCache] '/opt/redmine/redmine-2.5.1/plugins/redmine_git_hosting/bin/run_git_cmd_as_gitolite_user' '--git-dir' 'repositories/zoinx/zoinx-homepage.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
```

Did I forget or miss anything?

**Comment by nicholasruunu** [comment]
I have the same issue but I don't think it's RVM, it works without cache enabled.

Or does the git user also need some RVM setup?

**Comment by n-rodriguez** [comment]
> Or does the git user also need some RVM setup?

Nope, but you need to install Ruby globally with ```apt-get install ruby``` (http://redmine-git-hosting.io/get_started/#step-8-install-ruby-interpreter-for-post-receive-hook)

**Comment by OliverWieland** [comment]
I have the same issue here. Ruby is installed and I'm pretty sure that this worked for me a few weeks ago.
Since this I only installed the typical trusty-updates, but no redmine-update.
Where I have to look for the problem?

**Comment by OliverWieland** [comment]
An upgrade of the plugin to 1.0.4 and executing the hint on 
http://redmine-git-hosting.io/troubleshooting/#my-repository-seems-empty-but-im-sure-it-is-not
worked for me.

**Comment by nicholasruunu** [comment]
@n-rodriguez Had to upgrade ruby 1.9 but works, thank you.

**Comment by OliverWieland** [comment]
The issue is still there. I tought it would work now, but it seems that the repository were update only once.
I made a new commit and pushed it to the repository, but I don't see the changes in redmine.
The mailing list is enabled and I got a mail about the new commit, so there is definitvely a hook that works...
The manual execution of
  bundle exec rake redmine_git_hosting:fetch_changesets RAILS_ENV=production
works, and after that I can see the changes.

**Comment by nicholasruunu** [comment]
@OliverWieland Does it work without cache enabled? Because I seem to have problems getting that to work after upgrade, haven't tested after I upgraded ruby though.

**Comment by OliverWieland** [comment]
@nicholasruunu Which cache I have to disable and where?

**Comment by nicholasruunu** [comment]
![screen shot 2015-05-21 at 13 14 18](https://cloud.githubusercontent.com/assets/483658/7747514/5c3c1e34-ffbb-11e4-84b0-bbc340ccdc11.png)

**Comment by nicholasruunu** [comment]
Upgrading systems ruby version to 1.9.3 did fix the cache issue for me though, just confirmed.

**Comment by OliverWieland** [comment]
Since I disabled the cache the last changes are visible

**Comment by OliverWieland** [comment]
BTW, my ruby version is 
1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

**Comment by nicholasruunu** [comment]
On the git user too? `sudo su git && ruby --version`

**Comment by OliverWieland** [comment]
redmine@tbsw-bugtracker:~$ ruby --version
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

**Comment by nicholasruunu** [comment]
You run Gitolite and Redmine on the user redmine?

**Comment by OliverWieland** [comment]
sry, wrong user...
git@tbsw-bugtracker:~$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

**Comment by nicholasruunu** [comment]
Strange, then I don't know. Assuming you don't get a hook error when pushing?

**Comment by OliverWieland** [comment]
No, there isn't a hook error

**Comment by nicholasruunu** [comment]
Then it's different issue than I had I'm afraid.

**Comment by OliverWieland** [comment]
Thanks for your help nevertheless.
I switched off the cache for now.

**Comment by nicholasruunu** [comment]
You could try pressing Install hooks in the upper right corner.
It's a bit hidden.

![screen shot 2015-05-21 at 13 41 14](https://cloud.githubusercontent.com/assets/483658/7747864/1f14c6f6-ffbf-11e4-8085-23ff05aa2157.png)

**Comment by OliverWieland** [comment]
They are all installed.

**Comment by cinco** [comment]
i have same issue on redmine 3 with redmine git hosting 1.1.1 and ruby 2.1.2p95 for users git and redmine. I run redmine over nginx and puma.

apparently everything seems to be working, but does not appear the hook messages when I push to repo.

In addition, the repository in redmine interface is not updated after each commit. I could only see the changes after disabling the cache as indicated in this thread.
