### ISSUE TITLE
Predictable gitolite usernames

### ISSUE THREAD

**Issue by castedmo** [jbox-web/redmine_git_hosting#22]
Is is possible to have predictable (and probably friendly) users in gitolite being generated by this plugin? This will be useful for scenarios in which this plugin should be bypassed (Like user created repos in gitolite. )

**Comment by xSmurf** [comment]
Is there currently a fix for this? I'm looking to precisely what @rchady was doing.

**Comment by n-rodriguez** [comment]
@xSmurf  yes : use a separate Gitolite config file for Redmine and set it in plugin settings.

**Comment by xSmurf** [comment]
@n-rodriguez that still has the `_\d` suffix.

**Comment by n-rodriguez** [comment]
@xSmurf : can you be more specific?

**Comment by xSmurf** [comment]
After I changed the gitolite config file and removed the `redmine_` preffix, add a key to a user ends up as username_123, where 123 is the redmine user id. I fully understand the potential conflicts with removing this suffix as explained in this thread and would still like this behavior to be configurable.
