### ISSUE TITLE
Force push only when "manage repository" permission?

### ISSUE THREAD

**Issue by hameno** [jbox-web/redmine_git_hosting#264]
Hello,
I just recently upgraded to 0.7.6 and now users can't force push to their feature branches when they don't have the manage repository permission. How can I disable this? We need to be able to force push our rebased feature branches and not every developer should be able to manage the repository.

Please advise

**Comment by tchemineau** [comment]
Hi all,

I tried to install the v0.8-beta branch.

My first try return an error which indicates that the task `redmine_git_hosting:fix_migration_numbers` was not found. After reading again this thread, I checked out the devel branch and installed missing gem.

From the root redmine directory, I then tried again the command :

```
$ bundle exec rake --trace redmine_git_hosting:fix_migration_numbers RAILS_ENV=production
Your Gemfile lists the gem inifile (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem database_cleaner (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem redcarpet (~> 2.3.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem shoulda (~> 3.5.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem database_cleaner (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
rake aborted!
Don't know how to build task 'redmine_git_hosting:fix_migration_numbers'
```

What are the steps to migrate ot this devel branch ?

Thank you !

**Comment by tchemineau** [comment]
OK, I get it. I should use `redmine_git_hosting:migration_tools:fix_migration_numbers` task.

**Comment by tchemineau** [comment]
As said @hameno, this task failed the first time and succeed the second time. However, I verified into the database and all migration numbers have been correctly migrated.

Then, I checked out the v0.8-beta branch, and proceed to the plugin migration and all work has expected. I will see if new functionnalities work as expected.

**Comment by tchemineau** [comment]
Hi all,

@n-rodriguez, is your fix https://github.com/jbox-web/redmine_git_hosting/commit/9b13720146f3f61c29884ad5f73e29fe18576d2a on v0.8-branch ?

I have the same error as described by @hameno with a `ActionView::Template::Error (can't convert nil into String)` error.

**Comment by n-rodriguez** [comment]
> @n-rodriguez, is your fix 9b13720 on v0.8-branch ?

yes

> I have the same error as described by @hameno with a ActionView::Template::Error (can't convert nil into String) error.

this might come from other place

By the way, the v0.8 branch has been dropped in favor of v1.0.0-beta.
You should be able to switch to it when it will be released.

**Comment by hameno** [comment]
So, I tried to update my beta installation, saw that the branch no longer exists and switched to v1.0.0-beta. But now I cannot edit any repository, it just shows the standard settings but no settings from this plugin. I also tried the latest devel branch but it did not change anything.

My installation:

Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.2.2
  Git                            1.7.10.4
  Filesystem                     
  Xitolite                       1.7.10.4
Redmine plugins:
  redmine_bootstrap_kit          0.1
  redmine_git_hosting            0.8-devel

**Comment by hameno** [comment]
Ahhh, I just notices that there is now a "Xitolite" Repository-Type. Just created a new Repository with that and there are the settings. Did I forget a migration task?

**Comment by n-rodriguez** [comment]
> Did I forget a migration task?

Nope, it's my fault, I didn't write it yet... But it should be simple : if you can connect to Redmine database update the ```repositories``` table and change the ```type``` field to ```Repository::Xitolite```.

**Comment by hameno** [comment]
Yep, worked. Looks good now.

**Comment by n-rodriguez** [comment]
Great! You can take a look at the [changelog](https://jbox-web.github.io/redmine_git_hosting/about/releases-notes/) There might be other interesting features for you.

**Comment by hameno** [comment]
Ahh so a release date is already planned, thats nice ;)

Really great work! :+1:

**Comment by n-rodriguez** [comment]
https://jbox-web.github.io/redmine_git_hosting/howtos/migrate/#step-by-step-migration-from-0710-version-to-v100

**Comment by hameno** [comment]
Great, now all we need is https://github.com/jbox-web/redmine_git_hosting/issues/264#issuecomment-67736424

**Comment by n-rodriguez** [comment]
The regression has been fixed by the Protected branch feature.
But this one needs to be improved. To be continued here : https://github.com/jbox-web/redmine_git_hosting/issues/389
