### ISSUE TITLE
Change the Git timeout in the Global pane of the plugin settings

### ISSUE THREAD

**Issue by raphaelkong** [jbox-web/redmine_git_hosting#274]
Hi !
I've been working on a redmine-githosting migration from redmine 1.2 to redmine 2.5 ; The plugin version used is 0.7.7.
I have a huge repo from my old server that I push to the new server.  In debug mode, the hook display this message : 

```
remote: Notifying Redmine about changes to this repository : 'xxxx' ...
remote: Redmine URL : 'http://server.fqdn.name/githooks/post-receive/redmine/xxxx'
remote: HTTP_ERROR : Timeout::Error
remote: Error contacting Redmine about changes to this repo.
```

I guess it is related to the git timeout in the global pane. But when I change it to something bigger, the value "comes back" to 10. In redmine, everything seem to be in order ...

For my personnal knowledge, what kind of notifying is done at this level ?

**Comment by hameno** [comment]
I'm having the same problem now on 1.2.1 (previously 1.1.2). We cannot switch to async mode as we need be sure that the git mirror has been updated once the push is done (needed for reviewboard).
What changed since 1.1.2 that broke this?
Should I simply increase the timeout? (If yes: how?)

**Comment by bellatriks** [comment]
> I'm having the same problem now on 1.2.1 (previously 1.1.2). We cannot switch to async mode as we need be sure that the git mirror has been updated once the push is done (needed for reviewboard).
> What changed since 1.1.2 that broke this?
> Should I simply increase the timeout? (If yes: how?)

In order to get rid of HTTP_ERROR : Net::ReadTimeout error, just add a read_timeout in http request ->

--- a/lib/redmine_git_hosting/utils/http.rb
+++ b/lib/redmine_git_hosting/utils/http.rb
@@ -61,6 +61,7 @@ module RedmineGitHosting
         def build_http_request(url)
           uri  = URI(url)
           http = Net::HTTP.new(uri.host, uri.port)
+          http.read_timeout = 50000 # in seconds
           if uri.scheme == 'https'
             http.use_ssl = true
             http.verify_mode = OpenSSL::SSL::VERIFY_NONE
