### ISSUE TITLE
Repository urls change / inconsistent

### ISSUE THREAD

**Issue by oliwel** [jbox-web/redmine_git_hosting#287]
I updated from redmine 1.4, so this might be a migration issue?

Problem: After renaming/moving a project, the external git url and the internal repository no longer match. Even more weird, the name in the "url" column of the repository database is correct, but the url shown in the UI and the url written to the gitolite.conf is always recreated from the current values of the projects path. The filesystem path of the repository also gets screwed, the archive view still shows the old one while all git updates go to the new one.

Example:
* I startet a project as "Root Project", so it became hostname/projectname.git as repository.
* I created a new Main Project "Acme Inc" and moved the project below
* The visible Url (in tho copy&paste boxes) is now hostname/acme/projectname.git which is also what is used by all git operations from external
* The repository view in the UI shows still the data from the old repo

Note: I set up hierarchical mode, going back to flat mode will not cure the problem as it affects ALL urls and I already have repos that have subfolder structure.

**Comment by oliwel** [comment]
This is v0.8-beta - had to use this as 0.7 was not installing due to the mime-type problem (see #282)

**Comment by n-rodriguez** [comment]
https://jbox-web.github.io/redmine_git_hosting/howtos/migrate/#step-by-step-migration-from-0710-version-to-v100

**Comment by dgeo** [comment]
Here, after migration from 0.7.10 to 1.0.0, some url's changed (mainly sub-projects's main repos went from repository/mainproject/subrepo.git to repository/mainproject/subproject/subrepo.git).
I moved them manually in gitolite to the new location (overwriting the empty new .git), removed now useless entries in gitolite.conf, corrected the db (repositories.%url), and informed our users of the change.
IMHO, some url's had to change, but I still think that the plugin should use database's URLs blindly instead of computing them (to not break git access after a project 'move' for example).
PS: using hierarchical mode
Thanks a lot for the good work !

**Comment by oliwel** [comment]
Tried a migration of my live system (runs 0.8-beta) to v1.0. The migration script runs smooth but afterwards the Repo-List is fully broken and shows a 500 error. The log complains about "missing repositories" and nil values....

**Comment by Akasch** [comment]
I also have this Problem. The migration went smoth, but the paths to the repos changed in some places, with the effect that npbody can access annything: the new urepourls dosn't apear on the gitolite. in the gitolite config the old repos with the old keynames remain. 

The repo-Admin inteface says the repo dos not exists. If i click save the log says:

    2015-02-09 10:13:29 +0100 [INFO] User '10rokita' has modified repository 'robocup/robocup-darwin/code'
    2015-02-09 10:13:29 +0100 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/gitolite/gitolite-admin.git'
    2015-02-09 10:13:29 +0100 [WARN] update_repository : repository 'robocup/robocup-darwin/code' does not exist in Gitolite, exit !
    2015-02-09 10:13:29 +0100 [INFO] update_repository : commiting to Gitolite...
    2015-02-09 10:13:30 +0100 [INFO] Execute Gitolite Plugins

the repo was at robocup/code.

I would prefer to not change the repo paths, if they change i will have problems with some of my users.

**Comment by n-rodriguez** [comment]
> I would prefer to not change the repo paths, if they change i will have problems with some of my users.

I understand, but there is no magic. If you don't update urls I won't do it for you.

**Comment by Akasch** [comment]
A warning in the migrate guide that the paths change and that you have to do it manually in the database would be good

**Comment by n-rodriguez** [comment]
> A warning in the migrate guide that the paths change and that you have to do it manually in the database would be good

I can do that.

**Comment by Akasch** [comment]
It seems that the paths in the gitolite config have to be adjusted by hand to

**Comment by n-rodriguez** [comment]
Doc updated : https://jbox-web.github.io/redmine_git_hosting/howtos/migrate/
