### ISSUE TITLE
redmine_git_hosting conflicts with redmine_scm_creator plugin

### ISSUE THREAD

**Issue by overmind88** [jbox-web/redmine_git_hosting#310]
Hi! I use redmine with git on same host and now i need move outer svn-server on this host.
I was going to use SCM creator plugin (http://projects.andriylesyuk.com/project/redmine/scm-creator) to create svn repos if it was needed.
So I installed it, but when i try to create svn repo on test project I get error:

<pre>
Started GET "/devredmine/projects/svntest/repositories/new" for 10.10.3.1 at 2014-11-12 20:10:25 +0400
Processing by RepositoriesController#new as HTML
  Parameters: {"project_id"=>"svntest"}
  Current user: admin (id=1)
  Rendered plugins/redmine_scm/app/views/repositories/_form.html.erb (74.6ms)
  Rendered repositories/new.html.erb within layouts/base (84.1ms)
Completed 500 Internal Server Error in 141.4ms

ActionView::Template::Error (undefined local variable or method `limit_exceeded' for #<#<Class:0x000000084528d0>:0x00000008451728>):
    21: <% button_disabled = true %>
    22: <% if @repository %>
    23:   <%  button_disabled = ! @repository.class.scm_available %>
    24:   <%= repository_field_tags(f, @repository) %>
    25: <% end %>
    26: </div>
    27: 
  app/helpers/repositories_helper.rb:126:in `repository_field_tags'
  app/views/repositories/new.html.erb:4:in `block in _app_views_repositories_new_html_erb__1582324803988057897_69389480'
  app/helpers/application_helper.rb:1043:in `labelled_form_for'
  app/views/repositories/new.html.erb:3:in `_app_views_repositories_new_html_erb__1582324803988057897_69389480'
</pre> 

I found bugreport on SCM creator project page: http://projects.andriylesyuk.com/issues/2326 ( btw there is link which can help http://aeturnalus.com/software/hacking-scm-creator-redmine-git-hosting-cooperate/ ) but author doesnt answer on it.

I understand that it is possible not your bug, but maybe you can do some workaround?

Thanks in advance!

Info about my environment:

Ubuntu 12.04, rails starts with nginx+passenger

Redmine info:

<pre>
Environment:
  Redmine version                2.5.2.stable
  Ruby version                   2.1.1-p76 (2014-02-24) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  once_assigned_ever_watcher     0.1.0
  redmine_bootstrap_kit          0.1
  redmine_code_review            0.6.3
  redmine_git_hosting            0.7.8
  redmine_plugin_views_revisions 0.0.1
  redmine_scm                    0.5.0b
  redmine_wiki_gchart_formula    0.0.5
</pre>

**Comment by l337r007** [comment]
Sorry to post on a closed bug, but I'm running into issues with `redmine_scm` right now.
Since you deleted your patch repository and Andriy hasn't followed up on the bug, what would be your suggested route?

**Comment by n-rodriguez** [comment]
> Since you deleted your patch repository and Andriy hasn't followed up on the bug, what would be your suggested route?

To contact redmine_scm developer. Sorry.
