### ISSUE TITLE
diff is incomplete

### ISSUE THREAD

**Issue by gituser** [jbox-web/redmine_git_hosting#312]
Hi

I'm using 
```
Environment:
  Redmine version                2.5.2.stable.13421
  Ruby version                   2.0.0-p576 (2014-09-19) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.12
  Mercurial                      1.6.4
  Git                            1.7.2.5
  Filesystem                     
Redmine plugins:
  redmine_auto_percent           0.0.1
  redmine_bootstrap_kit          0.1
  redmine_git_hosting            0.7.7
  redmine_information            1.0.2
  redmine_lightbox               0.0.1
  redmine_pastebin               0.2.0
```

and there is a problem in exporting unified diffs, if diff is more than 65 535 bytes it gets cut to 65 535 bytes for some reason.

I do not have any limit on nginx/unicorn, so what could be an issue?

**Comment by n-rodriguez** [comment]
Hi there!
Can you please provide a way to reproduce this bug?

**Comment by gituser** [comment]
>Hi there!
>Can you please provide a way to reproduce this bug?

Very simple:

just try to download a diff larger than 65K bytes in the unified diff format.

1) go to repository
2) select two revisions
3) click on the 'show differences' button
4) at the end of the page there should be 'this diff is limited ... ' and link to export to unified diff format
5) click it and check file size it will be 65535 if diff is more than 65535 bytes.

**Comment by n-rodriguez** [comment]
```
TINYBLOB, TINYTEXT       L + 1 bytes, where L < 2^8    (255 Bytes)
BLOB, TEXT               L + 2 bytes, where L < 2^16   (64 Kilobytes)
MEDIUMBLOB, MEDIUMTEXT   L + 3 bytes, where L < 2^24   (16 Megabytes)
LONGBLOB, LONGTEXT       L + 4 bytes, where L < 2^32   (4 Gigabytes)
```

**Comment by n-rodriguez** [comment]
I've done some tests with v1.0 and it works :
```
-rw-r--r--  1 nicolas nicolas  82K 21 janv. 04:29 test.diff
```

**Comment by gituser** [comment]
it's rather a workaround than the actual fix, don't you think so?
so the only way to fix this is to disable cache completely?

what's the point in cache if I download unified diff file?

**Comment by n-rodriguez** [comment]
> it's rather a workaround than the actual fix, don't you think so?

Yes and no...

> what if i need to download 32mb diff..

You could increase the field size up to 4Go...

> so the only way to fix this is to disable cache completely?

Yes

> what's the point in cache if I download unified diff file?

actually the cache system doesn't know if you're going to download the diff or just display it in your browser...

**Comment by n-rodriguez** [comment]
> so the only way to fix this is to disable cache completely?

I could also monkey patch RepositoryController to override the ```diff``` method to add a flag do the ```repository.diff``` method to bypass the cache...

**Comment by gituser** [comment]
interesting.
well, i'm always up for a proper fix and i'm sure all other users would appreciate more cleaner solution :)

**Comment by n-rodriguez** [comment]
> well, i'm always up for a proper fix and i'm sure all other users would appreciate more cleaner solution :)

I agree with you. This will be done for the v1.0.0 version.

**Comment by n-rodriguez** [comment]
Erf... that will make a lot of monkey patch...
