### ISSUE TITLE
Unable to flag repository as Main

### ISSUE THREAD

**Issue by DProvorse** [jbox-web/redmine_git_hosting#324]
Found a weird one that I haven't been able to get past yet. Did a complete migration of all of our repositories from SVN to Git with this plugin. Originally the SVN was flagged as the Main so we created an additional repo on every project that is Git. After migrating all of our old commits and history using svn2git we then deleted the original SVN repo. When we go back in to the Git repo when it is the only repo in the project now the option to set as Main is there however it's greyed out and can't be changed.

Any thoughts?

![gitbug](https://cloud.githubusercontent.com/assets/3341157/5699269/3f0faee6-99d8-11e4-8244-8f27ce3ec2f2.jpg)

**Comment by n-rodriguez** [comment]
Hi! Thanks for your feedback!
Actually it's a known bug.It has been fixed in v1.0.
