### ISSUE TITLE
Make sure git repositories have their redminegitolite.xyz attributes set.

### ISSUE THREAD

**Issue by jamasi** [jbox-web/redmine_git_hosting#328]
When running git push on a repository I get this

    remote: Repository does not have 'redminegitolite.projectid' set, exiting...

The config-test page lists everything as "green"
Git version 1.7.10.4
gitolite 2.3-1 (Debian)
sudo 1.8.5
I'm on 0.7.10 of redmine_git_hosting
As I had some trouble with getting sidekiq to actually process the workqueue at first this might be the root of this.

`git_hosting.log` does not have any suspicious entry on this.

**Comment by n-rodriguez** [comment]
can you check the ```gitolite.conf``` file?

You should have something like that :

```
repo    blabla
  RW+                            = redmine_admin_1
  R                              = gitweb
  config redminegitolite.projectid = blabla
  config redminegitolite.repositoryid = 
  config redminegitolite.repositorykey = 9ER5FA27ALAwqlyEJ472aPnuVxsPdP2Fgd8KGdK6dsrXxH6HuzsU53UUWRH1dBm
  config http.uploadpack = true
  config http.receivepack = true
  config multimailhook.enabled = false
```

**Comment by n-rodriguez** [comment]
also can you test without Sidekiq?

**Comment by jamasi** [comment]
The entries of the repositories in `.gitolite/conf/gitolite.conf` are in the form like above.
But is it normal that /home/git/projects.list is an empty file?

Turning off sidekiq does not alter the behaviour, as the error is thrown by the post-commit hook script (run by gitolite) that cannot get the projectid as it seems.

**Comment by n-rodriguez** [comment]
> But is it normal that /home/git/projects.list is an empty file?

Yes. It only contains public projects with Gitweb enabled (if I remember well)

**Comment by n-rodriguez** [comment]
> Turning off sidekiq does not alter the behaviour, as the error is thrown by the post-commit hook script (run by gitolite) that cannot get the projectid as it seems.

Sorry. Turn off Sidekiq and do a "project resync" in *Rescue* tab.

It should update ```gitolite.conf``` file in ```<gitolite_tmp_dir>/redmine_git_hosting/git/gitolite-admin.git/conf``` dir. Then check in the file that you have such entry for your repo :
```redminegitolite.projectid = <your project name>```

**Comment by jamasi** [comment]
That file exists and looks good. I found a `<gitolite_tmp_dir>/redmine_git_hosting/git/gitolite-admin/` directory as well (most likely from an older version?) but removing it did not help either.

**Comment by n-rodriguez** [comment]
> So those values seem to be prefixed with hooks. is this the problem?

Yes :

```
git@dev:~/repositories/test.git$ git config -l
color.ui=true
redminegitolite.redmineurl=http://redmine2.jbox-web.fr/githooks/post-receive/redmine
redminegitolite.debugmode=false
redminegitolite.asyncmode=false
multimailhook.mailer=smtp
multimailhook.environment=gitolite
multimailhook.smtpauth=false
multimailhook.smtpserver=localhost
multimailhook.smtpport=25
core.repositoryformatversion=0
core.filemode=true
core.bare=true
http.receivepack=true
http.uploadpack=true
redminegitolite.repositorykey=800yYSqZ7dIdMPEGbSGSNiYIJg3NkoNqA79HgtnTNrdolWhH00BG92OyNyLz6Zn
redminegitolite.projectid=test
multimailhook.enabled=false
```

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/redmine_git_hosting/commit/3b157a030c8ae2f11dbee96d34d3ad4d6e17148a#diff-9de730fc398a8d4ca749a9b1fe9cd8c5L154

**Comment by n-rodriguez** [comment]
Enable ```:gitolite_force_hooks_update``` in *Administration -> Redmine Git Hosting -> Hooks* tab.

**Comment by n-rodriguez** [comment]
> But is it normal that /home/git/projects.list is an empty file?

You must configure Gitolite too :
in ```<git user home>/.gitolite.rc``` :

# creates projects.list file; if you don't use gitweb, comment this out
#'gitweb',
