### ISSUE TITLE
Internal Server Error on user details

### ISSUE THREAD

**Issue by hameno** [jbox-web/redmine_git_hosting#331]
Just updated to 1.0.0 and I get the following error when browsing to my user detail page:

```
Started GET "/users/3" for <IP> at 2015-01-26 08:50:09 +0100
Processing by UsersController#show as HTML
  Parameters: {"id"=>"3"}
  Current user: <username> (id=3)
  Rendered plugins/redmine_git_hosting/app/views/users/show.api.rsb within layouts/base (2.0ms)
Completed 500 Internal Server Error in 135.3ms

ActionView::Template::Error (No builder for format ):
    1: api.user do
    2:   api.id         @user.id
    3:   api.login      @user.login if User.current.admin? || (User.current == @user)
    4:   api.firstname  @user.firstname
  lib/redmine/views/builders.rb:28:in `for'
  app/controllers/users_controller.rb:76:in `block (2 levels) in show'
  app/controllers/users_controller.rb:75:in `show'
```

It seems it tries to do the API rendering on normal html requests.

**Comment by n-rodriguez** [comment]
Fixed in v1.01 branch.

**Comment by hameno** [comment]
Yep, fixed. Thanks ;)

Side note: Wouldn't it be easier to manage a 1.0-stable branch and tag each release version?

**Comment by n-rodriguez** [comment]
> Side note: Wouldn't it be easier to manage a 1.0-stable branch and tag each release version?

I have to think about it... Thanks for the tip ;)

**Comment by n-rodriguez** [comment]
> Side note: Wouldn't it be easier to manage a 1.0-stable branch and tag each release version?

Done.
