### ISSUE TITLE
(Question) Why can't I specify a repository identifier that is the same as the project identifier?

### ISSUE THREAD

**Issue by necramirez** [jbox-web/redmine_git_hosting#337]
I also noticed that with _Automatically initialize Git repositories for new projects_ turned on, the repo created has an empty repo identifier.  What's it supposed to be for, then?

**Comment by n-rodriguez** [comment]
> What's it supposed to be for, then?

Automatically initialize Git repositories for new projects.

> I also noticed that with Automatically initialize Git repositories for new projects turned on, the repo created has an empty repo identifier.

It's normal. Redmine accepts both.

**Comment by necramirez** [comment]
> What's it supposed to be for, then?

Haha, sorry I wasn't clear:  What's the _repo identifier_ supposed to be for, then?

**Comment by n-rodriguez** [comment]
> Haha, sorry I wasn't clear: What's the repo identifier supposed to be for, then?

Okay, let me be clearer : 

A long time ago, in a galaxy far away, Redmine (the empire) was only accepting one repository per project. At that time the repository identifier was the project's identifier. Everything was fine until the rebells came around and ask to the Jedis brotherhood to add the possibility to have many repositories per project. Thanks to the Force this could be done and then appears multi repositories in Redmine but with one condition : repository will have an identifier to recognize them among the others... except for one repository. The Architect introduces one subtility : one repository per project can have empty identifier. It's called The One ;)
