### ISSUE TITLE
My public key link is wrong

### ISSUE THREAD

**Issue by nogo** [jbox-web/redmine_git_hosting#340]
I update to 1.0 and the link to "My public keys" ist wrong. I installed redmine in a subdirectory. My url ist https://server/redmine and the link is pointing to https://server/my/public_keys instead of https://server/redmine/my/public_keys . Did I miss a configuration?

**Comment by Phiber2000** [comment]
Isn't fixed by 8097665de5868e699d0da91334192e2288340621. Still missing the subpath.
