### ISSUE TITLE
Overwriten gitolite.conf 

### ISSUE THREAD

**Issue by C0vax** [jbox-web/redmine_git_hosting#341]
When I change something in the module settings or settings in the project repository, module deletes all non-redmine users in gitolite.conf.

**Comment by C0vax** [comment]
If I change the users redmine project is also deleted from the file gitolite.conf manually added users

**Comment by Trim** [comment]
I've seen same result when I want to "remove" repositories by giving read access to only `redmine_dummy_key` user.

**Comment by Trim** [comment]
Ok, if I make same procedure than above and apply "Empty git cache" and "Synchronize all projects" it works.

Although, if I add gitweb user to a repository used by redmine, it's overridden (even if I empty cache and synchronize projects).

**Comment by n-rodriguez** [comment]
> even if I empty cache

Actually Git Cache has nothing to do with this. Git cache is only used to speed up repository browsing in Redmine.

**Comment by n-rodriguez** [comment]
> When I change something in the module settings or settings in the project repository, module deletes all non-redmine users in gitolite.conf.

If you have non Redmine users in ```gitolite.conf``` you should put Redmine Gitolite config in a separate file with an include in ```gitolite.conf```.

**Comment by n-rodriguez** [comment]
> Although, if I add gitweb user to a repository used by redmine, it's overridden (even if I empty cache and synchronize projects).

It's normal, Redmine has full control on its repositories. If you want to enable gitweb for a repository, make the project public and enable SmartHttp.

**Comment by n-rodriguez** [comment]
Hi there!

Can I close the issue?

**Comment by Trim** [comment]
Yes for me, that works well if separated redmine config and smarthttp enabled. And for you @C0vax ?

**Comment by C0vax** [comment]
Yes

Îòïðàâëåíî ñ iPhone

**Comment by jekel** [comment]
how can i manage access for same repos by both redmine and non-redmine users?
