### ISSUE TITLE
New v1 install not creating repos

### ISSUE THREAD

**Issue by oliwel** [jbox-web/redmine_git_hosting#342]
I setup a new fresh install using the v1.0 plugin on ruby2.1.5 - the UI integration seems to work, the config test page is all green. User keys are added to gitolite but no repos are created nor listed in the config.
Compared to a migrated install (which also does not work!) I still see "Redmine:Git" as class name in the repositories table.

I dont know what am I doing wrong as my installs always need a lot of tweaking till they work - what distribution with what ruby/rails versions can you recommend?

**Comment by oliwel** [comment]
Tried also on a fresh bootstrapped wheezy following this howto 
http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_2_integrated_with_Gitolite_2_on_Debian_Wheezy_with_Apache_and_Phusion_Passenger

with same result - logs are fine but no repos are installed.

**Comment by n-rodriguez** [comment]
> what distribution with what ruby/rails versions can you recommend?

```
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    development
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.2.2
  Git                            1.7.10.4
  Filesystem
  Xitolite                       1.7.10.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.0
  redmine_git_hosting            1.0-devel
  redmine_sidekiq                2.1.0

Sudo version is 1.8.5p2 (but I don't think we should care of it now)
Debian Wheezy 7.8
Gitolite v3.6.2-12-g1c61d57
```

**Comment by n-rodriguez** [comment]
I don't use Passenger. I find the installation a bit complicated. I prefere Puma.
In the same idea, I don't use Redmine Debian package to install Redmine but a dedicated user with RVM and Redmine inside. This is then easier to keep Redmine updated.
https://jbox-web.github.io/redmine_git_hosting/guide/redmine-installation/

**Comment by connecticus** [comment]
oliwel, look at this - http://stackoverflow.com/questions/22255742/getting-ruggednetworkerror-on-connect 

(you have error with gitolite-rugged compilling - missing libssl-dev )

**Comment by oneclickdev** [comment]
Hello!
Same problem here. Redmine doesn't create git repo with creating new project. Could you help, please?

Here is what in redmine (development mode) log:
  Project Load (0.3ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`id` = 182 LIMIT 1
  Setting Load (0.1ms)  SELECT `settings`.* FROM `settings` WHERE `settings`.`name` = 'enabled_scm' LIMIT 1
  Repository Load (0.4ms)  SELECT `repositories`.* FROM `repositories` WHERE `repositories`.`project_id` = 182 AND (identifier = '' or identifier is null)
   (0.2ms)  COMMIT
   (0.1ms)  BEGIN
  RepositoryGitExtra Exists (0.2ms)  SELECT 1 AS one FROM `repository_git_extras` WHERE `repository_git_extras`.`repository_id` IS NULL LIMIT 1
   (0.2ms)  ROLLBACK
Completed 422 Unprocessable Entity in 403.4ms

ActiveRecord::RecordInvalid (Validation failed: repository can't be blank, repository has already been taken):
  activerecord (3.2.21) lib/active_record/validations.rb:56:in `save!'
  activerecord (3.2.21) lib/active_record/attribute_methods/dirty.rb:33:in `save!'
  activerecord (3.2.21) lib/active_record/transactions.rb:264:in `block in save!'
  activerecord (3.2.21) lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'


Redmine environment: https://www.dropbox.com/s/8gvu2ed2yhnj46n/Screenshot%202015-02-17%2018.26.35.png?dl=0

Git version: 1.7.10.4
Gitolite version: 3
and everything is green on ConfigTest Tab in Redmine Git Hosting Plugin

**Comment by oneclickdev** [comment]
Seems like it doesn't insert any record into "repositories" table...

**Comment by oneclickdev** [comment]
I just installed empty redmine (with existing gitolite) and issue still exists...
Could you assist please? At lest tell me how can I find more logs?

**Comment by oneclickdev** [comment]
Seems I found the problem in here: #344 
I've updated redmine_git_hosting to devel branch and seems it works
so just discard everything above and close that task )

**Comment by n-rodriguez** [comment]
@oliwel Any news?

**Comment by oliwel** [comment]
Well, I dont see much help towards the problem here - the base system works and as redmine does at users to the gitolite I assume that the connector is working. What about the difference in the "class name"? Is this intended or a bug?
Is there any option to get some more debug info from the system? I already set "hooks in debug" mode but as the systems seems simply not to find the repos, the only thing I see is "silence".
Might you be willing to look at the system yourself? I can set up a test and provide ssh access.

**Comment by n-rodriguez** [comment]
> Might you be willing to look at the system yourself? I can set up a test and provide ssh access.

Can you please send me them to nrodriguez@jbox-web.com?

**Comment by n-rodriguez** [comment]
Can I close it? :)

**Comment by oliwel** [comment]
I hope so - I need some time to migrate my prod systems but I can reopen the ticket if the problem persists. Might you post the solution here for Follow Ups?

**Comment by n-rodriguez** [comment]
Enable Xitolite repositories in Administration -> Settings -> Repositories
