### ISSUE TITLE
ArgumentError: invalid byte sequence in US-ASCII (solution inside)

### ISSUE THREAD

**Issue by oliwel** [jbox-web/redmine_git_hosting#343]
when trying to install v1.0 on a fresh bootstrap of wheezy, I get

```
ArgumentError: invalid byte sequence in US-ASCII
An error occurred while installing gitolite-rugged (1.0.0), and Bundler cannot continue.
```

It looks like the gitolite-rugged gem is not working without a proper locale being set, it helped to install the "locales" package and do 

```
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
```

Credits go to http://stackoverflow.com/questions/8897194/bundling-jquery-rails-fails-with-error

**Comment by n-rodriguez** [comment]
> It looks like the gitolite-rugged gem is not working without a proper locale being set, it helped to install the "locales" package and do

Yep. Under Debian you can also do :

```
root@dev:~# apt-get install locales
root@dev:~# dpkg-reconfigure locales # it opens a dialog box to select the locales you want to generate then an other one to choose your default locale.
```

**Comment by n-rodriguez** [comment]
Doc updated! Thank you!
