### ISSUE TITLE
Migration from old 0.6.4 caused problem with new repositories or adding people to old ones

### ISSUE THREAD

**Issue by psyclone241** [jbox-web/redmine_git_hosting#346]
I migrated from 0.6.4 to 0.7.8, and ran into an issue where the repositories are not getting created (or at least gitolite isn't seeing them) So I migrated from 0.7.8 to 0.7.10 to 1.0.1, hoping that this was a bug in 0.7.8.  So far, it seems that I still have an issue with new repositories, or adding people to an old one.

I've gone through all the other bugs like this that are listed on here, and so far none of the steps have corrected the issue.  In fact, once reaching version 1.0.1, now when I create a repository, I no longer see gitolite as the user creating the repositories, and when I create a new one, it asks me for a directory location?

So, I'm a  bit confused as to where the issue lies?  What did I do?? Help!!

**Comment by indera** [comment]
Maybe revert to 0.6.4?

**Comment by psyclone241** [comment]
Thought about that, but I don't want to lose functionality available in > 0.7.8 as well as there are upgraded gems that other plugins are using.

**Comment by psyclone241** [comment]
The config check passes, all green.  I've manually tested running commands as the git user and the user running redmine.  They all seem to work just fine from the command line.

**Comment by dgeo** [comment]
New gitolite repos in v1 are named 'Gitolite' (or Xitolite), not 'git' - 'git' is now the back redmine's 'git' support (without any redmine_git_hosting features).
Are you sure you try to create a 'gitolite' repo ?

**Comment by n-rodriguez** [comment]
> Are you sure you try to create a 'gitolite' repo ?

Yep. Go in *Administration -> Settings -> Repositories* tab and enabled Xitolite repositories.

**Comment by psyclone241** [comment]
Ok, so I was finally able to fix the issue.  It was a combination of 2 things.  First, the setting in .gitolite.rc for GIT_CONFIG_KEYS. The other article with a similar issue #166 had these issues too.  The second one, was the duplicate keys in the keydir.  I removed all the old keys and now I can create new repos, as well as add people to old ones.

Funny thing is the brand new repositories have files, but they are showing up blank.  I'm pretty sure that I've seen another article with that, going to look for it now.

**Comment by psyclone241** [comment]
All good, thanks!

**Comment by indera** [comment]
Roy, your fix is confirmed. Great job.
