### ISSUE TITLE
Strange max number of gitolite repos (21/27) per project since v1

### ISSUE THREAD

**Issue by dgeo** [jbox-web/redmine_git_hosting#347]
Hi,

Strange behaviour in one project that contains 37 repos since upgrade to v1.0.1 (then v1.x):
Blank page (HTTP 200, head as usual but void body) for project's page, and blank frame for settings/{versions,categories,repositories}…

If I "remove" 10 repos or more (by changing repositories.project_id to an unexisting one in DB), project page is back (max 27 repos with this project_id)
To get settings/repositories page to work again, I have to remove more until going under 21 repos...

I created those repositories with v0.6 and v0.7 through redmine interface, without this strange limit…

I found no errors in logs (debug level in redmine and plugin, nothing in unicorn's stdout/stderr), HTTP code is 200 :-/

ps: I may take some beers this friday evening in la b[oa]te talking about SSL si ça te tentes :)

**Comment by n-rodriguez** [comment]
> ps: I may take some beers this friday evening in la b[oa]te talking about SSL si ça te tentes :)

avec plaisir :)

**Comment by n-rodriguez** [comment]
faudra me montrer ça en live si possible parce que là... j'en perds mon latin.

**Comment by dgeo** [comment]
On 02/05/2015 01:05 AM, Nicolas wrote:
> faudra me montrer ça en live si possible parce que là... j'en perds mon
> latin.
> 
C'est possible aussi :)

A demain si tu peux !

http://plugfr.org/reunions/6-fevrier-2015/

**Comment by n-rodriguez** [comment]
Merci de me le rappeler :)
Je serai là aux alentours de 21h, c'est bon pour toi?

**Comment by dgeo** [comment]
On 02/05/2015 10:02 PM, Nicolas wrote:
> Merci de me le rappeler :)
> Je serai là aux alentours de 21h, c'est bon pour toi?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jbox-web/redmine_git_hosting/issues/347#issuecomment-73127499>.
> 
je devrais y être dans ces eaux là aussi :)

**Comment by n-rodriguez** [comment]
ok, a demain alors!

**Comment by n-rodriguez** [comment]
A propos de la discussion d'hier soir :
Linux et la résolution DNS : http://www.tldp.org/LDP/nag2/x-087-2-resolv.library.html
Apache et la résolution DNS : http://httpd.apache.org/docs/trunk/fr/dns-caveats.html

A bientot!
