### ISSUE TITLE
Repo page remains empty after initial git push

### ISSUE THREAD

**Issue by necramirez** [jbox-web/redmine_git_hosting#353]
"Forked" from https://github.com/jbox-web/redmine_git_hosting/issues/336#issuecomment-72154123 :

The repo page isn't updated in Redmine after an initial `git push`.
1. Create new project/repo -- repo is empty
2. I see the empty repo page
3. I do the initial push from my local
4. I still see the empty repo page
5. I manually run the rake task `fetch_changesets`
6. Repo page is now updated
7. I make a new commit and push
8. Repo page is updated immediately

My current workaround is I added a cron job to run the `fetch_changesets` rake task every hour, such that newly-created projects/repos will show up, after a while.

* Ruby: 2.0.0-p598
* Redmine: 2.6.0.stable
* Git: 1.9.5
* redmine_git_hosting: v1.x branch
* Gitolite: 3.6.2

**Comment by n-rodriguez** [comment]
Can you please post the output of a ```git push -u origin master``` ?

**Comment by necramirez** [comment]
This is now fixed.

I mentioned in https://github.com/jbox-web/redmine_git_hosting/issues/336#issuecomment-72147811 that I had Ruby 1.8.7 in my system, and that I didn't see any additional output for `git push -u origin master`, so I guessed that the hooks weren't executed at all.

I upgraded my system Ruby, and the git hooks now work.  I installed the latest Ruby, 2.2, so I'm not sure what the correct minimum version really is (1.9?, 2.0?).

**Comment by necramirez** [comment]
BTW, the installation doc (https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-7-install-ruby-interpreter-for-post-receive-hook) does not specify a minimum system Ruby version, it just says:
> Our post-receive hook is triggered after each commit and is used to fetch changesets in Redmine. As it is written in Ruby, you need to install Ruby on your server. Note that this does not conflict with RVM.

So I simply installed from `yum` on CentOS 6, and that's what gave me Ruby 1.8.

**Comment by n-rodriguez** [comment]
> I upgraded my system Ruby, and the git hooks now work. I installed the latest Ruby, 2.2, so I'm not sure what the correct minimum version really is (1.9?, 2.0?).

It should work with Ruby 1.9.

> BTW, the installation doc does not specify a minimum system Ruby version

Yep. I'm gonna update the doc. Thank you!
