### ISSUE TITLE
Port to Redmine 3.0.0

### ISSUE THREAD

**Issue by Trim** [jbox-web/redmine_git_hosting#354]
Hello,

Last week I've upgraded my server to Debian Jessie and I was surprised that Redmine version is the not already [released 3.0.0](https://packages.debian.org/jessie/redmine). As this plugin is really useful, I want to help to port it to Redmine 3.0.0 (certainly on a virtual machine first) if I'm able.

The only informations I've found about Redmine 3.0.0 is [their roadmap](http://www.redmine.org/versions/80) which say the release is due in 14 days. I'll try to view code in their [trunk svn repository](http://www.redmine.org/projects/redmine/repository) to see if I can find some clue about big changes.

While upgrading Debian, I've noticed these incompatible gems:

* `gem "redcarpet", "~> 3.1.2"`
* the rack gem version (I think implied by the `gem "rails", "4.2.0"` line) which conflicts with your [gitlab-grack repo](https://github.com/jbox-web/grack/commits/fix_rails3). I've seen a new pre-version of [gitlab-grack 2.0.0](https://rubygems.org/gems/gitlab-grack/versions/2.0.0.rc1) which appears have no more conflict

I'll investigate to find which SQL table have been modified since 2.6.1. Which SQL structures do you need for your plugin ?

Hope I can help,
Adrien

**Comment by n-rodriguez** [comment]
> Last week I've upgraded my server to Debian Jessie and I was surprised that Redmine version is the not already released 3.0.0.

This is not very surprising due to the Debian release policy. The package tree is freezed since 3 or 4 months.

**Comment by n-rodriguez** [comment]
> I want to help to port it to Redmine 3.0.0

Thanks for your help but I think there won't be too much work to port it to Redmine 3.0.0 :)

**Comment by Trim** [comment]
So, I've begun work here [Trim/redmine_git_hosting](https://github.com/Trim/redmine_git_hosting/tree/redmine3/wip) and I've found [this bug](http://stackoverflow.com/questions/23239130/input-string-is-longer-than-namedatalen-1-63-ruby-on-rails-4) due to Rails4 and Postgresql during install:

```
== 20130909195929 RenameTableDeploymentCredentials: migrating =================
-- rename_table(:deployment_credentials, :repository_deployment_credentials)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Input string is longer than NAMEDATALEN-1 (63)/usr/share/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql/quoting.rb:170:in `quote_ident'
```

I think the solution to rename the auto keys or tables isn't possible for already in production migration database files. The issue is that to modify NAMEDATALEN value [we have to recompile PostgreSQL](http://stackoverflow.com/questions/3836247/how-do-i-change-the-namedatalen-configuration-after-installing-postgresql-9-0).

**Comment by n-rodriguez** [comment]
> I think the solution to rename the auto keys or tables isn't possible for already in production migration database files. The issue is that to modify NAMEDATALEN value we have to recompile PostgreSQL.

From what I see on StackOverflow it can be an index name :

> Most likely it is an index name which is hitting the character limit.

One solution would be to remove indexes before renaming the table.

**Comment by n-rodriguez** [comment]
Everything has been fixed [here](https://github.com/jbox-web/redmine_git_hosting/commit/24e65510e586f5feaed02b22b9651bde67f54002) and [here](https://github.com/jbox-web/redmine_git_hosting/commit/30a99e2f7f81c78247b3678f9b1641bf12265bc6) :)

**Comment by Trim** [comment]
Many thanks, I'll try it this afternoon :)

**Comment by Trim** [comment]
Ok, it worked for me after little tweaking of Debian Jessie default redmine Gemfile (just commented the constraint on rails version which were in conflict with grack [they've set it to ~>4.1.4]).
