### ISSUE TITLE
Overwrites existing gitolite post-receive hook without any warning

### ISSUE THREAD

**Issue by AlexeyDemidov** [jbox-web/redmine_git_hosting#359]
There is no warning in documentation or in interface that this plugin overwrites existing gitolite post-receive hook.

**Comment by n-rodriguez** [comment]
> There is no warning in documentation or in interface that this plugin overwrites existing gitolite post-receive hook.

You're right. But you have an option to disable this behavior : in *Administration -> Redmine Git Hosting -> Hooks* uncheck ```gitolite_force_hooks_update```.
