### ISSUE TITLE
Add rm -rf /tmp/redmine_git_hosting to migration task and troubleshooting document.

### ISSUE THREAD

**Issue by metimocyn** [jbox-web/redmine_git_hosting#361]
Hi,

I just upgraded to try and fix an issue, with the giolite config not getting updated properly. 
The key migration kept generating these types of errors:
```
error: 'keydir/redmine_me@redmine_1424450917_34480.pub' has changes staged in the index
(use --cached to keep the file, or -f to force removal)
```

It seems that this is a problem with the cache not being cleared from the /tmp/redmine_git_hostring copy of the gitolite admin repository. After removing this folder, it worked. It may also be the cause of the issue i was having that made me upgrade in the first place.

**Comment by metimocyn** [comment]
this did not fix my issue. my problem still seems to be with the gitolite.conf creation failing silently 
somewhere in the middle of creation. In other respects the plug in works, adding keys etc.

How do i check/examine the gitolite.conf creation process?

**Comment by n-rodriguez** [comment]
> 2015-02-23 11:07:37 +0100 WARN [GitWorker] update_members : repository 'infrastructure' does not exist in Gitolite, exit !

This error means that the repository does not exist in **Gitolite config file**. 

> Needless to say the repository exists.

You mean the directory? Can you please check in ```gitolite.conf``` file that it's the case?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by metimocyn** [comment]
Fool me, i was only at 0.7. Migration to 1.x seemed to fix all my outstanding issues.

**Comment by n-rodriguez** [comment]
> Migration to 1.x seemed to fix all my outstanding issues.

Great :)
