### ISSUE TITLE
Popen : wrong number of arguments

### ISSUE THREAD

**Issue by DasRoteSkelett** [jbox-web/redmine_git_hosting#362]
While redmine (2.6.1) runs  and I can have a look at the repos from the website, it is impossible to clone or push or even click on a Username (Internal Server Error). I am using thin(1.6.3) /nginx. 

Here is the dump: 
<EDIT> Corrected Dump...

```
Listening on /tmp/thin.0.sock, CTRL+C to stop
Unexpected error while processing request: wrong number of arguments (3 for 1..2)
        /usr/local/lib64/ruby/gems/1.9.1/bundler/gems/grack-971b468103ac/lib/grack/server.rb:78:in `popen'
        /usr/local/lib64/ruby/gems/1.9.1/bundler/gems/grack-971b468103ac/lib/grack/server.rb:78:in `block in service_rpc'
        /usr/lib64/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/response.rb:89:in `call'
        /usr/lib64/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/response.rb:89:in `each'
        /usr/lib64/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/body_proxy.rb:31:in `each'
        /usr/local/lib64/ruby/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:46:in `each'
        /usr/local/lib64/ruby/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:460:in `each'
        /usr/lib64/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/body_proxy.rb:31:in `each'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/lib/thin/response.rb:96:in `each'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:114:in `post_process'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
        /usr/local/lib64/ruby/gems/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
        /usr/local/lib64/ruby/gems/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
        /usr/lib64/ruby/gems/1.9.1/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
        /usr/bin/thin:9:in `load'
        /usr/bin/thin:9:in `<main>'
```

I am thankful to any hint, I am not familiar with ruby...

**Comment by DasRoteSkelett** [comment]
I changed line 78 in /usr/local/lib64/ruby/gems/1.9.1/bundler/gems/grack-971b468103ac/lib/grack/server.rb

to

IO.popen(command, File::RDWR) do |pipe|

which seems to work?? I have to check on possible side effects...

**Comment by n-rodriguez** [comment]
> which seems to work?? I have to check on possible side effects...

You *must not* do that. Actually this class is overriden by the plugin (in ```redmine_git_hosting/lib/grack/server.rb```) and your issue looks like https://github.com/jbox-web/redmine_git_hosting/issues/345

**Comment by n-rodriguez** [comment]
Which version of Ruby are you using?

**Comment by n-rodriguez** [comment]
Btw, there is a [new release 1.0.1](https://jbox-web.github.io/redmine_git_hosting/about/releases-notes/#toc-release-1-0-1) which fixes the bug on User view.

**Comment by n-rodriguez** [comment]
[Support of Ruby 1.9.x has ended](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) so I highly recommend you to upgrade to Ruby 2.1 or 2.0.0.

**Comment by DasRoteSkelett** [comment]
Fine. I reverted, switched to ruby2, and on git clone I get:
Unexpected error while processing request: wrong number of arguments (3 for 1..2)
	/var/lib/redmine/.gem/ruby/1.9.1/bundler/gems/grack-971b468103ac/lib/grack/server.rb:78:in `popen'
	/var/lib/redmine/.gem/ruby/1.9.1/bundler/gems/grack-971b468103ac/lib/grack/server.rb:78:in `block in service_rpc'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/rack-1.4.5/lib/rack/response.rb:89:in `call'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/rack-1.4.5/lib/rack/response.rb:89:in `each'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/rack-1.4.5/lib/rack/body_proxy.rb:31:in `each'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:46:in `each'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:460:in `each'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/rack-1.4.5/lib/rack/body_proxy.rb:31:in `each'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/lib/thin/response.rb:96:in `each'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:114:in `post_process'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
	/var/lib/redmine/.gem/ruby/1.9.1/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
	/usr/local/bin/thin:23:in `load'
	/usr/local/bin/thin:23:in `<main>'

So, well, if i *must not* do this, what do I have to do to get this to work???

git error message:
Cloning into 'rcs-ng'...
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly

**Comment by n-rodriguez** [comment]
Are you sure you're using Ruby2? :

```/var/lib/redmine/.gem/ruby/1.9.1/bundler/gems/grack-971b468103ac/lib/grack/server.rb:78:in `popen'```

**Comment by DasRoteSkelett** [comment]
@n-rodriguez : Thanks, turns out, eselect set ruby20 does not seal the deal ;) so now I am running ruby20, redmine_git_hosting 1.0.1 and issue seems to be fixed for me! Thank you once again

**Comment by n-rodriguez** [comment]
You're welcome ;)
