### ISSUE TITLE
Empty repository throws 404

### ISSUE THREAD

**Issue by saz** [jbox-web/redmine_git_hosting#363]
I'm running into an issue, if I'm trying to open an empty repository, Redmine just shows a 404 error message, not the instructions, how to clone this repository (as it was before).

The following information is logged:

```
Started GET "/projects/entwicklung-allgemein/repository" for [...IP...] at 2015-02-23 16:47:08 +0100
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"entwicklung-allgemein"}
  Current user: saz (id=16)
  Rendered common/error.html.erb within layouts/base (0.2ms)
Filter chain halted as :find_project_repository rendered or redirected
Completed 404 Not Found in 62.1ms (Views: 30.0ms | ActiveRecord: 9.4ms)
```

The following is the error message I'm seeing in the browser:
```
The entry or revision was not found in the repository.
```

If you need anything else, just let me know

(I've mentioned this in #339)

**Comment by n-rodriguez** [comment]
Have you tried with version 1.0.1?

**Comment by saz** [comment]
Yeah. It's working. Thank you!

**Comment by WMP** [comment]
I have this same problem, could you tell me how to upgrade to 1.0.1?

@saz, @n-rodriguez
