### ISSUE TITLE
User profile page broken after migration

### ISSUE THREAD

**Issue by carukc** [jbox-web/redmine_git_hosting#366]
Hello,

First of all.. thank you for the plugin.. I have been a long time user and it's simply fantastic!

I initially thought that this might have been a docker integration issue... I've managed to get docker working with redmine and redmine_git_hosting :) ... but it's not... I've gone back to my original Ubuntu 14.04 native install (which uses phusion passenger) and there's a problem there too.

I migrated from 7.04 (I think... so I first moved to 7.10 and then upgraded to 1.0 from there.

Repositories work... The config check works and reports that all is good... I CAN ssh to git from redmine using the appropriate key... (that said, I would not get a clean report from the config check if I could not do this). 

I can browse repos, look at stats, etc... I have not yet tried creating a repo but when I go to a users profile page I get:

-------------------------
Started GET "/users/8" for 90.155.11.150 at 2015-02-23 19:18:59 +0000
Processing by UsersController#show as HTML
  Parameters: {"id"=>"8"}
  Current user: quicksilver (id=6)
  Rendered plugins/redmine_git_hosting/app/views/users/show.api.rsb within layouts/base (0.8ms)
Completed 500 Internal Server Error in 66.5ms

ActionView::Template::Error (No builder for format ):
    1: api.user do
    2:   api.id         @user.id
    3:   api.login      @user.login if User.current.admin? || (User.current == @user)
    4:   api.firstname  @user.firstname
  lib/redmine/views/builders.rb:28:in `for'
  app/controllers/users_controller.rb:76:in `block (2 levels) in show'
  app/controllers/users_controller.rb:75:in `show'

--------------------------

I've tried to go a git pull to see if there have been any changes..  
  git checkout 1.0.0
produces:
  HEAD is now at 7c6494f... Use a long term repo for gitolite-rugged gem

and... 
  git pull 
produces:
  You are not currently on a branch. Please specify which branch you want to merge with. See git-pull(1) for details.
   git pull <remote> <branch>

Perhaps I missed something in the install instructions that was supposed to put me on a branch?

I have removed all other plugins from the system (except for the boostrap one) and rerun the plugin migration scripts and 'bundle install'

I've rerun the migration script (and restarted nginx)... countless times.

I'm stumped.  Please assist.  What should I try next?  Should I be able to pull recent changes.

Thanks

**Comment by carukc** [comment]
All seems to work after applying the update here: https://jbox-web.github.io/redmine_git_hosting/releases-notes/release-1.0.1.html  (on dccker too).

**Comment by n-rodriguez** [comment]
> Perhaps I missed something in the install instructions that was supposed to put me on a branch?

Nope. Now we use Git tags to manage plugin releases so it's normal.
