### ISSUE TITLE
Rugged::NetworkError (This transport isn't implemented. Sorry)

### ISSUE THREAD

**Issue by sabarish14** [jbox-web/redmine_git_hosting#367]
Hi,
I'm using bitnami stack redmine.I followed all the procedures explained in the instructions page.I have the following problems:
Bitnami stack doesn't provide me a login for its user daemon.Because of this I couldn't create public keys for this user.How to overcome this?
After configuring the repositories, how should I add a new repository ? Is there any link which specifies this procedure? How does the integration between the redmine users and  this gitolite work? Should we need to do any configuration for this integration?

**Comment by n-rodriguez** [comment]
> Bitnami stack doesn't provide me a login for its user daemon.Because of this I couldn't create public keys for this user.How to overcome this?

Can you please be a bit more precise?

> how should I add a new repository ?

Just as usual, in project's configuration tab, then in 'repositories' tab, 'add a repository' link.
In the repository creation form select 'Gitolite' in the select box.
If there's no 'Gitolite' entry in the select box, go in *Administration -> Settings -> Repositories* and check the Xitolite checkbox.


> How does the integration between the redmine users and this gitolite work?

You have a link in your Redmine account to add/remove SSH keys in Gitolite.


> Should we need to do any configuration for this integration?

https://jbox-web.github.io/redmine_git_hosting/howtos/install/

**Comment by sabarish14** [comment]
I installed redmine using bitnami stack.The user created to run redmine is named daemon.It doesn't have a shell login.The following is its entry in /etc/passwd:
daemon:x:2:2:daemon:/sbin:/sbin/nologin.
In the installation procedure of redmine git hosting, it is said that I should login as redmine user and generate keys. But as this user daemon doesnt have a login , how can I do this?

Also in redmine web application,when I click My account and then click my public keys, the following error occurs:
Not Found

The requested URL /my/public_keys was not found on this server. 


Kindly give me a solution to solve these problems

**Comment by oskarp** [comment]
You should be able to log in to your daemon account using `sudo -u daemon /bin/bash`.

**Comment by sabarish14** [comment]
I'm able to do that. But when I create a new repository, I get Internal error.My production.log file is

Rugged::NetworkError (This transport isn't implemented. Sorry):
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone_at'
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone'
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:110:in `initialize'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:67:in `new'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:67:in `gitolite_admin'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:39:in `resync_gitolite'
  plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:49:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:97:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:27:in `create_repository'
  plugins/redmine_git_hosting/app/use_cases/create_repository.rb:64:in `create_repository'
  plugins/redmine_git_hosting/app/use_cases/create_repository.rb:16:in `call'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:87:in `call_use_cases'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:44:in `create_with_git_hosting'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:502:in `_run__2686589911236617405__process_action__2758964419579246664__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.1) lib/rack/openid.rb:99:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'

Mirroring ssh key is also failing.

**Comment by n-rodriguez** [comment]
You need to install some dependencies :
```apt-get install libssh2-1 libssh2-1-dev cmake libgpg-error-dev``` or
```sudo apt-get install libssh2-1 libssh2-1-dev cmake libgpg-error-dev```

Then ```bundle install --without development test```

**Comment by sabarish14** [comment]
I have all these dependencies already installed.I installed gitolite plugin with bundle install --without development test command only

**Comment by sabarish14** [comment]
I repeated the integration of gitolite. When I completed everything and run Administration-> redmine git hosting, I get this error.Kindly help me out. This is very urgent
Completed 500 Internal Server Error in 1077.2ms

ActionView::Template::Error (undefined method `join' for nil:NilClass):
    24:     %td= l(:label_sudo_redmine_to_gitolite_user)
    25:     %td= image_tag (RedmineGitHosting::Config.can_redmine_sudo_to_gitolite_user? ? 'true.png' : 'exclamation.png')
    26:
    27:   - gitolite_checks = RedmineGitHosting::Config.check_hooks_install!
    28:
    29:   %tr
    30:     %td= l(:label_gitolite_hooks_installed)
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__1942582412984706303_69979759650720'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__1942582412984706303_69979759650720'
  app/helpers/application_helper.rb:328:in `render_tabs'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___2443152060578276512_69979492614380'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___2443152060578276512_69979492614380'

**Comment by n-rodriguez** [comment]
```cd redmine/plugins/redmine_git_hosting && git checkout v1.x```

Then restart Redmine.

**Comment by sabarish14** [comment]
Thank you Nicolas. I got rid of that error.But when I try to create a new repository, I get the following error:
Rugged::NetworkError (This transport isn't implemented. Sorry):
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone_at'
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone'
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:110:in `initialize'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `new'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `gitolite_admin'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:38:in `resync_gitolite'
  plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:50:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:97:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:39:in `destroy_repository'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:93:in `call_use_cases'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:58:in `destroy_with_git_hosting'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:502:in `_run__375277922962209541__process_action__464152910588452048__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.1) lib/rack/openid.rb:99:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'

Kindly help me out

**Comment by n-rodriguez** [comment]
```gem uninstall gitolite-rugged``` then ```bundle install --without development test```

**Comment by sabarish14** [comment]
It says couldnt locate gem file.
Should I type this command before bundle install?
git clone https://github.com/jbox-web/redmine_git_hosting.git

**Comment by n-rodriguez** [comment]
> It says couldnt locate gem file.

```cd redmine``` then ```gem uninstall``` ....

**Comment by sabarish14** [comment]
It still says couldnt locate gem file.Should I clone the redmine git hosting?

**Comment by n-rodriguez** [comment]
> Should I clone the redmine git hosting?

Nope. You should have already cloned it in ```redmine/plugins``` directory.

**Comment by sabarish14** [comment]
Ya.Now it works.Shoud I start redmine and check now?

**Comment by n-rodriguez** [comment]
Yes

**Comment by sabarish14** [comment]
I'm again getting the error:
Completed 500 Internal Server Error in 124.5ms

Rugged::NetworkError (This transport isn't implemented. Sorry):
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone_at'
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone'
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:110:in `initialize'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `new'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `gitolite_admin'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:38:in `resync_gitolite'
  plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:50:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:97:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:39:in `destroy_repository'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:93:in `call_use_cases'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:58:in `destroy_with_git_hosting'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:502:in `_run__339352051274792650__process_action__3981809221457080838__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'

**Comment by n-rodriguez** [comment]
Ok.
Can you please run ```apt-get install build-essential``` then repeat the operation (gem uninstall, bundle install) ?

**Comment by sabarish14** [comment]
I'm using CentOS.Can you please tell the equivalent command in yum?

**Comment by n-rodriguez** [comment]
yum groupinstall "Development Tools"

**Comment by sabarish14** [comment]
No luck.Getting the same error:
Rugged::NetworkError (This transport isn't implemented. Sorry):
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone_at'
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone'
  /home/y/ruby/lib/ruby/gems/2.0.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:110:in `initialize'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `new'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `gitolite_admin'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:38:in `resync_gitolite'
  plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:50:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:97:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:39:in `destroy_repository'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:93:in `call_use_cases'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:58:in `destroy_with_git_hosting'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:502:in `_run__2179485034394077202__process_action__3315749043356752517__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.1) lib/rack/openid.rb:99:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'

**Comment by n-rodriguez** [comment]
Try to find this file : ```redmine$ /home/redmine/.rvm/gems/ruby-2.1.4/extensions/x86_64-linux/2.1.0/rugged-0.21.4/gem_make.out```. It contains the compilation logs for Rugged. Check if there's any errors in it. (missing dependencies, things like that)

**Comment by sabarish14** [comment]
My installation is a bitnami stack installation.When I searched for gem_make.out, I found these files only:
/home/y/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0-static/rmagick-2.13.4/gem_make.out
/home/y/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0-static/mysql2-0.3.14/gem_make.out
/home/y/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0-static/redcarpet-2.3.0/gem_make.out
/home/y/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0-static/json-1.8.1/gem_make.out

**Comment by n-rodriguez** [comment]
Weird...

**Comment by sabarish14** [comment]
Any idea on how to proceed now?

**Comment by n-rodriguez** [comment]
There might be something wrong in your installation, but I don't know what.
I've never worked with Bitnami stack so maybe someone else could help you.

**Comment by n-rodriguez** [comment]
As root :

```
root# yum groupinstall "Development Tools"
root# yum install libssh2 libssh2-devel cmake libgpg-error-devel
```

Then as Redmine :

```
redmine$ cd REDMINE_ROOT
redmine$ gem uninstall gitolite-rugged
redmine$ bundle install --without development test
```

Restart Redmine.
