### ISSUE TITLE
"My public keys" link is still missing the subpath

### ISSUE THREAD

**Issue by Phiber2000** [jbox-web/redmine_git_hosting#368]
According to #340, I upgraded from v1.0.0 to v1.0.1 successfully. But the "My public keys" link is still missing the subpath.
As I wrote, I did a test upgrade to Redmine v3.0.0 and the link is complete. But the plugin seems to have a compatibility issues here (f.e. can't acces repository tab), so I still have to use Redmine v2.6.2.

**Comment by n-rodriguez** [comment]
> As I wrote, I did a test upgrade to Redmine v3.0.0 and the link is complete. But the plugin seems to have a compatibility issues here (f.e. can't acces repository tab), so I still have to use Redmine v2.6.2.

Work on Redmine 3.0 compatibility is in progress ;)

**Comment by Phiber2000** [comment]
Great! It isn't urgent.
In the meanwhile it's done by using the admin panel or inserting the missing subpath manually.

Maybe nice to know:
* Debian wheezy
* Redmine version 2.6.2.stable
* Ruby version 1.9.3-p194
* Rails version 3.2.21
* Database adapter Mysql2
* redmine_bootstrap_kit 0.2.0
* redmine_git_hosting 1.0.1
* nginx 1.6.2
* Phusion Passenger 4.0.59

nginx mode:           HTTPS only
repository access:    via SSH & HTTPS

**No changes in any files had to be made!**

That's the **only** bug I got reported in the last two weeks.
Repository access and redmine notification works like a charm. That's how to have fun at work.

In production environment I upgraded from v0.7.6 **following the migration instructions**, in a test environment I did a clean install - no problems at all.
Great job, awesome plugin!

**Comment by n-rodriguez** [comment]
> Great job, awesome plugin!

Thank you :)

Btw, note that the support of Ruby 1.9.3 has ended : https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

**Comment by Phiber2000** [comment]
Unfortunately **not** fixed by 8263b072ba478dd8f18fa6e6fcc4adf785c0bce7.

**Comment by Phiber2000** [comment]
Unfortunately 8263b072ba478dd8f18fa6e6fcc4adf785c0bce7 is **no** fix for Redmine v2.6.2.

**Comment by n-rodriguez** [comment]
> Unfortunately 8263b07 is no fix for Redmine v2.6.2.

Weird... I've done some tests and it seems to work :

in ```config/routes.rb``` :

```
Redmine::Utils::relative_url_root = "/redmine"

RedmineApp::Application.routes.draw do
scope Redmine::Utils::relative_url_root do
# RedmineApp::Application.routes.draw do
  root :to => 'welcome#index', :as => 'home'
  ....
end
end
```

```redmine$ rake routes``` :

```
...
                           public_keys GET          /redmine/my/public_keys(.:format)                                                              gitolite_public_keys#index
                                       POST         /redmine/my/public_keys(.:format)                                                              gitolite_public_keys#create
                        new_public_key GET          /redmine/my/public_keys/new(.:format)                                                          gitolite_public_keys#new
                       edit_public_key GET          /redmine/my/public_keys/:id/edit(.:format)                                                     gitolite_public_keys#edit
                            public_key GET          /redmine/my/public_keys/:id(.:format)                                                          gitolite_public_keys#show
                                       PUT          /redmine/my/public_keys/:id(.:format)                                                          gitolite_public_keys#update
                                       DELETE       /redmine/my/public_keys/:id(.:format)                                                          gitolite_public_keys#destroy
      download_git_revision_repository GET          /redmine/repositories/:id/download_revision(.:format)                                          download_git_revision#index
                 repository_git_extras PUT          /redmine/repositories/:repository_id/git_extras(.:format)                                      repository_git_extras#update
          repository_git_notifications POST         /redmine/repositories/:repository_id/git_notifications(.:format)                               repository_git_notifications#create
      new_repository_git_notifications GET          /redmine/repositories/:repository_id/git_notifications/new(.:format)                           repository_git_notifications#new
     edit_repository_git_notifications GET          /redmine/repositories/:repository_id/git_notifications/edit(.:format)                          repository_git_notifications#edit
                                       GET          /redmine/repositories/:repository_id/git_notifications(.:format)                               repository_git_notifications#show
                                       PUT          /redmine/repositories/:repository_id/git_notifications(.:format)                               repository_git_notifications#update
                                       DELETE       /redmine/repositories/:repository_id/git_notifications(.:format)                               repository_git_notifications#destroy
          repository_post_receive_urls GET          /redmine/repositories/:repository_id/post_receive_urls(.:format)                               repository_post_receive_urls#index
                                       POST         /redmine/repositories/:repository_id/post_receive_urls(.:format)                               repository_post_receive_urls#create
       new_repository_post_receive_url GET          /redmine/repositories/:repository_id/post_receive_urls/new(.:format)                           repository_post_receive_urls#new
...
```

**Comment by n-rodriguez** [comment]
![capture d ecran de 2015-02-25 19 48 44](https://cloud.githubusercontent.com/assets/3433835/6377894/c0413ca6-bd27-11e4-9c68-a3edeb9a39fa.png)

**Comment by Phiber2000** [comment]
In your answer was the hint for solving the problem.
I added the "relative_url_root" lines in Redmines routes.rb. But to get it working correctly I had to remove the passenger_base_uri from the nginx virtual host definition of the redmine page.
I don't think, that's the "clean" way (in older version of your plugin it wasn't necessary - in Redmine 3.x won't be too) - but it works!
Thanks a lot!!

**Comment by n-rodriguez** [comment]
I found another solution : https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#deploying_rack_to_sub_uri

**Comment by Phiber2000** [comment]
Unfortunately that's already the way It was configured before, too.

**Comment by Phiber2000** [comment]
1. Problem's gone using Redmine v3.x since Git hosting plugin got compatible with e206d1de508ab9b197209c769e0fbe40cea7d7f8 (1.0.2).
2. If Redmine v2.x has to be used, cf276cd65584a59eb9e6e500bca7a3dcb97b460b still had to be applied here.

My conclusion:
* The issue seems to be caused by a Redmine bug and how v2.x handles the hook - not by the plugin!
* Plugins version 1.0.2 released 2 days ago allowed me to migrate to Redmine v3.x - so the plugin developer did a great job again!

**Comment by mqu** [comment]
hello,

I am having same problem with a fresh install with Redmine 3.2 and redmine_git_hosting 1.2.0.

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.0
```

**Comment by Phiber2000** [comment]
Try this fix: https://github.com/Phiber2000/redmine_git_hosting/commit/f9aa20c17914c16e7143e1c72aaf3c8931ad67a6

**Comment by mqu** [comment]
thanks Phiber2000.
