### ISSUE TITLE
Automatic Repository Initialization not fired

### ISSUE THREAD

**Issue by chadyred** [jbox-web/redmine_git_hosting#370]
Hello, I try to make the ' Automatic Repository Initialization'. So i did this

<pre>
root$ su - git
git$ vi (or nano) .gitolite.rc

## Look for GIT_CONFIG_KEYS and make it look like :
GIT_CONFIG_KEYS                 =>  '.*',

## Enable local code directory
LOCAL_CODE  =>  "$ENV{HOME}/local"

## then save and exit
</pre>

And then I try like it indicate in the tuto : 

<pre>
To make it work you must allow Redmine Admin key to write on every repo :

First declare the Gitolite Admin SSH key in .ssh/config to easily clone/push :

root$ su - redmine
redmine$ vi .ssh/config
* [add this]
Host localhost
  User git
  IdentityFile /home/redmine/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa
  IdentitiesOnly yes
Then clone Gitolite Admin repository :

redmine$ git clone ssh://git@localhost:<PORT>/gitolite-admin.git /tmp/gitolite-admin-temp
Then edit gitolite.conf file to add this :

redmine$ cd /tmp/gitolite-admin-temp
redmine$ vi conf/gitolite.conf
* [add this]
repo    @all
  RW+                            = redmine_gitolite_admin_id_rsa
Finally commit and push :

redmine$ git commit -a -m 'Allow Redmine Key to access all repositories'
redmine$ git push -u origin master
</pre>

But it seems that when I create a new project with the option 'Create a repository with the created project',  I have a message that indicate 'Gitolite disable , can't create the repository' !

However, all is ok. I create un .git repo in 'repositories' folder, and I initialize this folder when I clone with a user, and I commit change on this repo. Then I references this repositorie in a project and all commit appear !

TO summeries : The last thing I'll do is to realizethe Automatic Repository Initialization!

**Comment by chadyred** [comment]
Forever "Gitolite repositories are disabled, cannot create repository!"

I notice that I don't see this in my config

<pre>
 /data/redmine/redmine/plugins/redmine_git_hosting/bin/run_git_cmd_as_gitolite_user 
</pre>

What is missing to have this?

**Comment by chadyred** [comment]
It's what I thank, I took 0.7.9 version and all is good : I have the 'bin' repo with 

gitolite_admin_ssh and run_git_cmd_as_gitolite_user  and run_shell_cmd_as_gitolite_user.

A project create a repository for project but it's in repositories/project_name.git and in my apache log : 

<pre>
   App 29958 stderr: fatal: Not a git repository: 'repositories/aaaa.git'
</pre>

And when I run a manual creation with 

<pre>
rails runner "Repository.fetch_changesets" -e production
</pre>

No error....I have all check in Redmine conf tab in Redmine Git Hosting. Just "Repository identifiers are globally unique?" is unchecked test are all green and I have in Admin > Settings > Repositories : 

<pre>
Git     /opt/redmine/plugins/redmine_git_hosting/bin/run_git_cmd_as_gitolite_user
</pre>

All seems be good, but the folder are not create in repositories folder...

**Comment by n-rodriguez** [comment]
https://jbox-web.github.io/redmine_git_hosting/about/releases-notes/#toc-release-1-0-0

**Comment by chadyred** [comment]
All right : 

<pre>
The plugin doesn’t override Repository::Git object anymore. Instead it introduces a new type of repository in Redmine : Gitolite repositories.
</pre>

My main purpose is to know how can I create automatic repository in Redmine with the 1.0.1 plugin version?
However, the configuration with the 0.7.9 plugin version works fine! 

So, What should I do to make the Automatic Repository Creating work? The configuration is not the same because the shell command is not launch like before...

**Comment by n-rodriguez** [comment]
> My main purpose is to know how can I create automatic repository in Redmine with the 1.0.1 plugin version?

What you did in a first place is right (first post of this issue) but you need to enable Gitolite repositories in  *Administration -> Settings -> Repositories*.

**Comment by chadyred** [comment]
Yes, the checkbox Git was already checked : 
<pre>
" /opt/redmine/plugins/redmine_git_hosting/bin/run_git_cmd_as_gitolite_use"
</pre>

I'm checking "Enable WS for repository management" to test it.

 However, the repositories which is created is "repositories/myProject.git" which not exist, so an error
is fired...
I want to create "/opt/gitolite/repositories/myProject.git". 
My config Redmine Git Hosting > Storage > Gitolite repositories base path? "./repositories/ 

Yeah, I think I'm closer to solve this! Maybe a permission problem ?
Is it another way to configure this path and make it fired?

**Comment by n-rodriguez** [comment]
> Yes, the checkbox Git was already checked :

Actually you must enable **Xitolite** repositories.

**Comment by chadyred** [comment]
I don't have this checkbox...see all my checkbox, this Xitolite checkbox should be here?

![gitolite_no_xitolite](https://cloud.githubusercontent.com/assets/5954673/6473043/dd54a41c-c1f6-11e4-8ab0-3df643be4368.png)

**Comment by n-rodriguez** [comment]
Ok. You rolled back to 0.7. Try with 1.0.1 version it shoud work..

**Comment by chadyred** [comment]
I rolled back because I don't have the bin repository, and I think it's because of that I don't have Gitolite active ! It will be cool to indicate exactly 'Check Xitolite check box' for dummy like me  ;)

![gitolite_yes_xitolite](https://cloud.githubusercontent.com/assets/5954673/6473441/ac75456a-c1f9-11e4-83a8-ac12086fcbca.png)

...but I can't see the path next to git, he disappear after go to 1.0.1 version, is it the way of this new version, like you said 'Not override Repository::Git object" ?

This folder is useless here? Because I still have it.

**Comment by n-rodriguez** [comment]
> This folder is useless here? Because I still have it.

Yes. You can safely remove it.

**Comment by n-rodriguez** [comment]
> but I can't see the path next to git, he disappear after go to 1.0.1 version

It's normal. We don't need scripts anymore.

**Comment by chadyred** [comment]
A last thing : the repository seems to be create but not initialize. However, I have check this in configuration, with the creation of a README file. It's not important, but I want to know if it's just easy or not to make it works?

**Comment by n-rodriguez** [comment]
> but I want to know if it's just easy or not to make it works?

It should be easy to do : check that Redmine public key is present in ```gitolite.conf```. It should be sufficient to work.

**Comment by n-rodriguez** [comment]
> It will be cool to indicate exactly 'Check Xitolite check box' for dummy like me ;)

Done : https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-8-finish-installation---configuration

**Comment by chadyred** [comment]
Good job ! ;)

So I check the /opt/gitolite/repositories but the repository are not on it, so I lauch manually the 
command 

<pre>
rails runner "Repository.fetch_changesets" -e production
</pre>

And i have

<pre>
fatal: Not a git repository: 'repositories/jus.git'
</pre>

But in the repository tab of the project I don't have an error like before, I've got the rules to create the repository (git init -> touch README...) 

In my <pre>gitolite.conf</pre>, I've got this 

<pre>
repo gitolite-admin
    RW+     =   redmine_gitolite_admin_id_rsa

repo testing
    RW+     =   @all

repo @all
     RW+    = redmine_gitolite_admin_id_rsa
</pre>

The @all seems to be not use, because the repositories is not really created physically in the /opt/gitolite/repositories folder.

**Comment by n-rodriguez** [comment]
> The @all seems to be not use, because the repositories is not really created physically in the /opt/gitolite/repositories folder.

This is an other issue. Check your Gitolite conf (in ```<git user home>/.gitolite.rc```). Be sure that ```no-auto-create``` is commented.
Also can you provide some logs of repository creation? (in ```<redmine dir>/log/git_hosting.log```)
