### ISSUE TITLE
compatible to Redmine 3.0.0

### ISSUE THREAD

**Issue by henhof** [jbox-web/redmine_git_hosting#371]
Hi,

at first this is a very good tool. I love it.

Now we planed to upgrade from Redmine 2.5.1 to the newer version 3.0.0. Actually we use the plugin version 0.7.6. Is this or the actually version (1.0.1) compatible to Redmine 3.0.0?

Because I get some errors while "bundle exec rake db:migrate RAILS_ENV=production".
```
/home/redmine/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/.rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
```
While the gem update, there also an mismatch with "'redcarpet', '~> 2.3.0'" and "redcarpet", "~> 3.1.2"

Thanks and best regards.

**Comment by Trim** [comment]
Hello,

The errors were already reported in #354 and fixed in the dev branch.
Apparently, the fixes are included in the next stable [1.0.2](http://jbox-web.github.io/redmine_git_hosting/about/releases-notes/#toc-release-1-0-2).

**Comment by n-rodriguez** [comment]
> Is this or the actually version (1.0.1) compatible to Redmine 3.0.0?

Nope. The 1.0.2 will.

**Comment by geno2k8** [comment]
Hello guys,
i don't want open a new issu, so i will post it under this topic. I resolve the "redcarpet" issu but now i get the following error:

<pre>
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    gitlab-grack (>= 0) ruby depends on
      rack (~> 1.4.1) ruby

    rails (= 4.2.0) ruby depends on
      railties (= 4.2.0) ruby depends on
        actionpack (= 4.2.0) ruby depends on
          rack (1.6.0)
</pre>

rails version: 4.2.0
ruby version: 2.1.1
redmine version: 3.0.0

Hope it will help to release 1.0.2 a little bit faster ;) Thx for this greate plugin.

**Comment by n-rodriguez** [comment]
> Hope it will help to release 1.0.2 a little bit faster ;) Thx for this greate plugin.

Actually it's already fixed in v1.x branch.
