### ISSUE TITLE
[ERROR] Failed to install Redmine Gitolite mirroring SSH keys !

### ISSUE THREAD

**Issue by chadyred** [jbox-web/redmine_git_hosting#372]
Hello,

In Config Test, everything else is green except Mirrors keys installed? 

I find this issue : https://github.com/jbox-web/redmine_git_hosting/issues/333

In case, I am indeed missing these:

git home dir/.ssh/redmine_gitolite_admin_id_rsa_mirroring
git home dir/.ssh/redmine_gitolite_admin_id_rsa_mirroring.pub
git home dir/.ssh/run_gitolite_admin_ssh

<strong>What exactly provides them, and when?</strong>

I think the second error is link to this first problem !

When I initilized my repostories like : 

<pre>
mkdir first_test
  cd first_test
  git init
  touch readme.txt
  git add readme.txt
  git commit -m 'Initializing first_test repository'
  git remote add origin ssh://git@my-redmine.com/aaaa/first_test.git
  git push -u origin master
</pre>

It prompt me the git's password. However, when I create the user I used the command: 

<pre>
adduser --system --shell /bin/bash --gecos 'Git Administrator' --group --disabled-password --home /opt/gitolite git
</pre>

This is my visudo file config. 

<pre>
# temp - *REMOVE* after installation
redmine    ALL=(ALL)      NOPASSWD:ALL
git        ALL=(ALL)      NOPASSWD:ALL

# redmine gitolite integration
redmine    ALL=(git)      NOPASSWD:ALL
git        ALL=(redmine)  NOPASSWD:ALL
</pre>

Of course, I'll remove  the three first line when all will be good !

Thanks.

**Comment by chadyred** [comment]
I try to make a password to git user but I have this error when I push : 

<pre>
git@my-redmine.com's password: 
fatal: '/aaaa/first_test.git.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
</pre>

**Comment by n-rodriguez** [comment]
> It prompt me the git's password. However, when I create the user I used the command:

It shouldn't ask for a password. Check your Gitolite installation : https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-3-user-running-redmine-must-have-rw-access-to-gitolite-admin

**Comment by n-rodriguez** [comment]
By the way... did you add your SSH key in Redmine and set you as a member of the project with the right to commit? (You must edit Redmine roles to add some permissions)

**Comment by chadyred** [comment]
Yes, i've done this !

**Comment by n-rodriguez** [comment]
> What exactly provides them, and when?

They are installed when you in *Administration -> Redmine Git Hosting*.
The result is put in cache.

**Comment by n-rodriguez** [comment]
> Yes, i've done this !

So it should not ask for a password...
Please recheck your installation with https://jbox-web.github.io/redmine_git_hosting/howtos/install

**Comment by chadyred** [comment]
My purpose is  re-try to install it in local but I've still other post problem before the last about the git's password wich was prompt.

In config test in Redmine all this section WAS red : 
Hooks installed?
Hooks parameters installed?
Mailer parameters installed?
Mirrors keys installed?

But all config is good I have

To resolve this I go to Hooks menu, and I clock on the 'Install hooks' lick on the right corner and all is good...can you write this in the documentation?

But one error : <b> Mirrors keys installed? stay red</b>.

So the initial problem is the same in local, mirrors don't want to be install...

**Comment by n-rodriguez** [comment]
Can you please provide some logs?

**Comment by n-rodriguez** [comment]
> To resolve this I go to Hooks menu, and I clock on the 'Install hooks' lick on the right corner and all is good...can you write this in the documentation?

You seem to be on devel branch. Can you do a git pull and retry? I've added some logs to track your issue.

**Comment by chadyred** [comment]
I have just this. 
<pre>
App 16138 stderr: fatal: Not a git repository: 'repositories/bbbbb.git'
App 16138 stderr: fatal: Not a git repository: 'repositories/bbbbb.git'
App 16138 stderr: fatal: Not a git repository: 'repositories/jus.git'
App 16138 stderr: fatal: Not a git repository: 'repositories/bbbbb.git'
</pre>

Anyway, it ask the password of git user, so I can't create repositories with my user. In each project, I have the user with his ssh key public within him! He is a developper and this roles has all checkbox check for repository option ! 

I think, I miss something, and I don't has mirrors key, do you think the problem could came bacause of this ?

Thanks !

**Comment by n-rodriguez** [comment]
> do you think the problem could came bacause of this ?

nope.

> Anyway, it ask the password of git user,

It should not... It means that the Gitolite SSH key you have declared in plugin settings don't match the one declared in Gitolite config file.

**Comment by chadyred** [comment]
So I pull your comme on devel branch and I have this : 

<pre>
2015-03-18 22:08:47 +0100 [INFO] Installing Redmine Gitolite mirroring SSH keys ...
2015-03-18 22:08:53 +0100 [INFO] Testing if Redmine user 'redmine' can sudo to Gitolite user 'git'...
2015-03-18 22:08:53 +0100 [INFO] OK!
2015-03-18 22:08:54 +0100 [INFO] Installing Redmine Gitolite mirroring SSH keys ...
2015-03-18 22:09:47 +0100 [INFO] Testing if Redmine user 'redmine' can sudo to Gitolite user 'git'...
2015-03-18 22:09:47 +0100 [INFO] OK!
2015-03-18 22:09:47 +0100 [INFO] Installing Redmine Gitolite mirroring SSH keys ...
2015-03-18 22:18:16 +0100 [INFO] Create tmp directory : '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-03-18 22:18:17 +0100 [INFO] Testing if Redmine user 'redmine' can sudo to Gitolite user 'git'...
2015-03-18 22:18:18 +0100 [INFO] OK!
2015-03-18 22:18:20 +0100 [INFO] Installing Redmine Gitolite mirroring SSH keys ...

</pre>

And then it stop and nothing, I have an error 500.

**Comment by n-rodriguez** [comment]
Can you paste the content of ```<redmine root dir>/log/production.log```. The 500 error should be logged here.

**Comment by chadyred** [comment]
Yes !

<pre>
Completed 500 Internal Server Error in 9915ms

ActionView::Template::Error (No such file or directory @ rb_sysopen - /opt/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa):
    36:
    37:   %tr
    38:     %td= l(:label_mirroring_keys_installed)
    39:     %td= image_tag (RedmineGitHosting::Config.mirroring_keys_installed?(reset: true) ? 'true.png' : 'exclamation.png')
    40:
    41:   %tr
    42:     %td= l(:label_git_version)
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__2574656213381535386_70085354060480'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__2574656213381535386_70085354060480'
  app/helpers/application_helper.rb:321:in `render_tabs'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__3725579448500126418_70085352620920'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__3725579448500126418_70085352620920'

</pre>

**Comment by n-rodriguez** [comment]
Ah!!
A Bitnami stack thing!
Ok you're gonna have move your ssh keys

**Comment by chadyred** [comment]
Yes, I had copy paste my .ssh/redmine_gitolite_admin_id_rsa and .ssh/redmine_gitolite_admin_id_rsa  in /opt/redmine/plugins/redmine_git_hosting/ssh_keys, is it a mistake?

**Comment by n-rodriguez** [comment]
> Yes, I had copy paste my .ssh/redmine_gitolite_admin_id_rsa and .ssh/redmine_gitolite_admin_id_rsa in /opt/redmine/plugins/redmine_git_hosting/ssh_keys, is it a mistake?

It depends.

What is the owner of the redmine directory?
Do you use Apache + Passenger?

**Comment by chadyred** [comment]
Yes I use apache with passenger, and redmine user is the redmine owner of the redmine directory !

**Comment by n-rodriguez** [comment]
And what user runs apache?

**Comment by n-rodriguez** [comment]
Maybe it will be easier to chat on Gitter : https://gitter.im/jbox-web/redmine_git_hosting#
It works with your Github account ;)

**Comment by n-rodriguez** [comment]
This was a permission issue.
Redmine runs with ```www-data``` so SSH keys must be readable for this user.
```
chmod 644 redmine_gitolite_admin_id_rsa
chmod 644 redmine_gitolite_admin_id_rsa.pub
```

Note that it's [not very secure](https://jbox-web.github.io/redmine_git_hosting/guide/redmine-installation/#why-not-apache)

**Comment by chadyred** [comment]
Thanks a lot, all is green now !
You are the best ! ;)
