### ISSUE TITLE
hooks/post-receive:9: undefined method `require_relative' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by nogo** [jbox-web/redmine_git_hosting#374]
I'm using redmine 2.6.2 and git_hosting 1.0.1. Any suggestion to this problem?
hooks/post-receive:9: undefined method `require_relative' for main:Object (NoMethodError)

**Comment by n-rodriguez** [comment]
Hi!

Check your Ruby version. I think you're using Ruby 1.8.

**Comment by nogo** [comment]
Hi maybe you are right, I'm using rvm und redmine is runing with ruby 2.1 but the git server has only the 1.8 I will check this.

**Comment by nogo** [comment]
So I checked the ruby version it is 2.1.5p273 and it is installed global. So the git server has the same version.

**Comment by n-rodriguez** [comment]
And? Does it work?

**Comment by nogo** [comment]
No it doesn't. The hook still bring this error. I deleted the hook folder, so that the plugin could install it again. But no change. The error remains.

**Comment by n-rodriguez** [comment]
Be careful, the hooks are called by ```#!/usr/bin/env ruby```.
Maybe it doesn't pick the right Ruby version.

**Comment by nogo** [comment]
Yeah I check this too and when I run /usr/bin/env ruby --version it is the same too. I used rvm to install the last version. Btw the server runs debian.

**Comment by n-rodriguez** [comment]
You have rvm in gitolite dir?

**Comment by nogo** [comment]
No I didn't. I Installed ruby globally.

**Comment by n-rodriguez** [comment]
And which Debian version?

**Comment by nogo** [comment]
Debian 6 Squezze

**Comment by n-rodriguez** [comment]
With Ruby 2.1?

**Comment by nogo** [comment]
Yes

**Comment by n-rodriguez** [comment]
You compiled it from the source or installed it by package?

**Comment by nogo** [comment]
I compile it with rvm.

**Comment by n-rodriguez** [comment]
Ok so it's not global. RVM is local to the user.

**Comment by nogo** [comment]
The package ist installed too. But when I run ruby --version as git user it shows 2.1.5

**Comment by n-rodriguez** [comment]
How do you switch to git user?

**Comment by nogo** [comment]
su - git

**Comment by n-rodriguez** [comment]
Is it a RVM mutli user installation ? https://rvm.io/rvm/install#installation-explained

**Comment by nogo** [comment]
Yes I installed, but maybe I fixed it now, when I execute rvm info there was a warning about the PATH. So I did rvm use as git user. I test it with a commit.

**Comment by nogo** [comment]
I'm sorry the error still remains. :(

**Comment by nogo** [comment]
Maybe I try to install rvm and ruby as single user installation, there could be an issue with my current installation.

**Comment by n-rodriguez** [comment]
You can give it try.

**Comment by nogo** [comment]
Bad news require_relative still not available. Maybe its too late for me today. Thanks for your time.

**Comment by n-rodriguez** [comment]
Last question :  what is the ruby version now?

**Comment by nogo** [comment]
ruby 2.1.5 at git and redmine user

**Comment by n-rodriguez** [comment]
> ruby 2.1.5 at git and redmine user

This is really really weird. Here another example of the same issue but there is no solution except reinstalling ruby/rvm : http://stackoverflow.com/questions/18934716/undefined-method-require-relative-for-mainobject-nomethoderror

**Comment by nogo** [comment]
I took a look to #388 and fix the hook path to the installed ruby version and now it work. Something with the "env" is not working correctly.
