### ISSUE TITLE
smart http link is not properly generated when redmine is installed in a sub-path

### ISSUE THREAD

**Issue by slawo** [jbox-web/redmine_git_hosting#375]
When accessing to the repositories tab in redmine from the following address: `https://intranet.mysite.com/projects/projects/product10/repository`.
The ssh link is properly generated: `ssh://git@repo.mysite.com/client1/project/product10.git`.
The https link is not: `https://user@repo.mysite.com/projects/client1/project/product10.git`.

Might be redmine's root path being intranet.mysite.com/projects/ messing the https link generation.

**Comment by n-rodriguez** [comment]
> The https link is not: https://user@repo.mysite.com/projects/client1/project/product10.git.

What do you mean? Does clone over http work?

**Comment by slawo** [comment]
Yes, but at the right address: `https://user@repo.mysite.com/client1/project/product10.git`. The address shown in redmine is this: `https://user@repo.mysite.com/**projects**/client1/project/product10.git`

**Comment by n-rodriguez** [comment]
Which version of the plugin are you using?

**Comment by slawo** [comment]
```
git describe --tags
1.0.1-36-ga3c7205
git rev-parse HEAD
a3c7205def2c396a60901c8a8bd40b054bed8456
```

**Comment by n-rodriguez** [comment]
Fixed by commit : https://github.com/jbox-web/redmine_git_hosting/commit/af4c3e8148dd73777399418250034c8c7fdf3bb8

**Comment by slawo** [comment]
Nice!
Thank you!
