### ISSUE TITLE
Bitnami Stack : Error on install undefined symbol: libssh2_session_init_ex

### ISSUE THREAD

**Issue by ibestrest** [jbox-web/redmine_git_hosting#376]
Migrating redmine_git_hosting (Redmine Git Hosting Plugin)...
    == 20111123214911 AddSettingsToPlugin: reverting ==============================
    /opt/bitnami/ruby/bin/.ruby.bin: symbol lookup error:         /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/lib/rugged/rugged.so:     undefined symbol: libssh2_session_init_ex

Redmine 3.0.0.stable

	Environment:
	  Redmine version                3.0.0.stable
	  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
	  Rails version                  4.2.0
	  Environment                    production
	  Database adapter               Mysql2
	SCM:
	  Subversion                     1.8.10
	  Cvs                            1.12.13
	  Git                            1.9.5
	  Filesystem                     
	Redmine plugins:
	  redmine_bootstrap_kit          0.2.1
	  redmine_git_hosting            1.0.2

**Comment by n-rodriguez** [comment]
As root :

```
root# yum groupinstall "Development Tools"
root# yum install libssh2 libssh2-devel cmake libgpg-error-devel
```

Then as Redmine :

```
redmine$ cd REDMINE_ROOT
redmine$ gem uninstall gitolite-rugged
redmine$ bundle install --without development test
```

Restart Redmine.

**Comment by ibestrest** [comment]
thanks for the reply.
On my server installed `Ubuntu 14.04.2 LTS`. I checked, the following (`libssh2-1, libssh2-1-dev`) packages are already installed. 
May need to specify the path to the library? What could be wrong?

**Comment by n-rodriguez** [comment]
And ```cmake libgpg-error-devel```?

**Comment by ibestrest** [comment]
Yes

**Comment by n-rodriguez** [comment]
Try to find this file : ```redmine$ /home/redmine/.rvm/gems/ruby-2.1.4/extensions/x86_64-linux/2.1.0/rugged-0.21.4/gem_make.out.``` It contains the compilation logs for Rugged. Can you post the content here?

**Comment by ibestrest** [comment]
I could not find logs for Rugged.

	root@redmine:~# find / -name "gem_make.out"
	/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0-static/nokogiri-1.6.6.2/gem_make.out
	/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0-static/mysql2-0.3.14/gem_make.out
	/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0-static/redcarpet-3.1.2/gem_make.out
	/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0-static/rmagick-2.13.4/gem_make.out
	/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0-static/json-1.8.2/gem_make.out
	/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/cmake-2.8.7/ext/cmake/gem_make.out

	root@redmine:~# find / -name "rugged"
	/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/ext/rugged
	/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/lib/rugged
	/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rugged-0.21.4/ext/rugged
	/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rugged-0.21.4/lib/rugged

**Comment by n-rodriguez** [comment]
What is the content of these directories :

```
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/ext/rugged
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/lib/rugged
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rugged-0.21.4/ext/rugged
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rugged-0.21.4/lib/rugged
```

**Comment by ibestrest** [comment]
I tried to install the `install rugged - --use-system-libraries`. 

	ls /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/ext/rugged
	extconf.rb       rugged_branch_collection.c  rugged_cred.c        rugged_diff_line.o  rugged_object.c                rugged_remote.c             rugged_settings.c        rugged_tag.o
	Makefile         rugged_branch_collection.o  rugged_cred.o        rugged_diff.o       rugged_object.o                rugged_remote_collection.c  rugged_settings.o        rugged_tree.c
	mkmf.log         rugged_branch.o             rugged_diff.c        rugged.h            rugged_patch.c                 rugged_remote_collection.o  rugged_signature.c       rugged_tree.o
	rugged_blame.c   rugged.c                    rugged_diff_delta.c  rugged_index.c      rugged_patch.o                 rugged_remote.o             rugged_signature.o
	rugged_blame.o   rugged_commit.c             rugged_diff_delta.o  rugged_index.o      rugged_reference.c             rugged_repo.c               rugged.so
	rugged_blob.c    rugged_commit.o             rugged_diff_hunk.c   rugged_note.c       rugged_reference_collection.c  rugged_repo.o               rugged_tag.c
	rugged_blob.o    rugged_config.c             rugged_diff_hunk.o   rugged_note.o       rugged_reference_collection.o  rugged_revwalk.c            rugged_tag_collection.c
	rugged_branch.c  rugged_config.o             rugged_diff_line.c   rugged.o            rugged_reference.o             rugged_revwalk.o            rugged_tag_collection.o

	ls /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/lib/rugged
	branch.rb  commit.rb  console.rb  credentials.rb  diff  diff.rb  index.rb  object.rb  patch.rb  reference.rb  remote.rb  repository.rb  rugged.so  tag.rb  tree.rb  version.rb  walker.rb


	ls /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rugged-0.21.4/ext/rugged
	extconf.rb       rugged_branch_collection.c  rugged_cred.c        rugged_diff_line.o  rugged_object.c                rugged_remote.c             rugged_settings.c        rugged_tag.o
	Makefile         rugged_branch_collection.o  rugged_cred.o        rugged_diff.o       rugged_object.o                rugged_remote_collection.c  rugged_settings.o        rugged_tree.c
	mkmf.log         rugged_branch.o             rugged_diff.c        rugged.h            rugged_patch.c                 rugged_remote_collection.o  rugged_signature.c       rugged_tree.o
	rugged_blame.c   rugged.c                    rugged_diff_delta.c  rugged_index.c      rugged_patch.o                 rugged_remote.o             rugged_signature.o
	rugged_blame.o   rugged_commit.c             rugged_diff_delta.o  rugged_index.o      rugged_reference.c             rugged_repo.c               rugged.so
	rugged_blob.c    rugged_commit.o             rugged_diff_hunk.c   rugged_note.c       rugged_reference_collection.c  rugged_repo.o               rugged_tag.c
	rugged_blob.o    rugged_config.c             rugged_diff_hunk.o   rugged_note.o       rugged_reference_collection.o  rugged_revwalk.c            rugged_tag_collection.c
	rugged_branch.c  rugged_config.o             rugged_diff_line.c   rugged.o            rugged_reference.o             rugged_revwalk.o            rugged_tag_collection.o

	ls /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rugged-0.21.4/lib/rugged
	branch.rb  commit.rb  console.rb  credentials.rb  diff  diff.rb  index.rb  object.rb  patch.rb  reference.rb  remote.rb  repository.rb  rugged.so  tag.rb  tree.rb  version.rb  walker.rb

**Comment by n-rodriguez** [comment]
Can you provide access to the server?

**Comment by ibestrest** [comment]
Yes of course. Tell your ssh key? You can send to my email. zhelonkinanton@gmail.com

**Comment by n-rodriguez** [comment]
I found it :

```
Gem files will remain installed in /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4 for inspection.
Results logged to /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/ext/rugged/gem_make.out
An error occurred while installing rugged (0.21.4), and Bundler cannot continue.
Make sure that `gem install rugged -v '0.21.4'` succeeds before bundling.
bitnami@redmine:~/apps/redmine/htdocs$ cat /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rugged-0.21.4/ext/rugged/gem_make.out
/opt/bitnami/ruby/bin/ruby extconf.rb --use-system-libraries
checking for cmake... yes
checking for gmake... no
checking for make... yes
checking for pkg-config... yes
Building Rugged using system libraries.
libgit2 version is not compatible
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/bitnami/ruby/bin/ruby
	--use-system-libraries
	--with-git2-dir
	--without-git2-dir
	--with-git2-include
	--without-git2-include=${git2-dir}/include
	--with-git2-lib
	--without-git2-lib=${git2-dir}/
	--with-libgit2-config
	--without-libgit2-config
	--with-pkg-config
	--without-pkg-config
```

**Comment by n-rodriguez** [comment]
root@redmine:/opt/bitnami/apps/redmine/htdocs/plugins/redmine_git_hosting# dpkg -l | grep libgit
ii  libgit2-0:amd64                               0.19.0-2                         amd64        low-level Git library
ii  libgit2-dev:amd64                             0.19.0-2                         amd64        low-level Git library (development files)

**Comment by n-rodriguez** [comment]
This a Bitnami Stack thing. Here the solution : http://jbox-web.github.io/redmine_git_hosting/guide/bitnami-installation/

**Comment by jak103** [comment]
The link posted on Mar 13 pulls up a 404. Can you post an updated link? Thanks!

**Comment by n-rodriguez** [comment]
@jak103 done!
