### ISSUE TITLE
Config Test ("Git user is able to sudo to Redmine user?") not correcly displayed

### ISSUE THREAD

**Issue by nicesw123** [jbox-web/redmine_git_hosting#377]
Hi there, 

I've just installed release 1.0.1 **under Apache (under Debian jessie** [stable soon!]), so my **Redmine user is `www-data`**

Everything is working correcly.

But - as far as I can tell - the Config Test regarding "Git user is able to sudo to Redmine user?" is **displayed incorrectly** ...
![config_test](https://cloud.githubusercontent.com/assets/7419913/6572175/6dab448a-c710-11e4-9fac-450d8fe4a0c0.png)

* `/etc/sudoers.d/redmine_git_hosting`
 is correct

 ```
 www-data     ALL=(git)       NOPASSWD:ALL
 git     ALL=(www-data)       NOPASSWD:ALL
 ```
 as it should be.

* Testing **sudo manually** is also *perfect*, if care is taken...:

 ```
### Test git -> sudo to -> www-data
###################################
USR@redminedebian:~$ sudo su - git

git@redminedebian:~$ sudo -u www-data -i whoami
              This account is currently not available.                ### OOPS!!!!
         ### This is because 
         ### login-shell of www-data is now (new!): /usr/sbin/nologin
         ### So instead do this:

git@redminedebian:~$ sudo -u www-data whoami                      ### works perfectly
              www-data
git@redminedebian:~$ exit


### Test www-data -> sudo to -> git
###################################
USR@redminedebian:~$ sudo su - www-data
             This account is currently not available.                 ### OOPS!!!!
         ### This is because 
         ### login-shell of www-data is now (new!): /usr/sbin/nologin
         ### So instead do this:

USR@redminedebian:~$ sudo -u www-data      sudo -u git whoami     ### works perfectly
              git


### Test both directions, in one step! ;)
###################################
USR@redminedebian:~$ sudo su - git
git@redminedebian:~$ sudo -u www-data     sudo -u git   sudo -u www-data  whoami  ### works perfectly
              www-data
 ```
 
 So note this **difference regarding login-shell** of `www-data`, between Debian Wheezy and Debian Jessie
 
 ```
### Debian Wheezy (using Apache 2.2) ############
USR@my_wheezy:~$ cat /etc/passwd | grep www-data
           www-data:x:33:33:www-data:/var/www:/bin/sh

### Debian Jessie (using Apache 2.4) NEW!! ############
USR@my_jessie:~$ cat /etc/passwd | grep www-data
           www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
 ```

.
.

I suspect (??) the Config Test, may try to sudo from git to a shell-of-`www-data`. This will not work.
Oh hey, I've found the spot in the code:

[redmine_git_hosting/lib/redmine_git_hosting/config/gitolite_config_tests.rb#L81](https://github.com/jbox-web/redmine_git_hosting/blob/3dd0f55af610b5b918fcc3ef10cb7583255debc8/lib/redmine_git_hosting/config/gitolite_config_tests.rb#L81)

I would probably change it to:
```
 RedmineGitHosting::Commands.sudo_capture('sudo', '-n', '-u', redmine_user, 'whoami')
```

The `-i` flag opens a login-shell, but for new Apache on Debian (jessie and newer) ... the login-shell is disabled (so leave the `-i` flag away)

(Hmmm... Are there any other *related* code-spots that need to be fixed because of this? hmmm)

**Comment by nicesw123** [comment]
Oh... in the same way, I would also update

https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-2-create-ssh-keys-for-user-running-redmine

to the following:
```
root$ sudo -u redmine ssh-keygen -N '' -f REDMINE_ROOT/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa
```

(Good for those user's like me, who have `www-data` as `redmine` user)

**Comment by n-rodriguez** [comment]
> (Hmmm... Are there any other related code-spots that need to be fixed because of this? hmmm)

https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/redmine_git_hosting/commands.rb#L136

**Comment by nicesw123** [comment]
Hi Nicolas,



>> (Hmmm... Are there any other related code-spots that need to be fixed because of this? hmmm)

> https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/redmine_git_hosting/commands.rb#L136

When sudoing **from redmine (www-data) into the git** user, `-i` is **ok**:
```
### Test www-data -> sudo to -> git
###################################
root@redminedebian:~$ sudo -n -u www-data      sudo -n -u git -i whoami     ### perfect
          git                                                #^^
```
(Therefore the code you mention [commands.rb#L136](https://github.com/jbox-web/redmine_git_hosting/blob/c428f6070640ed1db6c7c14acdab82e2a6dfa96a/lib/redmine_git_hosting/commands.rb#L136) is ok!)

But when sudoing **from git into redmine (www-data)**, then `-i` **should not be used** (->because in Debian Jessie... www-data has /usr/sbin/nologin):
```
### Test git -> sudo to -> www-data
###################################
root@redminedebian:~$ sudo -n -u git -i      sudo -n -u www-data    whoami     ### perfect
          www-data                                              #^^
```
Therefore the following should be changed:
[gitolite_config_tests.rb#L81](https://github.com/jbox-web/redmine_git_hosting/blob/3dd0f55af610b5b918fcc3ef10cb7583255debc8/lib/redmine_git_hosting/config/gitolite_config_tests.rb#L81)
[create-ssh-keys-for-user-running-redmine](https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-2-create-ssh-keys-for-user-running-redmine)

**Comment by n-rodriguez** [comment]
> Therefore the code you mention commands.rb#L136 is ok!. But when sudoing from git into redmine (www-data), then -i should not be used (->because in Debian Jessie... www-data has /usr/sbin/nologin):

Thanks for this precisions. But this makes me realize that the sudo test **git -> redmine** is quiet useless as we never execute shell commands in this 'direction'.

**Comment by n-rodriguez** [comment]
This test is here for historical reasons, but I think it should even work without having the sudo config for the git user.

**Comment by nicesw123** [comment]
Ah ok, right! ;) Hehe
The "source" is redmine (via webbrowser) and this triggers to git when needed.

**Comment by n-rodriguez** [comment]
> The "source" is redmine (via webbrowser) and this triggers to git when needed.

Yes

**Comment by nicesw123** [comment]
If this is so, then 
https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-5-configure-sudo
can probably also become one line shorter:
```
root$ visudo
# Add these lines
redmine        ALL=(git)      NOPASSWD:ALL
```

**Comment by n-rodriguez** [comment]
Exactly. I'm testing it right now.

**Comment by nicesw123** [comment]
Cool, thanks a lot!

**Comment by nicesw123** [comment]
Ok great.

Just note: the following could also be updated:
https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-2-create-ssh-keys-for-user-running-redmine

to the following:
```
root# sudo -u redmine ssh-keygen -N '' -f REDMINE_ROOT/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa
```
