### ISSUE TITLE
New Git repo not created

### ISSUE THREAD

**Issue by sabarish14** [jbox-web/redmine_git_hosting#379]
When I try to create  a new git repository, the repository is created in UI.But internally, I couldnt see any repo.My git hosting .log looks like this:
```
2015-03-11 16:36:18 -0500 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-03-11 16:36:18 -0500 [ERROR] Failed to authenticate SSH session: Unable to open public key file
```
Kindly help me out

**Comment by n-rodriguez** [comment]
Check your public/private key path in *Administration -> Redmine Git Hosting -> SSH Access*.
They must exist and be readable by Redmine user.

**Comment by sabarish14** [comment]
Thank you.Now it says Failed to authenticate SSH session:Callback returned error

**Comment by n-rodriguez** [comment]
Do you have more logs?

**Comment by sabarish14** [comment]
When I do config test, I get this error:

2015-03-11 16:56:05 -0500 [INFO] Installing Redmine Gitolite mirroring SSH keys ...
2015-03-11 16:56:05 -0500 [ERROR] Failed to install Redmine Git Hosting mirroring SSH private key !
2015-03-11 16:56:05 -0500 [ERROR] Error while getting Gitolite infos
2015-03-11 16:56:12 -0500 [ERROR] Git exited with non-zero status : 128

Then when I create the repo,I get this error:
2015-03-11 17:01:32 -0500 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-03-11 17:01:32 -0500 [ERROR] Failed to authenticate SSH session: Callback returned error
2015-03-11 17:01:44 -0500 [INFO] User 'redmine' created a new repository 'check/git'
2015-03-11 17:01:44 -0500 [INFO] Create tmp directory : '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-03-11 17:01:44 -0500 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-03-11 17:01:44 -0500 [ERROR] Failed to authenticate SSH session: Callback returned error
Is mirroring SSH keys anything to do with this?

**Comment by n-rodriguez** [comment]
Did you try to restart Redmine?

**Comment by sabarish14** [comment]
I tried restarting redmine.I get the same error.

**Comment by n-rodriguez** [comment]
As Redmine user can you test this command?

```ssh -i REDMINE_ROOT/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info```

**Comment by chukhman** [comment]
Hi, I'm collaborating with Sabarish on this project. and so when I try to run it, I don't  have anything in that folder that strikes me as a redmine_gitolite_admin_id_rsa:

this folder /usr/share/redmine/plugins/redmine_git_hosting/ssh_keys/
only has these files: .placeholder  www-data      www-data.pub

the redmine user is www-data; we're not talking about the www-data.pub key, are we?

When I use www-data.pub I still get asked for a password and here is the output I get:

www-data@redminegit:~$ ssh -i /usr/share/redmine/plugins/redmine_git_hosting/ssh_keys/www-data.pub git@localhost info
Could not create directory '/var/www/.ssh'.
The authenticity of host 'localhost (::1)' can't be established.
ECDSA key fingerprint is 74:ce:66:18:ab:64:41:01:c9:eb:9b:6c:f1:6e:74:e5.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts (/var/www/.ssh/known_hosts).
Enter passphrase for key '/usr/share/redmine/plugins/redmine_git_hosting/ssh_keys/www-data.pub':
git@localhost's password:
hello www-data, this is git@redminegit running gitolite3 v3.6.2-20-g78fc240 on git 1.9.1

 R W    gitolite-admin
 R W    testing
www-data@redminegit:~$

**Comment by n-rodriguez** [comment]
> Enter passphrase for key '/usr/share/redmine/plugins/redmine_git_hosting/ssh_keys/www-data.pub':

This key **must** not have a passphrase : https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-2-create-ssh-keys-for-user-running-redmine

> git@localhost's password:

User git should not have a password too. If the above works it should not ask for it.

**Comment by sabarish14** [comment]
Hi,
When I create a new repo in Settings ,I get this error now:
Rugged::NetworkError (Early EOF):
  /var/lib/gems/1.9.1/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone_at'
  /var/lib/gems/1.9.1/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone'
  /var/lib/gems/1.9.1/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:110:in `initialize'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `new'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:66:in `gitolite_admin'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:38:in `resync_gitolite'
  plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:50:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:97:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:27:in `create_repository'
  plugins/redmine_git_hosting/app/use_cases/create_repository.rb:64:in `create_repository'
  plugins/redmine_git_hosting/app/use_cases/create_repository.rb:16:in `call'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:89:in `call_use_cases'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:46:in `create_with_git_hosting'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:502:in `_run__1041882404386624270__process_action__2181869793736074720__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'

**Comment by n-rodriguez** [comment]
https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-7-install-ruby-interpreter-for-post-receive-hook

**Comment by chukhman** [comment]
"ruby is already the newest version."

**Comment by n-rodriguez** [comment]
Can you try to clone Gitolite Admin repo by hand?

**Comment by n-rodriguez** [comment]
Look like this one : https://github.com/jbox-web/redmine_git_hosting/issues/372

**Comment by n-rodriguez** [comment]
The user that runs Redmine (it seems to be apache here) **must** have read access on both 
```/usr/share/redmine/plugins/redmine_git_hosting/ssh_keys/www-data``` and ```/usr/share/redmine/plugins/redmine_git_hosting/ssh_keys/www-data.pub```.

**Comment by n-rodriguez** [comment]
http://jbox-web.github.io/redmine_git_hosting/guide/redmine-installation/#why-not-apache

**Comment by n-rodriguez** [comment]
Check your public/private SSH key. They be **readable** by user running Redmine (here ```www-data```).

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/redmine_git_hosting/issues/372#issuecomment-83226633
