### ISSUE TITLE
Error while testing can_gitolite_sudo_to_redmine_user

### ISSUE THREAD

**Issue by sdragnev** [jbox-web/redmine_git_hosting#380]
I'm having trouble integrating the plugin with gitolite.
Both *can_gitolite_sudo_to_redmine_user* and *can_redmine_sudo_to_gitolite_user* fail even though I've tested each manually and it works fine.

I can run *sudo -n -u redmine -i whoami* as the git user no problem.

As a result, redmine can't see any of the gitolite repos.
Any hints on how to troubleshoot this?

I'm using passenger with apache and running redmine_git_hosting 1.0.1.

Thanks!

**Comment by nicesw123** [comment]
Perhaps the same as #377 ??

(For that issue #337, I believe the code needs to change: `-i` flags on sudo should not be used)

**Comment by sdragnev** [comment]
Unfortunately not the case. Both redmine and git users have a shell available and the command works with both -i and without it.

**Comment by n-rodriguez** [comment]
Fixed in commit https://github.com/jbox-web/redmine_git_hosting/commit/3b23dc9e13941949631657a395b5ad3251a5e567.
The test was not necessary and has been removed. Also you can remove this line in sudoers file :
```
git  ALL=(redmine)  NOPASSWD:ALL
```

**Comment by n-rodriguez** [comment]
> can_redmine_sudo_to_gitolite_user

For this one can you provide more logs please?

**Comment by sdragnev** [comment]
Certainly.
git_hosting.log: http://pastebin.com/stABgALp
production.log: http://pastebin.com/rpCdTSPs
/var/log/secure: http://pastebin.com/dyYNbJ9d

The installation of all hooks fail which makes sense since the process it can't seem to sudo into git.

**Comment by wilful** [comment]
I have a very similar problem. up. In the same logs

**Comment by n-rodriguez** [comment]
@wilful your link seems broken. Can you paste the content here?

**Comment by wilful** [comment]
![2015-03-14 17-57-32 - - yandex](https://cloud.githubusercontent.com/assets/350868/6717734/80e3349c-cdd0-11e4-8947-2cd13a85a471.png)
Of course.
I tried to disable LDAP. Also tried to run RM same user as Gitolite. Changed the options `sudo`. But nothing helped.

**Comment by n-rodriguez** [comment]
You're using git 1.7.1. Requirements specify at least git 1.7.2 : https://jbox-web.github.io/redmine_git_hosting/download/index.html

**Comment by n-rodriguez** [comment]
As Redmine user can you try this command :
```sudo -n -u git -i git --version --no-color```

**Comment by wilful** [comment]
Yes. Git is outdated. 
    -bash-4.1$ sudo -n -u git -i git --version --no-color
    git version 1.7.1
    -bash-4.1$ whoami
    redmine

This may be due to a main problem with sudo?
http://pastebin.com/LDjkWymJ
For example:
`2015-03-18 23:07:20 +0300 [DEBUG] Non-zero exit code pid 16566 exit 255 for ssh -T -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -i /home/redmine/redmine-3.0.0/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info`

    -bash-4.1$ ssh -T -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -i /home/redmine/redmine-3.0.0/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info
    Warning: Permanently added 'localhost' (RSA) to the list of known hosts.
    hello redmine_gitolite_admin_id_rsa, this is git@redmine_testing-28492-centos running gitolite3 3.6.2-1.el6 on git 1.7.1
     R W    testing
    -bash-4.1$ whoami 
    redmine
    -bash-4.1$ sudo -n -u git -i whoami
    git

![2015-03-19 01-16-59 redmine git hosting plugin - - yandex](https://cloud.githubusercontent.com/assets/350868/6718466/b15744d8-cdd5-11e4-9613-dc5d7d334895.png)

**Comment by n-rodriguez** [comment]
> This may be due to a main problem with sudo?

Seems to be...

```
2015-03-18 23:07:20 +0300 [DEBUG] Non-zero exit code pid 16566 exit 255 for ssh -T -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -i /home/redmine/redmine-3.0.0/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info
```

Actually this is not a command to execute but the content of a script to pipe/copy through sudo command to ```<git user home>/.ssh/run_gitolite_mirror``` file.

**Comment by n-rodriguez** [comment]
Here the script content :

```
#!/bin/sh 
 exec ssh -T -o BatchMode=yes -o StrictHostKeyChecking=no -i /data/git-repositories/jbox/.ssh/redmine_gitolite_admin_id_rsa_mirroring "$@"
```

**Comment by n-rodriguez** [comment]
> 2015-03-18 23:07:20 +0300 [DEBUG] Non-zero exit code pid 16566 exit 255 for ssh -T -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -i /home/redmine/redmine-3.0.0/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info

This command is used to get Gitolite version

**Comment by n-rodriguez** [comment]
> This may be due to a main problem with sudo?

It seems to be. What is the sudo version?

**Comment by wilful** [comment]
How can I verify that these command? They also run through the pipe?

    2015-03-18 23:20:37 +0300 [DEBUG] Non-zero exit code pid 20370 exit 1 for `sudo -n -u git -i whoami`
    2015-03-18 23:20:37 +0300 [ERROR] Error while testing can_redmine_sudo_to_gitolite_user

Manually it works:

    bash-4.1$ sudo -n -u git -i whoami
    git

I can not understand why all the commands SUDO do not work in my RM.

    -bash-4.1$ sudo -V
    Sudo version 1.8.6p3

**Comment by n-rodriguez** [comment]
Check your sudoers file for ```requiretty``` parameter.

**Comment by wilful** [comment]
The only indication in the file:

    # ack requiretty /etc/sudoers
    Defaults    requiretty

**Comment by n-rodriguez** [comment]
If you have the *requiretty* set in the *Defaults* directive of your sudoers file (it is there by default in CentOS) either remove it or add the following lines below the original directive :
```
Defaults:redmine !requiretty
```

**Comment by wilful** [comment]
YES! It works! I added:

    # cat /etc/sudoers.d/redmine 
    Defaults:redmine !requiretty
    redmine ALL=(git) NOPASSWD:ALL

Thank you for your help!

**Comment by n-rodriguez** [comment]
Great :)
Can you confirm that it works with Git 1.7.1 ?

**Comment by wilful** [comment]
No. After your message, I updated version Git (1.7.12)

**Comment by n-rodriguez** [comment]
ok

**Comment by n-rodriguez** [comment]
Doc udpated : https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-6-configure-sudo

Thank you!

**Comment by sdragnev** [comment]
Can confirm that setting !requiretty for redmine fixes the issue of redmine not running as git for me as well. Thanks you two for the continued troubleshooting.

I'm also running git 1.7.1 (damn you stale cent os!) and the hooks seem to be failing but this is a different issue that may be fixed by upgrading git.

**Comment by n-rodriguez** [comment]
> I'm also running git 1.7.1 (damn you stale cent os!) and the hooks seem to be failing but this is a different issue that may be fixed by upgrading git.

Are you sure that git is guilty?
I'd like to confirm Git minimum version to update requirements.

**Comment by n-rodriguez** [comment]
> the hooks seem to be failing but this is a different issue that may be fixed by upgrading git.

Can you please open an issue with hook output?

**Comment by sdragnev** [comment]
I'll take a closer look and possibly upgrade (if nothing else works) later today. Will let you know how that affects things.

**Comment by n-rodriguez** [comment]
Ok. Thank you!

**Comment by sdragnev** [comment]
All green after a server restart for me. Still git 1.7.1.

The script had created a "$HOME" directory (with the local/hooks in it) in */home/git*. For whatever reason it wasn't evaluating the $HOME var. The local/hooks dir was successfully created after restart though.

All is well it seems!

**Comment by n-rodriguez** [comment]
> The script had created a "$HOME" directory (with the local/hooks in it) in /home/git. For whatever reason it wasn't evaluating the $HOME var. The local/hooks dir was successfully created after restart though.

Yes this can happen.

**Comment by n-rodriguez** [comment]
> All green after a server restart for me. Still git 1.7.1.

Great :) Thank you!
