### ISSUE TITLE
"My public keys" for old users: link (with subpath) not correct  AND  for new users: link not shown

### ISSUE THREAD

**Issue by nicesw123** [jbox-web/redmine_git_hosting#381]
Hi there,

I've installed Git Hosting Plugin 1.0.1 on Redmine 2.6.2.

For old users, accessing "My account" shows:
"My public keys", but the **link is not correct**:
`https://site/my/public_keys`

For my setup the link should be
`https://site/redmine/my/public_keys`      -- note: I'm using a directory-path `redmine` there!

This is because under "Administration->Settings->General" I have
Host name and path: `site/redmine`

and also under "Administration->Redmine Git Hosting" I have
Hooks URL: `https://site/redmine`

.
.
.
.
For new users, the "My public keys" does not even appear.
If I try to access via `https://site/redmine/my/public_keys` I get:
"403 You are not authorized to access this page."

Is there some setting I am missing? Why is this not showing?

Thanks!

.
.
.
.
In case you are interested:
```
Environment:
  Redmine version                2.6.2.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.0
  redmine_git_hosting            1.0.1
  ...
```

**Comment by n-rodriguez** [comment]
Duplicate : https://github.com/jbox-web/redmine_git_hosting/issues/368
Fixed in 1.0.2.

**Comment by mqu** [comment]
hello : "my public key" link is not shown for non administrator user ; the link is shown for admin users. For non admin users going to _http://..../redmine/my/public_keys_ return 403 error.

Here is information about my system configuration : 

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.0
```

**Comment by n-rodriguez** [comment]
> hello : "my public key" link is not shown for non administrator user

until the user is added to a project... This is due to how Redmine permissions work.
