### ISSUE TITLE
Problem with RW+ privileges on manager user

### ISSUE THREAD

**Issue by WMP** [jbox-web/redmine_git_hosting#386]
Hello, i need to give my user RW+ privileges and i gave privileges him to manager, but ssh git@git info tell me that i have only RW privileges. 

Redmine version: 2.6.1
Git version: 1.9.1
Gitolite version	: 3
Redmine Git Hosting: 1.0.0

**Comment by n-rodriguez** [comment]
> Hello, i need to give my user RW+ privileges and i gave privileges him to manager, but ssh git@git info tell me that i have only RW privileges.

You need to give the ```:manage_repository``` permission to a role. Users with this role (and this permission) will have ```RW+``` privileges on project repositories.

**Comment by WMP** [comment]
How can i do this?

**Comment by n-rodriguez** [comment]
In *Administration -> Roles*

**Comment by WMP** [comment]
Users with manager role has select Manage Repository, but gitoline show only RW.

**Comment by n-rodriguez** [comment]
> Users with manager role has select Manage Repository, but gitoline show only RW.

Got the same here :

nicolas@tchoum-desktop:~$ ssh  git@example.net info
Debian GNU/Linux 7
hello redmine_developper1_5, this is git@example running gitolite3 v3.6.2-12-g1c61d57 on git 1.9.1

 R W	test

```
repo    @all
  RW+                            = DUMMY_REDMINE_KEY

repo    gitolite-admin
  RW+                            = redmine_gitolite_admin_id_rsa

repo    test
  RW+                            = redmine_admin_1 redmine_developper1_5
  R                              = redmine_rapporter1_6 gitweb
  config redminegitolite.projectid = test
  config redminegitolite.repositoryid = 
  config redminegitolite.repositorykey = 4R5zOWFvJ18aNvwn57uLC40nj3Q1RSrRXi9E3B5QIorG0bPUQJkqQWqrADEEo0L
  config http.uploadpack = true
  config http.receivepack = true
  config multimailhook.enabled = false
```

**Comment by n-rodriguez** [comment]
I don't this is an issue : http://gitolite.com/gitolite/user.html#info http://gitolite.com/gitolite/g2/info_expand.html
The info command only display R W or C status.
