### ISSUE TITLE
Better rvm support

### ISSUE THREAD

**Issue by stuxxn** [jbox-web/redmine_git_hosting#388]
Hello,
Im using a multiuser rvm setup to run redmine and dont want to install the normal ruby package as stated in the install docu. But with this setup i cant run the hooks because it uses '/usr/bin/env ruby' and they are invoked via the normal sudo.

It would be great if we could configure to use rvmsudo instead of the normal sudu. I changed  redmine_git_hosting/lib/redmine_git_hosting/commands.rb:124 to 'rvmsudo' and the hooks just worked fine.

Redmine 3.0.0 stable
redmine_git_hosting 1.0.2

**Comment by n-rodriguez** [comment]
> and they are invoked via the normal sudo.

What do you mean?

**Comment by stuxxn** [comment]
I installed ruby with the help of rvm as multi user setup. So there is no ruby binary in the normal PATH. To be able to find the ruby binary a profile script '/etc/profile.d/rvm.sh' extends the PATH enviornment variable. Example output: 
/usr/local/rvm/gems/ruby-2.2.0/bin:/usr/sbin:/usr/bin:/sbin:/bin
 If you login as a user or run 'su - git' this script is executed, but not with the 'sudo' command. To extend the PATH var you can run 'rvmsudo' (https://rvm.io/integration/sudo). 

So the problem is that you call the git hooks via the 'sudo' command and '#!/usr/bin/env ruby' cant find a binary because the PATH is not extendet. To be able to find the ruby installed with rvm you could simple run 'rvmsudo' instead.

**Comment by n-rodriguez** [comment]
> So the problem is that you call the git hooks via the 'sudo' command

Actually the plugin doesn't call hooks itself... They are called by Git/Gitolite when you do a ```git push```. But as you said RVM environment variables are not loaded.

What you can try is to add this to ```<git user home>/.profile``` :
```
source /etc/profile.d/rvm.sh
```

**Comment by stuxxn** [comment]
Hmm ok im kinda confused. 
If i edit / extend  'testo.git/hooks/post-receive' like this:
```
#!/usr/local/rvm/rubies/ruby-2.2.0/bin/ruby
# Path of my ruby binary insallted via rvm

system '/usr/bin/env > /tmp/ruby_env.txt'
```
And push  something to the testo repo the content of 'ruby_env.txt' is:
```
SUDO_GID=5002
MAIL=/var/mail/git
USER=git
GIT_DIR=.
HOME=/home/git
SUDO_UID=5001
LOGNAME=git
USERNAME=git
TERM=unknown
PATH=/usr/lib/git-core:/usr/lib/git-core:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GL_BYPASS_UPDATE_HOOK=true
SUDO_COMMAND=/bin/sh -c env GL_BYPASS_UPDATE_HOOK=true git receive-pack --stateless-rpc repositories/testo.git
SHELL=/bin/sh
SUDO_USER=redmine
PWD=/home/git/repositories/testo.git
```
This is why i thought the plugin itself is calling the hook.

Your tip doe not work. After editing the .profile file of the git user and calling this from the redmine user I still got:
```
sudo -u git ruby -v
sudo: ruby: command not found
```
But with rvmsudo everything works fine:
```
rvmsudo -u git ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

**Comment by n-rodriguez** [comment]
Ok, so what you can do is edit ```<plugin_dir>/contrib/hooks/post-receive/redmine_gitolite.rb``` and put the right shebang at the top (```#!/usr/local/rvm/rubies/ruby-2.2.0/bin/ruby```) then go in *Administration -> Redmine Git Hosting* to trigger hooks update.

Note that you can also declare your own Gitolite hooks (https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/load_gitolite_hooks.rb).
