### ISSUE TITLE
NoMethodError (undefined method `compact!' for... Error on the opening of the users

### ISSUE THREAD

**Issue by wilful** [jbox-web/redmine_git_hosting#391]
![2015-03-19 10-55-54 settings - testtest - yandex](https://cloud.githubusercontent.com/assets/350868/6725162/9358898c-ce26-11e4-93ec-aea461d655b6.png)
![2015-03-19 10-56-21 redmine 500 error yandex](https://cloud.githubusercontent.com/assets/350868/6725163/9f8fb18a-ce26-11e4-93f1-e03a70bddc94.png)

When I click on the link "users", I get a 500 error.
The logs found only a single entry:

    Started GET "/repositories/39/committers" for 95.78.252.69 at 2015-03-19 08:52:16 +0300
    Processing by RepositoriesController#committers as HTML
      Parameters: {"id"=>"39"}
      Current user: testuser (id=22)
    Completed 500 Internal Server Error in 13ms

    NoMethodError (undefined method `compact!' for #<User::ActiveRecord_Relation:0x0000000395c010>):
      app/controllers/repositories_controller.rb:98:in `committers'

**Comment by n-rodriguez** [comment]
Already fixed in 1.0.3 version.
