### ISSUE TITLE
Move/squash repositories from one project to another

### ISSUE THREAD

**Issue by metimocyn** [jbox-web/redmine_git_hosting#397]
In older versions of redmine, i could only associate one repo with one project. So to have multiple repos per project i had to create a tree of 'empty' sub-projects for my repositories. 

I would like a mechanism to 'move' the repository from one project to another, or 'squash' multiple projects with repositories into one project, migrating issues etc.

It would also be nice to manipulate the gitolite side folder tree so to create project related folders containing one projects repositories.

**Comment by n-rodriguez** [comment]
> I would like a mechanism to 'move' the repository from one project to another

A preliminary work has been done on the ```‘feat_move_repo``` branch. It works and allows you to move a repository from a project to another. But it may contains some bugs.
Also some cases are not handled :
* you can't move a repository with a blank identifier
* Neither move a repository with an identifier already taken (in the case you use hierarchical organization)

> or 'squash' multiple projects with repositories into one project, migrating issues etc.

This is out of the scope of this plugin. It implies a substantial amount of work that cannot be sponsored by JBoxWeb. 

> It would also be nice to manipulate the gitolite side folder tree so to create project related folders containing one projects repositories.

What do you mean?
