### ISSUE TITLE
"Redmine Configuration" not kept

### ISSUE THREAD

**Issue by reds-heig** [jbox-web/redmine_git_hosting#399]
Hi,

Apparently Redmine does not save the checkbox options in the "Redmine Configuration" menu. By this, I mean that I've selected "Automatically initialize Git repositories for new projects?" and pressed "Apply", but my choice was not kept. On the other hand, as a test I've removed the check in "Directory and URL structure for Redmine-managed repositories" and now I cannot set it back anymore :S
Could you please help me?
Thanks a lot!
Cheers,
Rob

**Comment by n-rodriguez** [comment]
> On the other hand, as a test I've removed the check in "Directory and URL structure for Redmine-managed repositories"

What do you mean? By the way you can check the log file in ```<redmine root dir>/log/git_hosting.log``` it should contains some hints about what's going on.

**Comment by reds-heig** [comment]
I mean that I've unchecked the corresponding case, just to see if my change was kept. The removal was indeed kept, but now I cannot check it anymore -- or better, I can check it, but when I click on apply, the check is not there anymore...

I've skipped the log because it showed nothing "useful", here's the content of git_hosting.log when I'm in the "Redmine configuration" tab, and I press "apply" after having checked the two aforementioned cases:
2015-03-31 07:28:56 +0200 [INFO] Flush Settings Cache !
2015-03-31 07:28:56 +0200 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-03-31 07:28:56 +0200 [INFO] Settings cache flushed!
2015-03-31 07:28:56 +0200 [INFO] Testing if Redmine user 'redmine' can sudo to Gitolite user 'git'...
2015-03-31 07:28:56 +0200 [INFO] OK!
2015-03-31 07:28:56 +0200 [INFO] Unset Git global parameter : multimailhook.smtpuser
2015-03-31 07:28:56 +0200 [INFO] Unset Git global parameter : multimailhook.smtppass
2015-03-31 07:28:56 +0200 [INFO] Installing Redmine Gitolite mirroring SSH keys ...
2015-03-31 07:28:56 +0200 [INFO] Done !

However, I've just seen that production.log shows something more interesting:
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_bootstrap_kit/javascripts/jquery_tag_it.js"):
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  puma (2.11.1) lib/puma/configuration.rb:82:in `call'
  puma (2.11.1) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.1) lib/puma/server.rb:375:in `process_client'
  puma (2.11.1) lib/puma/server.rb:262:in `block in run'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `call'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `block in spawn_thread'

I'll investigate a bit the issue by installing different plugin versions and I'll let you know.
Thanks for your answer!
Rob

**Comment by reds-heig** [comment]
Ok, I've updated git_hosting (getting the v1.0.x branch, in sync with devel), and I've taken the devel version of boostrap (no way to make the v0.2.x version work).
Not it *seems* to work.
A few minor problems though:
- in "Config test", I have (warning sign) git_hosting_post_receive.rb (hook left untouched)
- when I create a new project and I push some stuff to a repository, I still see nothing in the repository view unless I manually issue a
bundle exec rake redmine_git_hosting:fetch_changesets RAILS_ENV=production
as written in your troubleshooting page.
For the rest is seems to work fine!
Have a nice day!
Rob
