### ISSUE TITLE
Git cache "Until next commit" broken

### ISSUE THREAD

**Issue by niosHD** [jbox-web/redmine_git_hosting#401]
After the last upgrade of my installation I noticed that the cache seems to be broken. Opening any repository took ages. However, I think I found the issue.

The `gitolite_cache_max_time` value for "Disabled" is 0 and for "until next commit" is -1.
The check for `git_cache_enabled?` in the xitolite_adapter checks for > 0 which means that "until next commit" is treated as disabled.

I therefore tried `RedmineGitHosting::Config.gitolite_cache_max_time != 0` which seems to fix the issue.

regards

**Comment by n-rodriguez** [comment]
Good point for you! Thank you!

**Comment by n-rodriguez** [comment]
By the way which cache adapter do you use?

**Comment by niosHD** [comment]
Your welcome! I am currently still using the database cache adapter, but mainly because it has been used before. What are the advantages of the new adapters?

**Comment by n-rodriguez** [comment]
> What are the advantages of the new adapters?

They are faster :)

**Comment by niosHD** [comment]
good to know, I'll give them a try ;)
thanks for working on this awesome plugin!
