### ISSUE TITLE
How to clone the repository and use it?

### ISSUE THREAD

**Issue by sabarish14** [jbox-web/redmine_git_hosting#402]
We have created the repositories for the projects and new git files are created under /home/git/repositories/. Now we are stuck at the next step.We tried to clone the repository using a different user name but from the same machine where redmine and gitolite is installed. When we try to clone the repository we get this error:

```
morris@redminegit:~$ git clone ssh://git@check.cri.uic.edu/check/check-entrerprise-architecture/test_git_42.git
Cloning into 'test_git_42'...
FATAL: R any check/check-entrerprise-architecture/test_git_42 morris DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

By reading the gitolite's ssh concept page http://gitolite.com/gitolite/glssh.html , we knew that gitolite does only the authorization and not the authentication page.But in gitolite.conf , we could see the redmine user names in the corresponding repositories.We kinda confused how to clone the repository and where is the authentication part taken care of.Kindly help us in giving a detailed explanation of how it works.

Also, when we try to create a new repository with a Readme from within Redmine, we get the following error in our logs when it tries to create the Readme file.
```
2015-03-31 17:34:01 -0500 [INFO] Create README file for repository 'check/check-entrerprise-architecture/test_git_readme_3'
2015-03-31 17:34:02 -0500 [ERROR] Error while creating README file for repository 'check/check-entrerprise-architecture/test_git_readme_3'
```
Also, the redmine user on our system can successfully clone the gitolite-admin repo but it cannot clone any other repos and no other users can clone any repos at all.

**Comment by n-rodriguez** [comment]
> Also, the redmine user on our system can successfully clone the gitolite-admin repo but it cannot clone any other repos

https://jbox-web.github.io/redmine_git_hosting/configuration/troubleshooting/#initialization-of-the-repo-with-readme-file-does-not-work

**Comment by n-rodriguez** [comment]
> no other users can clone any repos at all.

https://jbox-web.github.io/redmine_git_hosting/howtos/install/#step-10-add-your-ssh-keys

**Comment by sabarish14** [comment]
I have created the SSH keys and when I do this:
dev1@dev1-KVM:~$ ssh git@172.17.0.241
PTY allocation request failed on channel 0
hello redmine_redmine_1, this is git@redminegit running gitolite3 v3.6.2-20-g78fc240 on git 1.9.1

 R W	check/check-entrerprise-architecture/check2
 R W	check/check-entrerprise-architecture/data-source-evaluation/git
 R W	check/check-entrerprise-architecture/data-source-evaluation/test231
 R W	check/check-entrerprise-architecture/data-source-evaluation/testrepo1
 R W	check/check-entrerprise-architecture/test_4324_w_readme
 R W	check/check-entrerprise-architecture/test_git_42
 R W	check/check-entrerprise-architecture/test_git_readme2
 R W	check/check-entrerprise-architecture/test_git_readme_3
 R W	check/git1
 R W	testing
But when I clone a repo,I get this:
dev1@dev1-KVM:~$ git clone ssh://git@172.17.0.241/check/bi-tool-spagobi/test_no_readme.git
Cloning into 'test_no_readme'...
FATAL: R any check/bi-tool-spagobi/test_no_readme redmine_redmine_1 DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by n-rodriguez** [comment]
Be sure to be a member of ```bi-tool-spagobi``` project with a role that has ```commit``` permissions.

**Comment by n-rodriguez** [comment]
any news?

**Comment by zbigniev** [comment]
Faced with a similar situation, reopening the thread.
Followed instructions on http://redmine-git-hosting.io/get_started/ for Bitnami Redmine.
Git: 2.7.4, Gitolite: 3, libgit2: 0.25.0
All Config Tests are green
Trying to clone a repo on client gives:

```
git clone -v ssh://git@192.168.59.104/test1/main.git
Cloning into 'main'...
FATAL: R any test1/main redmine_tester_1 DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
The only log that shows an issue is gitolite's log:
```
2017-03-13.23:46:40     10298   die     R any test1/main redmine_tester_1 DENIED by fallthru<<newline>>(or you mis-spelled the reponame)
2017-03-13.23:50:45     10549   cli     gitolite        list-phy-repos
2017-03-13.23:50:45     10549   END
```
ssh from client seems to be working:
```
ssh git@192.168.59.104 info
hello redmine_tester_1, this is git@gandalf running gitolite3 v3.6.6-6-g7c8f0ab on git 2.7.4

 R W	testing
```
and gitolite.conf reads:
```
repo    @all
  RW+                            = redmine_gitolite_admin_id_rsa

repo    gitolite-admin
  RW+                            = redmine_gitolite_admin_id_rsa

repo    test1/main
  R                              = DUMMY_REDMINE_KEY
  config redminegitolite.projectid = test1
  config redminegitolite.repositoryid = main
  config redminegitolite.repositorykey = SVyfi29ColX7TDidbG8WP8V7wHyzIEDCHAMgQkiAniQa2PEaR7mkBrmCAxlnPmUo
  config http.uploadpack = true
  config http.receivepack = true
  config multimailhook.enabled = false

repo    testing
  RW+                            = @all
```
Any ideas on what might be wrong?
