### ISSUE TITLE
[Git cache] "Until next commit" param is broken for redis

### ISSUE THREAD

**Issue by niosHD** [jbox-web/redmine_git_hosting#404]
I just tried the redis cache adapter like suggested in #401 and noticed that until next commit is broken there too. Insertion into redis fails with the following error.

```
[ERROR] Redis Adapter : could not insert in cache, this is the error : 'ERR invalid expire time in SETEX'
```

I suspect that it is again related to the -1 encoding of `gitolite_cache_max_time`. Redis seems not too happy when -1 is specified as timeout.

Using any other timeout seems to work fine and is really blazing fast. Great job!

**Comment by n-rodriguez** [comment]
Hi! Thanks for your feedback! I will take a look when I'll be less busy :)
