### ISSUE TITLE
Bug: Protected Branch Name Must be Unique Across Projects (with fix)

### ISSUE THREAD

**Issue by wilsoc5** [jbox-web/redmine_git_hosting#406]
We have multiple Xitolite repos across multiple projects hosted on the same Redmine instance. I'm starting to roll out protected branches to ensure no one clobbers the master or the release branches of the git repo. This works for one project. However, as soon as a protected branch name, e.g. master, is used in one project it cannot be used in others. 

The fix:
in app/models/repository_protected_branche.rb
The lines:
```
  ## Validations
  validates :repository_id, presence: true
  validates :path,          presence: true, uniqueness: { scope: :permissions }
  validates :permissions,   presence: true, inclusion: { in: VALID_PERMS }
  validates :user_list,     presence: true
```
validates :path should be updated 
```
  validates :path,          presence: true, uniqueness: { scope: [:permissions, :repository_id] }
```

**Comment by n-rodriguez** [comment]
Merged! Thank you!
