### ISSUE TITLE
Feature Request: Gray protected branches if not enabled by repo flag.

### ISSUE THREAD

**Issue by wilsoc5** [jbox-web/redmine_git_hosting#410]
It would be nice to gray out all Protected Branches entries if the repository setting "Enable protected branches" is unchecked. This is especially true in the case of adding a protected branch and forgetting to check the "Enable protected branches" box. Having a visual cue would be very helpful. Even a box saying that "The protected branches below are not enabled. Please enable Protected Branches in the repository settings above."

Alternatively, adding an Enable flag for each branch name and removing the repository-wide flag might be a better long-term option. The enable flag could just add a comment marker on the line in the gitolite.conf file.

**Comment by n-rodriguez** [comment]
> Alternatively, adding an Enable flag for each branch name and removing the repository-wide flag might be a better long-term option.

Why not... For now I'm thinking about creating a relation table to manage users rather than a serialized field...

**Comment by n-rodriguez** [comment]
> Why not... For now I'm thinking about creating a relation table to manage users rather than a serialized field...

It will be for next release.
