### ISSUE TITLE
Problems to retrieve Gitolite hook parameters in Gitolite config 'namespace : multimailhook'

### ISSUE THREAD

**Issue by Idleworks** [jbox-web/redmine_git_hosting#411]
Hi all,

this issue was described before here #393.

I have the same problem here with redmine 3.0.1 (bitnami stack) and redmine_git_hosting on tag 1.0.3 and redmine_bootstrap_kit on tag 0.2.3 like mentioned in installation step 2.
Switching to v1.1.x and v0.2.x just crashes my redmine on apache restart.

```
2015-04-03 21:22:47 +0000 [INFO] Testing if Redmine user 'daemon' can sudo to Gitolite user 'git'...
2015-04-03 21:22:47 +0000 [INFO] OK!
2015-04-03 21:22:47 +0000 [ERROR] Problems to retrieve Gitolite hook parameters in Gitolite config 'namespace : multimailhook'
```

![redmine](https://cloud.githubusercontent.com/assets/6685173/6989247/a2aedff0-da59-11e4-9b17-6b72588b74ce.png)

**Comment by n-rodriguez** [comment]
> Switching to v1.1.x and v0.2.x just crashes my redmine on apache restart.

Yep... You should  not use the v1.1.x but the v1.0.x branch

**Comment by n-rodriguez** [comment]
Did you try to install hooks? (in *Administration -> Redmine Git Hosting -> Hooks* install hooks link)

**Comment by Idleworks** [comment]
ouch...didn't recognized that link yesterday at all. Issue fixed with one click. Thank you!
