### ISSUE TITLE
Feature Request: improved gitolite support: negative permissions for protected branches

### ISSUE THREAD

**Issue by wilsoc5** [jbox-web/redmine_git_hosting#414]
Negative permissions can be very handy to restrict access to certain tags or branches.
Gitolite documentation refers to it: http://gitolite.com/gitolite/conf.html#what-does-a-rule-look-like

Similarly, option support for "option deny-rules = 1" would be a nice add as well.

**Comment by wilsoc5** [comment]
It might be useful to also support the @all group for the users field in order to restrict read access to a particular repository for any additional users that get added to a project (Explicit permission as opposed to implicit permission).

**Comment by DProvorse** [comment]
+1 for this. Definitely would be helpful!

**Comment by lukemorel** [comment]
+1, this is actually what I need !

**Comment by n-rodriguez** [comment]
Added in commit : https://github.com/jbox-web/redmine_git_hosting/commit/8f7e433834f27dab8ca57f283796c20889d8e663

Example (from [Gitolite](http://gitolite.com/gitolite/conf.html#rules)): 

```
repo    blibl
  RW+                            = redmine_admin
  -     master                   = redmine_developer1 redmine_developer2 redmine_developer3
  -     refs/tags/v[0-9]         = redmine_developer1 redmine_developer2
  RW+   dev/                     = redmine_developer1 redmine_developer2 redmine_developer3
  RW                             = redmine_developer1 redmine_developer2 redmine_developer3
  R                              = redmine_reporter1
  config redminegitolite.projectid = blibl
  config redminegitolite.repositoryid = 
  config redminegitolite.repositorykey = bMs2qj6sPl1ttTZJH5vWJOClIQ2V8ZhwK2d7Szy1CnSDX0EYzE7SuTgAnyrVS7b
  config http.uploadpack = true
  config http.receivepack = true
  config multimailhook.enabled = false
  option mirror.master = mars
  option mirror.slaves = phobos deimos
  option mirror.redirectOK = all
```
