### ISSUE TITLE
The plugin deletes all gitolite mirroring attributes

### ISSUE THREAD

**Issue by paolosystemx** [jbox-web/redmine_git_hosting#415]
Hi Nicolas,

We are using the gitolite mirroring feature (http://gitolite.com/gitolite/mirroring.html), which requires to add attributes to the repository description in gitolite.conf such as:
repo foo
    ...access rules...

    option mirror.master        =   mars
    option mirror.slaves        =   phobos deimos
    option mirror.redirectOK    =   all

We have setup such mirroring for some of our redmine managed repos and it works fine, until someone makes changes through redmine, e.g. adding new project members.
At this point, the repo configuration is rewritten and the mirroring attributes are lost.

Do you think it would be possible that all attributes that the plugin does not manage be kept as they are found?

If you agree with that design and are willing to head me to the code where the rewrite operation is done, I'd fork and suggest a pull request with pleasure.

Please let me know and thank you for this great plugin!

Cheers,

Paolo

**Comment by n-rodriguez** [comment]
Hi Paolo!

Why not using the provided mirroring feature?

**Comment by paolosystemx** [comment]
Hi Nicolas,

We need a two way mirroring between a private (intranet) gitolite and a public (internet acces but restricted to authorised users) gitolite, both of them being administrated by us.

Does the provided feature support two way mirroring ?
Does it support mirroring to another gitolite managed server ?

Thank you in advance.

Cheers,

Paolo

**Comment by n-rodriguez** [comment]
> Does the provided feature support two way mirroring ?

No.

> Does it support mirroring to another gitolite managed server ?

Yes. (actually it supports mirroring to any Git repository)

But I'm not sure this will fit your needs...

**Comment by paolosystemx** [comment]
Hi,

Thank you for your answers.

Well we do need the two way mirroring.

So do you think my suggestion that mirroring attributes (and perhaps any gitolite attribute not managed by the plugin) should be kept as is makes sense?

If yes, as I was telling you, I could do the job, provided that you give me a few hints on where to start.

Thank you in advance.

Paolo

**Comment by paolosystemx** [comment]
Hi Nicolas,

Any news on this topic?

Thank you in advance.

Paolo

**Comment by n-rodriguez** [comment]
Hi Paolo,

Unfortunately no. If you want to work on this you can take a look a these classes :
* [RepositoryHandler](https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/redmine_git_hosting/gitolite_handlers/repository_handler.rb)
* [RepositoryUpdater](https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/redmine_git_hosting/gitolite_handlers/repository_updater.rb)

RepositoryUpdater inherits from RepositoryHandler which defines most of the instance methods needed to update a repository config.

The real things happen here https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/redmine_git_hosting/gitolite_handlers/repository_handler.rb#L61

**Comment by paolosystemx** [comment]
Thank you very much, I'll do my best!

Cheers,

Paolo

**Comment by n-rodriguez** [comment]
Hi Paolo! Any news?

**Comment by paolosystemx** [comment]
Hi Nicolas,
No, sorry. May is not the most productive month nearby :-)
I don't see that I'll be able to work on the topic in the close future, I'll publish a proposal to work on this to my colleagues.
Wait and see...

**Comment by alessandroleite** [comment]
Hello @n-rodriguez
I've talked with @paolosystemx, and I will work on this issue. 
All best.

**Comment by n-rodriguez** [comment]
@alessandroleite Great! May the force be with you!

**Comment by n-rodriguez** [comment]
Hi! I've added support for Gitolite option in commit : https://github.com/jbox-web/redmine_git_hosting/commit/7b7e4586afb98305c1934055e7b55001aa19ab03.
Next to 'Git config keys' you'll be able to add 'Gitolite options' such as your mirroring options :)

**Comment by n-rodriguez** [comment]
Example : 

```
repo    blibl
  RW+                            = redmine_admin
  -     master                   = redmine_developer1 redmine_developer2 redmine_developer3
  -     refs/tags/v[0-9]         = redmine_developer1 redmine_developer2
  RW+   dev/                     = redmine_developer1 redmine_developer2 redmine_developer3
  RW                             = redmine_developer1 redmine_developer2 redmine_developer3
  R                              = redmine_reporter1
  config redminegitolite.projectid = blibl
  config redminegitolite.repositoryid = 
  config redminegitolite.repositorykey = bMs2qj6sPl1ttTZJH5vWJOClIQ2V8ZhwK2d7Szy1CnSDX0EYzE7SuTgAnyrVS7b
  config http.uploadpack = true
  config http.receivepack = true
  config multimailhook.enabled = false
  option mirror.master = mars
  option mirror.slaves = phobos deimos
  option mirror.redirectOK = all
```

**Comment by paolosystemx** [comment]
Thank you @n-rodriguez , we'll try this ASAP!

**Comment by timoc** [comment]
Hi,

I have a similar requirement. Did this work for you?

**Comment by paolo-crisafulli** [comment]
@timoc , yes, it works fine for us.
Our config: 
- redmine 3.3.0
- redmine-git-hosting 1.2.0
- gitolite3 v3.6.4-0-g93e6524 on git 1.9.1
