### ISSUE TITLE
redmine overwrites gitolite.conf even if another filename specified

### ISSUE THREAD

**Issue by jekel** [jbox-web/redmine_git_hosting#416]
hello
i have latest redmine_git_hosting plugin version
and i've changed Gitolite configuration file to redmine.conf
then, i have changed user access rights to one of my repos
and redmine had overwritten gitoline.conf, not redmine.conf

in gitolite-admin log i have found this records:
     update_projects : sales
    [gitolite-rugged] Merged `origin/master` into `master`

```
environment:
  Redmine version                2.4.7.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.6.16
  Mercurial                      1.7
  Git                            1.8.5.5
  Filesystem                     
  Xitolite                       1.8.5.5
Redmine plugins:
  redmine_bootstrap_kit          0.2.3
  redmine_git_hosting            1.0.3
  redmine_plugin_views_revisions 0.0.1
  redmine_sidekiq                2.1.0

```

**Comment by n-rodriguez** [comment]
did you try to restart Redmine?

**Comment by jekel** [comment]
nope,  i will try

**Comment by jekel** [comment]
it helped, thx
you should write on configuration page - that it is necessary to restart redmine after config change like this

**Comment by n-rodriguez** [comment]
> you should write on configuration page - that it is necessary to restart redmine after config change like this

http://redmine-git-hosting.io/get_started/#step-9-finish-installation---configuration
