### ISSUE TITLE
Define order of git urls

### ISSUE THREAD

**Issue by Idleworks** [jbox-web/redmine_git_hosting#417]
Hi,

is there a way to define order of git urls in git_url_box?
Our members use 99% HTTPS links and that should be first to show up in list.

At moment it seems that ordering of git urls is hardcoded.

**Comment by n-rodriguez** [comment]
Done in commit https://github.com/jbox-web/redmine_git_hosting/commit/332ce2b03893264cab53b79181ee56841704faef. Will be in 1.1.0 release.
