### ISSUE TITLE
Rugged::NetworkError (This transport isn't implemented. Sorry)

### ISSUE THREAD

**Issue by Garrcomm** [jbox-web/redmine_git_hosting#420]
I'm currently having issues creating repositories.
When creating a project (with auto repo creation enabled), I get a 500 Internal error error and an entry in my production.log which you can find below.

I've been trying all kinds of things I found in simular issues (#378 / #367) but so far nothing helped. I also noticed a screenshot in issue #370 where Xitolite is running as "git (with sudo)". In my installation, the "(with sudo)" part is missing. Maybe that's part of the cause, but I can't find how to change that.

In the config test, all is marked green, I'm using versions:
- redmine_bootstrap_kit v0.2.3 
- redmine_git_hosting v1.0.4
- git 1.7.10.4 
- gitolite3 v3.6.2-26-gf9c0008 
- Redmine 3.0.1.stable.14160

From my log file:
<pre>
Redirected to http://192.168.3.35/projects/test-01/settings
Completed 500 Internal Server Error in 454ms (ActiveRecord: 123.5ms)

Rugged::NetworkError (This transport isn't implemented. Sorry):
  /opt/redmine/.bundler/ruby/1.9.1/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone_at'
  /opt/redmine/.bundler/ruby/1.9.1/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in `clone'
  /opt/redmine/.bundler/ruby/1.9.1/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:110:in `initialize'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:67:in `new'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:67:in `gitolite_admin'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:39:in `resync_gitolite'
  plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:50:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:109:in `resync_gitolite'
  plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:27:in `create_repository'
  plugins/redmine_git_hosting/app/use_cases/create_repository.rb:64:in `create_repository'
  plugins/redmine_git_hosting/app/use_cases/create_repository.rb:16:in `call'
  plugins/redmine_git_hosting/app/use_cases/create_project_repository.rb:31:in `create_project_repository'
  plugins/redmine_git_hosting/app/use_cases/create_project_repository.rb:13:in `call'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/projects_controller_patch.rb:99:in `create_project_repository'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/projects_controller_patch.rb:31:in `create_with_git_hosting'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack-xml_parser (1.0.1) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:479:in `safe_fork'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:180:in `start'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb:129:in `start'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in `synchronize'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/share/phusion-passenger/helper-scripts/passenger-spawn-server:99:in `<main>'

</pre>

**Comment by n-rodriguez** [comment]
Is this a Bitnami stack?

**Comment by Garrcomm** [comment]
Hi Nicolas,

Thank you for your reply.
I'm not sure what you mean with a Bitnami stack, but I'm using Passenger and Apache. The logfile shown is production.log from Redmine itself.

Kind regards,
Stefan

**Comment by n-rodriguez** [comment]
[Bitnami](https://bitnami.com/)

**Comment by Garrcomm** [comment]
In that case, no. I installed Debian myself within VirtualBox in a testing environment, and in that, I installed the default debian packages for most things. For Redmine, I used "svn co https://svn.redmine.org/redmine/branches/3.0-stable redmine-3.0"

**Comment by n-rodriguez** [comment]
Ok. So I guess you missed that step : http://redmine-git-hosting.io/get_started/#step-1-install-dependencies

**Comment by Garrcomm** [comment]
Strange, I copy/pasted that before, I thought, but one dependency was still missing;

<pre>libgcrypt11-dev

root@debian:~# apt-get install build-essential libssh2-1 libssh2-1-dev cmake libgpg-error-dev
# libgcrypt11-dev was missing, now installed
root@debian:~# sudo su - redmine
redmine@debian:~$ cd redmine-3.0/
redmine@debian:~/redmine-3.0$ bundle install --without development test
redmine@debian:~/redmine-3.0$ exit
root@debian:~# service apache2 restart
root@debian:~#
</pre>

Still, the same issue though :(

**Comment by n-rodriguez** [comment]
```sudo su - redmine``` is useless as root ;)

**Comment by Garrcomm** [comment]
Good point, it's a habbit I guess ;)

**Comment by n-rodriguez** [comment]
You need to remove previous install of rugged gem. But as it's cloned from Github it's a bit tricky : http://stackoverflow.com/questions/7487391/how-do-i-clean-up-old-github-sourced-gems-in-bundler

**Comment by n-rodriguez** [comment]
The point here is to force recompilation of libgit2 provided by the rugged gem.

**Comment by Garrcomm** [comment]
<pre>redmine@debian:~/redmine-3.0$ gem cleanup -d
Cleaning up installed gems...
Clean Up Complete
redmine@debian:~/redmine-3.0$ gem uninstall libgit2
INFO:  gem "libgit2" is not installed
redmine@debian:~/redmine-3.0$ bundle install --without development test
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Your Gemfile lists the gem redcarpet (~> 3.1.2) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Using rake 10.4.2
Using RedCloth 4.2.9
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.6
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.1
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.1
Using globalid 0.3.5
Using activejob 4.2.1
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.1
Using actionpack-action_caching 1.1.1
Using actionpack-xml_parser 1.0.1
Using activemodel 4.2.1
Using arel 6.0.0
Using activerecord 4.2.1
Using asciidoctor 1.5.2
Using coderay 1.1.0
Using creole 0.5.0
Using dalli 2.7.4
Using github-markup 1.3.3
Using gitlab-grack 2.0.0.pre from https://github.com/jbox-web/grack.git (at fix_rails4)
Using gratr19 0.4.4.1
Using rugged 0.21.4
Using gitolite-rugged 1.0.0 from https://github.com/jbox-web/gitolite-rugged.git (at v1.0.0)
Using tilt 1.4.1
Using haml 4.0.6
Using sexp_processor 4.5.0
Using ruby_parser 3.6.6
Using html2haml 2.0.0
Using thor 0.19.1
Using railties 4.2.1
Using haml-rails 0.9.0
Using hike 1.2.3
Using hiredis 0.6.0
Using jquery-rails 3.1.2
Using multi_json 1.11.0
Using mysql2 0.3.18
Using net-ldap 0.3.1
Using rubypants 0.2.0
Using org-ruby 0.9.12
Using protected_attributes 1.0.9
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using bundler 1.9.2
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using rails 4.2.1
Using rbpdf 1.18.5
Using redcarpet 3.1.2
Using redis 3.2.1
Using request_store 1.0.5
Using rmagick 2.14.0
Using will_paginate 3.0.7
Bundle complete! 40 Gemfile dependencies, 68 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
redmine@debian:~/redmine-3.0$ gem install libgit2
ERROR:  Could not find a valid gem 'libgit2' (>= 0) in any repository
redmine@debian:~/redmine-3.0$
</pre>

It seems like the gem libgit2 is unknown completely.

**Comment by n-rodriguez** [comment]
> It seems like the gem libgit2 is unknown completely.

It's not a gem ;) It's [system lib](https://libgit2.github.com/) used by Rugged gem to manipulate Git repositories. This lib is bundled with Rugged gem and compile at installation time.

**Comment by Garrcomm** [comment]
I think I'm a bit further, I proceeded with the following steps:

<pre>root@debian:~# apt-get install build-essential libssh2-1 libssh2-1-dev cmake libgpg-error-dev
# libgcrypt11-dev was missing, now installed
root@debian:~# gem uninstall rugged
Successfully uninstalled rugged-0.21.4
root@debian:~# gem cleanup -d
Cleaning up installed gems...
Clean Up Complete
root@debian:~# su - redmine
redmine@debian:~$ cd redmine-3.0/
redmine@debian:~/redmine-3.0$ bundle install --without development test</pre>

Now I have another challenge, but I don't think it's redmine_git_hosting related, at least not to this error.

thanks for your patience!
