### ISSUE TITLE
[Feature Request] [Un]Grayed Protected Branches do not dynamically update with option status

### ISSUE THREAD

**Issue by wilsoc5** [jbox-web/redmine_git_hosting#421]
Great new 1.0.4 release with logs of bug fixes! Thanks! 
One minor quibble:
1. On a repository with protected branches currently disabled, add a new protected branch. The branches show up as grayed out (as desired from earlier request). 
2. Enable protected branches check box and click save.
3. View "Options successfully updated" green notification box.
4. Expect grayed-out branches to no longer be grayed out and message to no longer be present <=== Fails. 
5. Reload page, works.
6. Uncheck "Enable Protected branches"
7. Expect non-grayed-out branches to gray out and show protected branch settings notification. <=== Fails
8. Reload page
9. Works as expected. 

It seems as though there is no dynamic updating of the status of the protected branches on this page based on the checkbox "Enable Protected Branches"

**Comment by n-rodriguez** [comment]
> It seems as though there is no dynamic updating of the status of the protected branches on this page based on the checkbox "Enable Protected Branches"

That's right.

**Comment by n-rodriguez** [comment]
I'm sorry but this feature won't be added as it involves a lot of code for a small result.

Note that you can 'refresh' tabs in repository edit view by switching tabs back and forth (it's Ajax calls behind).
