### ISSUE TITLE
cannot add new repositorie to existing project

### ISSUE THREAD

**Issue by dziustino** [jbox-web/redmine_git_hosting#422]
Hello,

I am trying to add a new repository to an existing project. The projects are migrated from redmine 2.5.1. Previous system did not have any plugins. But repository tab gives me 404 not found.

I did connect to ssh server, placed new project and do:
```
git init --bare my-project.git
```

The git pollutes the directory where the project is but nothing else happens even after:
```
touch tmp/restart 
```
and/or 
```
rails runner "Repository.fetch_changesets" -e production
```

But if I create a NEW project. Than everything is fine. repositories are being created, and I can do commits and files are being created. I can browse through that new project files in the repository from redmine.

Any documentation given this? Or maybe I missed a solved issue already.

Environment:
- Redmine version                3.0.1.stable.14180
- Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
- Rails version                  4.2.1
- Environment                    production
- Database adapter               Mysql2

SCM:
- Subversion                     1.6.17
- Git                            1.7.9.5
- Filesystem                     
- Xitolite                       1.7.9.5

Redmine plugins:
 - progressive_projects_list      2.0.1
 - redmine_agile                  1.3.8
 - redmine_bootstrap_kit          0.2.3
 - redmine_checklists             3.0.4
 - redmine_dmsf                   1.5.1 stable
 - redmine_git_hosting            1.0.4

System:
- ubuntu 12.04
- rvm 1.26.11

Used this tutorial to install gitolite http://redmine-git-hosting.io/get_started . Everything is on the save server.

**Comment by n-rodriguez** [comment]
> Any documentation given this? Or maybe I missed a solved issue already.

This is just not the point of this plugin...

**Comment by dziustino** [comment]
Thx. Fixed this. But dont' know where to put now post-receive hook or whatever to make update redmine repository after git push.
```
#!/bin/sh
curl -k "http://redmine.domain.com/sys/fetch_changesets?key=<service key>
```

but doing myself in the terminal curl -k "..." everything gets updated.

Just it seems, that I cannot make run the script post-receive either from /opt/gitolite/repositories/my_repo/hooks/ dir
or 
/opt/gitolite/local/common/hooks/ dir

**Comment by n-rodriguez** [comment]
Hi!

You need to install hooks manually. To do so : go in *Administration -> Redmine Git Hosting -> Hooks* and click on the "Install hooks" link.
