### ISSUE TITLE
Can't add repository

### ISSUE THREAD

**Issue by Garrcomm** [jbox-web/redmine_git_hosting#423]
Hi,

I'm currently trying to get the git_hosting working. Already fixed a previous issue (#420) but still can't get it to work. In my git hosting log, the following entry came up:
<pre>root@debian:/opt/redmine/redmine-3.0/log# cat git_hosting.log
# Logfile created on 2015-04-26 23:01:40 +0200 by logger.rb/31641
2015-04-26 23:01:40 +0200 [INFO] User 'stefan' created a new repository 'test2'
2015-04-26 23:01:40 +0200 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-04-26 23:01:40 +0200 [INFO] add_repository : repository 'test2' does not exist in Gitolite, create it ...
2015-04-26 23:01:40 +0200 [INFO] add_repository : commiting to Gitolite...
2015-04-26 23:01:40 +0200 [INFO] add_repository : let Gitolite create empty repository 'repositories/test2.git'
2015-04-26 23:01:40 +0200 [INFO] Execute Gitolite Plugins
2015-04-26 23:01:41 +0200 [INFO] Create README file for repository 'test2'
2015-04-26 23:01:41 +0200 [ERROR] Error while creating README file for repository 'test2'
2015-04-26 23:01:41 +0200 [ERROR] Early EOF
2015-04-26 23:01:41 +0200 [ERROR] Git exited with non-zero status : 128
root@debian:/opt/redmine/redmine-3.0/log#
</pre>

When I look in my config files, my gitolite.conf looks like this:
<pre>repo    @all
  RW+                            = redmine_gitolite_admin_id_rsa

repo    gitolite-admin
  RW+                            = redmine_gitolite_admin_id_rsa

repo    test
  R                              = DUMMY_REDMINE_KEY gitweb
  config redminegitolite.projectid = test
  config redminegitolite.repositoryid =
  config redminegitolite.repositorykey = KGFEO1dJRtHTCqFpnHSPQb2h6J0KRCFcYX2ia0AyKUwoeBWqABidOFQI6dHlMTy
  config http.uploadpack = true
  config http.receivepack = true
  config multimailhook.enabled = false

repo    test2
  R                              = DUMMY_REDMINE_KEY gitweb
  config redminegitolite.projectid = test2
  config redminegitolite.repositoryid =
  config redminegitolite.repositorykey = Y9H5MHSwy8o5kFxTZXpnyKcZwfFxPKKHm528JFZNc2TizRd6M6ftZ0iznU8XwMR
  config http.uploadpack = true
  config http.receivepack = true
  config multimailhook.enabled = false

repo    testing
  RW+                            = @all
</pre>
The authorized_keys contains:
<pre># gitolite start
command="/opt/git/gitolite/src/gitolite-shell redmine_stefan_3",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa [valid_key] stefan@debian
command="/opt/git/gitolite/src/gitolite-shell redmine_gitolite_admin_id_rsa",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa [valid_key] redmine@debian
# gitolite end
</pre>

Could you please give some guidance on solving this issue?

**Comment by Garrcomm** [comment]
Hi @n-rodriguez ,

Did you find time to look into this by any chance? If you need any more info, please let me know. I can even provide access to the VM this is happening in.

Kind regards,
Stefan

**Comment by n-rodriguez** [comment]
Hi there!

Actually it seems to work as repositories are created. The issue here is README file creation that is not working. If you uncheck 'create README file' on repository creation you should not have these errors.

This might be a SSH key permission issue on Gitolite side : check that ```redmine_stefan_3``` and ```redmine_gitolite_admin_id_rsa``` are truly 2 different SSH keys. If not, Gitolite will pick up the first SSH key it'll find. So if the keys are the same Gitolite will use ```redmine_stefan_3``` as the current user to check the permissions against the repository. This will end in failure since at this moment ```redmine_stefan_3``` don't have the RW permission yet.

**Comment by n-rodriguez** [comment]
Check that you can clone those repositories by hand (even if they are empty).
If you have an error like 'repository don't exist' check your ```.gitolite.rc``` config file : http://redmine-git-hosting.io/get_started/#step-5-gitolite-must-accept-hook-keys and do a project resync.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by Garrcomm** [comment]
Hi,

Sorry for the late response. I retraced all steps and everything is working now. I probably forgot something.
