### ISSUE TITLE
Cannot clone/fetch repository from some machines

### ISSUE THREAD

**Issue by tomzx** [jbox-web/redmine_git_hosting#425]
Ruby: 1.9.3-p392
Rails: 3.2.18
Redmine: 2.5.1.stable
Redmine Git Hosting: 0.7.10
Git: 2.3.3
Gitolite: 3

Hi,

I have a weird issue I faced today while trying to clone/fetch a repository from three different machines.

On two machines, I was able to git clone/fetch through the https interface, but impossible to do so on the third one. I would get the following message:

```
fatal: https://server/project.git/info/refs not valid: is this a git repository?
```

Finally, if I made the redmine project public, it would allow me to clone/fetch without any issue.

**Comment by n-rodriguez** [comment]
What is the Git version installed on your machines?

**Comment by tomzx** [comment]
@n-rodriguez: 2.3.3 is installed on all machines. I've also tried 1.7.1 (from the CentOS 6.6 yum repository) and 2.3.7 on the machine that wouldn't work.

**Comment by kostgr** [comment]
@tomzx: Weird question: have you already checked the access rights on the git-files for web-server user?

**Comment by tomzx** [comment]
@kostgr: yes, that is generally my first reaction. Although I don't see how this would explain it working on some machines while not on others (considering I was using the exact same redmine user).

**Comment by n-rodriguez** [comment]
Hi! I don't think this is a permission issue but more a parsing issue. The SmartHttpController parse the URL and the parameters sent by git to determine the repository you're working with and what you're doing (git-push or git-pull). I think the error is around this.

The best way to solve this would be to migrate to the latest plugin version (1.0.4, http://redmine-git-hosting.io/how-to/migrate/#step-by-step-migration-from-0710-version-to-v10x).
In version 1.x the 'home made' SmartHttpController has been replaced by [Grack](https://github.com/gitlabhq/grack) which is used and maintained by Gitlab.

**Comment by tomzx** [comment]
@n-rodriguez We'll be upgrading our redmine+redmine_git_hosting plugin shortly. I'll let you know if we are still having issue after the upgrade.

Thanks for the support.

**Comment by n-rodriguez** [comment]
HI there! any news?

**Comment by tomzx** [comment]
Hey @n-rodriguez,

Sorry for not getting back to you. After upgrading to 1.0.3 we haven't had any issue (so far).

Thanks for the great work!

**Comment by n-rodriguez** [comment]
> After upgrading to 1.0.3 we haven't had any issue (so far).

Glad to hear it :) Don't forget to check out the new versions : http://redmine-git-hosting.io/blog/ ;)
