### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by Hugodby** [jbox-web/redmine_git_hosting#428]
Hello,

I edited plugins/redmine_git_hosting/init.rb before installing the plugin to change some default settings. Some of the change made to init.rb are applied to redmine settings but others don't.
It's ok with these one :
```
      :gitolite_ssh_private_key       => '/home/redmine/.ssh/redmine_gitolite_admin_id_rsa',
      :gitolite_ssh_public_key        => '/home/redmine/.ssh/redmine_gitolite_admin_id_rsa.pub',
```
For these settings it doesn't work :
```
:ssh_server_domain                => 'localhost:54376',

:http_server_subdir               => '/redmine',
```
The setting value in redmine remains default ('localhost', './') even if changed in init.rb.

However, after install these settings can be applied with the restore_default_settings task : 
```
redmine@af6948ccbb15:/opt/redmine$ bundle exec rake redmine_git_hosting:restore_default_settings RAILS_ENV=production                    
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
Reloading defaults from init.rb...
Changing 'gitolite_temp_dir' : /tmp/redmine_git_hosting/ => /opt/redmine/tmp/redmine_git_hosting
Changing 'gitolite_recycle_bin_expiration_time' : 24.0 => 24.0
Changing 'ssh_server_domain' : localhost => localhost:54376
Changing 'http_server_subdir' :  => /redmine
Committing changes ... 
Success!
Done!
```

**Comment by n-rodriguez** [comment]
Hi! 

> I edited plugins/redmine_git_hosting/init.rb before installing the plugin to change some default settings. Some of the change made to init.rb are applied to redmine settings but others don't.

I think this comes from the DB migrations which are very... complex. Some settings might be overriden during the migration.

The best way to update settings after install is to run the rake task like you did :
```redmine@af6948ccbb15:/opt/redmine$ bundle exec rake redmine_git_hosting:restore_default_settings RAILS_ENV=production```
