### ISSUE TITLE
Migration to a new server with new Redmine version (2->3).

### ISSUE THREAD

**Issue by MikhailKrasnobaev** [jbox-web/redmine_git_hosting#433]
Hi! Thanks for the great plugin.

I have a question about the correct way of moving to the new server. (Made a fresh install of Redmine + redmine_git_hosting using your guides). 
The way I see it:
1. Update redmine_git_hosting to the latest version on the old server.
2. Try to update Redmine itself on the old machine.
3. Move Redmine database, settings, ssh_keys folder to the new server. (Using official Redmine migration guideline)
4. Move repos, aut. keys form .ssh folder from old gitolite to the new one.
5. Check database and git_hosting settings.

Did i miss anything? 
```
My running configuration:
Environment:
  Redmine version                2.6.2.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.10.4
  Filesystem                     
  Xitolite                       1.7.10.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.3
  redmine_git_hosting            1.0.3

And the new one:
Environment:
  Redmine version                3.0.2.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.10.4
  Filesystem                     
  Xitolite                       1.7.10.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.3
  redmine_git_hosting            1.0.4
```

**Comment by n-rodriguez** [comment]
> The way I see it:
> 1. Update redmine_git_hosting to the latest version on the old server.
> 2. Try to update Redmine itself on the old machine.
> 3. Move Redmine database, settings, ssh_keys folder to the new server. (Using official Redmine migration guideline)
> 4. Move repos, aut. keys form .ssh folder from old gitolite to the new one.
> 5. Check database and git_hosting settings.
>
> Did i miss anything? 

Yes you can do it this way. For the step 4 I would use rsync to copy the entire Gitolite dir to the new server. Also don't forget to restore sudo settings.

Here what I do : imagine you have your Redmine installation with RVM in ```/home/redmine``` and your Gitolite install in ```/home/git```, all you have to do is :

1) recreate redmine and git users on the new server
2)
```
rsync -aPh /home/redmine ip_address:/home/
rsync -aPh /home/git ip_address:/home/
```
3) restore the database on the new server
4) restore sudo settings on the new server

Et voila :)

**Comment by MikhailKrasnobaev** [comment]
Thanks a lot!
I will give a feedback a soon as I try it out.

**Comment by n-rodriguez** [comment]
Hi there! Any news? Can I close this issue?

**Comment by MikhailKrasnobaev** [comment]
Hi, I haven't tried yet. Will try probably this week (holiday + vacation coming). So if you want you can close it, I will post my result in the survey thread.

**Comment by n-rodriguez** [comment]
Thanks!
