### ISSUE TITLE
Problem installing bundles and gitlab-grack

### ISSUE THREAD

**Issue by carukc** [jbox-web/redmine_git_hosting#434]
Hello,

I'm trying to install redmine_git_hosting on EasyRedmine.  After pulling the files I do a 'bundle install'

For some reason it does not get further than this:

Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    gitlab-grack (>= 0) ruby depends on
      rack (~> 1.6.0) ruby

    rails (= 3.2.21) ruby depends on
      actionpack (= 3.2.21) ruby depends on
        rack (~> 1.4.5) ruby

gitlab-grac is a requirement of redmien_git_hosting and seems to require rack 1.6.x

I thought initially that the problem was that rails 4 seemed to be loading by default but even after I changed to Ruby 2.1 with Rails 3.2 (as per listed requirements on redmine site).

Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    gitlab-grack (>= 0) ruby depends on
      rack (~> 1.6.0) ruby

    rails (= 3.2.21) ruby depends on
      actionpack (= 3.2.21) ruby depends on
        rack (~> 1.4.5) ruby

    rails (= 3.2.21) ruby depends on
      actionpack (= 3.2.21) ruby depends on
        rack-cache (~> 1.2) ruby depends on
          rack (>= 0.4) ruby

Unfortunately no matter what I do I cannot seem to get around this problem.

Is gitlab-grac required and does it really require rack 1.6?

Thanks
Chris

**Comment by n-rodriguez** [comment]
> Is gitlab-grac required and does it really require rack 1.6?

Yes

> Unfortunately no matter what I do I cannot seem to get around this problem.

You must edit plugin's Gemfile and comment/uncomment the lines corresponding to your Redmine version.

**Comment by carukc** [comment]
I see that now.  Many Thanks for your help

Chris
