### ISSUE TITLE
Add redmine groups to gitolite configuration

### ISSUE THREAD

**Issue by tomzx** [jbox-web/redmine_git_hosting#435]
It appears that groups defined in redmine are not imported in the gitolite config. It would probably be nice to have support for that so that things such as giving group permissions on protected branches can be done.

My current use case: I want to give READ permissions to developers (or @all) on the develop/master branches, while giving RW+ permissions to lead developers on those branches.

**Comment by n-rodriguez** [comment]
> It appears that groups defined in redmine are not imported in the gitolite config. It would probably be nice to have support for that so that things

Yes and it's normal. This won't be implemented.

> My current use case: I want to give READ permissions to developers (or @all) on the develop/master branches, while giving RW+ permissions to lead developers on those branches.

See [here](https://github.com/jbox-web/redmine_git_hosting/issues/389)

**Comment by tomzx** [comment]
I don't think #389 is exactly what I'm looking for. It's related to force pushing, while in my case I want to prevent @all from having RW permission.

Is there any plan to support having a "per group" set of permissions or will we have to define permissions on a per user basis (so you cannot use this right away if you add a new user to a project, you need to add them to the project under various group AND then add them to the specific protected branches rules under the repository settings).

**Comment by n-rodriguez** [comment]
Hi! Sorry for the delay. 

> I don't think #389 is exactly what I'm looking for. It's related to force pushing, while in my case I want to prevent @all from having RW permission.

Actually it's quite the same thing : protected branches. (http://gitolite.com/gitolite/conf.html#rules)

I worked on a group based implementation : https://github.com/jbox-web/redmine_git_hosting/commit/2912c1dc9db535fe269fedd28be7964617042ab8

With this new implementation you can add both users and groups on each protected branch (refex).
When you add a group, group's users are automatically added to the protected branch so you can do some exclusion latter.
When you add a user in a group, all the protected branches linked to this group are updated.
The same happens when you remove a user from a group.

**Comment by hameno** [comment]
Great! :)

**Comment by n-rodriguez** [comment]
![test - redmine](https://cloud.githubusercontent.com/assets/3433835/9486310/d8207eae-4bc5-11e5-9b7c-74865fc8b02f.png)

**Comment by n-rodriguez** [comment]
In Gitolite conf : 
```
repo    test/efzfezfzefze
  RW+   .*                       = redmine_admin_1 redmine_developer1_3 redmine_developer3_6 redmine_developer4_11
  -     master                   = redmine_admin_1 redmine_developer1_3 redmine_developer3_6 redmine_developer4_11
  -     refs/tags/v[0-9]         = redmine_developer2_4
  config redminegitolite.projectid = test
  config redminegitolite.repositoryid = efzfezfzefze
  config redminegitolite.repositorykey = 5MdUmqBkKAwvB9Ee2OScVZ6tArWy3TSEMxvG3GWdSvDbN8xSqNmiKKg7qI0Vd9x
  config http.uploadpack = true
  config http.receivepack = true
  config multimailhook.enabled = false
```

**Comment by n-rodriguez** [comment]
The last 3 lines are not in Gitolite conf because there's no users declared.
This mimic the example from [Gitolite doc](http://gitolite.com/gitolite/conf.html#rules).

**Comment by n-rodriguez** [comment]
Note there's some limitations : when protected branches are enabled, plugin assumes that it has full control on repository configuration. In other words : manual modifications won't be saved or handled in any ways.

**Comment by n-rodriguez** [comment]
Another limitation : it only works with SSH. And actually this is normal as rules checking is done by Gitolite. When pushing over HTTP these checks are not done. We only check if user has `commit` permission.
