### ISSUE TITLE
RedCloth cannot be found (Redmine 3.0)

### ISSUE THREAD

**Issue by shaneonabike** [jbox-web/redmine_git_hosting#436]
I followed your instructions but receive the following error for some reason?

```
bundle exec rake deploy:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting --trace
(in /opt/redmine)
rake aborted!
NoMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x00000003140fe8>
/var/lib/gems/1.9.1/gems/railties-4.2.1/lib/rails/railtie/configuration.rb:95:in `method_missing'
/opt/redmine/config/application.rb:20:in `<class:Application>'
/opt/redmine/config/application.rb:8:in `<module:RedmineApp>'
/opt/redmine/config/application.rb:7:in `<top (required)>'
/opt/redmine/Rakefile:5:in `require'
/opt/redmine/Rakefile:5:in `<top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

**Comment by shaneonabike** [comment]
Actually this was a result of me not properly installing redmine_bootstrap_kit before.

I am now experiencing a strange issue where it is complaining that the RedCloth version cannot be found. It's installed and I was sure to comment out the Redmine 2.x line and uncomment the Redmine 3.x line

<code>
-------- The exception is as follows: -------
Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)
</code>

**Comment by shaneonabike** [comment]
Also when I run the bundle install it complains because there are multiple declarations of the same redcarpet which I am not sure whether this is causing the issue?

<pre>
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Your Gemfile lists the gem redcarpet (~> 3.1.2) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.

Using rake 10.4.2
Using RedCloth 4.2.9
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.6.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.6
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.1
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.1
Using globalid 0.3.5
Using activejob 4.2.1
Using mime-types 2.5
Using mail 2.6.3
Using actionmailer 4.2.1
Using actionpack-action_caching 1.1.1
Using actionpack-xml_parser 1.0.2
Using activemodel 4.2.1
Using arel 6.0.0
Using activerecord 4.2.1
Using asciidoctor 1.5.2
Using coderay 1.1.0
Using creole 0.5.0
Using dalli 2.7.4
Using github-markup 1.3.3
Using gitlab-grack 2.0.0.pre from https://github.com/jbox-web/grack.git (at fix_rails4)
Using gratr19 0.4.4.1
Using rugged 0.21.4
Using gitolite-rugged 1.0.0 from https://github.com/jbox-web/gitolite-rugged.git (at v1.0.0)
Using tilt 2.0.1
Using haml 4.0.6
Using sexp_processor 4.5.1
Using ruby_parser 3.6.6
Using html2haml 2.0.0
Using thor 0.19.1
Using railties 4.2.1
Using haml-rails 0.9.0
Using hiredis 0.6.0
Using jquery-rails 3.1.2
Using mysql2 0.3.18
Using net-ldap 0.3.1
Using rubypants 0.2.0
Using org-ruby 0.9.12
Using protected_attributes 1.0.9
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using bundler 1.9.4
Using sprockets 3.0.3
Using sprockets-rails 2.2.4
Using rails 4.2.1
Using rbpdf 1.18.5
Using redcarpet 3.1.2
Using redis 3.2.1
Using request_store 1.0.5
Using rmagick 2.13.4
Using will_paginate 3.0.7
Bundle complete! 40 Gemfile dependencies, 66 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
</pre>

Any help would be awesome!

**Comment by n-rodriguez** [comment]
> Any help would be awesome!

Everything seems ok. It's just a warning : ```While it's not a problem now...```

**Comment by shaneonabike** [comment]
Yeah except that this is on Redmine 3.0.1 and I guess you aren't supporting that just yet?

**Comment by n-rodriguez** [comment]
> Yeah except that this is on Redmine 3.0.1 and I guess you aren't supporting that just yet?

Redmine 3.x is supported.

**Comment by shaneonabike** [comment]
But in the other ticket you said it wasn't (I'm confused).

I am getting this error in Redmine 3.x and it's complaining about not being able to find RedCarpet? Any clues....

**Comment by n-rodriguez** [comment]
> But in the other ticket you said it wasn't (I'm confused)

Redmine 3.x is supported, but Redmine 3.0.1 is buggy. So you can install Redmine 3.0.0 o Redmine 3.0.2 but not Redmine 3.0.1.

**Comment by shaneonabike** [comment]
Sorry I made a mistake I double checked the version.rb and it is 3.0.2....

So I am still stuck do you have any suggestions on how I can fix this?

**Comment by Hugodby** [comment]
You seem to use ruby 1.9.1 which isn't supported.
Check requirements : http://redmine-git-hosting.io/download/

**Comment by shaneonabike** [comment]
Well there's two Rubies actually... but from the recent error logs that I hadn't posted it seems to use the right one... maybe it's a path issue?

<pre>
<p>-------- The exception is as follows: -------</p>
Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)
<pre>  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler/spec_set.rb:92:in `block in materialize&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler/spec_set.rb:85:in `map!&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler/spec_set.rb:85:in `materialize&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler/definition.rb:132:in `specs&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler/definition.rb:177:in `specs_for&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler/definition.rb:166:in `requested_specs&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler/environment.rb:18:in `requested_specs&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler/runtime.rb:13:in `setup&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler.rb:122:in `setup&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/bundler-1.9.5/lib/bundler/setup.rb:18:in `&lt;top (required)&gt;&#39;
  /home/deploy/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require&#39;
  /home/deploy/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/passenger-5.0.7/lib/phusion_passenger/loader_shared_helpers.rb:399:in `activate_gem&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/passenger-5.0.7/lib/phusion_passenger/loader_shared_helpers.rb:277:in `block in run_load_path_setup_code&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/passenger-5.0.7/lib/phusion_passenger/loader_shared_helpers.rb:404:in `running_bundler&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/passenger-5.0.7/lib/phusion_passenger/loader_shared_helpers.rb:276:in `run_load_path_setup_code&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/passenger-5.0.7/helper-scripts/rack-preloader.rb:99:in `preload_app&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/passenger-5.0.7/helper-scripts/rack-preloader.rb:153:in `&lt;module:App&gt;&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/passenger-5.0.7/helper-scripts/rack-preloader.rb:29:in `&lt;module:PhusionPassenger&gt;&#39;
  /home/deploy/.rvm/gems/ruby-2.1.0/gems/passenger-5.0.7/helper-scripts/rack-preloader.rb:28:in `&lt;main&gt;&#39;</pre>


[ 2015-05-14 18:00:24.9831 26453/7fc96e732700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the error is 2dfe0520. Please see earlier logs for details about the error.
</pre>

**Comment by shaneonabike** [comment]
I had installed the other version of Ruby but it did not work properly. I reverted to using rvm instead. For those whom are having this issue they can use the instructions here. It was fairly easy afterwards to upgrade the Ruby version properly. AND NOW it works yeah!

http://www.webupd8.org/2014/11/how-to-install-rvm-ruby-version-manager.html
