### ISSUE TITLE
"Get Started" document

### ISSUE THREAD

**Issue by abubobe** [jbox-web/redmine_git_hosting#437]
Hi,
First of all, I really appreciate your work here. Awesome work!

I did different way setting-up my redmine than yours. It ends up I am using www-data as the user running redmine. I had successfully installed this redmine_git_hosting plugin though. 
While I was following your documentation at here (http://redmine-git-hosting.io/get_started/#step-2-clone-the-plugin), I was curious where this link (http://redmine-git-hosting.io/troubleshooting#a-note-about-path-variable) is pointing to. Because, as I said, I am using www-data user running redmine, I would like to know how to properly configure this plugin.
 
Is the link "a-note-about-path-variable" pointing to the right document?

Thanks!

**Comment by n-rodriguez** [comment]
Hi!

Sorry for the response delay. This points to an old documentation part. It's not needed anymore.
