### ISSUE TITLE
Mirror automatically isn't updated

### ISSUE THREAD

**Issue by vchess** [jbox-web/redmine_git_hosting#438]
Hi.
The Repository Mirrors in the project is set up. The mirror is updated if to make (to press the PUSH button).
If to make git push in a repository the mirror automatically isn't updated and in logs an error

```log
/opt/redmine/plugins/redmine_git_hosting/app/controllers/gitolite_hooks_controller.rb:30: warning: toplevel constant Redmine referenced by Hooks::Redmine
Thu May 21 20:18:36 2015 - /opt/redmine/plugins/redmine_git_hosting/app/controllers/gitolite_hooks_controller.rb:30:in `block in post_receive_redmine': undefined method `new' for Redmine:Module (NoMethodError)
Thu May 21 20:18:36 2015 -      from /usr/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/http/response.rb:44:in `each'
Thu May 21 20:18:36 2015 -      from /usr/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/http/response.rb:44:in `each'
Thu May 21 20:18:36 2015 -      from /usr/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/http/response.rb:44:in `each'
Thu May 21 20:18:36 2015 -      from /usr/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:46:in `each'
Thu May 21 20:18:36 2015 -      from /usr/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:460:in `each'
Thu May 21 20:18:36 2015 -      from /usr/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/body_proxy.rb:31:in `each'

**Comment by n-rodriguez** [comment]
Hi! I can't reproduce this bug. Do you have other plugins installed?

**Comment by vchess** [comment]
Hi!

Environment:
  Redmine version                2.6.5.stable
  Ruby version                   2.0.0-p510 (2014-06-28) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  a_common_libs                  1.1.3
  ajax_counters                  0.0.1
  appmenuadds                    1.4.4
  clipboard_image_paste          1.10
  extra_queries                  0.0.1
  global_roles                   1.0.0
  progressive_gantt_mods         0.0.2
  progressive_projects_list      2.0.1
  projects_treeview              0.0.3-78
  redmine_admin_monitor          1.0.0
  redmine_banner                 0.1.1
  redmine_better_gantt_chart     0.9.0
  redmine_bootstrap_kit          0.2.3
  redmine_cas                    1.2.1
  redmine_code_review            0.6.5
  redmine_codebutton             0.1.0
  redmine_dmsf    1.5.1 stable
  redmine_documents_short        0.3.0
  redmine_email_inline_images    1.0.0
  redmine_git_hosting            1.0.4
  redmine_helpdesk               0.0.14
  redmine_improved_searchbox     0.0.3
  redmine_issue_reminder         0.1.0
  redmine_issue_tabs             0.0.1
  redmine_ldap_sync              2.0.5.devel.g8cdd93e782
  redmine_lightbox               0.0.1
  redmine_questions              0.0.5
  redmine_sidekiq                2.1.0
  redmine_stealth                0.6.0
  timelog_on_issue_page          0.0.1
  under_construction             1.0.0
  unread_issues                  1.0.0
  usability                      1.0.0

**Comment by vchess** [comment]
Hi!
Found guilty, is a plug: https://github.com/dkuk/timelog_on_issue_page

**Comment by n-rodriguez** [comment]
Hi! I've made a fix : https://github.com/n-rodriguez/timelog_on_issue_page
I've submitted a pull request, waiting for the merge.
