### ISSUE TITLE
Rugged::NetworkError (Unsupported URL protocol) when interact with redmine git hosting

### ISSUE THREAD

**Issue by leohartx** [jbox-web/redmine_git_hosting#440]
Hi there, i got this issue when i do anything with redmine git hosting :
```
Rugged::NetworkError (Unsupported URL protocol):
vendor/bundle/ruby/2.2.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:in clone_at' vendor/bundle/ruby/2.2.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:311:inclone'
vendor/bundle/ruby/2.2.0/bundler/gems/gitolite-rugged-eaa0d7a84b30/lib/gitolite/gitolite_admin.rb:110:in initialize' plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:67:innew'
plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:67:in gitolite_admin' plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:39:inresync_gitolite'
plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:50:in resync_gitolite' plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:109:inresync_gitolite'
plugins/redmine_git_hosting/app/services/gitolite_accessor.rb:15:in `destroy_ssh_key'
```
from creating new repository, adding new key, edit repository , etc...

Config test show all green. is there any i'm missing ?

i followed this guide and all passed http://redmine-git-hosting.io/get_started/

there is one thing special is that i have custom ssh port, and i set custom ssh port in redmine git hosting config already.

please let me know what is the problem with my implemetation.

Thank you.

**Comment by seberoth** [comment]
Hi,

just had the same problem. After hours of debugging I have found the problem. The package libssh2-1-dev (Debian 8.0) was missing on my system. So I installed it and reinstalled/recompiled the rugged gem and everything is working fine now. Something like this:

```
sudo apt-get install libssh2-1-dev
sudo gem uninstall rugged
sudo gem install rugged -v='0.22.2'
```

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/get_started/#step-1-install-dependencies

**Comment by leohartx** [comment]
thank you, i will try it again. though i followed step 1 install dependencies before.

**Comment by leohartx** [comment]
hi there, i just tried again and still see the issue . please see git_hosting.log content below 

2015-06-01 08:58:11 -0400 [INFO] User 'atheotsky' created a new repository 'rostanvo/r18'
2015-06-01 08:58:11 -0400 [INFO] Create tmp directory : '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-06-01 08:58:11 -0400 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-06-01 08:58:11 -0400 [ERROR] Access denied for Gitolite Admin SSH Keys
2015-06-01 08:58:11 -0400 [ERROR] Unsupported URL protocol
2015-06-01 08:58:21 -0400 [INFO] Create tmp directory : '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-06-01 08:58:21 -0400 [INFO] Testing if Redmine user 'leo' can sudo to Gitolite user 'git'...
2015-06-01 08:58:21 -0400 [INFO] OK!
2015-06-01 08:58:21 -0400 [INFO] Installing Redmine Gitolite mirroring SSH keys ...
2015-06-01 08:58:21 -0400 [INFO] Done !
2015-06-01 08:58:27 -0400 [INFO] User 'atheotsky' has removed repository 'rostanvo/r18'
2015-06-01 08:58:27 -0400 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-06-01 08:58:27 -0400 [ERROR] Access denied for Gitolite Admin SSH Keys
2015-06-01 08:58:27 -0400 [ERROR] Unsupported URL protocol


i use centos 6.5 , this is output of dependencies installation 

yum groupinstall "Development Tools"; yum install libssh2 libssh2-devel cmake libgpg-error-devel
Loaded plugins: fastestmirror
Setting up Group Process
Loading mirror speeds from cached hostfile
 * base: centos-distro.cavecreek.net
 * epel: mirrors.kernel.org
 * extras: repos.lax.quadranet.com
 * passenger: passenger.stealthymonkeys.com
 * remi: mirrors.mediatemple.net
 * updates: mirrors.easynews.com
Package flex-2.5.35-9.el6.x86_64 already installed and latest version
Package gcc-4.4.7-11.el6.x86_64 already installed and latest version
Package redhat-rpm-config-9.0.3-42.el6.centos.noarch already installed and latest version
Package rpm-build-4.8.0-38.el6_6.x86_64 already installed and latest version
Package 1:make-3.81-20.el6.x86_64 already installed and latest version
Package patch-2.6-6.el6.x86_64 already installed and latest version
Package 1:pkgconfig-0.23-9.1.el6.x86_64 already installed and latest version
Package gettext-0.17-18.el6.x86_64 already installed and latest version
Package automake-1.11.1-4.el6.noarch already installed and latest version
Package bison-2.4.1-5.el6.x86_64 already installed and latest version
Package libtool-2.2.6-15.5.el6.x86_64 already installed and latest version
Package autoconf-2.63-5.1.el6.noarch already installed and latest version
Package gcc-c++-4.4.7-11.el6.x86_64 already installed and latest version
Package binutils-2.20.51.0.2-5.42.el6.x86_64 already installed and latest version
Package patchutils-0.3.1-3.1.el6.x86_64 already installed and latest version
Package byacc-1.9.20070509-7.el6.x86_64 already installed and latest version
Package indent-2.2.10-7.el6.x86_64 already installed and latest version
Package systemtap-2.5-5.el6.x86_64 already installed and latest version
Package diffstat-1.51-2.el6.x86_64 already installed and latest version
Package elfutils-0.158-3.2.el6.x86_64 already installed and latest version
Package cvs-1.11.23-16.el6.x86_64 already installed and latest version
Package rcs-5.7-37.el6.x86_64 already installed and latest version
Package subversion-1.6.11-12.el6_6.x86_64 already installed and latest version
Package gcc-gfortran-4.4.7-11.el6.x86_64 already installed and latest version
Package 1:doxygen-1.6.1-6.el6.x86_64 already installed and latest version
Package intltool-0.41.0-1.1.el6.noarch already installed and latest version
Package git-1.7.1-3.el6_4.1.x86_64 already installed and latest version
Package ctags-5.8-2.el6.x86_64 already installed and latest version
Package cscope-15.6-6.el6.x86_64 already installed and latest version
Package swig-1.3.40-6.el6.x86_64 already installed and latest version
Warning: Group development does not have any packages.
No packages in any requested group available to install or update
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos-distro.cavecreek.net
 * epel: mirrors.kernel.org
 * extras: repos.lax.quadranet.com
 * passenger: passenger.stealthymonkeys.com
 * remi: mirrors.mediatemple.net
 * updates: mirror.hmc.edu
Package libssh2-1.4.2-1.el6_6.1.x86_64 already installed and latest version
Package libssh2-devel-1.4.2-1.el6_6.1.x86_64 already installed and latest version
Package cmake-2.8.12.2-4.el6.x86_64 already installed and latest version
Package libgpg-error-devel-1.7-4.el6.x86_64 already installed and latest version
Nothing to do
