### ISSUE TITLE
Custom hooks

### ISSUE THREAD

**Issue by maxiv** [jbox-web/redmine_git_hosting#446]
Hello.
How I can add my custom hook to repository? For example I need post-commit hook for git-ftp uploading.

**Comment by n-rodriguez** [comment]
Put your hook scripts anywhere on the filesystem then edit [```plugins/redmine_git_hosting/lib/load_gitolite_hooks.rb```](https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/load_gitolite_hooks.rb) to declare your hook mapping (source file and destination file). You'll find more documentation in the file.

**Comment by maxiv** [comment]
Thank you.

**Comment by hallux4** [comment]
Hello,
I try to setup a mirror repository from my redmine_git to github.

So far I can to handle the creation and the deletion of the repository by using incrontab and the github API.
But now I try to exec the code below in a post-receive hook:

gitinfo="git@github.com:/hallux4/$GL_REPO.git"
git push --mirror ssh://$gitinfo >> /home/git/tmp.txt 2>&1

I put the file in plugins/redmine_git_hosting/contrib/hooks/post-receive/ and add this in the file you mentioned:
gitolite_hook do
    name        'mirror_repo.sh'
    source      'post-receive/mirror_repo.sh'
    destination 'post-receive.d/mirror_repo'
    executable  true
  end


Then I updated the hook:
RAILS_ENV=production rake redmine_git_hosting:install_gitolite_hooks it will install the hook in ~/gitolite-admin/local/hooks/common/post-receive.d/ directory

Then I must commit the change and push it, after this it's ok for all the repository.

But if I create a new project, the new repository will not have the hook installed.

Do you know what shoudl be done to have the hook added for all the new project ?

**Comment by n-rodriguez** [comment]
> Do you know what shoudl be done to have the hook added for all the new project ?

Well I thought Gitolite would handle the case automatically. Did you try to put your hooks in the Gitolite local dir? (http://gitolite.com/gitolite/non-core.html)

Btw why not using plugin's mirroring feature?
