### ISSUE TITLE
Github webhook return 404 error

### ISSUE THREAD

**Issue by vlaborie** [jbox-web/redmine_git_hosting#450]
Hi,
I want use Github webhook for issue syncing but Redmine return 404 error.

My config :
- Redmine 3.0.3-stable
- Redmine git Hosting : 1.0.6
- Github webhook : https://**********/githooks/post-receive/github/redmine
 ("redmine" is my project id)

An extract of my production.log :
```
Started POST "/githooks/post-receive/github/redmine" for 192.30.252.41 at 2015-06-05 15:06:55 +0200
Processing by GitoliteHooksController#post_receive as */*
  Parameters: { ............., "type"=>"github", "projectid"=>"redmine"}
  Current user: anonymous
Completed 404 Not Found in 147ms (ActiveRecord: 2.8ms)

ActiveRecord::RecordNotFound (Couldn't find Tracker with 'id'=first [WHERE `projects_trackers`.`project_id` = ?]):
```

The trouble is apparently in redmine_git_hosting/app/services/hooks/github_issues_sync.rb, line 78 :
```
issue.tracker_id = @project.trackers.find(:first).try(:id)
```

If i change :first by a tracker id like 1,2 or 3, it's work. :first does not seem to be defined.

**Comment by n-rodriguez** [comment]
Fixed in version 1.0.7 (and 1.1.0)
