### ISSUE TITLE
gitolite config test

### ISSUE THREAD

**Issue by abubobe** [jbox-web/redmine_git_hosting#452]
Hi,,
Items in my plugin/redmine_git_hosting?tab=gitolite_config_test are mostly with red exclamation marks. I know this is not normal. What did I miss?

![screenshot - 090615 - 14 21 46](https://cloud.githubusercontent.com/assets/12483273/8053285/4781bf8c-0eb9-11e5-97f7-da5c1262616b.png)

My environment seem okay:
<pre>
Environment:
  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [i686-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
  Xitolite                       1.9.1
Redmine plugins:
  clipboard_image_paste          1.10
  progressive_projects_list      2.0.1
  redmine_bootstrap_kit          0.2.3
  redmine_git_hosting            1.1.0
  redmine_spent_time             3.0.1
</pre>

Thanks.

**Comment by abubobe** [comment]
aha ... after I clicked "install hooks" link ... all turned green except "Gitolite version".
...

**Comment by n-rodriguez** [comment]
What Gitolite version are you using?

**Comment by n-rodriguez** [comment]
Duplicate : https://github.com/jbox-web/redmine_git_hosting/issues/444
