### ISSUE TITLE
Error installation, cannot load such file -- github/markup [SOLVED]

### ISSUE THREAD

**Issue by Dragnell87** [jbox-web/redmine_git_hosting#453]
I a new server i have 
Redmine 2.6.5
ruby 2.1.6p336
redmine_githosting 1.1.0

Following the procedure i comment out the section for redmine 3 leaving just the requirement for v2 
bundle install --without development test goes well as show:
```
Using rake 10.4.2
Using i18n 0.6.11
Using multi_json 1.11.1
Using activesupport 3.2.21
Using builder 3.0.4
Using activemodel 3.2.21
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.5
Using rack-cache 1.2
Using rack-test 0.6.3
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.2.3
Using actionpack 3.2.21
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 3.2.21
Using arel 3.0.3
Using tzinfo 0.3.44
Using activerecord 3.2.21
Using activeresource 3.2.21
Using coderay 1.1.0
Using rack-ssl 1.3.4
Using json 1.8.3
Using rdoc 3.12.2
Using thor 0.19.1
Using railties 3.2.21
Using jquery-rails 3.1.2
Using mysql2 0.3.18
Using net-ldap 0.3.1
Using puma 2.11.3
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using bundler 1.10.3
Using rails 3.2.21
Using rbpdf 1.18.5
Using redcarpet 2.3.0
Using request_store 1.0.5
Using rmagick 2.13.4
Bundle complete! 27 Gemfile dependencies, 42 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

How ever when i try 
bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting
i get
```
rake aborted!
LoadError: cannot load such file -- github/markup
/opt/redmine/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/hooks/display_repository_readme.rb:1:in `<top (required)>'
/opt/redmine/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting.rb:7:in `<top (required)>'
/opt/redmine/redmine/plugins/redmine_git_hosting/init.rb:5:in `<top (required)>'
/opt/redmine/redmine/lib/redmine/plugin.rb:150:in `block in load'
/opt/redmine/redmine/lib/redmine/plugin.rb:141:in `each'
/opt/redmine/redmine/lib/redmine/plugin.rb:141:in `load'
/opt/redmine/redmine/config/initializers/30-redmine.rb:19:in `<top (required)>'
/opt/redmine/redmine/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```
googled the problem but nothing helpfully come out, can you help me to sort this out? Thanks

**Comment by n-rodriguez** [comment]
Hi! Very weird... It seems that some gems are missing. Your gem list is incomplete. It misses gitolite-rugged and some others. Is this a Bitnami stack?

**Comment by Dragnell87** [comment]
Hi, nop, ubuntu server 14.04  redmine was install from tarball and ruby with rbenv

**Comment by n-rodriguez** [comment]
Weird... The ```bundle install --without development test``` command should install gems for all plugins too.

**Comment by Dragnell87** [comment]
So i should try from scratch, delete plugins...gem and start all over?

**Comment by n-rodriguez** [comment]
Nope... You can retry the ```bundle install --without development test``` command.
Be sure to run it from Redmine root dir.

**Comment by Dragnell87** [comment]
Already try that several time always from redmine_root directory

**Comment by n-rodriguez** [comment]
So you can retry from scratch but this is really weird..;

**Comment by Dragnell87** [comment]
On it

**Comment by Dragnell87** [comment]
So i coment out REDMINE_ROOT/plugin/redmine_git_hosting/Gemfile but this time i get this
when running  bundle install --without development test

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Your Gemfile lists the gem redcarpet (~> 2.3.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.

[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: shoulda (~> 3.3.2) and shoulda (~> 3.5.0). Bundler cannot continue.

 #  from /opt/redmine/redmine/Gemfile:112
 #  -------------------------------------------
 #    #TODO: switch to "eval_gemfile file" when bundler >= 1.2.0 will be required (rails 4)
 >    instance_eval File.read(file), file
 #  end
 #  -------------------------------------------

**Comment by n-rodriguez** [comment]
You must comment the development section in plugin Gemfile.

**Comment by Dragnell87** [comment]
I Comment this section in plugins/redmine_git_hosting/Gemfile

#group :development, :test do
#  gem 'rspec', '~> 3.0.0'
#  gem 'rspec-rails', '~> 3.0.1'

#  gem 'shoulda', '~> 3.5.0'
#  gem 'shoulda-matchers', '~> 2.7.0'
#  gem 'shoulda-context'

but get

[!] There was an error parsing `Gemfile`: /opt/redmine/redmine/plugins/redmine_git_hosting/Gemfile:59: syntax error, unexpected keyword_end, expecting end-of-input. Bundler cannot continue.

 #  from /opt/redmine/redmine/Gemfile:112
 #  -------------------------------------------
 #    #TODO: switch to "eval_gemfile file" when bundler >= 1.2.0 will be required (rails 4)
 >    instance_eval File.read(file), file
 #  end
 #  -------------------------------------------

**Comment by n-rodriguez** [comment]
You forgot to comment the ```end``` statement in Gemfile.

The group declaration look like that :

``` 
group :development do
  gem foo
  gem bar
end
```

**Comment by Dragnell87** [comment]
Yes, this time everything went right, so furthermore, beyond selecting the version of redmine is necessary also comment the development portion to make it work properly. i am marking this as solved, thanks for your help and time. Regards
