### ISSUE TITLE
Edit a repository - 500 Internal Error

### ISSUE THREAD

**Issue by lukemorel** [jbox-web/redmine_git_hosting#454]
Hi there !
When I'm trying to edit a repository from 
here : http://puu.sh/ipKX9/972f37c93b.png
or here : http://puu.sh/ipL25/8dde27536e.png
I'm getting an internal error 
like that : http://puu.sh/ipL4L/d231227d96.png

I installed Bitnami Redmine Stack (3.0.3) on a Virtual machine running Ubuntu 14.04 (x64)
And here the log :
```
Started GET "/redmine/repositories/5/edit" for 192.168.1.66 at 2015-06-15 16:14:07 +0200
Processing by RepositoriesController#edit as HTML
  Parameters: {"id"=>"5"}
  Current user: lmorel (id=1)
  Rendered plugins/redmine_bootstrap_kit/app/views/common/_modal_base.html.haml (0.2ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_hosting_js_headers.html.haml (1.7ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.haml (5.9ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_edit_top.html.haml (8.1ms)
  Rendered repositories/_form.html.erb (2.8ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_xitolite_options.html.haml (16.9ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/edit.html.haml within layouts/base (30.7ms)
Completed 500 Internal Server Error in 37ms (ActiveRecord: 1.9ms)

ActionView::Template::Error (undefined method `empty?' for nil:NilClass):
    35: 
    36:               %p
    37:                 = label_tag 'repository_git_extra[default_branch]', l(:label_repository_default_branch)
    38:                 - if !repository.branches.empty?
    39:                   = f.select :default_branch, repository_branches_list(repository.branches)
    40:                 - else
    41:                   %span{ class: 'label label-info' }= repository.git_default_branch
  plugins/redmine_git_hosting/app/views/repositories/_xitolite_options.html.haml:38:in `block in _plugins_redmine_git_hosting_app_views_repositories__xitolite_options_html_haml__1506132743896284688_70230208184140'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:137:in `call'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:137:in `block (2 levels) in form_for_with_haml'
  haml (4.0.6) lib/haml/helpers.rb:278:in `with_tabs'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:137:in `block in form_for_with_haml'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  haml (4.0.6) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.1) lib/action_view/helpers/form_helper.rb:444:in `form_for'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
  haml (4.0.6) lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
  plugins/redmine_git_hosting/app/views/repositories/_xitolite_options.html.haml:5:in `_plugins_redmine_git_hosting_app_views_repositories__xitolite_options_html_haml__1506132743896284688_70230208184140'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.1) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
  haml (4.0.6) lib/haml/helpers.rb:89:in `non_haml'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
  plugins/redmine_git_hosting/app/views/repositories/edit.html.haml:21:in `_plugins_redmine_git_hosting_app_views_repositories_edit_html_haml___2318401233785687014_70230207512620'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /opt/redmine/ruby/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack-xml_parser (1.0.1) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  rack (1.6.0) lib/rack/urlmap.rb:66:in `block in call'
  rack (1.6.0) lib/rack/urlmap.rb:50:in `each'
  rack (1.6.0) lib/rack/urlmap.rb:50:in `call'
  passenger (5.0.6) lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
  passenger (5.0.6) lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  passenger (5.0.6) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (5.0.6) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  passenger (5.0.6) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

**Comment by lukemorel** [comment]
Hello !
After a fresh reinstallation of gitolite and redmine+plugins, almost everything works fine.
Sorry for the useless post !

Have a nice day

**Comment by lukemorel** [comment]
Hi there !

I think that I can re-open this issue, the logs are similar.

But I have to replace the context !
Now i'm on Ubuntu server 14.04 with Redmine 2.6.0 installed in /usr/share/redmine directory.
The plugin version is 1.1.0.

When I try to edit a project gitolite repo, I get an internal error, exactly like above !
Here is the log :
<pre>
Started GET "/redmine/repositories/83/edit" for 192.168.1.66 at 2015-06-23 16:59:55 +0200
Processing by RepositoriesController#edit as HTML
  Parameters: {"id"=>"83"}
  Current user: admin (id=1)
  Rendered plugins/redmine_bootstrap_kit/app/views/common/_modal_base.html.haml (1.2ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_hosting_js_headers.html.haml (8.4ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.haml (7.7ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_edit_top.html.haml (19.1ms)
  Rendered repositories/_form.html.erb (3.2ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_xitolite_options.html.haml (20.5ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/edit.html.haml within layouts/base (51.5ms)
Completed 500 Internal Server Error in 58.4ms

ActionView::Template::Error (undefined method `empty?' for nil:NilClass):
    35: 
    36:               %p
    37:                 = label_tag 'repository_git_extra[default_branch]', l(:label_repository_default_branch)
    38:                 - if !repository.branches.empty?
    39:                   = f.select :default_branch, repository_branches_list(repository.branches)
    40:                 - else
    41:                   %span{ class: 'label label-info' }= repository.git_default_branch
  plugins/redmine_git_hosting/app/views/repositories/_xitolite_options.html.haml:38:in `block in _plugins_redmine_git_hosting_app_views_repositories__xitolite_options_html_haml___143803506395673966_57634660'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:137:in `call'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:137:in `block (2 levels) in form_for_with_haml'
  haml (4.0.6) lib/haml/helpers.rb:278:in `with_tabs'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:137:in `block in form_for_with_haml'
  actionpack (3.2.19) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
  actionpack (3.2.19) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
  haml (4.0.6) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionpack (3.2.19) lib/action_view/helpers/capture_helper.rb:40:in `capture'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionpack (3.2.19) lib/action_view/helpers/form_helper.rb:378:in `form_for'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
  haml (4.0.6) lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
  plugins/redmine_git_hosting/app/views/repositories/_xitolite_options.html.haml:5:in `_plugins_redmine_git_hosting_app_views_repositories__xitolite_options_html_haml___143803506395673966_57634660'
  actionpack (3.2.19) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.19) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.19) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.19) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
  actionpack (3.2.19) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
  actionpack (3.2.19) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.19) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.19) lib/action_view/renderer/partial_renderer.rb:237:in `render'
  actionpack (3.2.19) lib/action_view/renderer/renderer.rb:41:in `render_partial'
  actionpack (3.2.19) lib/action_view/helpers/rendering_helper.rb:27:in `render'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
  haml (4.0.6) lib/haml/helpers.rb:89:in `non_haml'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
  plugins/redmine_git_hosting/app/views/repositories/edit.html.haml:21:in `_plugins_redmine_git_hosting_app_views_repositories_edit_html_haml__660391430283774270_54748280'
  actionpack (3.2.19) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.19) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.19) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  actionpack (3.2.19) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.19) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.19) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.19) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.19) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.19) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.19) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.19) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.19) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  activesupport (3.2.19) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.19) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:39:in `render'
  actionpack (3.2.19) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.19) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.19) lib/active_support/callbacks.rb:513:in `_run__1273218955812672908__process_action__2574951410398483959__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.19) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.19) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `_run__2030555627231070674__call__2432039447788717785__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in `call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
</pre>

Thanks for you time !

**Comment by n-rodriguez** [comment]
What do you have in ```git_hosting.log```?

**Comment by lukemorel** [comment]
<pre>
2015-06-23 17:30:27 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:27 +0200 [INFO] Testing if Redmine user 'www-data' can sudo to Gitolite user 'git'...
2015-06-23 17:30:27 +0200 [INFO] OK!
2015-06-23 17:30:27 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:27 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:27 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:27 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:28 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:29 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:29 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:29 +0200 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
2015-06-23 17:30:37 +0200 [ERROR] Git exited with non-zero status : 128
2015-06-23 17:30:38 +0200 [ERROR] Git exited with non-zero status : 128
</pre>

I certainly have a problem in the www-data permissions. But I can't use something else, it's not a personnal-use installation :/

Does www-data need to read redmine_gitolite_is_rsa to edit a repo ?

**Comment by n-rodriguez** [comment]
> Does www-data need to read redmine_gitolite_is_rsa to edit a repo ?

More than that : www-data need to read redmine_gitolite_is_rsa.

Check the user/group/permssions on ```redmine_gitolite_is_rsa```.
You may need to do a ```chmod 644``` to make it work which is not very secure...

**Comment by lukemorel** [comment]
Okay thanks a lot !

It's not secure but but it works like you said. I don't know if I can find a more secure way, I will watch it later !

Thanks again for your reactivity ! :+1:
