### ISSUE TITLE
Mail notifications and STARTTLS

### ISSUE THREAD

**Issue by dwithnall** [jbox-web/redmine_git_hosting#456]
Howdy,

I'm trying to configure mail notifications on git pushes and getting the following error message

> remote: Calling additional post-receive hooks...
> remote:   - Executing extra hook 'hooks/post-receive.d/mail_notifications'
> remote:     Sending notification emails to: user1@blah.com, user2@blah.com
> remote: *** Error sending email***
> remote: *** (530, '5.7.0 Must issue a STARTTLS command first. k5sm3552569pdn.10 - gsmtp', 'git@blah.com')
> remote: Exception smtplib.SMTPServerDisconnected: SMTPServerDisconnected('please run connect() first',) in <bound method SMTPMailer.__del__ of <git_multimail.SMTPMailer object at > 0x7f46c703e5d0>> ignored
> remote:
> To ssh://git@tasks.blah.com/git-test.git
> 23b8bab..d135152  master -> master

We're using google apps for our mail server which may have something to do with it.
But using standard system commands (sendmail) as the git or redmine user account sends mail without issue. So I'm guessing that the post receive hook is doing something that doesn't use the system mail setup?

Does anyone have any ideas on where I can look to get this working?

Cheers,

Dave.

**Comment by n-rodriguez** [comment]
Git notifications use Redmine mail settings to send mails. Settings are copied on Gitolite side when installing hooks. So to make it works you need to configure Redmine to send mails.

**Comment by dwithnall** [comment]
Thanks for the reply Nicolas,

Unfortunately I am now more confused because Redmine itself is sending
email without issue.

Do you know where in  gitolite the mail settings are stored, so I can
confirm that they are correct there?

Kind regards,

Dave

---
Sent from a mobile device.
Please excuse any mistakes in spelling or grammar due to missed autocorrect.

**Comment by n-rodriguez** [comment]
> Do you know where in gitolite the mail settings are stored, so I can confirm that they are correct there?

```In <gitolite home dir>/.gitconfig```

**Comment by dwithnall** [comment]
Hi Nicholas.

Thanks for the feedback. I have found my issues, of which there were several.

For future reference here is an overview of what I found and why.
My install was an update from
* v2 redmine
* pre 1.0 version of redmine_git_hosting & 
* v2 of gitolite originally installed from the official ubuntu package. 
I upgraded everything at the same time (redmine v3, gitolite v3 & RGH 1.0.5)

There were old hooks in git/.gitolite/hooks/ from the v2 and for some reason the .gitolite.rc $RC['LOCAL_CODE'] setting wasn't being used until after I removed the old hooks.

I have also found an issue in the default hook scripts used by RGH 1.0.5 and gmail smtp using port 587. I'm assuming I have done something wrong somewhere, but I have no idea what, my knowledge of python is limited.

My SMTP configuration is as follows

>        mailer = smtp
>        environment = gitolite
>        smtpauth = true
>        smtpserver = smtp.gmail.com
>        smtpport = 587
>        smtpuser = gmailuser@googleappsdomain.com
>        smtppass = password

the smtpport 587 causes git_multimail.py to use the following code

>            elif self.smtpport == 587:
>                self.smtp = smtplib.connect(self.smtpserver, self.smtpport)
>                self.smtp.ehlo()
>                self.smtp.starttls()
>                self.smtp.ehlo()

My version of python (2.7.5) throws this error on smtplib.connect()  [Line 1448]
> AttributeError: 'module' object has no attribute 'connect'

I switched it to use smtplib.SMTP

>            elif self.smtpport == 587:
>                self.smtp = smtplib.SMTP(self.smtpserver, self.smtpport)
>                self.smtp.ehlo()
>                self.smtp.starttls()
>                self.smtp.ehlo()

And emails are now being sent on git pushes. YAY?
Anyway, thanks for your help and for redmine_git_hosting plugin. It is very useful.

Cheers,

Dave.

**Comment by hongsoog** [comment]
Hi! Dave
Thanks for your explatnation, 
I have the same problem and resolve it with your solution.

IMHO, RGH should update its git_multimail.py with https://github.com/git-multimail/git-multimail/blob/master/git-multimail/git_multimail.py

They have change as follows:
```python
        try:
            def call(klass, server, timeout):
                try:
                    return klass(server, timeout=timeout)
                except TypeError:
                    # Old Python versions do not have timeout= argument.
                    return klass(server)
            if self.security == 'none':
                self.smtp = call(smtplib.SMTP, self.smtpserver, timeout=self.smtpservertimeout)
            elif self.security == 'ssl':
                self.smtp = call(smtplib.SMTP_SSL, self.smtpserver, timeout=self.smtpservertimeout)
            elif self.security == 'tls':
                if ':' not in self.smtpserver:
                    self.smtpserver += ':587'  # default port for TLS
                self.smtp = call(smtplib.SMTP, self.smtpserver, timeout=self.smtpservertimeout)
                self.smtp.ehlo()
                self.smtp.starttls()
                self.smtp.ehlo()

**Comment by bes1002t** [comment]
Hi, I had the same problem and solved it with your fix, but this should be fix in new releases!
