### ISSUE TITLE
Doc: Create SSH keys - use: sudo -u redmine

### ISSUE THREAD

**Issue by nicesw123** [jbox-web/redmine_git_hosting#457]
Hi,

please can the following howto 
http://redmine-git-hosting.io/get_started/#step-3-create-ssh-keys-for-user-running-redmine
be updated/changed to the following:
```bash
root#                                   ## ~redmine/  --> is home-directory of user redmine
root# sudo -u redmine  mkdir               ~redmine/ssh_keys
root# sudo -u redmine  ssh-keygen -N '' -f ~redmine/ssh_keys/redmine_gitolite_admin_id_rsa
```

(This will **always** work; esp. when using `www-data` as user instead of `redmine`. See below)

#### Reason:
If I'm using `www-data` as user `redmine`, then the current howto gives these errors:
```
root# su - www-data
This account is currently not available.
```
The reason is that www-data does no longer have a login shell. `/etc/passwd` shows
`www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin` (**nologin**!)

**Comment by n-rodriguez** [comment]
Done! Thanks!
