### ISSUE TITLE
Possible to migrate 0.7.x to 1.1.0, if all I have is backups of 0.7.x ??? Can I skip prepare_migration_to_v1?

### ISSUE THREAD

**Issue by nicesw123** [jbox-web/redmine_git_hosting#458]
Hello,

I have backups of redmine (using redmine git hosting 0.7.x).
I want to install this on a new bare-metal computer, but immediately to new 1.1.0

Is it possible to install new version of redmine and new git hosting 1.1.0; and **then** load the old backup'd data; and **then** migrate (without `prepare_migration_to_v1`) ?
(How?)

Or do I first have to install old redmine and old 0.7.x; **then** load old backup'd data; **then** upgrade to 0.7.10 and **then** run `redmine_git_hosting:prepare_migration_to_v1` etc.;
and **then** upgrade (redmine and) git_hosting to 1.1.0 ???

Thanks.

**Comment by n-rodriguez** [comment]
> Or do I first have to install old redmine and old 0.7.x; then load old backup'd data; then upgrade to 0.7.10 and then run redmine_git_hosting:prepare_migration_to_v1 etc.;
> and then upgrade (redmine and) git_hosting to 1.1.0 ???

Yes.

**Comment by nicesw123** [comment]
Thanks for the quick answer.

As idea for **New installer** #382 :
Would it be possible to have new installations (of new versions) handle old backup-data?

So that I can install a new upgraded (!) version of redmine or redmine git hosting on a new bare-metal computer, and then load the old (!) backups (databases, repos, etc. - from old versions!); and then have that migrated (by the new version) to work with the new version?

Is that possible? (Is it possible with redmine, actually? - without plugins).

Thanks.

**Comment by n-rodriguez** [comment]
> Would it be possible to have new installations (of new versions) handle old backup-data?
> 
> So that I can install a new upgraded (!) version of redmine or redmine git hosting on a new bare-metal computer, and then load the old (!) backups (databases, repos, etc. - from old versions!); and then have that migrated (by the new version) to work with the new version?
> 
> Is that possible? (Is it possible with redmine, actually? - without plugins).

I would say yes and no... Actually the point of this feature is to shrink DB migrations and to remove useless (and maybe dangerous) Gitolite updates during the initial setup to ease the plugin install. This is done by recreating the exact same DB schema with less migration files and then renumbering versions in the ```schema_migrations``` table. So your 'old versions' will have to be at least in version 1.1.x to stay consistent.

**Comment by nicesw123** [comment]
Ok. Thanks.

I still have one question (related to top comment):
... if I don't care about old SSH keys and stuff...
Can I then install new git hosting 1.1.0 and just load old databases (redmine and git hosting 0.7.6) ???

Because
http://redmine-git-hosting.io/how-to/migrate/#step-by-step-migration-from-0710-version-to-v10x
just says: *"first need to launch this Rake task to delete SSH Keys in Gitolite (we’ll recreate them later) "*
But I'm doing a new install on a new bare-metal computer, so I'll not touch the newly installed Gitolite.
I just want to copy data and repos over. (If user's loose their own SSH keys, that's ok. For me it is easier to just tell them to upload a new key).

Will that work? 
Thanks

**Comment by n-rodriguez** [comment]
It should. Don't forget to run the ```migrate_to_v1``` task.
