### ISSUE TITLE
No able to use ssh keys

### ISSUE THREAD

**Issue by rodionmdk** [jbox-web/redmine_git_hosting#462]
Hi! I use fresh install of Redmine+Git installations, and I have troubles with access via TortoiseGit (on very old server it works fine). It ask password for git user, when I set password then I have error

fatal: project does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Same error I get if I input password when try git clone localy on server by using user without rsa-keys, but if i use them I git clone successfully .

Can you guilde me were I can find solution?

**Comment by n-rodriguez** [comment]
http://gitolite.com/gitolite/

**Comment by rodionmdk** [comment]
Hi, n-rodriguez! Can you help me to find way to check I my keys and users are added to gitolite via git hosting plugin?
My redmine are can work with repos (I even can make git clone from redmine user). But for users, when I use TortoiseGit it ask password for git user.

**Comment by n-rodriguez** [comment]
> It ask password for git user, when I set password then I have error
> 
> fatal: project does not appear to be a git repository
> fatal: Could not read from remote repository.

It should not ask for password. Users shoud add their SSH keys in Redmine and use them to clone/push. Also you should not set a password to the git user.

http://redmine-git-hosting.io/get_started/#step-10-add-your-ssh-keys
