### ISSUE TITLE
1.1.x keeps disabling global repository access

### ISSUE THREAD

**Issue by mnencia** [jbox-web/redmine_git_hosting#465]
My use case is simple:

* I don't want to create a repository for every project.
* I don't want to create a README for every repository.
* I want to be able to choose to create a README when I create a repository.

The [documentation](http://redmine-git-hosting.io/troubleshooting/#initialization-of-the-repo-with-readme-file-does-not-work) says that I can do it by manually adding the following line to gitolite.conf

    repo    @all
      RW+                            = redmine_gitolite_admin_id_rsa

but unfortunately, redmine_git_hosting removes them the next time I touch the configuration, unless I set both :init_repositories_on_create and :all_projects_use_git to true.

I think that these should be unrelated things, and I'd like to have an option to enable global access rights for redmine_gitolite_admin_id_rsa user.

**Comment by mnencia** [comment]
Moreover, at the moment :init_repositories_on_create is disabled if :all_projects_use_git is set to false. I think that these two settings should not be related at all, and :init_repositories_on_create should only depend on the eventual new setting to enable global access rights for redmine_gitolite_admin_id_rsa user.

**Comment by n-rodriguez** [comment]
> Moreover, at the moment :init_repositories_on_create is disabled if :all_projects_use_git is set to false. I think that these two settings should not be related at all

They **must** be related otherwise how can you ```git init``` a repo if it doesn't exist in Gitolite ;)

> :init_repositories_on_create should only depend on the eventual new setting to enable global access rights for redmine_gitolite_admin_id_rsa user.

I think it should depend on both (see above).

**Comment by n-rodriguez** [comment]
The setting is name ```:redmine_has_rw_access_on_all_repos``` and is enabled by default so it can fill your use case :
* I don't want to create a repository for every project.
* I don't want to create a README for every repository.
* I want to be able to choose to create a README when I create a repository.
