### ISSUE TITLE
Hooks update URL

### ISSUE THREAD

**Issue by sli921** [jbox-web/redmine_git_hosting#467]
Hi,

I've tried for hours but I don't know how to set the Hooks Update URL right. My redmine installation is reachable via https://iforge.at/redmine and the hooks url is set to: https://iforge.at/githooks/post-receive/redmine but I always get:

Notifying Redmine about changes to this repository : 'test/' ...
  Error while notifying Redmine ! (status code: 302)

Looking for additional global post-receive hooks...
  Global hooks found : ["hooks/post-receive.d/mail_notifications"]
...
To https://sebastian@iforge.at/redmine/test.git
  [new branch]      master -> master

Environment:
  Redmine version                3.0.3.stable
  Ruby version                   2.1.6-p336 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
  Xitolite                       1.8.3.1
Redmine plugins:
  redmine_bootstrap_kit          0.2-devel
  redmine_git_hosting            1.1-devel

**Comment by sli921** [comment]
Additional Notice: It's strange. The project repo and activities were updated although this error appears.

**Comment by sli921** [comment]
Can somebody give me a hint why the hook url gives an error page 302 instead of 200? I don't want to fix that with comment out the error message? Firewall is turned off.

**Comment by n-rodriguez** [comment]
Because you're redirecting from http to https?.

**Comment by sli921** [comment]
I've changed it to http. Now I get status code 404.

**Comment by n-rodriguez** [comment]
You should change it to HTTPs

**Comment by sli921** [comment]
It's HTTPs and no redirection now, but I still get 404 error page. Is there something I must set in the apache config or is the hook ready on its own?

**Comment by n-rodriguez** [comment]
Set your hook url to  https://iforge.at/redmine/githooks/post-receive/redmine

**Comment by sli921** [comment]
It worked. Thanks!
