### ISSUE TITLE
Issue with setup, not able add public user keys.

### ISSUE THREAD

**Issue by rodionmdk** [jbox-web/redmine_git_hosting#468]
Hi! When I try to git clone with newly added key in redmine it ask me password of git user, but if I use key that created for redmine it works.
In log I have this error:
* Access denied for Gitolite Admin SSH Keys
* Unsupported URL protocol

for 
```ssh -i ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info```

I have this 

```
hello admin, this is gitolite 2.3-1 (Debian) running on git 1.7.10.4
the gitolite config gives you the following access:
  #R  #W      @all
  #R  #W      gitolite-admin
  &R_ &W_     testing
```

My keydir have 2 keys:
```admin.pub  & redmine_gitolite_admin_id_rsa.pub```
and they are same.

My config in gitolite-admin.git is
```
repo    gitolite-admin
        RW+     =  admin
repo    gitolite-admin
        RW+     =  redmine_gitolite_admin_id_rsa
repo    @all
        RW+     = admin
repo    @all
        RW+     = redmine_gitolite_admin_id_rsa
repo    testing
        RW+     =   @all
```

And there is no errors in configuration tab.

I'm running Redmine 2.6.5, Gitolite 2.3.1, Git hosting plugin 1.1.0 on Debian Wheezy
When I install dependencies it report that I already have all installed.

**Comment by n-rodriguez** [comment]
> admin.pub & redmine_gitolite_admin_id_rsa.pub
> and they are same.

This is very bad : http://redmine-git-hosting.io/get_started/#step-10-add-your-ssh-keys

**Comment by n-rodriguez** [comment]
Remove admin.pub and generate a new SSH key for you very own use.

**Comment by rodionmdk** [comment]
I delete keys in keydir of gitolilte and replace with new pub key, my 
> ssh -i ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info

outputes:
> hello admin, this is gitolite 2.3-1 (Debian) running on git 1.7.10.4
>the gitolite config gives you the following access:
>   #R  #W      @all
>    #R  #W      gitolite-admin
>    &R_ &W_     testing

but during work with users keys in log file i have this:
>2015-06-29 01:43:42 +0300 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
>2015-06-29 01:43:42 +0300 [ERROR] Access denied for Gitolite Admin SSH Keys
>2015-06-29 01:43:42 +0300 [ERROR] Unsupported URL protocol

From redmine user I can git clone gitolite-admin.git repo.

**Comment by n-rodriguez** [comment]
Check that ```<git user home>/.ssh/authorized_keys``` doesn't contain duplicated admin keys with different identifiers.

**Comment by rodionmdk** [comment]
I delete row that starts from:
> command="/usr/share/gitolite/gl-auth-command admin"

now my gitolite banner is:
> hello redmine_gitolite_admin_id_rsa, this is gitolite 2.3-1 (Debian) running on git 1.7.10.4
the gitolite config gives you the following access:
    #R  #W 	@all
    #R  #W 	gitolite-admin
    &R_ &W_	testing

redmine user still able git clone gitolite-admin.git and in git-hosting log file i have:

>2015-06-29 02:05:04 +0300 [INFO] Create tmp directory : '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-06-29 02:05:04 +0300 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-06-29 02:05:04 +0300 [ERROR] Access denied for Gitolite Admin SSH Keys
2015-06-29 02:05:04 +0300 [ERROR] Unsupported URL protocol

**Comment by n-rodriguez** [comment]
> but when tried uninstall plugin and install in again I have many errors during db migrate

What kind of errors?

> is there any option to run db migrate with ignoring errors (just write down in log file)?

Nope. You must fix errors by hands if any.

> my output is only...

That means that all the migration have been played.

But I think your issue comes from rugged/libgit2.

> Unsupported URL protocol

Means that rugged/libgit2 has not been compiled with SSH support.

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/troubleshooting/#unsupported-url-protocol

**Comment by rodionmdk** [comment]
Interesting that if I run :
> bundle install --without development test
I get installed rugged version 0.22.2., but when I uninstall rugged and install:
>uninstall rugged
>gem install rugged -v='0.22.2'

I got error: 
>extconf.rb:13:in `sys': ERROR: 'cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"' failed (RuntimeError)

my full gem_make.out is :
>/usr/bin/ruby1.9.1 extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

>Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/ruby1.9.1
        --use-system-libraries
extconf.rb:13:in `sys': ERROR: 'cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"' failed (RuntimeError)
        from extconf.rb:66:in `block (2 levels) in <main>'
        from extconf.rb:65:in `chdir'
        from extconf.rb:65:in `block in <main>'
        from extconf.rb:62:in `chdir'
        from extconf.rb:62:in `<main>'


all commands I run from redmine user.

**Comment by rodionmdk** [comment]
I solve problem with ssh access via  "rugged" and now i have in configtest menu: 
> Rugged compiled features 	threads ssh

before i have only:
> Rugged compiled features 	threads

now in git_hosting log there is no errors, but when i try to gitclone from my PC testrepo ( redmine_git) I have error:
>R access for redmine_git DENIED to redmine_admin_1

I've trying use  as user key and  as deploy key.
my gitolite-admin config not changed (in tmp dir too), I not seen added string for redmine_admin_1 user. How I can check is user added to gitolite or not? My redmine key is able download this testrepo.

**Comment by n-rodriguez** [comment]
Repositories access are based on Redmine project's members and project's roles.
You must add users with the adequate role as project's member to be able to clone repositories.

**Comment by n-rodriguez** [comment]
About the compilation error :
```apt-get install ruby-dev```
