### ISSUE TITLE
Protected branch question

### ISSUE THREAD

**Issue by lukemorel** [jbox-web/redmine_git_hosting#469]
Hello again ! 

I try to setup a workflow to work efficiently on my projects.
So I've 2 branches **master** and **dev**.
I want to protect my master branch so just few guys can push/delete on this branch.
Here is my configuration : 
http://puu.sh/iCejm/98ca66ec05.png

The problem is that another user, ***l.morel*** cans push everything he wants on the **master** branch.

Is the branch path correct ?
Have I to set another forgotten option ?
I don't know.

Thanks for your time !

**Comment by n-rodriguez** [comment]
Maybe you'd need this : https://github.com/jbox-web/redmine_git_hosting/issues/414

**Comment by lukemorel** [comment]
This is exactly what I needed.

Hmm.. Another question : is the gitolite group management supported by the plugin at this time ? I can't see any clue about it

**Comment by n-rodriguez** [comment]
> is the gitolite group management supported by the plugin at this time ? I can't see any clue about it

Nope.

**Comment by lukemorel** [comment]
That would be a very very very very great idea ! :)
Thanks.

**Comment by n-rodriguez** [comment]
> That would be a very very very very great idea ! :)

I understand but I don't think this is a trivial thing to do... This question has already been asked here : https://github.com/kubitron/redmine_git_hosting/issues/66 and I agree with @kubitron.

**Comment by lukemorel** [comment]
Okay, so if I have 50 guys to put on my protected branch, I need to seach about the 50 usernames ? No other way ?

**Comment by n-rodriguez** [comment]
For now yes. But this can be solved without needing of Gitolite groups.

**Comment by lukemorel** [comment]
Of course, so :
That would be a very very great idea to solve it without needing of gitolite groups :+1: 

I use to go ahead in complicated problems while the solution is under my feet. Sorry for that !
Thanks !
