### ISSUE TITLE
Q: Why sudo is required?

### ISSUE THREAD

**Issue by firegurafiku** [jbox-web/redmine_git_hosting#471]
[Installation manual][man] required me to create another sudoers files with the following contents:

```text
Defaults:redmine !requiretty
redmine ALL=(git) NOPASSWD:ALL
```

What's the reason behind that? Can I mitigate that requirement to just changing permission on some files or directories?

I think that running `git` command as `root` is a possible security vulnerability, because `git` *can* run arbitrary shell commands in its turn. For example, if an attacker has obtained shell access with rights of `redmine` user (by breaking into Ruby application and installing a backdoor), then all they need to get a full-featured root access is a simple `sudo git filter-branch --index-filter /bin/bash HEAD` command.

[man]: http://redmine-git-hosting.io/get_started/

**Comment by n-rodriguez** [comment]
> What's the reason behind that?

1. Historical
2. To ease installation and integration with Gitolite

> Can I mitigate that requirement to just changing permission on some files or directories?

Maybe but you'll have to play with UNIX groups, Gitolite configuration (umask) and do some recursive chmod.

> think that running git command as root is a possible security vulnerability, because git can run arbitrary shell commands in its turn.

The command is not executed by root but by git user.
The sudo file is here to allow redmine user to execute git commands as git user.

> For example, if an attacker has obtained shell access with rights of redmine user (by breaking into Ruby application and installing a backdoor), then all they need to get a full-featured root access is a simple sudo git filter-branch --index-filter /bin/bash HEAD command.

The attacker will get a Bash shell with git user permissions.

**Comment by firegurafiku** [comment]
Seems like you're right, I'm just not that familiar with `sudoers` syntax. Trying to launch `sudo git --help` as `redmine` user leads to asking for the password. So the worst-case attack is losing or leaking Gitolite data (which are anyway available to `redmine` user as it has the management key).

**Comment by n-rodriguez** [comment]
> Trying to launch sudo git --help as redmine user leads to asking for the password

The command is : ```sudo -n -u git -i git --help```
