### ISSUE TITLE
404 on the "My public keys" link in the user panel

### ISSUE THREAD

**Issue by slawo** [jbox-web/redmine_git_hosting#472]
In the user panel the link to the public keys ends in a 404 if redline is installed in a subpath.

- I navigate to my user panel: https://my.site.com**/projects/my/account**
- I click on "My public keys"
- the url is: https://my.site.com/my/public_keys
- it should be: https://my.site.com/projects/my/public_keys

**Comment by n-rodriguez** [comment]
Yes It's a known issue. What version of Redmine are you running?

**Comment by slawo** [comment]
Ok I just saw the other questions related to this issue... I'm running redmine 2.6

**Comment by n-rodriguez** [comment]
What is the revision number? (2.6.**1**, 2.6.**2**)
And what is your plugin version?

**Comment by slawo** [comment]
Hi, currently this is my setup:

    Environment:
      Redmine version                2.6.2.stable.14045
      Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
      Rails version                  3.2.21
      Environment                    production
      Database adapter               Mysql2
    SCM:
      Git                            1.7.10.4
    Redmine plugins:
      redmine_bootstrap_kit          0.2.3
      redmine_git_hosting            1.1.1

**Comment by renanmarks** [comment]
Hello! I've just upgraded to most recent version. Same problem here:

    Environment:
      Redmine version                2.6.0.stable
      Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
      Rails version                  3.2.19
      Environment                    production
      Database adapter               Mysql2
    SCM:
      Subversion                     1.8.10
      Git                            2.1.4
      Filesystem                     
      Xitolite                       2.1.4
    Redmine plugins:
      redmine_bootstrap_kit          0.2.3
      redmine_git_hosting            1.1.1
      redmine_sidekiq                2.1.0

**Comment by n-rodriguez** [comment]
> Update: after updating Redmine to 3.0.4 the problem no longer exists.

Yes. Actually I think this is a Rails issue.

**Comment by amelentjev** [comment]
This fix won't work on latest redmine 2.6 (2.6.7). And will not work in future, according to http://www.redmine.org/issues/19024
Following fix helps me :
lib/redmine_git_hosting/hooks/add_public_keys_link.rb
```ruby
    def self.default_url_options
         {:script_name => Redmine::Utils.relative_url_root}
    end
```

**Comment by Phiber2000** [comment]
I confirm that c03f567b20ba8c4a88ea7560db95c9aa3b2c66d5 breaks subpath link to "My public keys" with redmine 3.1.2.stable.
Amelentjev's fix works.

**Comment by n-rodriguez** [comment]
> I confirm that c03f567 breaks subpath link to "My public keys" with redmine 3.1.2.stable.
> Amelentjev's fix works.

What is the plugin version?

**Comment by Phiber2000** [comment]
Full version information:

SW | Version
--- | ---
Redmine | 3.1.2.stable
Ruby | 2.2.3-p173 (2015-08-18) [x86_64-linux]
Rails | 4.2.4
Git | 2.6.3
Xitolite | 2.6.3
redmine_bootstrap_kit | 0.2.3
redmine_git_hosting | 1.1.4

**Comment by Phiber2000** [comment]
Same with Redmine v3.2.0.stable.
