### ISSUE TITLE
force-sync post receive hooks (URLs)

### ISSUE THREAD

**Issue by hkarasek** [jbox-web/redmine_git_hosting#474]
Hi,
it's awesome plugin, but we have problem with synchronization between Redmine and gitolite..

We just get:
```
Looking for additional local post-receive hooks...
  - No local hooks found
```
Is there any way how to force hooks re-sync?

Thanks

**Comment by n-rodriguez** [comment]
In *Administration -> Redmine Git Hosting -> Hooks* tab, install hooks link.

**Comment by n-rodriguez** [comment]
Also check http://redmine-git-hosting.io/get_started/#step-5-gitolite-must-accept-hook-keys to enable 'LOCAL CODE' directory (the place we store Gitolite hooks)

**Comment by hkarasek** [comment]
Thank's for response! That all I try:
![redmine_git_hosting](https://cloud.githubusercontent.com/assets/1782618/8512555/6d627ff4-2348-11e5-86b7-0be4f5759924.jpg)

**Comment by n-rodriguez** [comment]
Does it work?

**Comment by hkarasek** [comment]
Unfortunately not, because I did not do anything. In this state it was before creation of this issue...

**Comment by n-rodriguez** [comment]
What is your Gitolite version?

**Comment by hkarasek** [comment]
Gitolite version is 3.5.3.1

**Comment by n-rodriguez** [comment]
Did you uncomment LOCAL_CODE in ```.gitolite.rc``` file?

**Comment by hkarasek** [comment]
Yes, I did

**Comment by n-rodriguez** [comment]
Actually you should have this :

* with debug mode

```
nicolas@tchoum-desktop:~/blibl$ echo "coicoci" >> toto && git commit -a -m test && git push -u origin master 
[master 69c4297] test
 1 file changed, 1 insertion(+)
Debian GNU/Linux 7
Décompte des objets: 3, fait.
Delta compression using up to 4 threads.
Compression des objets: 100% (2/2), fait.
Écriture des objets: 100% (3/3), 283 bytes | 0 bytes/s, fait.
Total 3 (delta 0), reused 0 (delta 0)

Notifying Redmine about changes to this repository : 'blibl/' ...
  - Fetching changesets for 'blibl' repository ...  [success]

Looking for additional global post-receive hooks...
  - Global hooks found : ["hooks/post-receive.d/mail_notifications"]

Looking for additional local post-receive hooks...
  - No local hooks found

Calling additional post-receive hooks...
  - Executing extra hook 'hooks/post-receive.d/mail_notifications'
    multimailhook is disabled

To ssh://git-jbox@redmine2.jbox-web.fr/blibl.git
   f4dab64..69c4297  master -> master
La branche master est paramétrée pour suivre la branche distante master depuis origin.

```
* without debug mode

```
nicolas@tchoum-desktop:~/blibl$ echo "coicoci" >> toto && git commit -a -m test && git push -u origin master 
[master 2b4920a] test
 1 file changed, 1 insertion(+)
Debian GNU/Linux 7
Décompte des objets: 3, fait.
Delta compression using up to 4 threads.
Compression des objets: 100% (2/2), fait.
Écriture des objets: 100% (3/3), 286 bytes | 0 bytes/s, fait.
Total 3 (delta 0), reused 0 (delta 0)

Notifying Redmine about changes to this repository : 'blibl/' ...
  - Fetching changesets for 'blibl' repository ...  [success]

Calling additional post-receive hooks...
  - Executing extra hook 'hooks/post-receive.d/mail_notifications'
    multimailhook is disabled

To ssh://git-jbox@redmine2.jbox-web.fr/blibl.git
   69c4297..2b4920a  master -> master
La branche master est paramétrée pour suivre la branche distante master depuis origin.
```

**Comment by n-rodriguez** [comment]
This message :
```
Looking for additional local post-receive hooks...
  - No local hooks found
``` 
is normal if you don't have any other hooks to run.

**Comment by hkarasek** [comment]
Yes, I get something similar. I also looked to repositories/deploy_test.git/hooks/post-receive.d and there are only default hooks, like mail notifications etc..
But in Redmine I have 3 custom post-recieve hooks (of course, that for this repository :) )..

**Comment by n-rodriguez** [comment]
> But in Redmine I have 3 custom post-recieve hooks (of course, that for this repository :) )..

Do you mean 3 post receive urls?

**Comment by hkarasek** [comment]
Yes

**Comment by n-rodriguez** [comment]
These are not Gitolite hooks. They are urls that are called when a git push is done to the repo. Post receive urls report should appear in ```Notifying Redmine about changes to this repository``` section.

**Comment by n-rodriguez** [comment]
> Post receive urls report should appear in Notifying Redmine about changes to this repository section.

And they don't... But they do appear in logs.

**Comment by hkarasek** [comment]
Ok, so these URL's are called on the "redmine side"? If yes, then that's probably what I needed to know.

**Comment by n-rodriguez** [comment]
> Ok, so these URL's are called on the "redmine side"?

Yes.

**Comment by hkarasek** [comment]
Thanks for your time. In return, I will send some pull requests in the future..
