### ISSUE TITLE
Repo initialization over https breaks gitolite keys

### ISSUE THREAD

**Issue by Dragnell87** [jbox-web/redmine_git_hosting#475]
After some test, back and forward this is what i have found, Any project created under https fails to initiate the repo, though is created, no Readme file is present, also the changes in gitolite are no longer visible from the test tab, this is what i found after clone gitolite-admin
repo    @all
RW+                            = DUMMY_REDMINE_KEY

In the logs the initialization fails after
Create README file for repository 'galactus/avangers'
2015-07-05 17:47:54 -0400 [ERROR] Error while creating README file for repository 'galactus/avangers'
2015-07-05 17:47:54 -0400 [ERROR] Early EOF

Also it seem to be a problem somewhere when it trays to notify redmine abut any change in the repository

Notifying Redmine about changes to this repository : 'avengers/ironman' ...
HTTP_ERROR : Net::ReadTimeout.

Thanks for your time and effort
Ruby 2.1.6
Redmine 2.6
redmine_git_hosting 1.1.0 - 1.1.1

**Comment by n-rodriguez** [comment]
I think this duplicates this one : https://github.com/jbox-web/redmine_git_hosting/issues/465.
Fixed for next version (1.2.0).
