### ISSUE TITLE
repository server side hooks

### ISSUE THREAD

**Issue by ntnn** [jbox-web/redmine_git_hosting#478]
I can't find any information how to create server side hooks that are not supposed to apply to every repository.

E.g. I have a local, non-bare repository of a project on my redmine/gitolite server, where the program was recompiled upon every push by a `post-receive` hook. 
redmine-git-hosting doesn't seem to have a real replacement for that, seeing that `post-receive` and `post-receive.d` are both being replaced by symlinks to `~/local/hooks/common` and hooks in `~/local/hooks/$repo`.

So - is it possible to add repository-specific hooks without having to actually change the code of the plugin right now or was I just blind and didn't see it?

**Comment by n-rodriguez** [comment]
> redmine-git-hosting doesn't seem to have a real replacement for that, seeing that post-receive and post-receive.d are both being replaced by symlinks to ~/local/hooks/common and hooks in ~/local/hooks/$repo.

This is a Gitolite behavior, not a plugin one.

**Comment by ntnn** [comment]
Ah yes sorry, I just found [this](http://gitolite.com/gitolite/g2/hooks.html) page on hooks from gitolite. I thought since the symlinks only came up after installing redmine-git-hosting they had been setup by the plugin.

Thanks for the help and work
