### ISSUE TITLE
Undefined method `redmine_bootstrap_kit_load' -> 'bootstrap_load_base'

### ISSUE THREAD

**Issue by chadyred** [jbox-web/redmine_git_hosting#480]
Hello Nicolas, in my production.log I have this log when I get the 1.1.1 your gitolite plugin...

```
ActionView::Template::Error (undefined method `redmine_bootstrap_kit_load' for #<#<Class:0x007f2c2a1b01b8>:0x007f2c27db7ef0>):
    1: - content_for :header_tags do
    2:   = bootstrap_load_base
    3:   = bootstrap_load_module(:alerts)
    4:   = bootstrap_load_module(:label)
    5:   = bootstrap_load_module(:modals)
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___4526933832855774388_69913831103700'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___4526933832855774388_69913831103700'

```

This is because of the change in
plugins/redmine_git_hosting/app/views/common/_git_hosting_js_headers.html.haml of tag 1.1.1 is not compatible with older "redmine_boostrap_kit" plugin, so I remove it and download the latest and all is good !

Many thanks for this beautiful plugin :)

**Comment by tostasqb** [comment]
+1

**Comment by Zonork** [comment]
+1

**Comment by n-rodriguez** [comment]
Ugrade to the latest version of Redmine Bootstrap Kit plugin : https://github.com/jbox-web/redmine_bootstrap_kit/releases

**Comment by Zonork** [comment]
+1 i have that version 0.2.3 and make the installation steps, but this error still: "undefined method `redmine_bootstrap_kit_load'"
