### ISSUE TITLE
Migration Halted - Can not install or Remove 

### ISSUE THREAD

**Issue by erdembey** [jbox-web/redmine_git_hosting#487]
Hello,

We want to use redmine git hosting. We've just updated our redmine to latest 2.6 branch.
We've install an old version of redmine git hosting but it did'nt worked at our old env.
So we decided to upgrade redmine git hosting also.

Right now we have 1.1.1 in our server, we tried to install via rake but it halted somehow and right we can not either install or remove it :)

Can anyone share an actual database schema of the plugin so we can try to import and go on ?
We tried to remove related migration files which generates errors but it didnt worked well.

**Comment by n-rodriguez** [comment]
> We tried to remove related migration files which generates errors but it didnt worked well.

You should never do that.

**Comment by n-rodriguez** [comment]
Try `bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting VERSION=0`

**Comment by erdembey** [comment]
Thank you for fast response.
As you mentioned we shouldn't but the strange thing is the last command didnt worked out so we have to remove and try ...

Is it possible to create a exception handler in migration routines to skip next migration step ?

**Comment by n-rodriguez** [comment]
> Is it possible to create a exception handler in migration routines to skip next migration step ?

Nope.

What you can do :
remove all plugin tables by hand in database :

* git_caches
* github_comments
* github_issues
* gitolite_public_keys
* repository_deployment_credentials
* repository_git_config_keys
* repository_git_extras
* repository_git_notifications
* repository_mirrors
* repository_post_receive_urls
* repository_protected_branches

Remove all entries containing ```redmine_git_hosting``` in ```schema_migrations``` table and retry :)

**Comment by erdembey** [comment]
Allright i solved the migration issue.
Right now settings/plugin/redmine_git_hosting shows an internal error.
In the log file;

2015-07-28 20:22:46 +0300 [ERROR] Error while testing can_redmine_sudo_to_gitolite_user
2015-07-28 20:22:47 +0300 [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.

It seems we need to solve all installation requirements until we can use the interface right ?

**Comment by n-rodriguez** [comment]
Hi! Sorry for the delay. 

> It seems we need to solve all installation requirements until we can use the interface right ?

At this point you should be able to start Redmine and access to the *Config test* tab in plugin' settings.
But you will have to solve you SSH key issue to fully use the plugin.

Is it solved?

**Comment by n-rodriguez** [comment]
Any news?

**Comment by n-rodriguez** [comment]
As said here : no news, good news :)
Feel free to open a new issue if you still have troubles.
