### ISSUE TITLE
Master deployment key and hook

### ISSUE THREAD

**Issue by hkarasek** [jbox-web/redmine_git_hosting#490]
Is there any way how set-up deployment key for all available repositories? And also post-receive hook which will be called for all repositories?

Thanks

**Comment by n-rodriguez** [comment]
> Is there any way how set-up deployment key for all available repositories?

Nope. What you can do is creating a dedicated user that will a member of all projects.

> And also post-receive hook which will be called for all repositories?

Yes in : [lib/load_gitolite_hooks.rb](https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/load_gitolite_hooks.rb) file.
