### ISSUE TITLE
Redmine 3 & Sidekiq

### ISSUE THREAD

**Issue by madorin** [jbox-web/redmine_git_hosting#493]
Hello, Nicolas Rodriguez,

Have you configured successfully Redmine_git_hosting & sidekiq on redmine 3?
I tried but unsuccessful :( I see on sidekiq plugin page is was not updated last year, and it mention just redmine 2.5 compatibility.

-
  D.

**Comment by n-rodriguez** [comment]
Hi! I think it should work with Redmine 3.

**Comment by madorin** [comment]
Ok, thanks for info!
I found later your howto related to Sidekiq. It needs also Redis server etc... complicated for a not so loaded server. Just set to run hooks async and works fairly quickly. I'll consider later link Sidekiq if case.
