### ISSUE TITLE
Error initializing repositories with Readme

### ISSUE THREAD

**Issue by madorin** [jbox-web/redmine_git_hosting#495]
Hello!
Tested on v.1.1.1.

If we set in Plugin Settings/Redmine/Automatically initialize Git repositories for new projects? = NO

Then plugin change gitolite.conf with 
repo    @all
  RW+                            = DUMMY_REDMINE_KEY

Later, when we create repository manually, if we check initialize repo with Readme it does not work!
I think it should not change gitolite.conf file, but leave it was:
  RW+                            = redmine_gitolite_admin_id_rsa

**Comment by n-rodriguez** [comment]
Hi! This behavior has changed in the next release. You should not have this bug anymore.

**Comment by madorin** [comment]
Thanks for info!
