### ISSUE TITLE
Allow users to upload their public keys

### ISSUE THREAD

**Issue by madorin** [jbox-web/redmine_git_hosting#496]
Add an option to allow regular users to upload their public keys in user profile.

**Comment by n-rodriguez** [comment]
> Add an option to allow regular users to upload their public keys in user profile.

What do you meaan? It's already the case

**Comment by madorin** [comment]
I logged with a regular, non-admin user, and menu option "My public keys" is missing from menu.
Also, logged as admin, I didn't found an option to configure to allow users to setup their keys.

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/get_started/#step-10-add-your-ssh-keys

**Comment by madorin** [comment]
Ok, just added a test user, non-admin.
Logged, and "My public keys" is missing from user profile.

Users should be able to upload their public keys whatever is involved in a project or not.
Later he may select from his public keys some specific key for some specific project.

![pubkeys](https://cloud.githubusercontent.com/assets/11855141/9309582/3f7cdae8-4513-11e5-8e21-72c47c6d0946.PNG)

**Comment by n-rodriguez** [comment]
> Users should be able to upload their public keys whatever is involved in a project or not.

I know. This may be improved but it's not guaranted due to how Redmine works.

> Later he may select from his public keys some specific key for some specific project.

This would add too much complexity.

**Comment by madorin** [comment]
If it works for an admin user, I think it should work for a regular user too ;)
This approach is done also in GitLab.
I just want to add an user that will be involved in development and he is not able to upload his keys :(

**Comment by n-rodriguez** [comment]
> If it works for an admin user, I think it should work for a regular user too ;)

This is due to how roles work in Redmine.

> This approach is done also in GitLab.

I know. And Gitlab don't use Gitolite too ;)

> I just want to add an user that will be involved in development and he is not able to upload his keys :(

Add the user as a project member.

**Comment by madorin** [comment]
OK, big thanks for clarification!
Anyway, hope to see this at least in v.2.0 ;)

**Comment by n-rodriguez** [comment]
> OK, big thanks for clarification!

You're welcome.

> Anyway, hope to see this at least in v.2.0 ;)

I'll see what I can do ;)
