### ISSUE TITLE
Missing helpers/redmine_bootstrap_kit_helper.rb

### ISSUE THREAD

**Issue by madc** [jbox-web/redmine_git_hosting#498]
I've been following the instructuons on the project website, but getting the following error when runing the `bundle exec rake` command:

`AbstractController::Helpers::MissingHelperError: Missing helper file helpers/redmine_bootstrap_kit_helper.rb`

Any idea, what that could be all about?

**Comment by n-rodriguez** [comment]
Where did you install Redmine? Where did you install the plugin(s)?

**Comment by madc** [comment]
Redmine is installed to `/var/www/vhosts/redmine/`
The plugins are both installed to `/var/www/vhosts/redmine/plugins/` as `redmine_boottrap_kit` and `redmine_git_hosting`

**Comment by n-rodriguez** [comment]
Weird... Which version of Redmine are you running?

**Comment by madc** [comment]
The most current one:

````
Environment:
  Redmine version                3.1.0.stable
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.5
  redmine_bootstrap_kit          0.2-devel
  redmine_checklists             3.1.1
  redmine_contacts               4.0.1
  redmine_lightbox2              0.2.2
  redmine_slack                  0.1
  rm_user_mentions               1.0.0
  time_logger                    0.5.2
````
Anything else i can check?

**Comment by n-rodriguez** [comment]
I think this is caused by one of your plugins (redmine_contacts) since Travis tests are passing : https://travis-ci.org/jbox-web/redmine_git_hosting/jobs/77462004 (it does exactly the same things you need to do to install the plugin, with the same commands).

This is due to the way the plugin is loaded. Every developper has his own way of doing and some may break the whole system. I also use Redmine Contacts, I can provide you a patch if you want.

**Comment by n-rodriguez** [comment]
<script src="https://gist.github.com/n-rodriguez/abe8c0c20e54e502062c.js"></script>

**Comment by madc** [comment]
Thanks! A pacht is not perfect, but definitly better than not having one of this two plugins.
I'll give it a try when i have a couple of minutes and report back.

**Comment by n-rodriguez** [comment]
> Thanks! A pacht is not perfect, but definitly better than not having one of this two plugins.

I agree. Feel free to open an issue on their Github with the patch https://github.com/RCRM/redmine_contacts ;)

**Comment by madc** [comment]
"This is an automatically updated unofficial mirror of the RedmineCRM"

Guess it makes no sence...

**Comment by n-rodriguez** [comment]
Where did you see that?

**Comment by madc** [comment]
https://github.com/RCRM

**Comment by n-rodriguez** [comment]
erf :/

**Comment by n-rodriguez** [comment]
That's a pity that they don't have an official Github repository.

**Comment by madc** [comment]
I'm sorry, but i've to report back, that I aplied the patch, but still get the same error message.

````
$ patch -p1 < redmine_contact_patch.diff 
patching file init.rb
Hunk #1 succeeded at 108 (offset 1 line).
patching file lib/redmine_contacts.rb
patching file lib/redmine_contacts/patches/application_controller_patch.rb
````
anything else i need to do?

**Comment by n-rodriguez** [comment]
https://gist.github.com/n-rodriguez/8efa78fc0abb5b5d5da2

**Comment by n-rodriguez** [comment]
This is the patch that I use with Redmine Checklists.

**Comment by n-rodriguez** [comment]
But it might not be sufficient because of time_logger plugin : https://github.com/speedy32129/time_logger/blob/master/init.rb#L8

**Comment by n-rodriguez** [comment]
https://github.com/speedy32129/time_logger/issues/1#issuecomment-52170929

**Comment by n-rodriguez** [comment]
Btw, don't forget to restart Redmine after applying the patch.

**Comment by madc** [comment]
I just ran the second patch on redmine_checklists:

````
patching file init.rb
patching file lib/redmine_checklists.rb
patching file lib/redmine_checklists/patches/add_helpers_for_checklists_patch.rb
patching file lib/redmine_checklists/patches/issue_patch.rb
patching file lib/redmine_checklists/patches/issues_controller_patch.rb
patching file lib/redmine_checklists/patches/project_patch.rb
patching file lib/redmine_checklists/redmine_checklists.rb
````
Same issue.

Than I aplied the suggested changes to time_logger/init.rb. Still the same issue, so i removed all plugins except redmine_bootstrap_kit & redmine_git_hosting and i still get the same error messages.
I always restarted apache, reinstalled deps and then tried to applie the migrations.

There is the complete message: https://gist.github.com/madc/7ea12457ab34bcb67539
I'll go though everything again tomorrow, in case, i made some mistake somewere...

**Comment by Zonork** [comment]
@madc your directory is, "../plugins/redmine_bootstrap_kit/" or "../plugins/redmine_bootstrap_kit-devel" i have a similar problem and the cause was the name of the plugin folder, i only change "redmine_bootstrap_kit-0.2.3" for "redmine_bootstrap_kit" and the error gone, but i have "undefined method `redmine_bootstrap_kit_load" this error

**Comment by madc** [comment]
Hm, no its named `redmine_boottrap_kit`.

````
$ ls -al plugins/
drwxr-xr-x  9 www-data www-data   4096 Aug 21 08:56 a_common_libs
drwxr-xr-x  6 www-data www-data   4096 Aug 21 09:54 redmine_boottrap_kit
drwxr-xr-x  9 www-data www-data   4096 Aug 29 19:54 redmine_checklists
drwxr-xr-x  9 root     root       4096 Aug 28 18:42 redmine_contacts
drwxr-xr-x  8 www-data www-data   4096 Aug 21 08:22 redmine_lightbox2
drwxr-xr-x  5 www-data www-data   4096 Aug 20 13:35 redmine_slack
drwxr-xr-x  6 www-data www-data   4096 Jul  9 18:15 rm_user_mentions
drwxr-xr-x  9 www-data www-data   4096 Aug 20 13:42 time_logger
````

````
$ ls -al plugins/redmine_boottrap_kit/
drwxr-xr-x  4 www-data www-data 4096 Aug 21 09:45 app
drwxr-xr-x  6 www-data www-data 4096 Aug 21 09:45 assets
drwxr-xr-x  3 www-data www-data 4096 Aug 21 09:45 config
-rwxr-xr-x  1 www-data www-data   51 Aug 21 09:45 Gemfile
drwxr-xr-x  8 www-data www-data 4096 Aug 21 09:54 .git
-rwxr-xr-x  1 www-data www-data  340 Aug 21 09:54 init.rb
-rwxr-xr-x  1 www-data www-data 1151 Aug 21 09:45 LICENSE
-rwxr-xr-x  1 www-data www-data 4533 Aug 21 09:45 README.md
````

**Comment by n-rodriguez** [comment]
Be careful : the directory name **must** be : `redmine_bootstrap_kit`

**Comment by madc** [comment]
Ha! thanks, @Zonork. While appling the patches I move all e plugins around and must have misstyped the folder name. `bundle exec rake redmine:plugins:migrate` was just successful.

Thanks, @n-rodriguez for all your support so far! The patches and the modification for the time_logger plugin did the job. Maybe you should link to them from the "Geting Started"-Page.

**Comment by madc** [comment]
Btw, do you also have patches for other redminecrm plugins lying around?

**Comment by n-rodriguez** [comment]
> Btw, do you also have patches for other redminecrm plugins lying around?

Whiche one? :)

[Redmine Checklists Loading Patch](https://gist.github.com/n-rodriguez/8efa78fc0abb5b5d5da2)
[Redmine Contact Loading Patch](https://gist.github.com/n-rodriguez/abe8c0c20e54e502062c)
