### ISSUE TITLE
Gitolite version is unknow in Redmine config test.

### ISSUE THREAD

**Issue by Dragnell87** [jbox-web/redmine_git_hosting#499]
Is a fresh install Redmine 3.1 ruby 2.2.3, and for some reason it only happens from the web

From console 
ssh -i ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info
hello redmine_gitolite_admin_id_rsa, this is git@redmine running gitolite3 v3.6.3-11-g2417156 on git 1.9.1

 R W    gitolite-admin
 R W    testing

**Comment by n-rodriguez** [comment]
Check SSH keys path in plugin settings.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by Dragnell87** [comment]
I try a fresh install, but this time i didn't mess with gitolite for the auto initialization, and so far no problem, ubuntu 14.04 redmine 3.1 ruby 2.2.3 redmine_git_hosting 1.1.3 gitolite3 v3.6.3-11-g2417156. Thanks for your answer.

**Comment by n-rodriguez** [comment]
Great :)
