### ISSUE TITLE
Github Issues Sync

### ISSUE THREAD

**Issue by questers** [jbox-web/redmine_git_hosting#500]
Hi,

how can I use the feature "Github Issues Sync"?

best regards

**Comment by n-rodriguez** [comment]
* On your Github repo, go in *Settings -> Webhooks & services* then click on *Add webhook*.
* In the form fill the url field with your Redmine url : ```http://redmine.example.net/githooks/post-receive/github/<project_identifier>```.
The last part of the url ```<project_identifier>``` maps to a Redmine project. Issues will be created/updated for this project.
* Content type is json.
* Then check ```issues``` and ```issue comment```
* Validate

Now when an issue is created in Github it is automatically created in Redmine.

Note : this part of the plugin has been implemented a while and might need some improvements.
Actually I don't remember if the token is needed (and it should be).
