### ISSUE TITLE
Download Git Revision Archive for Anonymous user redirect to login page

### ISSUE THREAD

**Issue by vlaborie** [jbox-web/redmine_git_hosting#501]
Hi,
I want allow anonymous user to "Download Git Revision Archive" and I set it in Anonymous role but click on download button when not logged in, redirect to login page.

My config :
    Redmine 3.0.3-stable
    Redmine git Hosting : 1.1.1

I think the trouble is in plugins/redmine_git_hosting/app/controllers/download_git_revision_controller.rb line 4, because "before_filter :require_login" and "before_filter :can_download_git_revision" are present and anonymous user is'nt login.

ps: I'm work in Marseille not far from you, and I pay bug resolution with Beer ;)

**Comment by n-rodriguez** [comment]
Hi ! Fixed !

> ps: I'm work in Marseille not far from you, and I pay bug resolution with Beer ;)

Why not :) But I don't drink, you're warned ^^
