### ISSUE TITLE
Cannot apply Settings, got 500 Error

### ISSUE THREAD

**Issue by Rubinum** [jbox-web/redmine_git_hosting#506]
I installed a fresh new instance of redmine including the redmine-git-hosting plugin and the Redmine Bootstrap Kit plugin.

I strictly followed this guide to do so: 
http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_2_integrated_with_Gitolite_2_on_Debian_Wheezy_with_Apache_and_Phusion_Passenger

Everything works fine, but when I try to change settings on the redmine-surfice for this plugin(Redmine -> Administration (you have to be admin)-> Plugins -> Redmine Git Hosting Plugin Konfiguration) then I got an 500 error from Redmine.

The logs say (/path_to_Redmine/logs/production.log): 
```
Started GET "/redmine/settings/plugin/redmine_git_hosting?tab=gitolite_redmine_config" for 10.32.1.58 at 2015-09-09 07:02:53 -0400
Processing by SettingsController#plugin as HTML
  Parameters: {"tab"=>"gitolite_redmine_config", "id"=>"redmine_git_hosting"}
  Current user: admin (id=1)
  Rendered plugins/redmine_bootstrap_kit/app/views/common/_modal_base.html.haml (0.3ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_hosting_js_headers.html.haml (2.6ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_ssh.html.haml (0.6ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_storage.html.haml (0.7ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_file.html.haml (1.1ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_global.html.haml (1.1ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_access.html.haml (1.7ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_hooks.html.haml (1.7ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_cache.html.haml (0.7ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_notify.html.haml (1.0ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_display_access.html.haml (0.9ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_redmine_config.html.haml (2.8ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_sidekiq_interface.html.haml (0.4ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_test.html.haml (474.2ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_recycle_bin.html.haml (15.8ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_rescue.html.haml (0.9ms)
  Rendered common/_tabs.html.erb (508.3ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.haml (511.7ms)
  Rendered settings/plugin.html.erb within layouts/admin (513.2ms)
  Rendered admin/_menu.html.erb (3.3ms)
  Rendered layouts/base.html.erb (28.8ms)
Completed 200 OK in 549ms (Views: 546.0ms | ActiveRecord: 1.1ms)
Started POST "/redmine/settings/plugin/redmine_git_hosting" for 10.32.1.58 at 2015-09-09 07:05:10 -0400
Processing by SettingsController#plugin as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"emFExKfLHkaCYIZ21mcrth/BBO52I70HHLCXmuovHCrwFt1wNHmaG9fJWnVcitzhEymreLPRiHCzOB2Yj+Y3Mw==", "settings"=>{"gitolite_user"=>"git", "gitolite_ssh_private_key"=>"/opt/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa", "gitolite_ssh_public_key"=>"/opt/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa.pub", "gitolite_server_host"=>"localhost", "gitolite_server_port"=>"22", "gitolite_global_storage_dir"=>"repositories/", "gitolite_recycle_bin_dir"=>"recycle_bin/", "gitolite_redmine_storage_dir"=>"", "gitolite_lib_dir"=>"bin/lib/", "gitolite_config_file"=>"gitolite.conf", "gitolite_identifier_prefix"=>"redmine_", "gitolite_identifier_strip_user_id"=>"true", "gitolite_temp_dir"=>"/tmp/redmine_git_hosting/", "gitolite_recycle_bin_expiration_time"=>"24.0", "gitolite_log_level"=>"info", "git_config_username"=>"Redmine Git Hosting", "git_config_email"=>"redmine@example.net", "ssh_server_domain"=>"localhost", "http_server_domain"=>"localhost", "https_server_domain"=>"localhost", "http_server_subdir"=>"", "gitolite_http_by_default"=>"1", "show_repositories_url"=>"true", "gitolite_daemon_by_default"=>"false", "download_revision_enabled"=>"true", "gitolite_overwrite_existing_hooks"=>"true", "gitolite_hooks_are_asynchronous"=>"false", "gitolite_hooks_debug"=>"false", "gitolite_hooks_url"=>"http://localhost:3000", "gitolite_cache_max_time"=>"86400", "gitolite_cache_max_size"=>"16", "gitolite_cache_max_elements"=>"2000", "gitolite_cache_adapter"=>"database", "gitolite_notify_by_default"=>"false", "gitolite_notify_global_prefix"=>"[REDMINE]", "gitolite_notify_global_sender_address"=>"redmine@example.net", "gitolite_notify_global_include"=>[""], "gitolite_notify_global_exclude"=>[""], "redmine_has_rw_access_on_all_repos"=>"true", "all_projects_use_git"=>"false", "init_repositories_on_create"=>"false", "delete_git_repositories"=>"true", "hierarchical_organisation"=>"true", "gitolite_use_sidekiq"=>"false"}, "commit"=>"Anwenden", "id"=>"redmine_git_hosting"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.5ms)

ArgumentError (wrong number of arguments(1 for 0)):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

Can someone help me with this issue?

**Comment by n-rodriguez** [comment]
> ArgumentError (wrong number of arguments(1 for 0)): lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Obviously the plugin is not (yet) compatible with Redmine 3.1.x.

This needs to be investigated.

**Comment by Rubinum** [comment]
Interresting, keep us informed about that :)

**Comment by n-rodriguez** [comment]
Which version of Redmine are you running and which version of the plugin?

**Comment by Rubinum** [comment]
Redmine-Version: 3.1.0 stable
git_hosting Version: 1.1

**Comment by n-rodriguez** [comment]
Fixed in commit : https://github.com/jbox-web/redmine_git_hosting/commit/433f529f803371855ab343922633c631b6886345

**Comment by n-rodriguez** [comment]
By the way, even if it may be buggy right now, I strongly suggest you to use the current stable branch (v1.1.x) and not the devel one as it may contain unfinished work on DB migration.
This would lead you to inconsistent DB schemas.

**Comment by n-rodriguez** [comment]
Actually the plugin does work with Redmine 3.1.x but with the stable branch.
This bug was specific to the devel branch. Thanks for reporting it, but for the safety of your datas **please use the stable branch in production**. Contributions like yours are still welcomed :)

**Comment by r0perice** [comment]
Hi,

Same problem here with a fresh install of the new Redmine version (3.1.1-0 stable).

I have :
* bootstrap_kit : 0.2.3
* git_hosting : 1.1.3

I have followed this installation guide : http://redmine-git-hosting.io/get_started/ 

After step 2 when I try to access to the plugin configuration I have :

![git_hosting_error](https://cloud.githubusercontent.com/assets/7713432/10040626/8ad40d72-61dd-11e5-9b2c-bdf2be583248.PNG)

My **production.log**

>Started GET "/redmine/settings/plugin/redmine_git_hosting" for 80.14.188.84 at 2015-09-23 07:17:35 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_git_hosting"}
  Current user: admin (id=1)
  Rendered plugins/redmine_bootstrap_kit/app/views/common/_modal_base.html.haml (0.9ms)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_hosting_js_headers.html.haml (6.0ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_ssh.html.haml (1.4ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_storage.html.haml (114.5ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_file.html.haml (5.3ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_global.html.haml (3.1ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_access.html.haml (5.0ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_hooks.html.haml (5.6ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_cache.html.haml (1.7ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_notify.html.haml (3.0ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_display_access.html.haml (2.1ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_redmine_config.html.haml (6.8ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_sidekiq_interface.html.haml (1.2ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_test.html.haml (142.0ms)
  Rendered common/_tabs.html.erb (304.4ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.haml (313.1ms)
  Rendered settings/plugin.html.erb within layouts/admin (316.2ms)
Completed 500 Internal Server Error in 332ms (ActiveRecord: 1.4ms)

>ActionView::Template::Error (no implicit conversion of nil into String):
    20:     %td= l(:label_sudo_redmine_to_gitolite_user)
    21:     %td= image_tag (RedmineGitHosting::Config.can_redmine_sudo_to_gitolite_user? ? 'true.png' : 'exclamation.png')
    22:
    23:   - gitolite_checks = RedmineGitHosting::Config.check_hooks_install!
    24:
    25:   %tr
    26:     %td= l(:label_gitolite_hooks_installed)
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___2881743454243195429_70256380878100'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___2881743454243195429_70256380878100'
  app/helpers/application_helper.rb:322:in `render_tabs'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__1772209910909950766_70256380189440'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__1772209910909950766_70256380189440'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Any help will be appreciated.

Regards,
Robin

**Comment by r0perice** [comment]
Ok I don't really know why but I don't have problem now to access git_hosting/settings ...

**Comment by n-rodriguez** [comment]
> Same problem here with a fresh install of the new Redmine version (3.1.1-0 stable).

This is an other issue actually. Your issue happens when the git(tolite) user is not properly set.

**Comment by thelfensdrfer** [comment]
I have the same error as r0perice, what does it mean that the git user is not properly set @n-rodriguez? The user for gitolite on the gitolite server?

**Comment by n-rodriguez** [comment]
> The user for gitolite on the gitolite server?

yes

**Comment by firsyura** [comment]
Hi @n-rodriguez 
I have the same error.
```
Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.8ms)

ArgumentError (wrong number of arguments(1 for 0)):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
My configuration:
```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Git                            1.9.1
  Filesystem                     
  Xitolite                       1.9.1
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.0
```

**Comment by jblobb** [comment]
Hi Guys,

I had the same issue. The plugin does work it's just that the GUI is broken.

If you edit the default settings manually, then perform a CLI hooks update the plugin works with the following configuration:

`Environment:
  Redmine version                3.1.3.stable.15144
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  4.2.5.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.10.4
  Filesystem                     
  Xitolite                       1.7.10.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.0
  timelog_timer                  2.0.0`

@n-rodriguez I hope this helps [https://github.com/jbox-web/redmine_git_hosting/issues/567#issuecomment-180162516](url)

**Comment by invartam** [comment]
Hi,

Same problem here.
Have you some ideas ?

Stacktrace :
`Started POST "/redmine/settings/plugin/redmine_git_hosting" for ******** at 2016-04-08 09:56:59 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"85Rmrz***************0MdJEf+A=", "settings"=>{"gitolite_user"=>"git", "gitolite_ssh_private_key"=>"/opt/redmine/current/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa", "gitolite_ssh_public_key"=>"/opt/redmine/current/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa.pub", "gitolite_server_host"=>"127.0.0.1", "gitolite_server_port"=>"22", "gitolite_global_storage_dir"=>"repositories/", "gitolite_recycle_bin_dir"=>"recycle_bin/", "gitolite_redmine_storage_dir"=>"", "gitolite_lib_dir"=>"bin/lib/", "gitolite_config_file"=>"gitolite.conf", "gitolite_identifier_prefix"=>"redmine_", "gitolite_identifier_strip_user_id"=>"true", "gitolite_temp_dir"=>"/tmp/redmine_git_hosting/", "gitolite_recycle_bin_expiration_time"=>"24.0", "gitolite_log_level"=>"info", "git_config_username"=>"Redmine Git Hosting", "git_config_email"=>"redmine@example.net", "ssh_server_domain"=>"localhost", "http_server_domain"=>"localhost", "https_server_domain"=>"localhost", "http_server_subdir"=>"", "gitolite_http_by_default"=>"1", "show_repositories_url"=>"true", "gitolite_daemon_by_default"=>"false", "download_revision_enabled"=>"true", "gitolite_overwrite_existing_hooks"=>"true", "gitolite_hooks_are_asynchronous"=>"false", "gitolite_hooks_debug"=>"false", "gitolite_hooks_url"=>"http://localhost:3000", "gitolite_cache_max_time"=>"86400", "gitolite_cache_max_size"=>"16", "gitolite_cache_max_elements"=>"2000", "gitolite_cache_adapter"=>"database", "gitolite_notify_by_default"=>"false", "gitolite_notify_global_prefix"=>"[REDMINE]", "gitolite_notify_global_sender_address"=>"redmine@example.net", "gitolite_notify_global_include"=>[""], "gitolite_notify_global_exclude"=>[""], "redmine_has_rw_access_on_all_repos"=>"true", "all_projects_use_git"=>"false", "init_repositories_on_create"=>"false", "delete_git_repositories"=>"true", "hierarchical_organisation"=>"true", "gitolite_use_sidekiq"=>"false"}, "commit"=>"Appliquer", "id"=>"redmine_git_hosting"}
  Current user: ********** (id=9)
Completed 500 Internal Server Error in 2.7ms

ArgumentError (wrong number of arguments(1 for 0)):
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/settings_controller_patch.rb:55:in `initialize'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/settings_controller_patch.rb:55:in `new'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/settings_controller_patch.rb:55:in `handle_settings_update'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/settings_controller_patch.rb:41:in `plugin_with_git_hosting'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/base.rb:167:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:480:in `_run__1971948799082211547__process_action__82327795317054755__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  /usr/lib/ruby/vendor_ruby/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/base.rb:121:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/rendering.rb:45:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal.rb:203:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal.rb:246:in `block in action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:73:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:36:in `call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:608:in `call'
  /usr/lib/ruby/vendor_ruby/rack/openid.rb:98:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/conditionalget.rb:35:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/head.rb:14:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/flash.rb:242:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  /usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:64:in `call'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `_run__1740834776745846795__call__3877788832301530219__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/static.rb:83:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:140:in `forward'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:147:in `pass'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:159:in `invalidate'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:74:in `call!'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/engine.rb:484:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'`

Versions :
`Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.22.2
  Environment                    production
  Database adapter               MySQL
SCM:
  Git                            1.9.1
  Filesystem                     
  Xitolite                       1.9.1
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.0`
