### ISSUE TITLE
Cache timer doesn't seem to update when a commit is pushed

### ISSUE THREAD

**Issue by TakSuyu** [jbox-web/redmine_git_hosting#508]
The default option is 1 day or until the next commit, but I can't get it to update when a commit is pushed. Changing the option or setting it to a lower setting works for now, but is there anything you can recommend to solve this?

**Comment by TakSuyu** [comment]
Sorry I didn't realize that the hooks had to be installed for it to update.

Possibly showing a warning or putting it into the guide would keep this from popping up again.

**Comment by n-rodriguez** [comment]
Great :)

http://redmine-git-hosting.io/get_started/#step-9-finish-installation---configuration
