### ISSUE TITLE
Path to public keys in user account is broken (with subdir install)

### ISSUE THREAD

**Issue by oliwel** [jbox-web/redmine_git_hosting#509]
The link to "My public keys" in "My Account" is broken as it has the base path twice:

```
https://host/redmine/redmine/my/public_keys
```

I installed redmine to the subdirectory /redmine and I am using the CGI wrapper, I had some problems getting this to work and had to hack the rewrite component, so I guess that matters and might be a part of this problem.

Redmine version                3.1.0.stable
redmine_bootstrap_kit          0.2.3
redmine_git_hosting            1.1.1

**Comment by n-rodriguez** [comment]
Update to version 1.1.3 : http://redmine-git-hosting.io/releases-notes/release-1.1.3.html

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by oliwel** [comment]
No time to update yet, will keep you posted

**Comment by oliwel** [comment]
Works with 1.1.3
