### ISSUE TITLE
Adding a public key doesn't add it to repository permissions

### ISSUE THREAD

**Issue by sdragnev** [jbox-web/redmine_git_hosting#512]
Using 1.1.3 with redmine 2.6.6.

When a user adds a public key to their redmine account, the key is added to gitolite but not given RW permission for repositories of projects they have access to.
This used to work with an older version of redmine and redmine_git_hosting (from a few years ago).

SSHing with the newly added key connects to gitolite fine but only returns RW access to the "testing" repo.
All config checks in the plugin's settings pass.

This is what what the plugin's log says when deleting and readding a key:

```
2015-09-15 14:50:26 -0400 [INFO] User 'sdragnev' has deleted a SSH key
2015-09-15 14:50:26 -0400 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-09-15 14:50:27 -0400 [INFO] Deleting SSH key 
2015-09-15 14:50:27 -0400 [INFO] delete_ssh_key : commiting to Gitolite...
2015-09-15 14:50:38 -0400 [INFO] User 'sdragnev' has added a SSH key
2015-09-15 14:50:38 -0400 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2015-09-15 14:50:39 -0400 [INFO] Adding SSH key redmine_sdragnev_102@redmine_dev1
2015-09-15 14:50:39 -0400 [INFO] add_ssh_key : commiting to Gitolite...
```

No sign of trouble.
Redmine sees the project repositories fine so I think the link between the project and repo is fine.

Any tips to troubleshoot this?

**Comment by n-rodriguez** [comment]
> When a user adds a public key to their redmine account, the key is added to gitolite but not given RW permission for repositories of projects they have access to.

This is normal. These 2 notions are now decoupled as you can access to the repository via SSH or HTTP (SmartHTTP).
So when you declare a user as a project's member it is automatically added to the Gitolite config file in the repository section. If not this might be the root of the issue.

**Comment by sdragnev** [comment]
I tried removing and re-adding a user to a project and the new key wasn't added to the gitolite config. Nothing changed in fact - keys weren't being removed either.

I wonder if it's some issue with not properly migrated repo-key links with redmine.

**Comment by sdragnev** [comment]
Okay...
I hadn't enabled the "Xitolite" SCM setting in redmine. I had git but no "xitolite". Whatever xitolite is.
I finally got an error from the plugin when I test-created a new repo. After tracing the error trigger, I saw the xitolite check in the code.

Mystery solved but at what twisty cost!!
