### ISSUE TITLE
Support storing hooks in gitolite-admin repository

### ISSUE THREAD

**Issue by mrueg** [jbox-web/redmine_git_hosting#513]
It would be nice if your plugin could support the other location, too.
LOCAL_CODE                =>  "$rc{GL_ADMIN_BASE}/local",
See http://gitolite.com/gitolite/non-core.html#pushcode

**Comment by n-rodriguez** [comment]
What do you mean?

**Comment by mrueg** [comment]
Currently hooks are installed into $ENV{HOME}/local, i.e. git's home directory. 
Gitolite enables to install hooks (as a git commit) into the gitolite-admin repository, too. It would be nice to have an option to switch between those two locations (or check the LOCAL_CODE var in .gitolite.rc to install it to the proper location)

**Comment by n-rodriguez** [comment]
> It would be nice to have an option to switch between those two locations (or check the LOCAL_CODE var in .gitolite.rc to install it to the proper location)

You can already choose your LOCAL_CODE directory in plugin settings. I don't see the need of switching. Maybe you could enlight me on this point?

**Comment by mrueg** [comment]
If I set LOCAL_CODE to "$rc{GL_ADMIN_BASE}/local" in gitolite, the setting in redmine_git_hosting still needs to point to a checkout of gitolite-admin, which is usually not available in git's home directory. Therefore, an option to use the gitolite-admin repository would be helpful.

**Comment by n-rodriguez** [comment]
> If I set LOCAL_CODE to "$rc{GL_ADMIN_BASE}/local" in gitolite, the setting in redmine_git_hosting still needs to point to a checkout of gitolite-admin, which is usually not available in git's home directory. Therefore, an option to use the gitolite-admin repository would be helpful.

I see. Thank you!

**Comment by n-rodriguez** [comment]
Well this is doable, but it might need a lot more work than I thought as gitolite-rugged doesn't know about hooks.

**Comment by mrueg** [comment]
Thanks for considering this. Does gitolite-rugged need to know about hooks? Wouldn't a commit to gitolite-admin.git/local and fetching the hooks from a checked-out repository (like the one residing in /tmp/) be sufficient?

**Comment by jbox-admin** [comment]
> Wouldn't a commit to gitolite-admin.git/local and fetching the hooks from a checked-out repository (like the one residing in /tmp/) be sufficient?

Sure, but IMHO it would be the dirty way : to do this you can :

* exec(git add) && exec(git commit) and chdir
* do the same thing than for the [README creator](https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/redmine_git_hosting/plugins/extenders/readme_creator.rb) whick looks like a hack
* implement it in gitolite-admin where most of the logic to add files/commit/update files already exists

Eventually it may help to improve README creator.
