### ISSUE TITLE
Unable to mirror local repository to another local repository

### ISSUE THREAD

**Issue by tchemineau** [jbox-web/redmine_git_hosting#516]
Hi,

After a fresh upgrade of my Redmine instance (v2.6.6) with Redmine_Git_Hosting plugin (v1.1.3), everything is working as excepted. There is still an error with the mirroring function (first time I try to use it).

I setup a mirror into the mirroring section of my repository. The mirror is in fact another repository onto the same server. Then I try to force the mirroring by clicking on the "Push" link. Redmine answers me with the following error :

    Envoi des changements au miroir ssh://git@redmine.example.com/myrepo.git : Échec
    
    Sortie :
    Non-zero exit code pid 6517 exit 128 for `sudo -n -u git -i env GIT_SSH=/data/git/.ssh/run_gitolite_admin_ssh git --git-dir repositories/myrepo.git push --mirror ssh://git@redmine.example.com/myrepo2.git`

Indeed, I check if the admin key (the same as defined as the mirroring key) is configured on all projects with RW+ access. But it is not the case, only onto the gitolite-admin repository.

I try to add this key into my redmine instance (via my profile view), but Redmine returns me an error: "The key is already used for the gitolite admin key".

What can I do ?

**Comment by tchemineau** [comment]
Still have this error with Redmine_Git_Hosting 1.14. I can't make it work.

When I go into the administration panel, into the Test Configuration tab, I can read this :

    Gitolite banner
    hello redmine_gitolite_admin_id_rsa, this is git@XXXX running gitolite3 v3.6-2-g2d5c690 on git 1.7.10.4

     R W	gitolite-admin
     R W	testing

I check this page : http://redmine-git-hosting.io/troubleshooting/
I try to apply the steps described into the section "Initialization of the repo with README file does not work", but it doesn't work for me. In fact, the change is correclty set manually, but then canceled when a user add a key.

Any idea on how to configure this key to have RW access on all repository ?

**Comment by tchemineau** [comment]
Ok, I found it. It seems it is not yet possible via Redmine_Git_Hosting to mirror 2 repository inside Redmine.

I edited `lib/redmine_git_hosting/gitolite_wrapper/global.rb` and comment code into `remove_redmine_key`:

    81           # Delete the key
    82           #repo_conf.permissions[0]['RW+'][''].delete(redmine_gitolite_key)
    83 
    84           # We cannot remove this repository as it may contains other configuration that we didn't check.
    85           # Instead add a dummy key so the repo_conf is still valid for Gitolite
    86           # RW+ = <empty string> is not valid
    87           #repo_conf.permissions[0]['RW+'][''].push('DUMMY_REDMINE_KEY') if repo_conf.permissions[0]['RW+'][''].empty?

Then restart Redmine.

Add the admin git into the @all section of `gitolite.conf`, and finally resynchronize keys via the admin panel of Redmine_Git_Hosting. Admin key should now have RW access to all.

Could it be possible to dissociate the mirror key from the admin key ? In the settings of each git repository, we could imagine having a checkbox to give write access to the mirror key.

**Comment by n-rodriguez** [comment]
> Could it be possible to dissociate the mirror key from the admin key ?

This is already done for the next release.
