### ISSUE TITLE
Changesets are not updating into Redmine

### ISSUE THREAD

**Issue by tchemineau** [jbox-web/redmine_git_hosting#518]
Redmine 2.6.6
Redmine_Git_Hosting 1.1.4
Debian 7

When I commit a change into a repository, changesets seem not to be updated into Redmine. The revision doesn't appear into Redmine.

When I clone the repository, I see that the commit is here.

When I force to refresh changesets, I got this error :

    $ bundle exec rake --trace redmine_git_hosting:fetch_changesets RAILS_ENV=production
    Your Gemfile lists the gem redcarpet (~> 2.3.0) more than once.
    You should probably keep only one of them.
    While it's not a problem now, it could cause errors if you change the version of just one of them later.
    ** Invoke redmine_git_hosting:fetch_changesets (first_time)
    ** Invoke environment (first_time)
    ** Execute environment
    ** Execute redmine_git_hosting:fetch_changesets
    Performing manual fetch_changesets operation...
    rake aborted!
    Mysql2::Error: closed MySQL connection
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:66:in `escape'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:66:in `quote_string'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/quoting.rb:22:in `quote'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:205:in `quote'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:482:in `quote'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:450:in `quoted'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:478:in `block in visit_Array'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:478:in `map'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:478:in `visit_Array'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:376:in `visit_Arel_Nodes_In'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:389:in `block in visit_Arel_Nodes_And'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:389:in `map'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:389:in `visit_Arel_Nodes_And'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:136:in `block in visit_Arel_Nodes_SelectCore'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:136:in `map'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:136:in `visit_Arel_Nodes_SelectCore'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/mysql.rb:41:in `visit_Arel_Nodes_SelectCore'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:121:in `block in visit_Arel_Nodes_SelectStatement'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:121:in `map'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:121:in `visit_Arel_Nodes_SelectStatement'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/mysql.rb:36:in `visit_Arel_Nodes_SelectStatement'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:5:in `accept'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:19:in `accept'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/arel-3.0.3/lib/arel/visitors/bind_visitor.rb:11:in `accept'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in `to_sql'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/querying.rb:38:in `block in find_by_sql'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/explain.rb:41:in `logging_query_plan'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/querying.rb:37:in `find_by_sql'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/relation.rb:171:in `exec_queries'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/relation.rb:160:in `block in to_a'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/explain.rb:41:in `logging_query_plan'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/relation.rb:159:in `to_a'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/relation/delegation.rb:6:in `map'
    /home/redmine/redmine/app/releases/redmine-2.6.6/app/models/repository/git.rb:199:in `save_revisions'
    /home/redmine/redmine/app/releases/redmine-2.6.6/app/models/repository/git.rb:153:in `fetch_changesets'
    /home/redmine/redmine/app/releases/redmine-2.6.6/app/models/repository.rb:342:in `block (2 levels) in fetch_changesets'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/associations/collection_proxy.rb:91:in `each'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/activerecord-3.2.22/lib/active_record/associations/collection_proxy.rb:91:in `method_missing'
    /home/redmine/redmine/app/releases/redmine-2.6.6/app/models/repository.rb:340:in `block in fetch_changesets'
    /home/redmine/redmine/app/releases/redmine-2.6.6/app/models/repository.rb:339:in `each'
    /home/redmine/redmine/app/releases/redmine-2.6.6/app/models/repository.rb:339:in `fetch_changesets'
    /home/redmine/redmine/app/releases/redmine-2.6.6/plugins/redmine_git_hosting/lib/tasks/redmine_git_hosting.rake:36:in `block (2 levels) in <top (required)>'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
    /home/redmine/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
    /home/redmine/.rbenv/versions/1.9.3-p547/bin/rake:23:in `load'
    /home/redmine/.rbenv/versions/1.9.3-p547/bin/rake:23:in `<main>'
    Tasks: TOP => redmine_git_hosting:fetch_changesets

What can I do ?

**Comment by tchemineau** [comment]
I follow this tips and it works now :
http://stackoverflow.com/questions/11773930/ruby-exception-occured-mysql2error-closed-mysql-connection

**Comment by tchemineau** [comment]
In fact, there are no more errors with this manual tips.
But, changes are still not displayed into Redmine, when I browse source code.

**Comment by tchemineau** [comment]
I just put this command into a cronjob which run every 10 minutes in order to refresh Redmine browser.

How can I make Redmine_Git_Hosting refresh it everytime a push is done ?

**Comment by n-rodriguez** [comment]
> How can I make Redmine_Git_Hosting refresh it everytime a push is done ?

It should be automatic. Check the hooks url in *Administration -> Redmine Git Hosting -> Hooks*. This url is called by a git hook which is installed when you click on 'install hooks' links.
This url must be callable by the hook.

**Comment by rtestaverde** [comment]
Hi all, I have the same problem, but it seems that the hook url

> http://domain.tld/post-receive/redmine 

don't exists **404 error** although the configuration seems fine.
Another issue (don't know if is related) is when I make a push from the git repo, the output is:
> git push redmine master
> Counting objects: 4, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (4/4), done.
> Writing objects: 100% (4/4), 383 bytes | 0 bytes/s, done.
> Total 4 (delta 2), reused 0 (delta 0)
> 
> Notifying Redmine about changes to this repository : 'fujifilm-mis-navarra-modulo-informe-radiologico/' ...
> HTTP_ERROR : execution expired
> 
> Looking for additional global post-receive hooks...
>   - Global hooks found : ["hooks/post-receive.d/mail_notifications"]
> 
> Looking for additional local post-receive hooks...
>  - No local hooks found
> 
> Calling additional post-receive hooks...
>   - Executing extra hook 'hooks/post-receive.d/mail_notifications'
> remote: *** Error establishing SMTP connection to localhost:25***
> remote: *** [Errno 111] Connection refused
> remote: Exception AttributeError: "'SMTPMailer' object has no attribute 'smtp'" in <bound method  SMTPMailer.__del__ of <git_multimail.SMTPMailer object at 0x7f1558fd1990>> ignored
> 
> 
> To ssh://git@redmine.choice.es/fujifilm-mis-navarra-modulo-informe-radiologico.git
   d8001c0..95aba29  master -> master


I'm new in redmine and quite new in Ruby... how can I debug the ulrs?
The installation is on fresh Ubuntu 14.04 64bit
Ruby 2.1.7
Git 1.9.1
Redmine Bootstrap Kit plugin 0.2.3
Redmine Git Hosting Plugin 1.1.4

The only way is to clear repositories cache.
 
Any help is apreciated

**Comment by tchemineau** [comment]
> It should be automatic. Check the hooks url in Administration -> Redmine Git Hosting -> Hooks. This url is called by a git hook which is installed when you click on 'install hooks' links.
> This url must be callable by the hook.

Indeed, the default URL was wrong.
Thanks !

**Comment by n-rodriguez** [comment]
> don't exists 404 error although the configuration seems fine.

This url is only accessible by ```POST```.

**Comment by n-rodriguez** [comment]
@rtestaverde can you please open another issue if not solved? thanks
