### ISSUE TITLE
Is there a possibility to use already done features in dev branch?

### ISSUE THREAD

**Issue by amelentjev** [jbox-web/redmine_git_hosting#519]
I'm talking about negative permissions in protected branches. I've tried to checkout dev version, commented out in gemfile everything about development/testing, but redmine:plugins:migrate task failed, complaining about undefined constant Base in lib/core_ext/faker/git.rb. Should I enable faker gem to get it to work? Unfortunately I'm not ruby developer :(

**Comment by n-rodriguez** [comment]
Redmine Git Hosting 1.2.0 has been released : https://github.com/jbox-web/redmine_git_hosting/releases/tag/1.2.0.
