### ISSUE TITLE
Automatically initialize Git repositories for new projects - Fails

### ISSUE THREAD

**Issue by BAndonovski** [jbox-web/redmine_git_hosting#520]
Did an upgrade to the 1.1.4 . Everything seems to be working fine, except for initializing git repos for new projects. 
I get this: [ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user. 
(nothing else useful)

But, it doesn't make any sense... The SSH keys are there and accessible. Pretty much as they were before the upgrade. 
Even more, the already existing repos function without an issue. 
I did the standard test that people are doing mentioned throughout the issues, everything seems fine.

After 4-5 days trying to figure this out, I'm getting desperate. Any help would be appreciated.

**Comment by BAndonovski** [comment]
Ok, the SSH keys issue is solved, and the Config Test passes successfully. Everything seems to be in order, except that creating a new repo still fails. 
Regardless if it's creating a new project, or a new repo to an existing project, it fails. 
git_hosting has nothing, it's empty.

**Comment by n-rodriguez** [comment]
Can you please try with the latest release? (1.2.0)
