### ISSUE TITLE
Failing to fetch changesets

### ISSUE THREAD

**Issue by reezer** [jbox-web/redmine_git_hosting#522]
When trying to fetch changesets it fails:

```
$ RAILS_ENV=production rake redmine_git_hosting:fetch_changesets --trace
** Invoke redmine_git_hosting:fetch_changesets (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine_git_hosting:fetch_changesets
Performing manual fetch_changesets operation...
fatal: Not a git repository: 'repositories/example.git'
Done!
```

Can it be that somehow the git users home directory is missing. Should it be `/home/git/repositories/example.git`? If so, how is the home directory being set?

Strangely enough removing stuff from the Recycle Bin works.

The `Config Test` page is completely green and all the repositories are shown there. The repositories exist in `/home/git/repositories`. In those directories I can also run `git log`, etc.

**Comment by reezer** [comment]
Strangely enough stuff like removing the repo, creating a new one, etc. appears to work. So it seems to be related to upgrading from an earlier version. However I followed the migration instruction.

**Comment by bes1002t** [comment]
Mh I think If you remove the example.git repository, you should remove it in the configfile too.

**Comment by n-rodriguez** [comment]
> Should it be /home/git/repositories/example.git?

Nope, this path is always relative

> how is the home directory being set?

From ```/etc/passwd``` file

**Comment by n-rodriguez** [comment]
Btw does clone work on this repo ```repositories/example.git```?
