### ISSUE TITLE
Repository view crashes after update plugin or postgres

### ISSUE THREAD

**Issue by kovalevvv** [jbox-web/redmine_git_hosting#523]
After new tag in cyrullic and error on push repository view show mew only one tag named 'x' and empty file tree.
Fix it error help 'Flush Git Cache?' option on settings, but only until refrashe page. Next view error return.

redmine 3.0.3.stable
plugin 1.1.4

**Comment by derats** [comment]
Oops, sorry. These error make upgrade postgres 8.4 to 9.3

**Comment by derats** [comment]
Oops.... these error after upgrade plugin from verstion 1.1.1 to 1.1.4 using manual http://redmine-git-hosting.io/how-to/upgrade/
... =)

**Comment by derats** [comment]
After upgrade to postgres 9.3 plugin 1.1.1 raise 404 error on repository view page. Upgrade plugin to 1.1.4 correct 404, but make error "one refresh".

**Comment by n-rodriguez** [comment]
Hi there! You can disable the cache in plugin settings.

**Comment by derats** [comment]
Hello! 
hmm... why cache not working on upgraded database?

**Comment by n-rodriguez** [comment]
> hmm... why cache not working on upgraded database?

I'm sorry but actually I don't understand your issue.

**Comment by n-rodriguez** [comment]
Hi there! Any news?
