### ISSUE TITLE
Auto-create README fails, 'admin' denied by fallthru

### ISSUE THREAD

**Issue by j0bb13** [jbox-web/redmine_git_hosting#525]
Good night,

When I create a new project with repo as my Redmine administrator 'job' no README file will be created and the git_hosting.log file shows the following:

    2015-10-22 03:12:07 +0200 [INFO] User 'job' created a new repository 'testtest'
    2015-10-22 03:12:07 +0200 [INFO] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
    2015-10-22 03:12:08 +0200 [INFO] add_repository : repository 'testtest' does not exist in Gitolite, create it ...
    2015-10-22 03:12:08 +0200 [INFO] add_repository : commiting to Gitolite...
    2015-10-22 03:12:08 +0200 [INFO] add_repository : let Gitolite create empty repository 'repositories/testtest.git'
    2015-10-22 03:12:09 +0200 [INFO] Execute Gitolite Plugins
    2015-10-22 03:12:10 +0200 [INFO] Create README file for repository 'testtest'
    2015-10-22 03:12:13 +0200 [ERROR] Error while creating README file for repository 'testtest'
    2015-10-22 03:12:13 +0200 [ERROR] FATAL: R any testtest admin DENIED by fallthru (or you mis-spelled the reponame)

My gitolite-admin/conf/gitolite.conf file has the following admin (retreived via git clone git@localhost:gitolite-admin):

    repo    @all
      RW+                            = redmine_gitolite_admin_id_rsa

Whenever I change this line, commit and push, it will change back to redmine_gitolite_admin_id_rsa when I create a repo in Redmine. I assume I'm very stupid or just too tired and I can change the user if I just read the manual better.

But then I thought, is it possible to tell redmine to use this user instead of 'admin'?

Kind regards,
Job

**Comment by j0bb13** [comment]
System info: Ubuntu 14.04 64bit

    Environment:
      Redmine version                3.1.1.stable.14695
      Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
      Rails version                  4.2.4
      Environment                    production
      Database adapter               Mysql2
    SCM:
      Subversion                     1.8.8
      Git                            1.9.1
      Filesystem                     
      Xitolite                       1.9.1
    Redmine plugins:
      clipboard_image_paste          1.10
      redmine_bootstrap_kit          0.2.3
      redmine_checklists             3.1.3
      redmine_codemirror             0.0.1
      redmine_dmsf                   1.5.5
      redmine_git_hosting            1.1.4
      redmine_issue_templates        0.1.0
      redmine_knowledgebase          3.0.7
      redmine_lightbox2              0.2.2

**Comment by BartoszF** [comment]
Have the same problem.

**Comment by j0bb13** [comment]
I still think it should be possible to change the username of the admin user used by redmine_git_hosting.

But in the mean time for other people with this problem:
By changing the gitolite user at "repo    @all" from "redmine_gitolite_admin_id_rsa" to "admin" it creates README files.

(I got another problem when pushing, but that's seems to be unrelated to this plugin: http://gitolite.com/gitolite/emergencies.html#ce)

**Comment by n-rodriguez** [comment]
Can you please try with the latest release? (https://github.com/jbox-web/redmine_git_hosting/releases/tag/1.2.0)

**Comment by n-rodriguez** [comment]
> I still think it should be possible to change the username of the admin user used by redmine_git_hosting.

what for?

**Comment by j0bb13** [comment]
Sorry, I didn't see this earlier.

I don't really have a good reason. I would say it feels natural to let people choose their preferred usernames, including the username of the admin user.

**Comment by n-rodriguez** [comment]
> I don't really have a good reason. I would say it feels natural to let people choose their preferred usernames, including the username of the admin user.

Ok. I would prefer to stick on Gitolite default username. The plugin install is still something difficult for some people. I don't to add unneeded complexity in the middle.
