### ISSUE TITLE
Redmine in subdirectory

### ISSUE THREAD

**Issue by stochastical** [jbox-web/redmine_git_hosting#530]
My redmine installation is working not on top of virtual host (like, http://dom.ain/_redmine_)  but in subdirectory (http://dom.ain/projects/_redmine_).
At this situation "My account" page generates wrong link on "My public keys". It should be 
http://dom.ain/projects/my/public_keys
but now it is without subdirectory part
http://dom.ain/my/public_keys
Of course bad link is 404.

![redmine_gitolite](https://cloud.githubusercontent.com/assets/5994727/10871233/63d889e4-80f2-11e5-9aed-59df5dc6a236.jpg)

Version of redmine_git_hosting is 1.1.4

**Comment by bes1002t** [comment]
I have the same problem. 

http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root
maybe this describes why this is happening. But I'm not sure because adding the relative url to application.rb won't change something.

**Comment by n-rodriguez** [comment]
http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI

**Comment by bes1002t** [comment]
This Issue was closed, but your link won't help, sorry. I followed all instructions and edit my environment.rb. 

'ActionController::AbstractRequest.relative_url_root = "/redmine"' let my redmine crash, without this line everything is like before. But I will consider why this codeline will cause a redmine crash.

**Comment by n-rodriguez** [comment]
I've already done the test in the past and it appears that the one which is working is : "Using-UnicornNginx".

**Comment by bes1002t** [comment]
so there is no way to get this working with passenger?

**Comment by n-rodriguez** [comment]
https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#deploying_rails_to_sub_uri

**Comment by bes1002t** [comment]
thx but this link is deprecated and redirects to this one: https://www.phusionpassenger.com/library/deploy/apache/deploy/ruby/#deploying-an-app-to-a-sub-uri

tried everything on this page but it does not work. Everytime the link to my public key page, links to the wrong page. But this is the only link in whole redmine that does not work correctly in ../redmine/ subdirectory. So I think maybe you use a wrong variable to access it.
