### ISSUE TITLE
Migration from 0.7.6 to 1.1.4: RepositoryGitExtra validation again

### ISSUE THREAD

**Issue by l337r007** [jbox-web/redmine_git_hosting#531]
Hi!
I'm upgrading an installation from 0.7.6 (Redmine 1.4.4) to 1.1.4 (Redmine 2.6.7).
I'm running into an issue with migration `20140305083200` (add default branch to RepositoryGitExtra).
Similarly to #459 it fails on checking `urls_order`, which only gets added in a 2015 migration AFAICS.
Also, I had to fool around with the `Gemfile`, basically working around #510.

I've migrated Redmine first (no problem there), then tried `migrate_to_v1`, which fails as above.

Any advice?

**Comment by l337r007** [comment]
Hm, looks like it's my fault. I hadn't done the migration to 0.7.10 before trying to go to 1.1.4 (apparently wrongly assuming I didn't need to, since I came from post-0.6).
At any rate, the documentation (http://redmine-git-hosting.io/how-to/migrate/) should be updated to reflect that the 0.7.10 step is necessary for everything <0.7.10.

**Comment by n-rodriguez** [comment]
Hi there! Thanks for your feedback!
Doc updated : http://redmine-git-hosting.io/how-to/migrate/
