### ISSUE TITLE
[devel] Incorrect protected branch gitolite refex

### ISSUE THREAD

**Issue by netsuo** [jbox-web/redmine_git_hosting#534]
Without any protected branch setup, the refex is correctly generated with every "developer_team" users that have the "commit" role set: 
```
repo    project
  RW+   				= user1, user2, user3
```

When you add a protected branch, there is only one line remaining for the users that you added on the protected branch:
```
repo    project
  RW+   master			= user1
```

This is not correct, because now you only have one protected branch and every other team member cannot do anything in any branch. 
The generated config should include 2 lines for each protected branch, one "RW+/RW/whathever" for the user you added and one "-" for every other users on the team. It should also add the main refex without any specified branch, like if you hadn't setup a protected branch:
```
repo    project
  RW+   master			= user1
  -		master			= user2, user3
  RW+   				= user1, user2, user3
```

At best, the generated config file should generate the "normal" refex that you would obtain without setting any protected branch + add theses 2 lines for every protected branch.

I don't know if it's what you tried to achieve but with this, you can set a group in Redmine that can commit on every branch by default, and with adding protected branch, you can allow only certain user to push/delete/whatever to theses branches, while retaining full Redmine user role management.

**Comment by n-rodriguez** [comment]
> The generated config should include 2 lines for each protected branch, one "RW+/RW/whathever" for the user you added and one "-" for every other users on the team

This part is up to you. I can't guess which users should be able to commit or not.

**Comment by n-rodriguez** [comment]
Can you please test with the latest release? (1.2.0)
