### ISSUE TITLE
Configuration of the plugin

### ISSUE THREAD

**Issue by KueWW** [jbox-web/redmine_git_hosting#535]
Hello everybody,

I tried to install gitolite and the plugin to manage it. I used the installation tutorial for that.
Gitolite is working using the console. I'm using redmine 2.6.0. Everytime I try to configure the pluging redmine says that it has no access to the plugin. I've checked the rights multiple times and it seems to be good. The apache logs doesn't give any help.
Can you give any help.

Thanks in advance....

**Comment by bes1002t** [comment]
I think you did something wrong with ssh access.
your redmine needs ssh access to gitolite.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
> Everytime I try to configure the pluging redmine says that it has no access to the plugin.

What do you mean?

**Comment by KueWW** [comment]
Hi there,

I'm sorry. I was off for a few days.
I'm not sure about the ssh access. I think that it works. Using the console ssh and gitolite works.
I will check that again.

What I meant with access to the plugin? See attched files.
The user rights should be well.
![2015-11-18 12_00_48-redmine 500 error](https://cloud.githubusercontent.com/assets/7642828/11239480/8ffc3a82-8dec-11e5-8f67-b54379507751.png)
![2015-11-18 11_59_18-administration - sks-entwicklungs-projektverwaltung _ reklamationsbearbeitung](https://cloud.githubusercontent.com/assets/7642828/11239481/9000b526-8dec-11e5-89d6-21776e7ef543.png)

**Comment by n-rodriguez** [comment]
> The user rights should be well.

This is not a permission issue. Check your logs (in ```<redmine root>/log/git_hosting.log```)

**Comment by KueWW** [comment]
Hi there,

I'm sorry. I was off for a few days.
The ssh should run. Out of the console it works fine.
I will check it again.

See the attached files to see what I meant with accessing the plugin.

![2015-11-18 12_00_48-redmine 500 error](https://cloud.githubusercontent.com/assets/7642828/11239563/214e85a8-8ded-11e5-8423-5091e5ccc232.png)
![2015-11-18 11_59_18-administration - sks-entwicklungs-projektverwaltung _ reklamationsbearbeitung](https://cloud.githubusercontent.com/assets/7642828/11239562/214bf1bc-8ded-11e5-8cca-1db1f556258c.png)

**Comment by KueWW** [comment]
Hi there,

you were right! It seems to be a problem with the ssh keys.
So, I will fix that.

Thank you very much!

**Comment by KueWW** [comment]
It works!!!
Thank you very, very much!!!
