### ISSUE TITLE
Cannot create new repo

### ISSUE THREAD

**Issue by modprobe** [jbox-web/redmine_git_hosting#537]
I cannot create a new repo. The existing repo in the project is of the type "Gitolite" (seems reasonable), but if I try to create one, it only lets me chose the type "Git", for which I have to create a bare repo manually.

`production.log` and `git_hosting.log` show no errors or exceptions, and all existing repos work properly and as expected. I don't really know where to begin looking for this.

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/get_started/#step-9-finish-installation---configuration :

> Enable Xitolite repositories in Administration -> Settings -> Repositories
