### ISSUE TITLE
Just watch repos

### ISSUE THREAD

**Issue by bes1002t** [jbox-web/redmine_git_hosting#538]
Hi, 

is it possible to access a repository but don't allow that user to commit to this repository?
e.g. I want a user to look at my sourcecode so he should be able to checkout it, maybe in eclipse or something, but I don't want to allow this user to send commits to my repository.
I can't find a specific permission in role permissions configuration. Don't know whether it's possible now or this should be considered as a enhancement

thanks

**Comment by n-rodriguez** [comment]
> is it possible to access a repository but don't allow that user to commit to this repository?

Yes you can. 

> I can't find a specific permission in role permissions configuration.

Look better ;) You have a ```commit``` permission in Repository section.
