### ISSUE TITLE
My Account link to public keys does not work

### ISSUE THREAD

**Issue by bes1002t** [jbox-web/redmine_git_hosting#539]
Hi,

I'm running Redmine 3.0.2.stable and redmine_git_hosting 1.1.4. My Problem is, that I've installed redmine in a subdirectory named redmine. Well, all other buttons and links are working, just the link to my public keys for gitolite ssh access won't work. 

Normal link: www.mydomain.com/redmine/my/account
While the link to my public keys looks this way: www.mydomain.com/my/public_keys

I can access the key page anyway by adding the redmine suffix to this url
www.mydomain.com/redmine/my/public_keys

greets

**Comment by n-rodriguez** [comment]
Duplicate : https://github.com/jbox-web/redmine_git_hosting/issues/530

The answer : http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI
