### ISSUE TITLE
Move to original grack 

### ISSUE THREAD

**Issue by mrueg** [jbox-web/redmine_git_hosting#540]
Seems like the origin grack package is developed again.
https://github.com/grackorg/grack

Could you check if it's possible to move the dependency from the gitlab fork to that one?

**Comment by n-rodriguez** [comment]
> Could you check if it's possible to move the dependency from the gitlab fork to that one?

What's the point?

**Comment by mrueg** [comment]
The devs of grack work on a release that can be installed via rubygems. It makes it easier to package it, as right now we need to clone the according branch from github

**Comment by n-rodriguez** [comment]
> It makes it easier to package it, as right now we need to clone the according branch from github

I'm not sure. Actually we need to clone the repo because of a dependency issue :
* https://github.com/jbox-web/grack/commit/0feeaae8036dfe3a56f7bdfaac442ed622c1b7a2
* https://github.com/jbox-web/grack/commit/1bc51d833970d8544790198cc1d75310dd835175

**Comment by baby-gnu** [comment]
The plugin may be updated to latest https://github.com/gitlabhq/grack (as found in #568)

**Comment by n-rodriguez** [comment]
Done : https://github.com/jbox-web/redmine_git_hosting/commit/927f984b4b56a5b3af40c866a7cd4107775c6974
