### ISSUE TITLE
SSH/Gitolite server host on 1.2

### ISSUE THREAD

**Issue by madorin** [jbox-web/redmine_git_hosting#541]
Hello,

After successful upgrade to 1.2, pressing in Config [Apply] button it says that "SSH/Gitolite server host" is invalid (it is set to default value as "localhost"). Setting it to 127.0.0.1, config was accepted.
It seems that it accepts IPs only, strange. Tried with different values, IPs and hostnames.

Thanks!

**Comment by dgeo** [comment]
Same here: I looked in the code, and it MUST be an IP(v4) address. Dunno if the code have to be changed here (I'd prefer) to accept hostnames, or if admin interface should precise 'SSH/Gitolite server IP(v4)' …
My 2 cts…

**Comment by n-rodriguez** [comment]
> Same here: I looked in the code, and it MUST be an IP(v4) address. Dunno if the code have to be changed here (I'd prefer) to accept hostnames, or if admin interface should precise 'SSH/Gitolite server IP(v4)' …

Yep. I chose to fill the field with an IP because of :
* validation (easier to valid an IP adress than a domain name)
* there is no vhost concept in SSH so domain is useless

**Comment by madorin** [comment]
I think it should accept host names beside of IPs.
It give more flexibility, especially on changes, migrations.
SSH connect functions require "host" parameter. It can be an IP or a NAME.
Also, why limit it just to IPv4? v6 is much closer than it looks ;)

**Comment by n-rodriguez** [comment]
> I think it should accept host names beside of IPs.

Well this sounds difficult as '12345.36.70.fr' is a valid hostname and an invalid IPv4 or IPv6.
I think I'm gonna rollback to hostname and only hostname.
