### ISSUE TITLE
Gitolite local code dir can't be blank

### ISSUE THREAD

**Issue by LoriKarikari** [jbox-web/redmine_git_hosting#543]
After the installation of the plugin I edited the public and private key locations and several other settings successfully. Now I want to change the 'SSH server domain' and 'HTTP server domai'n at the 'Access tab' but when I click on 'Apply' I get this error shown below.

![selection_093](https://cloud.githubusercontent.com/assets/7902980/11456320/1cc83744-9686-11e5-842e-00c8986a49f9.png)

I can't seem to find the setting for 'local code dir'.
Thanks in advance

**Comment by LoriKarikari** [comment]
Never mind. I figured I had to configure the 'Gitolite non-core hooks directory'. The error message is a bit unclear though.

![selection_001](https://cloud.githubusercontent.com/assets/7902980/11456591/3b402dd2-968e-11e5-802e-0869479054aa.png)

**Comment by acosonic** [comment]
Hm, how did you fix it...?

**Comment by acosonic** [comment]
I fixed it also, forgot to run rake redmine:plugins:migrate RAILS_ENV=production and after that I re-installed hooks, now everything is OK...
