### ISSUE TITLE
Cannot connect to repository through SSH (public key)

### ISSUE THREAD

**Issue by LoriKarikari** [jbox-web/redmine_git_hosting#548]
Hi

I have some users who are in the same group with the same permissions. They have uploaded a public key on Redmine. Some are able to connect to the repository and some are not. I get this error: "Permission denied (publickey).fatal: Could not read from remote repository." The process of generating and adding the keys was identical for all the users. I also have another server with Jenkins CI which cannot access the repos with the same error. All the keys are in conf/keydir and in the gitolite.conf file I can see the usernames with the right permissions. I also deleted users completely on Redmine and re-added them but the error persists. And I re-synced everything and flushed the cache.

**Comment by n-rodriguez** [comment]
> Permission denied (publickey).fatal: Could not read from remote repository.

Check in the ```gitolite.conf```file that users are present and associated with the right repo.

**Comment by LoriKarikari** [comment]
The users are present in gitolite.conf and have RW+ permissions. Also the keys are in the keydir directory.

**Comment by bes1002t** [comment]
Maybe they pasted a corrupt key?!

Sometimes people don't paste the whole key

**Comment by n-rodriguez** [comment]
@bes1002t SSH keys are validated before being saved to db.

@LoriKarikari : clone the Gitolite admin repo by hand and compare it with the one in Redmine Git Hosting temp dir. Also check the Gitolite logs.

**Comment by kovalevvv** [comment]
i have same problem
keys present in keydir, but gitolite.conf not have configuration for keys (only redmine users for https access), v.1.2.0
i'am upgraded from 1.1.0, after version worked fine for ssh keys, but not worked for protected branches.. =(
