### ISSUE TITLE
Add dynamically branch and commit number to post receive URLs

### ISSUE THREAD

**Issue by VoidAndAny** [jbox-web/redmine_git_hosting#550]
Is it possible to define post receive URL, like this : 
```
/webhook/git/xxx?branch=<branch>&commit=<commit> 
```

And let redmine git hosting plugin replace branch and commit keywords with the current branch and commit ?
For your information I try to use Redmine + Redmine Git Hosting + PHPCI .
The PHPCI code which handle web hook request is here : 
https://github.com/Block8/PHPCI/blob/1385379f1a63e7bbf228e51f32470b94fb5c7dcb/PHPCI/Controller/WebhookController.php#L119

PHPCI can also handle message and committer.

**Comment by n-rodriguez** [comment]
> Is it possible to define post receive URL, like this :

What for? Why not use PostReceivedUrls to handle this?

**Comment by VoidAndAny** [comment]
I want to use PostReceivedUrls, but how can I define branch/commit number keyword in URL to be replaced by git hosting plugin when the link is called ?

**Comment by n-rodriguez** [comment]
PostReceivedUrls send a payload like this [one](https://github.com/jbox-web/redmine_git_hosting/blob/devel/spec/fixtures/master_payload.yml) to the called url.
