### ISSUE TITLE
NameError (uninitialized constant RedmineGitHosting::GitoliteAccessor::GithostingShellWorker)

### ISSUE THREAD

**Issue by elbertcastaneda** [jbox-web/redmine_git_hosting#551]
When i activate any these options in the "Rescue tab":
* Resync all projects ?
* Resync all SSH keys ?
* Flush Git Cache?

**In the "Config Tab" everything is fine.**

I am getting this error in the production.log.
<pre>
Completed 200 OK in 3066ms (Views: 0.6ms | ActiveRecord: 1.3ms)
Started POST "/settings/plugin/redmine_git_hosting" for 187.189.155.18 at 2015-12-11 02:16:41 -0600
Processing by SettingsController#plugin as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"FKQAyJ6asHDKw6pc5E5Ps605ZpO6QrnI/6IyaQH8gq6rIUo7CykwZK599YGP6HR5mDyrDRUuXJjYK9ZpUP07wQ==", "settings"=>{"gitolite_user"=>"git", "gitolite_ssh_private_key"=>"/srv/www/rails_apps/sbx_retail_redmine/ssh_keys/redmine_gitolite_admin_id_rsa", "gitolite_ssh_public_key"=>"/srv/www/rails_apps/sbx_retail_redmine/ssh_keys/redmine_gitolite_admin_id_rsa.pub", "gitolite_server_host"=>"127.0.0.1", "gitolite_server_port"=>"22", "gitolite_global_storage_dir"=>"repositories/", "gitolite_recycle_bin_dir"=>"recycle_bin/", "gitolite_redmine_storage_dir"=>"_redmine/", "gitolite_local_code_dir"=>"_noncore_hooks/", "gitolite_lib_dir"=>"bin/lib/", "gitolite_config_file"=>"gitolite.conf", "gitolite_identifier_prefix"=>"redmine_", "gitolite_identifier_strip_user_id"=>"true", "gitolite_temp_dir"=>"/tmp/redmine_git_hosting/", "gitolite_recycle_bin_expiration_time"=>"24.0", "gitolite_log_level"=>"info", "git_config_username"=>"SBX Retail Git Server", "git_config_email"=>"git@sbxretail.com", "ssh_server_domain"=>"git.sbxretail.com", "http_server_domain"=>"redmine.sbxretail.com", "https_server_domain"=>"redmine.sbxretail.com", "http_server_subdir"=>"", "gitolite_http_by_default"=>"1", "show_repositories_url"=>"true", "gitolite_daemon_by_default"=>"true", "download_revision_enabled"=>"true", "gitolite_overwrite_existing_hooks"=>"true", "gitolite_hooks_are_asynchronous"=>"true", "gitolite_hooks_debug"=>"true", "gitolite_hooks_url"=>"https://redmine.sbxretail.com", "gitolite_cache_max_time"=>"86400", "gitolite_cache_max_size"=>"16", "gitolite_cache_max_elements"=>"2000", "gitolite_cache_adapter"=>"database", "gitolite_notify_by_default"=>"false", "gitolite_notify_global_prefix"=>"[REDMINE]", "gitolite_notify_global_sender_address"=>"redmine@example.net", "gitolite_notify_global_include"=>[""], "gitolite_notify_global_exclude"=>[""], "redmine_has_rw_access_on_all_repos"=>"true", "all_projects_use_git"=>"true", "init_repositories_on_create"=>"true", "delete_git_repositories"=>"true", "hierarchical_organisation"=>"true", "gitolite_use_sidekiq"=>"true", "rescue"=>{"resync_all_projects"=>"true", "resync_all_ssh_keys"=>"true", "flush_gitolite_cache"=>"true"}}, "commit"=>"Apply", "id"=>"redmine_git_hosting"}
  Current user: elbert (id=1)
Completed 500 Internal Server Error in 21ms (ActiveRecord: 4.6ms)

NameError (uninitialized constant RedmineGitHosting::GitoliteAccessor::GithostingShellWorker):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
</pre>

**Comment by elbertcastaneda** [comment]
The problem is the "Sidekiq" option, am sorry.

**Comment by Eredin** [comment]
I get this when I hit "apply" on every git_hosting plugin tab. If you know the cause, Does that mean there's a workaround or manual fix we can apply ourselves?

**Comment by n-rodriguez** [comment]
What is your plugin version?

**Comment by Eredin** [comment]
I'm sorry, I should have included that up front. Here is the whole env
listing :

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem
  Xitolite                       1.9.1
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_code_review            0.7.0
  redmine_git_hosting            1.2.0


Thank you!

**Comment by n-rodriguez** [comment]
Ok. You forgot to install ```redmine_sidekiq``` plugin : http://redmine-git-hosting.io/how-to/use-sidekiq-mode/

**Comment by Eredin** [comment]
I'm sorry, we upgraded from a working 1.x version of git_hosting using the
instructions here : http://redmine-git-hosting.io/how-to/upgrade/ which
made no mention of that requirement. We don't intend to use that if it is
an option. Is its installation a requirement or can we simply configure it
off somewhere that I overlooked?

Thank you!

**Comment by Eredin** [comment]
I have setup a fresh redmine environment on a newly installed machine, and
confirmed that with only the bootstrap and git-hosting 1.1.5 plugins
installed the sidekiq plugin is not necessary if the sidekiq feature is
configured off. only when I upgrade to 1.2.0 does it become necessary, even
when it is configured off; This seems like it can't possibly be what you
intended ?

Please advise ?

Thanks!
