### ISSUE TITLE
when i remove project in redmine, stop working correctly "redmine_git_hosting"

### ISSUE THREAD

**Issue by elbertcastaneda** [jbox-web/redmine_git_hosting#554]
- I create one project without Repository feature (Parent Project).
- After, i create a second project with repository Feature Flag activated in side of Parent Project.
- I remove the second project.

These are steps for trigger this bugs.

**Comment by bes1002t** [comment]
sorry but can you explain what happens after removing the second project?

**Comment by elbertcastaneda** [comment]
I dont have this problem any more !!!
