### ISSUE TITLE
redmine status afret git push

### ISSUE THREAD

**Issue by grawerpl** [jbox-web/redmine_git_hosting#556]
after 3 days I get plug-in work (the best part is that plug-in need to work properly libssh2-dev on ubuntu).
Now i have issu witch **git push**
```remote:
remote: Notifying Redmine about changes to this repository : 'client-service-app/' ...
remote: /srv/git/local/hooks/common/lib/git_hosting/http_helper.rb:54:in `build_post_request': undefined method `request
_uri' for #<URI::Generic:0x00000001b365e0> (NoMethodError)
remote:         from /srv/git/local/hooks/common/lib/git_hosting/http_helper.rb:10:in `http_post'
remote:         from /srv/git/local/hooks/common/lib/git_hosting/post_receive.rb:33:in `notify_redmine'
remote:         from /srv/git/local/hooks/common/lib/git_hosting/post_receive.rb:19:in `exec'
remote:         from hooks/post-receive:15:in `<main>'
```

The best part is that in repository is everything OK (branch, commits, etc.) but redmine still show old info

oo and i forgot do ass my conf :d 
```Environment:
  Redmine version                3.2.0.devel
  Ruby version                   2.1.7-p400 (2015-08-18) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Bazaar                         2.7.0
  Git                            2.6.4
  Filesystem                     
  Xitolite                       2.6.4
Redmine plugins:
  redmine_agile                  1.3.12
  redmine_banner                 0.1.1
  redmine_bootstrap_kit          0.2.3
  redmine_checklists             3.1.3
  redmine_git_hosting            1.1.4
  redmine_logs                   0.1.0
  redmine_theme_changer          0.2.0
```

**Comment by n-rodriguez** [comment]
> the best part is that plug-in need to work properly libssh2-dev on ubuntu

http://redmine-git-hosting.io/get_started/#step-1-install-dependencies

> The best part is that in repository is everything OK (branch, commits, etc.) but redmine still show old info

This is due to the previous error: hooks are not executed, so Redmine is not called, hence changes are not fetched.

> ```undefined method `request _uri' for #<URI::Generic:0x00000001b365e0> (NoMethodError)```

Check your Ruby version

**Comment by grawerpl** [comment]
my ruby version is shown in previous post  ruby 2.1.7-p400
and still don't know what is wrong. 

i have trued find something in google about request_uri method not defined but still no luck.

**Comment by grawerpl** [comment]
I'm not ruby developer but think this isn't right:
 ```       # Build request
        uri, http = build_http_request(url, opts)
        request = Net::HTTP::Post.new(uri.request_uri)
```
**uri** here isn't defined so method request_uri wont exist. I can be think wrong.

**Comment by n-rodriguez** [comment]
```       
# Build request
**ur**i, http = build_http_request(url, opts)
request = Net::HTTP::Post.new(uri.request_uri)
```

**Comment by grawerpl** [comment]
i don't understand your comment :D

**Comment by n-rodriguez** [comment]
the **uri** variable is returned by the call to ```build_http_request(url, opts)```

**Comment by grawerpl** [comment]
if i understand this code right, it parse url but only http, so where is option to parse https ?

**Comment by n-rodriguez** [comment]
> if i understand this code right, it parse url but only http, so where is option to parse https ?

https://github.com/jbox-web/redmine_git_hosting/blob/devel/contrib/hooks/post-receive/lib/git_hosting_http_helper.rb#L77

**Comment by grawerpl** [comment]
hmm so what about this. maybe url isn't uri bat path ?

**Comment by n-rodriguez** [comment]
Check your hook url in plugin settings.

**Comment by grawerpl** [comment]
Hooks URL `https://localhost/githooks/post-receive/redmine`
Hooks Git namespace `redminegitolite`

**Comment by grawerpl** [comment]
ok i found where is problem.

Hook URL shows what i write above but in reality uses `localhost/githooks/post-receive/redmine`
I found this after reset whole server :D then in field **Hook URL** was only `localhost` and tip `Default: https://localhost` so i changed to right value and now working :p
