### ISSUE TITLE
HTTP_ERROR : Net::OpenTimeout

### ISSUE THREAD

**Issue by basakanupam** [jbox-web/redmine_git_hosting#559]
I am not having proxified network. But in the post receive hook I am getting this error
My ruby version is 2.3.0
redmine _git_hosting_plugin version latest.
## redmine version 3.1.3

Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 271 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)

Notifying Redmine about changes to this repository : 'testproject/testproject-git' ...
HTTP_ERROR : Net::OpenTimeout

Looking for additional global post-receive hooks...
- Global hooks found : ["hooks/post-receive.d/mail_notifications"]

Looking for additional local post-receive hooks...
- No local hooks found

Calling additional post-receive hooks...
- Executing extra hook 'hooks/post-receive.d/mail_notifications'
  multimailhook is disabled

To https://anupam@xxxxxx:3000/testproject/testproject-git.git
   36b66b8..84f9872  master -> master

**Comment by bes1002t** [comment]
seems like your mail_notifications hook is not activated.

**Comment by n-rodriguez** [comment]
Check your hook url in plugin settings. This url must be callable (to check : dns/ip, proxy, firewall, webserver restriction rules, etc...)

**Comment by n-rodriguez** [comment]
Hi! Can you please provide some logs? (from `logs/git_hosting.log`)

**Comment by n-rodriguez** [comment]
Hi there! any news?

**Comment by baby-gnu** [comment]
Hello,

It happens to us too but with `HTTP_ERROR : Net::ReadTimeout`, it seems that sometimes it take times for redmine to process the commit.

To reproduce I just need to:

1. clone a repository
2. create a new `test` branch (it must not exists on remote)
3. make a commit
4. push the new branch

Interestingly, when I make a new commit on `test` and push it, it does not take times. It may be related to branch creation in my case.

I finally increase both timeouts and install the new hooks:

```diff
diff --git a/contrib/hooks/post-receive/lib/git_hosting_http_helper.rb b/contrib/hooks/post-receive/lib/git_hosting_http_helper.rb
index 7caaa16..fe86faa 100644
--- a/contrib/hooks/post-receive/lib/git_hosting_http_helper.rb
+++ b/contrib/hooks/post-receive/lib/git_hosting_http_helper.rb
@@ -76,8 +76,8 @@ module GitHosting
 
       def build_http_request(url, opts = {})
         # Get HTTP options
-        open_timeout = opts.delete(:open_timeout) { 5 }
-        read_timeout = opts.delete(:read_timeout) { 10 }
+        open_timeout = opts.delete(:open_timeout) { 10 }
+        read_timeout = opts.delete(:read_timeout) { 60 }
 
         uri  = URI(url)
         http = Net::HTTP.new(uri.host, uri.port)
```

Regards.
