### ISSUE TITLE
SSH remote: error: hook declined to update refs

### ISSUE THREAD

**Issue by gvandenbosch** [jbox-web/redmine_git_hosting#562]
Hello,

My GIT repo was all working fine. I am running on latest 1.2.0.
Using ssh to push to the GIT repo.

Only since today it says:

    remote: W refs/heads/atheros_wifi chibios/chibi-os redmin_gvandenbosch_5 DENIED by fallthru   
    remote: error hook declined to update refs/heads/atheros_wifi 

I tried re-adding myself to the project, tried all options in the rescue tab in the redmine git hosting settings, rebooted the server but nothing works.

One weird thing I see in the redmine_githosting log is:

     [ERROR] The revision 'core' has a wrong format

Also it is only happening to 1 project, the other projects all still work fine.

Could anyone advice me what to do with this.

Cheers,
Gerard

**Comment by gvandenbosch** [comment]
It seems I found out what is going wrong.

I added Master as a protected branch and when I checked out gitolite-admin I saw in gitolite.conf
RW+ master = user1 user2

But all other users had disappeared and no thereby no access.
Then when I removed the protected branch I got the following again and it started to work again,
RW+ = user1 user2
RW = user3 user4 etc...

How can I prevent people comitting or merging to master but still have commit access to other branches?

**Comment by antuansoft** [comment]
Use protected Branches!!!

![captura1](https://cloud.githubusercontent.com/assets/1808111/12560168/7d41726c-c399-11e5-8651-92d8fe93259c.png)

and use "/master" and denegate accces with "-" to the groups or users.

![captura](https://cloud.githubusercontent.com/assets/1808111/12560254/f9d3f228-c399-11e5-8cec-62eb7c260459.png)


note that if you use protected branches you have to define the access to all the branches for all your groups or users.
