### ISSUE TITLE
Hooks parameter redmineurl not installed

### ISSUE THREAD

**Issue by dimtion** [jbox-web/redmine_git_hosting#565]
I'm having a hard time configuring the plugin.

I've followed the [procedure](http://redmine-git-hosting.io/get_started/) it seems that the hooks are installed but I have a strange message : "hook left untouched".

Here is a screen of the test tab
![Test tab](https://cloud.githubusercontent.com/assets/1964358/12530260/4098ea1e-c1d9-11e5-8a67-78eee392f74f.png)

I know this is not the best place for support, but I haven't found another way.

**Comment by dimtion** [comment]
A little follow up if this can help. 

Our stack : 
 - Redmine 3.2.0
 - Redmine Git Hosting 1.2.0
 - Gitolite v3.6.4
 - Ruby 2.1.5p273

When loading the hooks url `/githooks/post-receive/redmine`  the server respond with a 404. Is it normal ?

**Comment by jblobb** [comment]
Hi @dimtion

It might be as the GUI is broken, try this fix [https://github.com/jbox-web/redmine_git_hosting/issues/567#issuecomment-180162516](url)

**Comment by n-rodriguez** [comment]
> When loading the hooks url /githooks/post-receive/redmine the server respond with a 404. Is it normal ?

This url is only callable by Post with specific parameters, so yes.

> I've followed the procedure it seems that the hooks are installed but I have a strange message : "hook left untouched".

Force hook update in plugin settings.
