### ISSUE TITLE
Redmine Git Hosting Plugin configuration tabs. (Rugged::OdbError - Object not found)

### ISSUE THREAD

**Issue by antuansoft** [jbox-web/redmine_git_hosting#566]
Hi!, everyone

 We have an error when we click in every submit button in the Git Hosting Plugin configuration page.

Redmine 500 error
An error occurred on the page you were trying to access...............

Eveything was working perfecty for 1 moth but we were trying to add new public keys for new users and the errors appears when we tried to Resync all SSH keys.

We have realized that is no possible to add new public keys, all the stored ones works but you can not add new public keys or change the existing ones. 

We appreciate any idea to solve it, or investigate it because all our access policy to the repos are compromised.

We have tried rebooting everything but the error still there, and we have not reinstalled the plugin because all the configuration will be lost. 

Here i show you all the logs, Any ideas?

The production.log shows that:

```
Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_sidekiq_interface.html.haml (1.6ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_test.html.haml (2067.2ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_recycle_bin.html.haml (175.4ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_rescue.html.haml (2.6ms)
  Rendered common/_tabs.html.erb (2590.3ms)
  Rendered plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.haml (2629.1ms)
  Rendered settings/plugin.html.erb within layouts/admin (2652.6ms)
  Rendered admin/_menu.html.erb (4.5ms)
  Rendered layouts/base.html.erb (34.2ms)
Completed 200 OK in 2754ms (Views: 2694.8ms | ActiveRecord: 5.9ms)
Started POST "/settings/plugin/redmine_git_hosting" for 127.0.0.1 at 2016-01-22 17:06:40 +0100
Processing by SettingsController#plugin as HTML

  Parameters: 
  Current user: admin (id=1)
Completed 500 Internal Server Error in 365ms (ActiveRecord: 5.8ms)

**Rugged::OdbError (Object not found - no matching loose object (b37b3122d49d1253d9efb5e42ec90085283e3151)):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'**

Started GET "/settings/plugin/redmine_git_hosting" for 127.0.0.1 at 2016-01-22 17:46:58 +0100
```

We have installed the next versions of redmine and redmine git hosting plugin

```
Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.6.4
  Filesystem                     
  Xitolite                       2.6.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.0
```

The git hosting plugin config test is all green and shows the nexts versions

```
Git version     2.6.4
Gitolite version    3
Count of physical repositories in Gitolite  17
Rugged compiled features    threads ssh https
libgit2 version     0.23.3
```

Thank you so much

**Comment by n-rodriguez** [comment]
Go in Redmine Git Hosting temp dir and run ```git fsck``` **as redmine user**.

**Comment by jblobb** [comment]
@antuansoft can you try the following please?

https://github.com/jbox-web/redmine_git_hosting/issues/567#issuecomment-180162516
