### ISSUE TITLE
Can't add Git Config Key

### ISSUE THREAD

**Issue by bc-23** [jbox-web/redmine_git_hosting#576]
Hi,

when I try to add a Git Config Key, the request results in a 500 Internal Server Error.
In the production.log I see the following error:
```
Completed 500 Internal Server Error in 29ms (ActiveRecord: 12.6ms)
ActiveRecord::SubclassNotFound (Invalid single-table inheritance type: RepositoryGitConfigKey::Config is not a subclass of RepositoryGitConfigKey::GitConfig):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Adding a Gitolite option works without problems.

I'm running redmine 3.2.0 with redmine_git_hosting 1.2.0 and gitolite v3.

**Comment by jjongbloets** [comment]
+1 Same here

Figured there is a name mismatch:

`app/models/repository_git_config_key.rb` uses (line 12):
``` ruby
validates :type,          presence: true, inclusion: { in: ['RepositoryGitConfigKey::GitConfig', 'RepositoryGitConfigKey::Option'] }
```

while in `app/controllers/repository_git_config_keys_controller.rb` it says (line 56):
``` ruby
when 'RepositoryGitConfigKey::Config'
```
and in `app/helpers/repository_git_config_keys_helper.rb`:
``` ruby
def git_config_key_options
    [
      [l(:label_git_key_type_config), 'RepositoryGitConfigKey::Config'],
      [l(:label_git_key_type_option), 'RepositoryGitConfigKey::Option']
    ]
end
```

I was able to fix the issue by changing the latter 2 files.
