### ISSUE TITLE
[bitnami] sudo daemon not redmine

### ISSUE THREAD

**Issue by schotter** [jbox-web/redmine_git_hosting#577]
Hi,
I was playing with the latest virtual machine from bitnami and am mostly interested in the git integration. So I set up a VM, got i running and tried to install this plugin. It kind of worked but not completely. The "Conig Test" page showed me:

> Redmine username  daemon
> Gitolite username     git
> Redmine user is able to sudo to Git user?     No

The manual is always talking about the user redmine, but bitnami is using the user daemon. So I changed /etc/sudoers.d/redmine to

> Defaults:daemon !requiretty
> daemon ALL=(git) NOPASSWD:ALL

but it didn't work :( By chance I found out, if I add these two lines to /etc/sudoers it does. The exclamation mark changes to a check mark :)

I still got plenty of exclamation marks left, hooks aren't working but at least I'm one step further.

Maybe someone can explain why the two lines didn't work in /etc/sudoers.d/redmine.

Kind regards,
thorsten

**Comment by n-rodriguez** [comment]
> Maybe someone can explain why the two lines didn't work in /etc/sudoers.d/redmine.

Because it was not included by `/etc/sudoers`?
