### ISSUE TITLE
Repository changes not shown in Redmine

### ISSUE THREAD

**Issue by irieger** [jbox-web/redmine_git_hosting#578]
I recently set up redmine_git_hosting after having a gitolite run before manually managed with the repos manually linked to Redmine. Now I realised that changes to the repo aren't shown in the projects activity report and not in the commit log in the repository view. Interesting is, that in the file list the last changes are indeed shown with the change time but without a Revision or Comment information.

The log of gitolite says:
```
2016-03-02.20:42:11	28807	ssh	ARGV=redmine_USERNAME_3	SOC=git-receive-pack 'projects/foobar/code.git'	FROM=X.Y.Z.A
2016-03-02.20:42:11	28807	pre_git	projects/foobar/code	redmine_USERNAME_3	W	any	refs/.*
2016-03-02.20:42:11	28807		system,git,shell,-c,git-receive-pack '/home/projects/repositories/projects/foobar/code.git'
2016-03-02.20:42:11	28807	update	projects/foobar/code	redmine_USERNAME_3	W	refs/heads/master	1651bee81c55b47081dadd65dae9346a66941726	1db87f9a115b8f7deaab92b6136fdfcee56eb89b	refs/.*
2016-03-02.20:42:11	28807	END
```

Additionally I have a cron job set up to update repositories every 5 minutes which should also fetch the changes, shouldn't it?  (`redmine  rake -f /srv/rails/redmine/Rakefile RAILS_ENV=production redmine:fetch_changesets`)

Does anybody have an idea or a tip how to fix this or at least debug this further?

Everything else like key management, repo creation etc. runs as expected.

**Comment by l337r007** [comment]
I've been scratching my head about this as well, when it was just a "dumb" user error. For me it didn't work because I had configured the Hooks URL (in the Hooks tab) wrong. The post-receive hook needs to tell redmine to fetch the new changesets after each push.
If you want or need to further investigate, set "Run hooks asynchronously" to no (also in the Hooks tab). Then you'll get whatever error occurs to you `git push` command as a `remote:` output.

HTH

**Comment by irieger** [comment]
I have it on off for asychron execution but I don't get any error. It seems like the repo isn't created with the correct hooks!

**Comment by irieger** [comment]
Adding to the last short comment I checked my nginx logs and found no access to a githooks/post-receive/redmine suburl for redmine. So indeed it seems to not work properly on the hook-side.

**Comment by n-rodriguez** [comment]
You need to set this for hooks to work : http://redmine-git-hosting.io/get_started/#step-5-gitolite-must-accept-hook-keys

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by irieger** [comment]
Ups, just realised I didn't wrote back here. Something with the hooks was wrong. Don't really remember as I fixed it months ago. Thanks for asking.
