### ISSUE TITLE
Ability to select which protocols get displayed for git URLs

### ISSUE THREAD

**Issue by mdovey** [jbox-web/redmine_git_hosting#584]
Whilst the plugin allows you to resort the access URLs (albeit on a repository by repository basis -I can't see how to configure a default ordering), it doesn't appear possible to disable\remove a URL entirely.

The use case in question would be where a firewall prevents ssh traffic so only the smartHTTP(s) URL will work for external users.

**Comment by nO-OnE-910** [comment]
maybe [this](https://github.com/jbox-web/redmine_git_hosting/issues/592#issuecomment-223562457) helps
