### ISSUE TITLE
Cannot delete repositories after restore

### ISSUE THREAD

**Issue by ioiobzit** [jbox-web/redmine_git_hosting#586]
Hi,

I restored a redmine installation, now when I try to delete a repository the page just says:

> Internal error
> 
> An error occurred on the page you were trying to access.
> If you continue to experience problems please contact your Redmine administrator for assistance.
> 
> If you are the Redmine administrator, check your log files for details about the error.
> 
> Back

What can I check?

Thanks

**Comment by ioiobzit** [comment]
The errore message from production.log

`Started DELETE "/repositories/27" for 127.0.0.1 at 2016-03-31 09:33:16 +0200
Processing by RepositoriesController#destroy as HTML
  Parameters: {"authenticity_token"=>"nqhXQoGZrBmoHKr4BkoR16nntgFCesMnrwZkNcECH2M7Y244QoFqnGrlaWWME3fWr1JoUhldVvMRKI8LYbX0tA==", "id"=>"27"}
  Current user: antonio (id=5)
Completed 500 Internal Server Error in 54ms (ActiveRecord: 40.3ms)`

**Comment by ioiobzit** [comment]
Here after other tries `Started DELETE "/repositories/26" for 127.0.0.1 at 2016-03-31 10:49:55 +0200
Processing by RepositoriesController#destroy as HTML
  Parameters: {"authenticity_token"=>"9L+F5ICGgKi4XEPbCLGYmUmhcU2LnyLIjVb43sSq11fbPpsWw9IbJvTgfacy9maMVElJGcOgOCOJBJbuEJ7BGQ==", "id"=>"26"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 35ms (ActiveRecord: 18.5ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'redmine.repository_git_notifications' doesn't exist: SHOW FULL FIELDS FROM `repository_git_notif
ications`):
  app/controllers/repositories_controller.rb:109:in `destroy'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
`

Anyone knows what I did wrong? Thanks..

**Comment by ioiobzit** [comment]
When I try to clone a repository this error comes up:

`Cloning into 'testrepodel'...
FATAL: R any redmine/redmine/testrepodel id_rsa DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by floSoX** [comment]
Hi @ioiobzit,

We had the same problem, this table was not in our database. We don't know why.
I hope you found a solution. If not and for others, please find the solution we came up with.

 Create file **create_repository_git_notifications.sql** with this content :

``` sql
---
-- Table structure for table `repository_git_notifications`
--

DROP TABLE IF EXISTS `repository_git_notifications`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `repository_git_notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `repository_id` int(11) DEFAULT NULL,
  `include_list` text,
  `exclude_list` text,
  `prefix` varchar(255) DEFAULT NULL,
  `sender_address` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
```

Add this table to your MySQL database :
`redmine$ mysql -u redmine -p redmine < create_repository_git_notifications.sql`

Apply plugin migration command:
`redmine$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting`

**Comment by n-rodriguez** [comment]
> We had the same problem, this table was not in our database. We don't know why.

Because you're on devel branch...

**Comment by floSoX** [comment]
Yes, we were.
But we migrated to the v1.2.1 and this table still absent.

**Comment by n-rodriguez** [comment]
This is normal, this table has been removed in devel branch.

**Comment by floSoX** [comment]
OK.
Thank you for your reactivity and your work.

**Comment by nO-OnE-910** [comment]
I have the same problem, table does not exist, deleting repo results in error 500.

I dont fully get what being on devel means? I checked out version 1.2.2
