### ISSUE TITLE
github sync 

### ISSUE THREAD

**Issue by mdovey** [jbox-web/redmine_git_hosting#588]
There seems to be a lack of documenation on setting up github issue sync so these may be mistakes in my setup.

i) Additional comments made to the github issue are not synced with the redmine issues - I had expected these to show up as additional notes

ii) It would be useful if there was some way of identifying an redmine issue as having originated from github - for example by including a link to the original github issue

**Comment by n-rodriguez** [comment]
Hi! 

> Additional comments made to the github issue are not synced with the redmine issues - I had expected these to show up as additional notes

It's the case : https://github.com/jbox-web/redmine_git_hosting/blob/devel/app/models/github_comment.rb. Did you select `comments` event in Github?

> It would be useful if there was some way of identifying an redmine issue as having originated from github - for example by including a link to the original github issue

Sure!

**Comment by mdovey** [comment]
There appears to be a bug in the sync script which prevents comments being synced (at least against my working environment
  Redmine version                3.2.1.stable
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5.2

I've posted a fix plus some other enhancements at pull request #596

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
