### ISSUE TITLE
Redmine gitolite doesn't synchronize with my local gitolite

### ISSUE THREAD

**Issue by hamdijmii1992** [jbox-web/redmine_git_hosting#590]
After installing redmine git plugin correctly,I added a repo to my projects on gitolite,but when i update my git repositories ,my redmine doesn't trigger this modification 
Please help me.
If anyone need more information to help me ,just tell me what kind of information it needed

**Comment by fizista** [comment]
Try to manually download the changes:

bundle exec rake redmine_git_hosting:fetch_changesets RAILS_ENV=production

for me it helped solve the problem.

It is possible that reason was not installed hooks. I installed it after creating repositories.

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/get_started/#step-9-finish-installation---configuration

In Administration -> Settings -> Repositories -> Hooks tab, you have a link 'Install hooks', click on it.
