### ISSUE TITLE
Permit to disable GO url

### ISSUE THREAD

**Issue by baby-gnu** [jbox-web/redmine_git_hosting#592]
Hello,

I install a new redmine 3.2.1 with redmine_git_hosting 1.2.0 for test and I would like to hide the `GO` URL.

It looks like it's enabled automatically with SmartHTTP.

**Comment by mdovey** [comment]
See also #584 - it would be useful to be able to control which URLs get displayed

**Comment by nO-OnE-910** [comment]
You can comment out the line `hash[:go]        = go_access if go_access_available?` in `.../redmine_git_hosting/app/models/concerns/gitolitable/urls.rb`

**Comment by n-rodriguez** [comment]
Close it as it duplicates https://github.com/jbox-web/redmine_git_hosting/issues/584
