### ISSUE TITLE
can't create any repository +  Gitolite version :	Unknown version

### ISSUE THREAD

**Issue by ahmedosama80** [jbox-web/redmine_git_hosting#595]
dears
i tried so hard so solve this issue , kindly try to help me , thanks alll

my system  bitnami redmine stack (mysql+apache+passenger ) on ec2 amazon server

Redmine Bootstrap Kit plugin Nicolas Rodriguez  0.2.4  
Redmine Git Hosting Plugin 1.2.0

important note
![00](https://cloud.githubusercontent.com/assets/4008100/14828869/1e59c5d6-0be9-11e6-9ba8-401017a3c1be.jpg)
![02](https://cloud.githubusercontent.com/assets/4008100/14828870/1e5b4492-0be9-11e6-99a5-5e9daa115087.jpg)
![03](https://cloud.githubusercontent.com/assets/4008100/14828871/1e5c652a-0be9-11e6-98a6-bedd40695910.jpg)
![04](https://cloud.githubusercontent.com/assets/4008100/14828872/1e5e5146-0be9-11e6-91d8-eb2b9466866e.jpg)
![05](https://cloud.githubusercontent.com/assets/4008100/14828873/1e64154a-0be9-11e6-9293-2881f6702be1.jpg)
![06](https://cloud.githubusercontent.com/assets/4008100/14828874/1e657f8e-0be9-11e6-9ca3-10c4bd619ab4.jpg)
![07](https://cloud.githubusercontent.com/assets/4008100/14828875/1e80b182-0be9-11e6-974f-6bd2ee77570d.jpg)
![08](https://cloud.githubusercontent.com/assets/4008100/14828876/1e865b14-0be9-11e6-86fc-91302a320ba6.jpg)
![09](https://cloud.githubusercontent.com/assets/4008100/14828877/1e8c52da-0be9-11e6-9d51-27d84291e98f.jpg)

 :  redmine path :   myip/redmine

the problems:
1-  can't create any repository from the redmine git hosting plugin  

2- the tmp gitolite-admin repo which should be created by the plugin never created , i have created it 

3- Gitolite version :   Unknown version

4- Count of physical repositories in Gitolite   This is Gitolite v2, not implemented...

some logs

[INFO] User 'user' has created a new repository 'proj3/testtestrep'
[ERROR] Invalid Gitolite Admin SSH Keys
[ERROR] Failed to authenticate SSH session: Callback returned error

Invalid Gitolite Admin SSH Keys
 [ERROR] Failed to authenticate SSH session: Callback returned error
 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/proj3/testoo.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
[ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/proj3/testoo.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
[ERROR] Error while getting Gitolite infos, check your SSH keys (path, permissions) or your Git user.
[INFO] Testing if Redmine user 'daemon' can sudo to Gitolite user 'git'...
 [INFO] OK!

my system

26-04-2016

OS version:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

Bash version:
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

Perl Version:

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Apache Version:
Server version: Apache/2.4.18 (Unix)
Server built:   Mar  3 2016 01:25:19

MySQL Version:
/opt/bitnami/mysql/bin/mysql.bin  Ver 14.14 Distrib 5.6.29, for linux-glibc2.5 (x86_64) using  EditLine wrapper

OpenSSL Version:
OpenSSL 1.0.2g  1 Mar 2016

Git Version:
git version 2.6.1

Gitolite Version:
2016-02-20  v3.6.5  allow creator check to be bypassed during mirroring

Ruby version:
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]

passenger  version:
Phusion Passenger version 5.0.6 "Phusion Passenger" is a trademark of Hongli Lai & Ninh Bui.

Bitnami  version:
Version 3.2.1-0      2016-03-16

Redmine version:
== 2016-03-13 v3.2.1

my testing

gitolite : is working fine i have tried it using the same keys of redmine from inside bitnami account and from external 

gitolite sshkeys-lint
git@ip-172-31-44-56:~$ gitolite sshkeys-lint
sshkeys-lint: ==== checking authkeys file:
ssh-keygen: /opt/bitnami/common/lib/libcrypto.so.1.0.0: no version information available (required by ssh-keygen)
ssh-keygen: /opt/bitnami/common/lib/libcrypto.so.1.0.0: no version information available (required by ssh-keygen)
sshkeys-lint: ==== checking pubkeys:
ssh-keygen: /opt/bitnami/common/lib/libcrypto.so.1.0.0: no version information available (required by ssh-keygen)
ssh-keygen: /opt/bitnami/common/lib/libcrypto.so.1.0.0: no version information available (required by ssh-keygen)
sshkeys-lint: redmine_gitolite_admin_id_rsa.pub maps to user redmine_gitolite_admin_id_rsa

bitnami@ip-172-31-44-56:~$ ssh git@localhost info
hello redmine_gitolite_admin_id_rsa, this is git@ip-172-31-44-56 running gitolite3 v3.6.5-4-g6ed0156-dt on git 2.6.1

 R W    gitolite-admin
 R W    testRepo5
 R W    testing

bitnami@ip-172-31-44-56:/opt/bitnami/apps/redmine/htdocs/plugins/redmine_git_hosting$ ssh -i ssh_keys/redmine_gitolite_admin_id_rsa  git@localhost info
hello redmine_gitolite_admin_id_rsa, this is git@ip-172-31-44-56 running gitolite3 v3.6.5-4-g6ed0156-dt on git 2.6.1

 R W    gitolite-admin
 R W    testRepo5
 R W    testing

bitnami@ip-172-31-44-56:/tmp/test$ git clone git@localhost:gitolite-admin
Cloning into 'gitolite-admin'...
ssh: /opt/bitnami/common/lib/libcrypto.so.1.0.0: no version information available (required by ssh)
ssh: /opt/bitnami/common/lib/libcrypto.so.1.0.0: no version information available (required by ssh)
remote: Counting objects: 27, done.
remote: Compressing objects: 100% (23/23), done.
Receiving objects: 100% (27/27), 4.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4/4), done.
remote: Total 27 (delta 4), reused 0 (delta 0)
Checking connectivity... done.

bitnami@ip-172-31-44-56:/tmp/test/gitolite-admin$ ls
conf  keydir

after ssh wrapper
$ sudo mv /usr/bin/ssh /usr/bin/ssh.bin
$ sudo nano /usr/bin/ssh
# !/bin/bash

export LD_LIBRARY_PATH=""
exec /usr/bin/ssh.bin "$@"

$ chmod 755 /usr/bin/ssh

bitnami@ip-172-31-44-56:/tmp/test$ git clone git@localhost:gitolite-admin
Cloning into 'gitolite-admin'...
remote: Counting objects: 27, done.
remote: Compressing objects: 100% (23/23), done.
Receiving objects: 100% (27/27), 4.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4/4), done.
remote: Total 27 (delta 4), reused 0 (delta 0)
Checking connectivity... done.

![redmine git hosting plugin - plugins - redmine 2016-04-26 19-30-23](https://cloud.githubusercontent.com/assets/4008100/14828499/7cebea0e-0be7-11e6-937a-0ac60be30fe7.jpg)

**Comment by joanmarcriera** [comment]
I have a similar situation, 

I keep getting the following lines but no repo created. 

redmine@redmine ~]$ tail -f log/git_hosting.log 
2016-10-12 15:16:35 +0100 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/redmine-managed-repos/test5.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2016-10-12 15:16:35 +0100 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/redmine-managed-repos/test5.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2016-10-12 15:16:46 +0100 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/redmine-managed-repos/test5.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2016-10-12 15:16:46 +0100 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/redmine-managed-repos/test5.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2016-10-12 15:17:25 +0100 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/redmine-managed-repos/test5.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2016-10-12 15:17:25 +0100 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/redmine-managed-repos/test5.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2016-10-12 15:17:30 +0100 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/redmine-managed-repos/test5.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
2016-10-12 15:17:30 +0100 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/redmine-managed-repos/test5.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'

**Comment by joanmarcriera** [comment]
I forgot to add my environment info:

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
  Xitolite                       1.8.3.1
Redmine plugins:
  clipboard_image_paste          1.10
  progressive_projects_list      3.0.1
  redmine_agile                  1.4.1
  redmine_bootstrap_kit          0.2.4
  redmine_checklists             3.1.5
  redmine_git_hosting            1.2.1
  redmine_monitoring_controlling 0.1.1
  redmine_sidekiq                2.1.0
  redmine_tweaks                 0.5.9-dev
  scrum                          0.15.0
  sidebar_hide                   0.0.7


![image](https://cloud.githubusercontent.com/assets/402036/19313711/6ade9852-908f-11e6-8a1e-571997852867.png)

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/get_started/#step-7-add-gitolite-server-in-knownhosts-list

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/how-to/install-on-bitnami/
