### ISSUE TITLE
After upgrade from .7, ssh keys in multiple places

### ISSUE THREAD

**Issue by jdkoelsch** [jbox-web/redmine_git_hosting#597]
I upgraded the plugin over the weekend, and everything has gone well except for the following: for a subset of Redmine users, their public keys are added to the top level keydir directory AND also in the redmine_git_hosting subdirectory.

I have deleted the keys from the top level keydir both in the /tmp/redmine_git_hosting/git/gitolite-admin.git/keydir and in the gitolite/keydir directory, but when I flush the Git Cache, they are regenerated. I also deleted the /tmp/redmine_git_hosting directory and had the plugin regenerate it, but the same thing happened. 

I also had one of these three people that this is happening to delete their key from Redmine and re-add it. No dice.

I don't see anything in the plugin config that would cause this, and it is only happening for three people out of about 20. Any ideas?

**Comment by jdkoelsch** [comment]
I have deleted one user's key entirely from his user profile, regenerate keys, and they are back! I searched for the keys on the server, and can only find them in the gitolite directory and the tmp directory. I dumped the Redmine sql database, and searched for them there and didn't find anything. 

I don't get it -- once removed from the user, they shouldn't exist anywhere on the server. How do they keep coming back?

**Comment by jdkoelsch** [comment]
So, it was in the gitolite-admin.git repo. I deleted the keys and committed the changes, and voila! No more duplicate keys.

I am leaving this open, because I don't know why the git repo didn't change appropriately during the migration. Or perhaps there is a step missing from the migration instructions? Do you normally need to commit changes to the repo? But, my issue is solved so if you would like to close, please feel free. Thank you!

**Comment by medfreeman** [comment]
I got exactly the same problem, except that it happens for all users, and after deleting keys and commiting the changes to gitolite-admin repo, all works well until a setting regarding redmine_git_hosting is changed from redmine, and the repo consequently updated.
I then do a pull or new clone of gitolite-admin on my local machine, and see all the keys and duplicates regenerated.

**Comment by medfreeman** [comment]
They are all listed in [GITOLITE_HOME]/.ssh/authorized_keys, thus preventing access to all repositories to specific users (the ones that got the old format public keys listed before the new format in authorized_keys).

**Comment by medfreeman** [comment]
Looks like #170, #460. No proposed fix does the job for me.

**Comment by medfreeman** [comment]
It seems that executing ```RAILS_ENV=production rake redmine_git_hosting:regenerate_ssh_keys``` did the job.

**Comment by baby-gnu** [comment]
I think it was related to #619.

Regards.

**Comment by nerd-rider** [comment]
Same Problem here after Update from 0.7 to 1.2.1.
No proposed fix works. Manual delete from gitolite-admin repo works until membership settings in redmine are changed. Then all old keys reapear again. I cannot find the key-names in redmine db or anywhere else. I think redmine must be generating them when i change membership settings of a project.
Help :-(
