### ISSUE TITLE
http error when attempting to push to remote repository

### ISSUE THREAD

**Issue by exponentus** [jbox-web/redmine_git_hosting#598]
When attempting to push from local to remite repository, the following error comes up.

`HTTP_ERROR : Address family not supported by protocol - socket(2) for "localhost" port 3000`

The full verbose shown at the command line prompt shows as follows.

```
user@machine ~/D/rtvn-joomla-component-to-collect-leads> git push -u origin master
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 243 bytes | 0 bytes/s, done.
Total 2 (delta 0), reused 0 (delta 0)

Notifying Redmine about changes to this repository : 'rtvn-joomla-component-to-collect-leads/' ...
HTTP_ERROR : Address family not supported by protocol - socket(2) for "localhost" port 3000

Looking for additional global post-receive hooks...
  - Global hooks found : ["hooks/post-receive.d/mail_notifications"]

Looking for additional local post-receive hooks...
  - No local hooks found

Calling additional post-receive hooks...
  - Executing extra hook 'hooks/post-receive.d/mail_notifications'
    multimailhook is disabled

To https://user:pass@domain.tld/rtvn-joomla-component-to-collect-leads.git
   5883232..d29bd65  master -> master
Branch master set up to track remote branch master from origin.

```

I'm not sure if the error in question is preventing the successful completion of the operation, but the fact of the matter is that the 2 files added to the local copy do not upload to the remote repository and therefore the plugin does not show any files on the Repository tab.

**Comment by exponentus** [comment]
Sorted.

Running 

ruby bin/rails server -e production -b 127.0.0.1

from the redmine root dir did the trick.

**Comment by n-rodriguez** [comment]
Hi! check your `/etc/hosts` file ;)
