### ISSUE TITLE
Creating a new repo launches a shit-ton of unnecessary jobs.

### ISSUE THREAD

**Issue by SimonPe** [jbox-web/redmine_git_hosting#599]
When I create e new  project with a repo, and let it inherit users, A lot of update_project jobs get queued, these are all identical, and just end up doing empty commits in the gitolite repo.
This is so bad that it takes more than half an hour for just creating a project with a repo.

There are multiple issues here:

1. For every user added to a project upon project creation an update_projects job is launched
2. update_projects still does stuff if the project doesn't have any repo's (yet, the repo creation job ends up in the tail of the queue)
3. In general duplicated jobs should be avoided.

This is a screenshot from our sidekiq after creating a project.
![screenshot from 2016-05-05 23-42-46](https://cloud.githubusercontent.com/assets/595410/15059532/815489c8-1323-11e6-8e1f-53fe7d84b453.png)

**Comment by n-rodriguez** [comment]
Merged!
