### ISSUE TITLE
Error when i tried to set configuration or create repository

### ISSUE THREAD

**Issue by ydeeps** [jbox-web/redmine_git_hosting#607]
Hello,

Sorry for my english,

Distrib : Gentoo
Redmine : 3.2.1
Gitolite-gentoo : 2.3.1-r1 (i have same problem with gitolite 3.6.3)
Redmine_git_hosting : 1.2.0

When i tried to set redmine_git_hosting plugin configuration (Administration -> Plugins -> redmine_git_hosting) I have 
```
Internal server error : NameError (uninitialized constant PluginSettingsValidation::SshConfig::Resolv):
  plugins/redmine_git_hosting/app/forms/plugin_settings_validation/ssh_config.rb:23:in `block in <module:SshConfig>'
  plugins/redmine_git_hosting/app/forms/plugin_settings_form.rb:28:in`include'
  plugins/redmine_git_hosting/app/forms/plugin_settings_form.rb:28:in `<class:PluginSettingsForm>'
  plugins/redmine_git_hosting/app/forms/plugin_settings_form.rb:1:in`<top (required)>'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/settings_controller_patch.rb:55:in `handle_settings_update'
  plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/settings_controller_patch.rb:41:in`plugin_with_git_hosting'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

And, when i create repository, it doesn't appears in /var/lib/gitolite/repositories/ but it's visible on redmine GUI.

Can you please help me ?

**Comment by n-rodriguez** [comment]
Hi! This is fixed in 1.2.1 release. Btw `Resolv` is from the standard Ruby library (https://ruby-doc.org/stdlib-2.3.0/libdoc/resolv/rdoc/Resolv/IPv4.html). You're on Gentoo so maybe you should check your compilation option, it might be useful elsewhere.
