### ISSUE TITLE
multiple redmine instance with one git user (one gitolite server) problems

### ISSUE THREAD

**Issue by ahmedosama80** [jbox-web/redmine_git_hosting#608]
dears
now i have a multiple redmine instance with one git user (one gitolite server) , i am facing two main problems
1- when i am adding a new repo. from one redmine instance , it deletes the other repo. entries which belongs to the other instances (from gitolite.conf file)
2- Hooks are not working and not stable (some times working ) , redmine didn't fetch changes for new repo. execept when i run the manual fetchchange bundle ..... at least once

could any one give me some checks to check it ??

thanks all

**Comment by baby-gnu** [comment]
Hello,

I never tried this, but I think you may want to modify the configuration to differenciate both redmine instances:

* split the configuration in different files, see `Configururation file` → `Gitolite configuration file`, for example, you have a master `gitolite.conf` file which include:
  * `redmine1.conf` for the first redmine
  * `redimne2.conf` for the second redmine
* you can set different `Configururation file` → `Gitolite prefix` to avoid key name collision:
* you can set different `Storage` → `Subdirectory for Redmine-managed repositories` to avoid repository name collision:
  * `redmine1` for the first, which stores repositories under `$(gitolite query-rc GL_REPO_BASE)/redmine1`
  * `redmine2` for the second, which stores repositories under `$(gitolite query-rc GL_REPO_BASE)/redmine2`

Regards.

**Comment by baby-gnu** [comment]
Hello @ahmedosama80.

Do you have any news on this? Did you manage to make it working?

Regards.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
