### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by madorin** [jbox-web/redmine_git_hosting#609]
Hi Nicolas,

We have troubles with git email notifications.

Error message on commit is:

Calling additional post-receive hooks...
- Executing extra hook 'hooks/post-receive.d/mail_notifications'
  remote: **\* Error establishing SMTP connection to mail.ourdomainhere.com:587***
  remote: **\* 'module' object has no attribute 'connect'
  remote: Exception AttributeError: "'SMTPMailer' object has no attribute 'smtp'" in <bound method SMTPMailer.**del** of <git_multimail.SMTPMailer object at 0x7f23af39c150» ignored

Redmine general  mail notifications are configured and works perfectly.
Any steps to do yet to make it work? Why you are not using redmine mail config?

Thanks in advice!

**Comment by madorin** [comment]
Some tech details:

Redmine 3.2.3.stable

Environment:
  Redmine version                3.2.3.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.0

**Comment by n-rodriguez** [comment]
Hi! Notifications are sent by https://github.com/git-multimail/git-multimail. git-multimail is installed as a Gitolite hook by Redmine Git Hosting.
