### ISSUE TITLE
No access to some repo's, after 0.7.9 -> 1.2.0 migration

### ISSUE THREAD

**Issue by nivanko** [jbox-web/redmine_git_hosting#610]
Hello!
I have done the migration as described in [wiki](http://redmine-git-hosting.io/how-to/migrate/). **Config Test** shows everything green. But now I have no access to some (not all) repositories - there is no repo's URL on project page, when I try to open **Repository** Tab, 

I see "The entry or revision was not found in the repository.", **git clone** gives me:
```
FATAL: R any zog-did redmine_nikolay_i_44 DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.
```
In database, "good" repository looks like:
```
INSERT INTO `repositories` VALUES (141,183,'repositories/pbx-api.git','','','repositories/pbxww-api.git','Repository::Xitolite','',NULL, <here is a long string with repo parameters> ,NULL,1,'2015-03-10 11:23:02');
```

when "bad" repository looks like:
```
INSERT INTO `repositories` VALUES (130,172,'/repo/git/repositories/zog-did.git','','','/repo/git/repositories/zog-did.git','Repository::Git','',NULL, <here is a long string with repo parameters> ,NULL,1,NULL);
```

Both projects are root, both have sub-projects with their own repositories.

WBR,
 Nik.

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/redmine_git_hosting/issues/460#issuecomment-114109324
