### ISSUE TITLE
Hooks not executed properly

### ISSUE THREAD

**Issue by hubiktomas** [jbox-web/redmine_git_hosting#611]
Hello,

I have some issue with hooks - it looks like the hooks binding commits to issues using keywords are not executed properly. The issues are not updated. They are updated when I disable repository cache and load repository page manually.

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Mercurial                      3.1.2
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
```

```
Git version 2.1.4
Gitolite version    2
Count of physical repositories in Gitolite  This is Gitolite v2, not implemented...
Rugged compiled features    threads ssh https
libgit2 version 0.23.3
Gitolite banner
hello admin, this is gitolite 2.3-1 (Debian) running on git 2.1.4

the gitolite config gives you the following access:
     R   W  gitolite-admin
    @R_ @W_ testing
```

Everything is green in the config test.

Any ideas?

Thank you very much.

Best regards
Tomas

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/get_started/#step-5-gitolite-must-accept-hook-keys

**Comment by baby-gnu** [comment]
Hello,

Are you sure the `Hooks URL` is well configured, it should be `https://<your host>/githooks/post-receive/redmine`

Regards.

**Comment by n-rodriguez** [comment]
Hi @hubiktomas! any news?
