### ISSUE TITLE
Error 500 (TemplateError) on Statistics page

### ISSUE THREAD

**Issue by frasten** [jbox-web/redmine_git_hosting#612]
Hi, the plugin works really well overall, but I'm getting a 500 error when entering the repository Statistics page. The URL is: https://redmine.MYDOMAIN.net/redmine/projects/MYPROJECT/repository/statistics
The logs show:

<pre>
Started GET "/redmine/projects/MYPROJECT/repository/statistics" for 95.232.76.193 at 2016-07-09 15:49:52 +0200
Processing by RepositoriesController#stats as HTML
  Parameters: {"id"=>"MYPROJECT"}
  Current user: MYUSER (id=3)
  Rendered plugins/redmine_git_hosting/app/views/repositories/statistics/_global.html.haml (16.5ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/stats.html.erb within layouts/base (19.6ms)
Completed 500 Internal Server Error in 63ms (ActiveRecord: 5.7ms)

ActionView::Template::Error (wrong number of arguments(1 for 0)):
    1: - report = RepositoryGlobalStats.new(repository).build
    2: 
    3: %ul{ class: 'thumbnails' }
    4:   - report.each do |key, value|
  plugins/redmine_git_hosting/app/views/repositories/statistics/_global.html.haml:1:in `initialize'
  plugins/redmine_git_hosting/app/views/repositories/statistics/_global.html.haml:1:in `new'
  plugins/redmine_git_hosting/app/views/repositories/statistics/_global.html.haml:1:in `_plugins_redmine_git_hosting_app_views_repositories_statistics__global_html_haml___3253852336449490871_78985780'
  plugins/redmine_git_hosting/app/views/repositories/stats.html.erb:20:in `_plugins_redmine_git_hosting_app_views_repositories_stats_html_erb___3236890162697526964_71892460'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
</pre>

My system:

<pre>
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Git                            1.9.1
  Filesystem                     
  Xitolite                       1.9.1
Redmine plugins:
  clipboard_image_paste          1.10
  easy_gantt                     1.2
  redmine_bootstrap_kit          0.2.5
  redmine_checklists             3.1.3
  redmine_code_review            0.7.0
  redmine_codebutton             0.1.0
  redmine_dashboard              2.7.1
  redmine_favorite_projects      2.0.2
  redmine_git_hosting            1.2-devel
  redmine_graphs                 0.1.0
  redmine_http_auth              0.3.0-dev
  redmine_issue_favicon          0.0.1
  redmine_jenkins                1.0.1
  redmine_js_syntax_highlighter  0.0.2
  redmine_latex_mathjax_macro    0.3.0
  redmine_lightbox2              0.2.5
  redmine_mentions               0.0.1
  redmine_my_page_queries        2.1.6
  redmine_plugin_views_revisions 0.0.1
  redmine_revision_diff          0.1.1
  redmine_sidebar_toc_pt         1.7.0
  redmine_sidekiq                2.1.0
  redmine_slack                  0.1
  redmine_tags                   3.1.0
  redmine_theme_changer          0.1.1
  redmine_time_tracker           0.10.5
  redmine_wiki_gchart_formula    0.0.5
  redmine_wiki_html_util         0.0.1
  redmine_wiki_preview_ext       0.3.0
  redmine_zenedit                0.0.2
  sidebar_hide                   0.0.7
  wiking                         1.0.0b
</pre>

I'm using the `devel` branch (@da2fe12).

Do you need any other info in order to reproduce the issue?

Thank you very much.

**Comment by frasten** [comment]
This issue is still there as of today (@a4a24a7).

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
