### ISSUE TITLE
No git user in bitnami redmine

### ISSUE THREAD

**Issue by kthkaya** [jbox-web/redmine_git_hosting#617]
The tutorial uses redmine and git users however they do not exist in bitnami redmine.

Also I get the following
bitnami@ubuntu:/opt/bitnami/apps/redmine/htdocs$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting
The git source https://github.com/jbox-web/gitolite-rugged.git is not yet checked out. Please run `bundle install` before trying to start your application

Should I install gitolite before maybe?

Any suggestions?

**Comment by n-rodriguez** [comment]
> Any suggestions?

http://redmine-git-hosting.io/get_started/ :)

**Comment by kthkaya** [comment]
Thanks. That is the document that instructs su - git but no such user in the bitnami redmine VM. In the link "Installation on Bitnami" I believe the daemon user is in charge instead. However I can't su - daemon can I?

**Comment by n-rodriguez** [comment]
> However I can't su - daemon can I?

As far as I remember when you connect on Bitnami server you are the daemon user. no?

**Comment by kthkaya** [comment]
Shell login is bitnami. Neither git nor redmine users exist. Shall I follow the tutorial swapping redmine and git with bitnami instead?

**Comment by n-rodriguez** [comment]
@kthkaya yes
any news?

**Comment by kthkaya** [comment]
Apologies for no response. I ended up installing bitnami redmine and git rather than trying to make the pre-installed VM work.
