### ISSUE TITLE
User 'git' and password

### ISSUE THREAD

**Issue by jeshio** [jbox-web/redmine_git_hosting#625]
Hello! Please help! I want to use this plugin, and tryied about 15 hours, but fail. I'm went throught many steps and now I have a good config, users has a rights. But, users can't clone repositories. My 'git' user asked a password for cloning.

User has **all rights** for the project and **added SSH-key**. After wrote:
`ssh -i .ssh/redmine_admin_1_deploy_key_1 git@192.168.0.61 info`

I'm got:
```
hello redmine_admin_1_deploy_key_1, this is git@tx running gitolite3 v3.6.6-2-g8620d5f on git 2.7.4

 R W    lir/lirapp
 R W    testing
```

Aaaand:
`git clone ssh://git@192.168.0.61/lir/lirapp.git`

Got:
```
Cloning into 'lirapp'...
git@192.168.0.61's password:
```

After wrote it:
```
fatal: '/lir/lirapp.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Please make me happy! What is it?

My config:
https://yadi.sk/i/5mcuCbgIwk4PG

My system information:
```
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Mercurial                      3.7.3
  Git                            2.7.4
  Filesystem                     
  Xitolite                       2.7.4
Redmine plugins:
  clipboard_image_paste          1.10
  redmine_bootstrap_kit          0.2.4
  redmine_dmsf                   1.5.7
  redmine_git_hosting            1.2.1
```

**Comment by baby-gnu** [comment]
Are you sure the `.ssh/redmine_admin_1_deploy_key_1` key is the default one for `git@192.168.0.61`?

Because `git clone` will use whatever ssh does.

So to test your access, try:

`ssh git@192.168.0.61`

And modify you `.ssh/config` as describe in the [gitolite documentation](http://gitolite.com/gitolite/gitolite.html#stsapp3).

Regards.

**Comment by jeshio** [comment]
@baby-gnu  Oohhooo! It's works! So many thanks!
My steps:

* Login to needed user
* `nano .ssh/config`
* Insert to it:
```
 host gitolite
     user git
     hostname 192.168.0.61
     port 22
     identityfile ~/.ssh/redmine_admin_1_deploy_key_1
```
* `Ctrl+x` and `y+Enter`
* `ssh gitolite` .. works!
* `git clone gitolite:lir/lirapp.git` works!!

**Comment by jeshio** [comment]
But don't understand why it's so..

In this
[(step 7) Add Gitolite server in known_hosts list](http://redmine-git-hosting.io/get_started/#step-7-add-gitolite-server-in-knownhosts-list)

> Also the SSH config file for Redmine user (<redmine user home>/.ssh/config) is not needed anymore! Remove it if exists!

This for redmine-user only? 

So, another users needs to do my steps above?
What about _only_ SSH key?

**Comment by n-rodriguez** [comment]
> Also the SSH config file for Redmine user (/.ssh/config) is not needed anymore! Remove it if exists!
> 
> This for redmine-user only?

Yes. This is done on the 'server side', when you're installing RGH.

> So, another users needs to do my steps above?

If you're doing this on your laptop or a server to clone repositories, yes.

> What about only SSH key?

And not deployment keys? It works the same way.

> And Windows.. SourceTree?

On Windows I don't know, but it should work the same way.
