### ISSUE TITLE
EOF kept in installed hooks

### ISSUE THREAD

**Issue by snakevil** [jbox-web/redmine_git_hosting#626]
Hi. I'm working on making a docker with Redmine-3.3.1 and RedmineGitHosting-1.2.1. But when testing to install hooks, `hook left untouched`occurred.

I tried to push commits, I found the error message:

```
remote: $GITOLITE/local/hooks/common/lib/git_hosting/http_helper.rb:127:in `<top (required)>': uninitialized constant EOF (NameError)
remote:     from hooks/post-receive:9:in `require_relative'
remote:     from hooks/post-receive:9:in `<main>'
```

And then, I found the literal `EOF` were kept in installed hooks. That's weired.

```
$ cat /etc/issue
Welcome to Alpine Linux 3.4
Kernel \r on an \m (\l)

$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux-musl]

$ grep -nFr 'EOF' $GITOLITE/local/hooks/common
./post-receive.d/mail_notifications:36:EOF
./post-receive.d/git_multimail.py:2588:EOF
./post-receive:20:EOF
./lib/git_hosting/http_helper.rb:127:EOF
./lib/git_hosting/custom_hook.rb:100:EOF
./lib/git_hosting/post_receive.rb:74:EOF
./lib/git_hosting/hook_logger.rb:38:EOF
./lib/git_hosting/config.rb:134:EOF
```

After I deleted those lines manually, **Config Test** told me hooks installed well.

**Comment by n-rodriguez** [comment]
Well... this is weird.. but I don't know how to reproduce it ^^

**Comment by n-rodriguez** [comment]
And if you delete hooks and reinstall them? what happens?

**Comment by n-rodriguez** [comment]
And if you delete hooks and reinstall them? what happens?
