### ISSUE TITLE
Use “gitolite query-rc” to get gitolite variables

### ISSUE THREAD

**Issue by baby-gnu** [jbox-web/redmine_git_hosting#630]
Instead of asking the admin to set some variables we can get them from @gitolite itself:

```
redmine@xenial:~$ for var in GL_BINDIR GL_LIBDIR; do sudo -n -u git -i gitolite query-rc ${var}; done
/home/git/gitolite/src
/home/git/gitolite/src/lib
```

Then the admin only need to define which variable to export.

Regards.

**Comment by n-rodriguez** [comment]
Great!

**Comment by n-rodriguez** [comment]
Done! https://github.com/jbox-web/redmine_git_hosting/commit/58f4fe33058244ab19308624bf0710353e5cc835
