### ISSUE TITLE
Mirroring does not work on git push

### ISSUE THREAD

**Issue by baby-gnu** [jbox-web/redmine_git_hosting#632]
Hello,

I upgraded our redmine and the redmine_git_hosting plugin and I can't figure out why the mirroring does not work:

- As admin, in the _<Project> -> Settings -> Repository -> Repository Mirrors_, I can click on **Push** and it's working
- As a developer, when I push a commit to that repository, it's not mirrored.

I see nothing in the logs.

**Comment by baby-gnu** [comment]
It's related to `Gitolite non-core hooks directory`.

```
git@xenial:~$ gitolite query-rc LOCAL_CODE
/home/git/.gitolite/local
```

By default, it's `local/`.

A new point for #630 ;-)

**Comment by n-rodriguez** [comment]
Done : https://github.com/jbox-web/redmine_git_hosting/commit/337bbbc3d038e1530c5fd9da0aead36bceb7abea
