### ISSUE TITLE
Display of big repository can exhaust memory

### ISSUE THREAD

**Issue by baby-gnu** [jbox-web/redmine_git_hosting#635]
Hello,

We sometime encounter issues when a user want to look at a repository:

- when it works, it's long before displaying anything
- sometime it does not work with a `Cannot allocate memory` error
```
Cannot allocate memory - 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/big_repo.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'tag'
```

It looks like the git command itself is quite long to execute

```
redmine@forge-mim:~/redmine-3.2.1$ time sudo -n -u git -i git --git-dir repositories/big_repo.git -c core.quotepath=false -c log.decorate=no log --no-color --encoding=UTF-8 --raw --date=iso --pretty=fuller --parents -n 10 >| output.txt 

real	0m22.064s
user	0m10.596s
sys	0m11.180s
```

Then the `output.txt` is huge:

```
redmine@forge-mim:~/redmine-3.2.1$ wc -l output.txt 
1700525 output.txt
```

Is there a way to avoid that issue?

Regards.

**Comment by baby-gnu** [comment]
Note that the devs had a bad use of Git, storing several releases of a software in separate directories instead of using branches.

This result in lots of files, and one day, they deleted nearly all the noisy files in one commit, this is the reason for so may lines in the outputs.

Regards.

**Comment by baby-gnu** [comment]
You can test by importing the Debian samba repository from `git://anonscm.debian.org/pkg-samba/samba.git`

The repository is around 278MB and it took 41 seconds to execute the following command:

``` bash
time for rev in 32841b292ef41e4b17367f7bd464f882d57a39dc 4fc764450b6a45509214e0fd54bb54f18d6bc7c4 552f08f2607bbcf9ce5009b2cfe6161bc0743f3b
do
    echo $rev | git -c core.quotepath=false -c log.decorate=no log --no-color --encoding=UTF-8 --raw --date=iso --pretty=fuller --parents --reverse --stdin > /dev/null
done
```

When I limit with `-n 100` the output is quick.

Regards.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
