### ISSUE TITLE
New repository form not seen properly 

### ISSUE THREAD

**Issue by Roshan56** [jbox-web/redmine_git_hosting#639]
Hi there,

Good Day

I have installed redmine_git_hosting plugin with latest version. When I am going to configure New repository I am not able to see git repository form as per your screen shot. Please find the attachment of my New repository form image.
```
Environment:
  Redmine version                3.2.4.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            2.11
  Filesystem                     
  Xitolite                       2.11
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_favorite_projects      1.0.7
  redmine_git_hosting            1.2.1
  redmine_inventory_manager      0.9
  redmine_issue_templates        0.1.3
  redmine_knowledgebase          3.2.1
  redmine_testlinklink           1.0.0
```

![new-repo](https://cloud.githubusercontent.com/assets/4560702/21544403/76580b62-cdf4-11e6-8074-9571fb5e643b.png)

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/get_started/#step-9-finish-installation---configuration
Enable Xitolite repositories in Administration -> Settings -> Repositories

**Comment by Roshan56** [comment]
Hi n-rodirguez,

I have already done Xitolite setting but still I am not able to see New repository form properly. Kindly find the attachment of my settings images. Could you please help me out for the same.

![plugins-settings](https://cloud.githubusercontent.com/assets/4560702/21560508/5ac7ada2-ce86-11e6-8adf-3e3a4f1926f6.png)
![settings](https://cloud.githubusercontent.com/assets/4560702/21560510/5e582258-ce86-11e6-9009-c03aab19bdf2.png)

**Comment by n-rodriguez** [comment]
You must select 'Gitolite' in the dropdown. The form will refresh automatically.

**Comment by Roshan56** [comment]
Hello n-rodiriguez,

Happy New Year

Thanks for resolved my problem. I have one question 

I have migrated svn repository to git and I am trying to add repsitory but I am getting below error while adding the repo. Could you please provide me exact migration steps from svn to git(redmine-git-hosting.)


    Identifier invalid
    Identifier can not match the ID of an existing project

Thanks,

**Comment by Roshan56** [comment]
Hello n-rodiriguez,

Thanks for your help. I have resolved issue myself.
