### ISSUE TITLE
[Feature Request] Pull requests feature

### ISSUE THREAD

**Issue by madorin** [jbox-web/redmine_git_hosting#647]
Nicolas, 
Is "Pull requests" a feature that can be added in Your plugin or this is completely a different area?

**Comment by pva** [comment]
We are looking for this feature as well. A best solution that we are currently testing is to use gitlab for pull requests and keep everything else in redmine. I found redmine issue on this subject and note-5 there suggests same way :) http://www.redmine.org/issues/8363 but there should be better way! So I'll be happy to see this feature implemented. This is related to #73 but still possible to implement without full code review solution.

**Comment by borismedovnik** [comment]
We'd really love to see this feature implemented and are willing to donate to the development. This is the only feature we miss that makes us think about switching to gitlab for git hosting. However, it seems wasteful to use gitlab just for pull requests, especially considering the fact that gitlab is more resource-hungry and would not allow for the tight integration with redmine that we're used to with redmine_git_hosting (referencing commits, auto-linking revisions to tickets, etc)

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.

**Comment by madorin** [comment]
I dont think it's pinned to v3, of course valable to v4 (and v5). However we slowly move to GitLab where this feature exists already, instead a lot of project management features are missing threre in community version, compared to Redmine.

**Comment by PowerKiKi** [comment]
You're correct that this is not tied to a specific version of Redmine. But, as you've probably noticed over the past few years, this project lack manpower. We are mostly focused on maintenance for the time being. And it seems rather unlikely that such a huge feature will be implemented unless a contributor create a PR for it.

In those conditions it seemed that closing the issue would better reflect the reality and not give false hopes.
