### ISSUE TITLE
Can't retrieve Gitolite param :  for `sudo -n -u git -i gitolite query-rc GL_BINDIR`

### ISSUE THREAD

**Issue by hamdijmii1992** [jbox-web/redmine_git_hosting#649]
After reaching (successfully) step (7) in  http://redmine-git-hosting.io/get_started/ tutorial, I tried to open "Redmine Git Hosting" menu  but I got this error from redmine log : 

 ```
Rendered settings/plugin.html.erb within layouts/admin (31.7ms)
Completed 500 Internal Server Error in 41.5ms

ActionView::Template::Error (Permission denied @ rb_sysopen - /opt/redmine/redmine/log/git_hosting.log):
    4:
    5:   %tr
    6:     %td= l(:label_temp_dir_writeable)
    7:     %td= render_temp_dir_writeable(RedmineGitHosting::Config.temp_dir_writeable?(reset: true), RedmineGitHosting::Config.gitolite_admin_dir)
    8:
    9:   %tr
    10:     %td= l(:label_redmine_user)
```

from git_hosting.log I got this log

```
2017-02-01 17:23:03 -0800 [INFO] Testing if Redmine user 'root' can sudo to Gitolite user 'git'...
2017-02-01 17:23:04 -0800 [INFO] OK!
2017-02-01 17:23:04 -0800 [ERROR] Can't retrieve Gitolite param : Non-zero exit code pid 62464 exit 127 for `sudo -n -u git -i gitolite query-rc GL_BINDIR`
```

**Comment by n-rodriguez** [comment]
Hi! I think you have 2 bugs here :

The first one is permission issue :
```ActionView::Template::Error (Permission denied @ rb_sysopen - /opt/redmine/redmine/log/git_hosting.log):```

The second one :
```Can't retrieve Gitolite param : Non-zero exit code pid 62464 exit 127 for `sudo -n -u git -i gitolite query-rc GL_BINDIR``` is fixed by https://github.com/jbox-web/redmine_git_hosting/pull/646

By the way you should not run Redmine with the `root` user : 
```Testing if Redmine user 'root' can sudo to Gitolite user 'git'...```

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
