### ISSUE TITLE
Cannot access repository by http (sub-uri)

### ISSUE THREAD

**Issue by marek99** [jbox-web/redmine_git_hosting#653]
I have installed the plugin. My redmine version is 3.2.1., plugin 1.2.2. It seems it has installed and configured sucessfully, "config test" tab in the configuration shows all green.
The `Subdirectory for HTTP access` in the plugin configuration tab is `git/`

I have created a new project with a gitolite repo in redmine. But when I want to access the https URL of the supposed repo, I get  Redmine 404 error "page not found".

the redmine log looks as follows:

`Started GET "/redmine/git/energy-peak/energy_peak.git" for xxx.xxx.xxx.xxx at 2017-02-13 22:42:55 +0100`
`ActionController::RoutingError (No route matches [GET] "/git/energy-peak/energy_peak.git"):`

I suppose the issue might be due to the redmine being deployed in a sub URI (/redmine/) but I do not know if this is the real issue or how to configure plugin correctly for it to work.

I'd appreciate any help with debuging/fixing this issue.

**Comment by n-rodriguez** [comment]
Hi! Those HTTP(s) urls are for git not for browsing.
Example : `git clone http://redmine.local/git/test/blabla.git`

**Comment by marek99** [comment]
Ok, I understand, I somehow (wrongly) assumed there will be something available there for the browser. But git direct access seem to work fine. thanks.
