### ISSUE TITLE
greyout button - Automatically initialize Git repositories with a README file

### ISSUE THREAD

**Issue by ahmedosama80** [jbox-web/redmine_git_hosting#654]
Dears,
the button which used to enable/disable **"Automatically initialize Git repositories with a README file (à la Github)"** is disabled and **greyout** !!
any tips about this issue??

Redmine version                3.2.1.stable
redmine_git_hosting       version 1.2.0
gitolite3 v3.6.5-4-g6ed0156-dt on git 2.6.1

thanks all

**Comment by sdfg2** [comment]
Have you made sure the hooks are installed?

**Comment by baby-gnu** [comment]
> the button which used to enable/disable "Automatically initialize Git repositories with a README file (à la Github)" is disabled and greyout !!
> any tips about this issue??

I think this is because **Automatically initialize Git repositories for new projects?** is set to **No**.

I think that **Automatically initialize Git repositories with a README file (à la Github)** could be make independant.

Regards.

**Comment by ahmedosama80** [comment]
> I think this is because Automatically initialize Git repositories for new projects? is set to No.
> 
> I think that Automatically initialize Git repositories with a README file (à la Github) could be make independant.

I guess they already independant

**Comment by baby-gnu** [comment]
No [they are not](https://github.com/jbox-web/redmine_git_hosting/blob/1.2.2/app/views/settings/redmine_git_hosting/_redmine_config.html.haml#L26)

``` haml
  %label= l(:label_init_repositories_on_create).html_safe
  = bootstrap_switch_tag do
  = hidden_field_tag 'settings[init_repositories_on_create]', 'false'
  = check_box_tag 'settings[init_repositories_on_create]', init_repositories_on_create, init_repositories_on_create, {:disabled => !all_projects_use_git}
```

You can notice the

```
{:disabled => !all_projects_use_git}
```

Regards.

**Comment by n-rodriguez** [comment]
> I think that Automatically initialize Git repositories with a README file (à la Github) could be make independant.

How could I automatically init a repo if it's not automatically created? FYI, this settings only apply on `Project` creation.

**Comment by baby-gnu** [comment]
> How could I automatically init a repo if it's not automatically created? FYI, this settings only apply on Project creation

We could automatically initialise a repository on its creation, the repository creation could be done automatically at project creation or manually as requested by the user.

Otherwise we will be unable to initialise the `README` of sub-repositories.

Regards.

**Comment by n-rodriguez** [comment]
> We could automatically initialise a repository on its creation, the repository creation could be done automatically at project creation or manually as requested by the user.
> 
> Otherwise we will be unable to initialise the README of sub-repositories.

This is already the case or I miss something...

**Comment by baby-gnu** [comment]
> This is already the case or I miss something...

I don't know because we do not want to automatically initialize Git repositories for new projects since some projects are just a grouping of several sub-project to centrally manage issues.

So, when **Automatically initialize Git repositories for new projects?** is set to **No**, I can't set **Automatically initialize Git repositories with a README file (à la Github)** to **Yes**.

This is the main issue for us.

Regards.

**Comment by baby-gnu** [comment]
OK, here is the recap:

When **Automatically initialize Git repositories for new projects?** is set to **No** then **Automatically initialize Git repositories with a README file (à la Github)** is unselectable: 

![automatic-readme-initialisation-greyout](https://cloud.githubusercontent.com/assets/1233212/24578714/4d4d2c62-16e6-11e7-924c-612a4a819b41.png)

in which case, the **Initialize this repository with a README** is not automatically selected:

![readme-initialisation-not-pre-selected](https://cloud.githubusercontent.com/assets/1233212/24578724/bb21ee08-16e6-11e7-9820-ac4a02e110a1.png)

I think **Automatically initialize Git repositories with a README file (à la Github)** could be independent from **Automatically initialize Git repositories for new projects?**, this way a repository is not automatically created when a new project is created but the checkbox is automatically pre-selected:

![readme-initialisation-pre-selected](https://cloud.githubusercontent.com/assets/1233212/24578725/c7310fbc-16e6-11e7-8271-e97f41d39e21.png)

Regards.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
