### ISSUE TITLE
can't clone using smart HTTPS

### ISSUE THREAD

**Issue by ahmedosama80** [jbox-web/redmine_git_hosting#658]
dears,
I am facing an error while cloning ( https://admin@XXXXXXXXXX/demo/development-process.git ) using smart https

my system
Redmine version 3.2.1.stable using suburi  /demo
redmine_git_hosting version 1.2.0
gitolite3 v3.6.5-4-g6ed0156-dt on git 2.6.1

> [ERROR] Problems while getting SmartHttp params
> 
> NoMethodError (undefined method `chomp' for true:TrueClass):
>   plugins/redmine_git_hosting/lib/grack/auth.rb:44:in `auth!'
>   plugins/redmine_git_hosting/lib/grack/auth.rb:22:in `call'

thanks all

**Comment by n-rodriguez** [comment]
Duplicate https://github.com/jbox-web/redmine_git_hosting/issues/568
