### ISSUE TITLE
Additional local hooks

### ISSUE THREAD

**Issue by acosonic** [jbox-web/redmine_git_hosting#659]
I can't find any docs how to configure additional local hooks

```
Looking for additional local post-receive hooks...
  - No local hooks found

```

Can you please update your docs, and teach us how to use those additional local hooks?

**Comment by n-rodriguez** [comment]
Done : https://github.com/jbox-web/redmine_git_hosting/commit/60716acca5aea0eda52c8bb1a95e42d38eb49294
I'll add some documentation later.
