### ISSUE TITLE
Repo clone not working

### ISSUE THREAD

**Issue by zbigniev** [jbox-web/redmine_git_hosting#660]
Very similar to https://github.com/jbox-web/redmine_git_hosting/issues/402

Followed instructions on http://redmine-git-hosting.io/get_started/ for Bitnami Redmine.
Git: 2.7.4, Gitolite: 3, libgit2: 0.25.0
All Config Tests are green
Trying to clone a repo on client gives:

```
git clone -v ssh://git@192.168.59.104/test1/main.git
Cloning into 'main'...
FATAL: R any test1/main redmine_tester_1 DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
The only log that shows an issue is gitolite's log:
```
2017-03-13.23:46:40     10298   die     R any test1/main redmine_tester_1 DENIED by fallthru<<newline>>(or you mis-spelled the reponame)
2017-03-13.23:50:45     10549   cli     gitolite        list-phy-repos
2017-03-13.23:50:45     10549   END
```
ssh from client seems to be working:
```
ssh git@192.168.59.104 info
hello redmine_tester_1, this is git@gandalf running gitolite3 v3.6.6-6-g7c8f0ab on git 2.7.4

 R W	testing
```
and gitolite.conf reads:
```
repo    @all
  RW+                            = redmine_gitolite_admin_id_rsa

repo    gitolite-admin
  RW+                            = redmine_gitolite_admin_id_rsa

repo    test1/main
  R                              = DUMMY_REDMINE_KEY
  config redminegitolite.projectid = test1
  config redminegitolite.repositoryid = main
  config redminegitolite.repositorykey = SVyfi29ColX7TDidbG8WP8V7wHyzIEDCHAMgQkiAniQa2PEaR7mkBrmCAxlnPmUo
  config http.uploadpack = true
  config http.receivepack = true
  config multimailhook.enabled = false

repo    testing
  RW+                            = @all
```
Any ideas on what might be wrong?

**Comment by ahmedosama80** [comment]
Well u have dumy key so you didn't assign a user key , in ur account profile page at Redmine, you must add a ssh key as user key and of course this key is the same key used at the client which processes the git clone at .ssh folder

**Comment by zbigniev** [comment]
I had already added a public key in redmine, as is evident from this screenshot
![screen shot 2017-03-14 at 1 21 19 am](https://cloud.githubusercontent.com/assets/61141/23872556/c1b49928-0854-11e7-9bbb-4ee30f192934.png)

though I hadn't made any corresponding changes to gitolite.conf (Will I have to update the conf file for every new user added to the project?).

I did try replacing DUMMY_REDMINE_KEY with both the key generated in http://redmine-git-hosting.io/get_started/#step-3-create-ssh-keys-for-user-running-redmine as well as the client key (which is what I thought you suggested) but neither worked; returning the same response when trying to clone.

**Comment by zbigniev** [comment]
@ahmedosama80 I guess I figured out the issue. I hadn't added a user to the project, once I did, it worked. Thanks a lot for the help.
I just hope I am able to find some way (read plugin) to let users add their public key from their logins, rather than emailing them to admin, each time.

**Comment by zbigniev** [comment]
Found that as well, under roles and permissions. Thanks a ton.

**Comment by n-rodriguez** [comment]
http://redmine-git-hosting.io/get_started/#step-10-add-your-ssh-keys
