### ISSUE TITLE
missing repository url/reference 

### ISSUE THREAD

**Issue by kaspercools** [jbox-web/redmine_git_hosting#661]
Since the update from version 1.2.1 to 1.2.2. We notice that the repository URL is not always showing (it seems to disappear and reappear at random). 
At the same time it seems as if new users are not automatically granted access to their repository. 

Furthermore there I was not able to find any errors in the log files. Everything worked fine before the update. I do however need to mention that we were not able to install the hooks yet.

Just to clarify, I followed the steps as mentioned on the website.

**Comment by gituser** [comment]
having exactly same issue... on `redmine v3.3.3` and `redmine-git-hosting 1.2.x`

no ssh url there..

**Comment by kaspercools** [comment]
update fixed my issues-> closing
