### ISSUE TITLE
Add Repository Mirror does not accept the gitlab repo

### ISSUE THREAD

**Issue by xuanhoang** [jbox-web/redmine_git_hosting#662]
I would want to use gitlab as a mirror repo...however when i add the path to repo...example ssh://git@gitlab.com:myuser/test-mirror.git...Redmine report invalid url. Why we can not use gitlab as mirror?

**Comment by n-rodriguez** [comment]
Hi! Try with `ssh://git@gitlab.com:22/myuser/test-mirror.git`

**Comment by xuanhoang** [comment]
Thanks, it works correctly :)
