### ISSUE TITLE
Line break in LOCAL_CODE configuration variable.

### ISSUE THREAD

**Issue by fdamken** [jbox-web/redmine_git_hosting#664]
# Context
The creation of Gitolite-Hooks are not working correctly. That is they get not created correctly. If found a solution myself which I will describe in the following text.

# Code Context
I am talking about [this line of code](https://github.com/jbox-web/redmine_git_hosting/blob/master/lib/redmine_git_hosting/config/gitolite_hooks.rb#L32).

# Problem
My hooks did not get registered and I searched thru all my settings and the code and finally found that it was trying to copy the hook files to a path that contains a line break, which was caused by this line of code as the variable has contained a line break at its end.

# Solution
I fixed it for myself by appending ``.rstrip`` to the code line to remove the last blanks (and also line breaks!).

**Comment by n-rodriguez** [comment]
Hi! Thanks for your report, but this issue is already fixed : https://github.com/jbox-web/redmine_git_hosting/commit/348d9249aceb491540a69d59cbf426046bef54ed
It's part of the next 1.2.3 release. Stay tuned!

**Comment by fdamken** [comment]
Oh, I have not seen that commit. I looked up nearly every branch but not the release branch (-es)… My mistake :)

**Comment by n-rodriguez** [comment]
No problem, very nice job 👍
