### ISSUE TITLE
hooks not working on centos 7:  .... is already present but it's not ours!

### ISSUE THREAD

**Issue by bougui** [jbox-web/redmine_git_hosting#666]
Hello,

From the hooks tab I get this error for all the hooks when I click the install hooks link

Warning redmine_gitolite.rb (hook left untouched)
Warning mail_notifications.py (hook left untouched)
Warning git_hosting_config.rb (hook left untouched)
Warning git_hosting_custom_hook.rb (hook left untouched)
Warning git_hosting_http_helper.rb (hook left untouched)
Warning git_hosting_hook_logger.rb (hook left untouched)
Warning git_hosting_post_receive.rb (hook left untouched)
Warning git_multimail.py (hook left untouched)

from the git_hosting.log I see this for all the hooks

Hook 'git_hosting_hook_logger.rb' is already present but **it's not ours!**

I have apply this fix https://github.com/jbox-web/redmine_git_hosting/issues/642 to prevent the newline bug

Any help on this would be greatly appreciated !

I'm on centos 7, ruby is from rh-ruby22-ruby-2.2.2-16.el7.x86_64

And here is the redmine env.

Environment:
  Redmine version                3.1.6.stable
  Ruby version                   2.2.2-p95 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
  Xitolite                       1.8.3.1
Redmine plugins:
  redmine_bootstrap_kit          0.2.5
  redmine_default_assign         0.6
  redmine_git_hosting            1.2.2
  redmine_image_clipboard_paste  1.0.0
  redmine_silencer               0.4.1

Thanks

**Comment by bougui** [comment]
Here is the output if I try via bash (http://redmine-git-hosting.io/how-to/maintain/#install-hooks):

_ bundle exec rake redmine_git_hosting:install_gitolite_hooks RAILS_ENV=production_

/home/redmine/.rvm/gems/ruby-2.2.6/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"

 * Installing/updating Gitolite hooks :
---
:hook_files:
  redmine_gitolite.rb: 2
  mail_notifications.py: 2
  git_hosting_config.rb: 2
  git_hosting_custom_hook.rb: 2
  git_hosting_http_helper.rb: 2
  git_hosting_hook_logger.rb: 2
  git_hosting_post_receive.rb: 2
  git_multimail.py: 2
:global_params:
  redmineurl: true
  debugmode: true
  asyncmode: true
:mailer_params:
  mailer: true
  environment: true
  smtpauth: true
  smtpserver: true
  smtpport: true
   Done !


 * Installing/updating Gitolite hook parameters :
---
redmineurl: true
debugmode: true
asyncmode: true
   Done !


In redmine the asyncmode is to false but here I see true ...

Thanks

**Comment by gituser** [comment]
Use branch `1.2.x`

via:

`git checkout remotes/origin/v1.2.x`

**Comment by Lexycon** [comment]
Thanks man, had a similar issue with the hooks on debian an this fixed it...

**Comment by bougui** [comment]
Yes working for centos 7 /   Redmine 3.1.6.stable

I had to modify this file 
`vi $REDMINE_ROOT/Gemfile
`

I commented out this entry
```
# because of git_hosting who require rdoc ~>4.3 (plugins/redmine_git_hosting/Gemfile)
# gem "rdoc", ">= 2.4.2"
```

And all status are now green in the git_hosting config test page after installing the hook.

https://your-redmine/settings/plugin/redmine_git_hosting?tab=gitolite_config_test

Thanks

Guillaume

**Comment by CieNTi** [comment]
Thanks @gituser ... works perfect now
