### ISSUE TITLE
Redmine 500 error while flushing cache: Rugged::ReferenceError (Corrupted loose reference file: refs/heads/master):

### ISSUE THREAD

**Issue by ioiobzit** [jbox-web/redmine_git_hosting#671]
Hello,

here the server info:

> Environment:
>   Redmine version                3.3.3.stable
>   Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
>   Rails version                  4.2.7.1
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Git                            2.1.4
>   Filesystem                     
>   Xitolite                       2.1.4
> Redmine plugins:
>   redmine_bootstrap_kit          0.2.5
>   redmine_default_assign         0.6
>   redmine_editauthor             0.9.1
>   redmine_git_hosting            1.2.2
>   redmine_issue_checklist        2.1.0
>   redmine_mail_checker           1.0.0

Here the error message in production.log
```
Rugged::ReferenceError (Corrupted loose reference file: refs/heads/master):
   plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:68:in `new'
   plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:68:in `gitolite_admin'
   plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:45:in `execute_action'
   plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:24:in `resync_gitolite'
   plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_accessor.rb:146:in `resync_gitolite'
   plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_accessor.rb:77:in `update_projects'
   plugins/redmine_git_hosting/app/use_cases/settings/apply.rb:143:in `do_resync_projects'
   plugins/redmine_git_hosting/app/use_cases/settings/apply.rb:51:in `apply_settings'
   plugins/redmine_git_hosting/app/use_cases/settings/apply.rb:36:in `call'
   plugins/redmine_git_hosting/app/use_cases/settings/apply.rb:28:in `call'
   plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/settings_controller_patch.rb:79:in execute_post_actions'
   plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/settings_controller_patch.rb:69:in `handle_settings_update'
   plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/settings_controller_patch.rb:41:in `plugin_with_git_hosting'
   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Here the git_hosting.log

```
2017-05-03 11:04:13 +0200 [DEBUG] Getting Gitolite banner...
2017-05-03 11:04:17 +0200 [INFO] Flush Settings Cache !
2017-05-03 11:04:17 +0200 [INFO] Settings cache flushed!
2017-05-03 11:04:17 +0200 [INFO] Forced resync of all projects (active, closed, archived)...
2017-05-03 11:04:17 +0200 [DEBUG] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git'
2017-05-03 11:08:00 +0200 [DEBUG] Testing if Gitolite Admin directory '/tmp/redmine_git_hosting/git/gitolite-admin.git' is writeable ...
2017-05-03 11:08:00 +0200 [INFO] Testing if Redmine user 'redmine' can sudo to Gitolite user 'git'...
2017-05-03 11:08:00 +0200 [INFO] OK!
```

What am I doing wrong?

**Comment by r0perice** [comment]
Same problem here with :

> Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.0.0-p647 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Git                            1.9.5
  Filesystem                     
  Xitolite                       1.7.1
  redmine_git_hosting            1.1.3

**Comment by n-rodriguez** [comment]
https://gitlab.com/gitlab-com/infrastructure/issues/773

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
