### ISSUE TITLE
redmine-git-hosting.io is OFF

### ISSUE THREAD

**Issue by fbruandrade** [jbox-web/redmine_git_hosting#674]
Guys, the main website is OFF

**Comment by bugiii** [comment]
Temporarily modify the host file as follows:
151.101.72.133 redmine-git-hosting.io

**Comment by gituser** [comment]
@n-rodriguez can you fix this?

**Comment by tomepsilva** [comment]
Appending this to /etc/hosts or to C:\Windows\System32\drivers\etc\hosts it works but if you could fix on ther DNS server it would be perfect

**Comment by n-rodriguez** [comment]
> @n-rodriguez can you fix this?

This will be fixed this week.
Thank you.

**Comment by n-rodriguez** [comment]
Hi! I have some issues with the registrar to transfer the domain name. I'm doing my best to recover it. I'll keep you posted.

**Comment by n-rodriguez** [comment]
fixed :)
