### ISSUE TITLE
Some parameters in settings.yml are not taken into account

### ISSUE THREAD

**Issue by phirivet** [jbox-web/redmine_git_hosting#677]
Hello,

I am trying to automate Redmine and redmine-git-hosting plugin installation.
I copy the default_settings.yml to $REDMINE_HOME/plugin/redmine_git_hosting/settings.yml and change some parameters.
When the installation is completed I connecte to Redmine and go to Redmine Git Hosting configuration. Some parameters are taken into account correctly but not some others.

The parameter not taken into account are:
gitolite_temp_dir
git_config_email
ssh_server_domain
gitolite_notify_global_sender_address
all_projects_use_git
init_repositories_on_create
hierarchical_organisation

Unique_repo_identifier is not in the GUI then I don't know if it is taken into account correctly.

I don't set every parameters so I can't tell if there are other parameters not taken into account. The following parameters are treated correctly:
http_server_domain
https_server_domain
gitolite_http_by_default
gitolite_hooks_url

Installation informations:

<pre>Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.7.4
  Filesystem                     
  Xitolite                       2.7.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.5
  redmine_git_hosting            1.2.2</pre>

<pre># bundle list
Gems included by the bundle:
  * RedCloth (4.3.2)
  * actionmailer (4.2.7.1)
  * actionpack (4.2.7.1)
  * actionpack-action_caching (1.2.0)
  * actionpack-xml_parser (1.0.2)
  * actionview (4.2.7.1)
  * activejob (4.2.7.1)
  * activemodel (4.2.7.1)
  * activerecord (4.2.7.1)
  * activesupport (4.2.7.1)
  * addressable (2.5.1)
  * arel (6.0.4)
  * asciidoctor (1.5.5)
  * builder (3.2.3)
  * bundler (1.11.2)
  * coderay (1.1.1)
  * concurrent-ruby (1.0.5)
  * creole (0.5.0)
  * css_parser (1.4.10)
  * dalli (2.7.6)
  * deface (1.2.0)
  * erubis (2.7.0)
  * gemoji (3.0.0)
  * github-markup (1.6.0)
  * gitlab-grack (2.0.0.pre 1bc51d8)
  * gitolite-rugged (1.2.0 551741d)
  * globalid (0.4.0)
  * gratr19 (0.4.4.1)
  * haml (5.0.1)
  * haml-rails (1.0.0)
  * hiredis (0.6.1)
  * html2haml (2.2.0)
  * htmlentities (4.3.4)
  * i18n (0.7.0)
  * jquery-rails (3.1.4)
  * json (1.8.6)
  * loofah (2.0.3)
  * mail (2.6.5)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * mimemagic (0.3.2)
  * mini_portile2 (2.1.0)
  * minitest (5.10.2)
  * net-ldap (0.12.1)
  * nokogiri (1.6.8.1)
  * org-ruby (0.9.12)
  * pg (0.18.4)
  * polyglot (0.3.5)
  * protected_attributes (1.1.4)
  * public_suffix (2.0.5)
  * rack (1.6.8)
  * rack-openid (1.4.2)
  * rack-parser (0.7.0)
  * rack-test (0.6.3)
  * rails (4.2.7.1)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.8)
  * rails-html-sanitizer (1.0.3)
  * railties (4.2.7.1)
  * rainbow (2.2.2)
  * rake (12.0.0)
  * rbpdf (1.19.2)
  * rbpdf-font (1.19.1)
  * rdoc (4.3.0)
  * redcarpet (3.3.4)
  * redis (3.3.3)
  * request_store (1.0.5)
  * rmagick (2.16.0)
  * roadie (3.2.1)
  * roadie-rails (1.2.1)
  * ruby-openid (2.3.0)
  * ruby_parser (3.9.0)
  * rubypants (0.6.0)
  * rugged (0.25.1.1)
  * sexp_processor (4.9.0)
  * sprockets (3.7.1)
  * sprockets-rails (3.2.0)
  * temple (0.8.0)
  * thor (0.19.4)
  * thread_safe (0.3.6)
  * tilt (2.0.7)
  * tzinfo (1.2.3)
  * will_paginate (3.1.6)</pre>

Thanks for the help.

**Comment by n-rodriguez** [comment]
Hi! After changing settings you must run `rake redmine_git_hosting:update_settings`

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
