### ISSUE TITLE
redmine git hosting rugged compiled features ssh red

### ISSUE THREAD

**Issue by aripod** [jbox-web/redmine_git_hosting#679]
Hello,

I finally managed to install the plugin and gitolite, but I still have `ssh` in red for rugged compiled features. In `configuration test` everything is in green but this. And in `Administration -> Settings -> Repositories` I have ticked Suversion, Git and Xitolite. All of them have a green tick with `svn`, `git` and `git` respectfully. I have seen some other issues where xitolite had an absolute path rather than just `git`. 

Could the `ssh` being in red and having just 'git´ rather than an absolute path be the problem that I have now? I have been able to create a new repository, but when I check the configuration of the repository, it says that it does not exist in gitolite.

Just in case, I can do on the `redmine` user where I installed redmine with bitnami:

```
redmine@cintra-bekesy:~/redmine-3.3.3-0$ ssh -i ssh_keys/redmine_gitolite_admin_id_rsa git@localhost info
hello redmine_gitolite_admin_id_rsa, this is git@cintra-bekesy running gitolite3 v3.6.6-14-g45e11f1 on git 2.7.4

 R W	gitolite-admin
 R W	testing
```
Searching for the solution I found a closed issue here asking if jbox-gitolite was installed. I did not have this. Therefore, I installed it. Should I have done something else besides `gem install jbox-gitolite`? Should I have ran `bundle install` after `gem install jbox-gitolite`?

I have seen on another issue here that having ssh red in rugged compiled features can be because rugged/libgit2 has not been compiled with SSH support. So, I followed the `Unsupporterd URL protocol` steps but I still have the issue.

Also, if it helps, this is what my `/home/git/.gitolite/conf/gitolite.conf` file looks like:

```
repo gitolite-admin
    RW+     =   redmine_gitolite_admin_id_rsa

repo testing
    RW+     =   @all
```
Besides, I `ran gem` update just it case as well.

One thing that I have just realized is when I follow [this steps](http://redmine-git-hosting.io/how-to/install-on-bitnami/#step-4-clone-libgit2-repository-and-build-the-lib) to install the `libgit2` library, it says to copy:
`
sudo cp /usr/lib/x86_64-linux-gnu/pkgconfig/libssh2.pc /opt/bitnami/common/lib/pkgconfig/`

But as I did not install bitnami redmine with sudo, I copied it to `/home/redmine/redmine-3.3.3-0/common/lib/pkgconfig/` and rather than using `v0.22.2` as suggested, I checkout to `v0.25.1`.

And one last thing, for step 8 of the `get_started` guide `Install Ruby interpreter for post-receive hook`, rather than doing it with apt-get, I followed [these steps](https://stackoverflow.com/questions/37720892/you-dont-have-write-permissions-for-the-var-lib-gems-2-3-0-directory):

```
cd $HOME
sudo apt-get update 
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev

git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec $SHELL

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
exec $SHELL

rbenv install 2.3.1
rbenv global 2.3.1
ruby -v
gem install bundler
rbenv rehash
```

Thanks for the help.

**Comment by CMoH** [comment]
Yes, I'm going through this right now. Nothing works... investigating.

**Comment by CMoH** [comment]
Following the project's "troubleshooting instructions":http://redmine-git-hosting.io/troubleshooting/#unsupported-url-protocol I have found that a better expression is `bundle exec gem uninstall rugged` - basically this accounts for the `vendor/bundle` folder location of the gems.

On Gentoo I had to `emerge libssh2` for this rugged gem.

**Comment by ArcolaJasper** [comment]
On Debian you need libssh-dev for rugged to build with ssh support.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.

**Comment by iq2luc** [comment]
> Following the project's "troubleshooting instructions":http://redmine-git-hosting.io/troubleshooting/#unsupported-url-protocol I have found that a better expression is `bundle exec gem uninstall rugged` - basically this accounts for the `vendor/bundle` folder location of the gems.
> 
> On Gentoo I had to `emerge libssh2` for this rugged gem.

Thanks a lot! Adding libssh2-dev (on Alpine) saved my day.

**Comment by Alwaysin** [comment]
From Redmine 5.0, using rugged 1.5.0.1, you need to build the gem with a specific flag to make it work with SSH:

```
gem uninstall rugged
gem install rugged -- --with-ssh
```

Cf. https://github.com/libgit2/rugged/pull/928/files
