### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by michelerota** [jbox-web/redmine_git_hosting#682]
the website http://redmine-git-hosting.io/ is down

**Comment by n-rodriguez** [comment]
HI! Yeah, I know, it wiil be back soon :)

**Comment by artembeloglazov** [comment]
Version of 2016: http://web.archive.org/web/20161030000441/http://redmine-git-hosting.io

**Comment by hubiktomas** [comment]
Temporarily append a line to the /etc/hosts file as follows:

`151.101.72.133 redmine-git-hosting.io`

And it will work. No need for archive.

**Comment by Warlib1975** [comment]
The problem still exists. :-(
