### ISSUE TITLE
Annotation doesnt work - undefined method "is_binary_data?"

### ISSUE THREAD

**Issue by IOMK** [jbox-web/redmine_git_hosting#684]
Hi,

after updating to the new Redmine 3.4.2 and the new redmine_git_hosting 1.2.3 there’s an error if you try to annotate some file in a repostitory trough the website 

>Started GET "/projects/internal-testproject/repository/revisions/master/annotate/Testfile" for <IP> at >2017-07-28 10:48:14 +0200
>Processing by RepositoriesController#annotate as HTML
>  Parameters: {"id"=>"internal-testproject", "rev"=>"master", "path"=>"Testfile"}
>  Current user: admin 
> Completed
> 500 Internal Server Error in 27ms (ActiveRecord: 11.7ms)

>NoMethodError (undefined method is_binary_data?' for #<String:0x007feef34b95a8>):
> plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:360:in annotate'
>  app/controllers/repositories_controller.rb:184:in annotate'
> lib/redmine/sudo_mode.rb:63:in sudo_mode'`

I'm not really sure if its a problem of the plugin,or redmine itself.
I followed the upgrade procedure and did the `rake redmine:plugins:migrate` and the rest.
Any ideas how to fix it?

**Comment by seberoth** [comment]
I had the same issue. You need to edit the following line:

https://github.com/jbox-web/redmine_git_hosting/blob/devel/lib/redmine/scm/adapters/xitolite_adapter.rb#L360

Replace:

`return nil if content.is_binary_data?`

with:

`return nil if ScmData.binary?(content)`

**Comment by corozcop** [comment]
#684
