### ISSUE TITLE
Hooks URL returns 404

### ISSUE THREAD

**Issue by EvilBMP** [jbox-web/redmine_git_hosting#688]
Sorry, I didn't find any information on the web regarding this topic so I open an issue. I installed redmine_git_hosting today as documentated on the website.

Server/ Software configuration is Ubuntu 14.04 LTS with Ruby 2.1.3 and Redmine 3.2. Redmine is served by Puma which is proxied by an Apache2 webserver, as other tools are running on that server as well.

Well everything seems to work - I installed the hooks via GUI link in the configuration section and the symlinks are added to the git repositories via gitolite. Config test is all green. But when I push something the post-receive hooks are not called.

So I tried to debug this and started with a call of the Hooks URL in my web browser, which results in a 404. 

Called: https://hostname/githooks/post-receive/redmine

That should not be the case?! Any idea?

**Comment by drewlsvern** [comment]
I just set this plugin up today as well, I have the same issue. Although my config-test shows that no hooks are installed.

My config is a bit different than @EvilBMP has.

Ubuntu 16.04 LTS
Ruby 2.4.1
Rails 4.2.8
Redmine 3.4.4
Gitolite 2.7.4

I have attached a screenshot of my config test.

Any help would be much appreciated.

![capture](https://user-images.githubusercontent.com/6773010/35084958-1709bda0-fbec-11e7-9356-8a85d0355142.PNG)

**Comment by EvilBMP** [comment]
To shed some light on the dark, I want to add some notes to this topic.

First, the hooks always execute, if you push via ssh.
Second, if you push via http(s) - DAV - then repository name must be the same as the project identifier. Otherwise it will not work. This is a bug/ limitation in Redmine, not in Gitolite!
So, if you have multiple repositories per project, pushing via http(s) will Work only for the main (respectively the repo with name=project identifier) repository.

That's why we completely switched from http(s) to ssh authentication with private/ public keys for every developer.

**Comment by cbobof** [comment]
Hello,
I have exactly te same problem, my git repositories are never refresh.
my configuration seems clean
when i check hooks url, it returns 404 error  and the path "githooks/post-receive/redmine"  doesn't match with anything on redmine host.
do you know what am I doing wrong ? 

![capture](https://user-images.githubusercontent.com/51409543/58961158-ddfb4c00-87a8-11e9-8140-eb232812315e.png)

**Comment by n-rodriguez** [comment]
> when i check hooks url, it returns 404 error and the path "githooks/post-receive/redmine" doesn't match with anything on redmine host.

It's a POST url, it won't work in your browser.

**Comment by n-rodriguez** [comment]
```sh
                                                      POST                /githooks/post-receive/:type/:projectid                                                 #<Rack::Builder:0x00563aa1aca350 @run=#<Hrack::Server:0x00563aa1aca1e8>, @map=nil, @use=[#<Proc:0x00563aa1aca210@/data/www/redmine/shared/bundle/ruby/2.3.0/gems/rack-1.4.7/lib/rack/builder.rb:82>]>
```

**Comment by cbobof** [comment]
thank you, i had error in my  url.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
