### ISSUE TITLE
Migrate Redmine database to new server without this plugin

### ISSUE THREAD

**Issue by ioiobzit** [jbox-web/redmine_git_hosting#696]
Hello,

I'm migrating my actual installation to a new server.
I would like to migrate my actual redmine DB without using the redmine_git_hosting plugin.
What do I have to do to migrate it successfully?

If only the DB is migrated redmine gives the following error:

Completed 500 Internal Server Error in 139ms (ActiveRecord: 7.6ms)

ActionView::Template::Error (The single-table inheritance mechanism failed to locate the subclass: 'Repository::Xitolite'. This error is raised because the column 'type' is reserved for stori
ng the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Repository.inheritance_column to use another c
olumn for that information.):
    87:     <% end %>
    88: 
    89:     <h1><%= page_header_title %></h1>
    90: 
    91:     <% if display_main_menu?(@project) %>
    92:     <div id="main-menu" class="tabs">
    93:         <%= render_main_menu(@project) %>
  lib/redmine.rb:297:in `block (2 levels) in <top (required)>'
  lib/redmine/menu_manager.rb:483:in `allowed?'
  lib/redmine/menu_manager.rb:194:in `block in menu_items_for'
  lib/redmine/menu_manager.rb:193:in `each'
  lib/redmine/menu_manager.rb:193:in `menu_items_for'
  lib/redmine/menu_manager.rb:112:in `render_menu'
  lib/redmine/menu_manager.rb:101:in `render_main_menu'
  app/views/layouts/base.html.erb:90:in `_app_views_layouts_base_html_erb___1289057474886282866_70281887541140'
  app/controllers/projects_controller.rb:165:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Thank you

**Comment by ioiobzit** [comment]
I've tried with:

rake redmine:plugins:migrate NAME=plugin_name VERSION=0 RAILS_ENV=production

but got no luck since it gives the following error:

mysql2::Error: Table 'git_cia_notifications' already exists

Anyone?

**Comment by nicolasmeric** [comment]
When you uninstall the plugin, the repositories are not deleted from the repositories table. You have to delete the rows yourself :

**Comment by ioiobzit** [comment]
Thank you
