### ISSUE TITLE
git annex works?

### ISSUE THREAD

**Issue by kovalevvv** [jbox-web/redmine_git_hosting#698]
i have installed git annex on server and client, using http://redmine-git-hosting.io/how-to/install-addons/
ok, when i push files i see error

`# git annex sync --content
commit
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
ok
pull origin
ok
copy bin (checking origin...) (to origin...)
SHA256E-s42106880--b9e1d42e98d20aae7d98f34f63f175e63578c895f3ac4c74c7e2d3d777c03e38
     42,106,880 100%   82.39MB/s    0:00:00 (xfr#1, to-chk=0/1)
rsync: open "/home/git/repositories/annex.git/annex/tmp/SHA256E-s42106880--b9e1d42e98d20aae7d98f34f63f175e63578c895f3ac4c74c7e2d3d777c03e38" failed: Permission denied (13)
git-annex: /home/git/repositories/annex.git/annex/objects: createDirectory: permission denied (Permission denied)
git-annex-shell: recvkey: 1 failed
rsync error: syntax or usage error (code 1) at main.c(1196) [sender=3.1.2]

  rsync failed -- run git annex again to resume file transfer
failed
push origin
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (8/8), 1.11 KiB | 1.11 MiB/s, done.
Total 8 (delta 1), reused 0 (delta 0)

Notifying Redmine about changes to this repository : 'x-test/annex' ...
  - Fetching changesets for 'annex' repository ...  [success]

Looking for additional global post-receive hooks...
  - Global hooks found : ["hooks/post-receive.d/mail_notifications"]

Looking for additional local post-receive hooks...
  - No local hooks found
remote:
Calling additional post-receive hooks...
  - Executing extra hook 'hooks/post-receive.d/mail_notifications'
    multimailhook is disabled

To ssh://172.16.250.218/annex.git
   edebc0a..9aaf9ee  git-annex -> synced/git-annex
   bd12ee6..ca2afd4  master -> synced/master
ok
git-annex: sync: 1 failed
`

in documentation 

> By default git annex sync only syncs the metadata about your files that is stored in git. It does not sync the contents of files, that are managed by git-annex. To do that, you can use git annex sync --content

How i can using redmine-git-hosting with git annex? i see annex using rsync, but ssh server denied these operation ;( i need upload big file to repo, share and storage in redmine. Standalone git give me error when i push big files.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
