### ISSUE TITLE
Unable to install redmine_git_hosting Plugin

### ISSUE THREAD

**Issue by SchorppD** [jbox-web/redmine_git_hosting#709]
Hello there,
I am trying to install the git_hosting_plugin on debian.
Should not be that difficult - normally :(

I installed all dependencies,
after that I proceed to step 2.
I clone the repos in ./plugins and check them out according to the instruction.
I continue with...
```
# Install gems and migrate database
redmine$ cd REDMINE_ROOT
redmine$ bundle install --without development test
redmine$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting

I can execute "bundle install --without development test" without any problems. 
As soon as I try to "bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting"

I get the following error
rake aborted!
LoadError: cannot load such file -- redmine_git_hosting
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
etc...........
```
Whats wrong? LoadError normally shows a missing dependency in the gems.
I found nothing on the web. Is there anybody with a solution/tip? 

Thank you!

**Comment by SchorppD** [comment]
I managed to get it working by chaning the "require" in some of the *.rb files to "require_relative "./xxx". After that, the migration process started. Unfortunatelly I ran into the next issue. As soon I logon to Redmine (btw. it is EasyRedmine Debian VM v2018.01.04) I get an error 500 when I am trying e.g. to load the projects list... (other sites do still work)

The log shows things like...
ActionView::Template::Error (undefined method `new' for <#Hash..xxx..): etc.

Any ideas?

**Comment by rtestaverde** [comment]
Hi all, we're facing the same problem 
Ubuntu 14.04 
Ruby 2.5
EasyRedmine 2018
Redmine Git Hosting 1.2.3 

in file [plugindir]/redmine_git_hosting/init.rb we tried to change require 'redmine_git_hosting' with require_relative '.' but no changes in the migration. Commenting it, the migrations reads RedmineGitHosting. constant unknown...

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
