### ISSUE TITLE
redmine with smart http and redmine_git_hosting does not allow pushing to repository

### ISSUE THREAD

**Issue by ghost** [jbox-web/redmine_git_hosting#717]
Redmine version: 3.4.4.stable
redmine_git_hosting plugin version: 1.2.3
gitolite v.3

HTTPS only access to repositories. I can clone OK but when pushing I get the following error:

fatal: Authentication failed for '<repo URL>'

On the server side in the git_hosting.log I get the following error however:

SmartHttp : your are trying to push data without SSL!, exiting !

I am confused on what the real cause of the problem is

My virtual host redmine configuration file is:

`<VirtualHost *:443>
     ServerName .....
     ServerAlias ......
     ServerAdmin ....
     DocumentRoot  /opt/redmine/public
     PassengerRuby ......
     PassengerFriendlyErrorPages on

     ErrorLog /var/log/httpd/redmine-error_log
     CustomLog /var/log/httpd/redmine-access_log common

    <Directory "/opt/redmine">
      Require all granted
      # MultiViews must be turned off
      Options -MultiViews
    </Directory>

    PerlLoadModule Apache::Authn::Redmine

    <Location />
     Order allow,deny
     Allow from all

     PerlAccessHandler Apache::Authn::Redmine::access_handler
     PerlAuthenHandler Apache::Authn::Redmine::authen_handler

     RedmineDSN "DBI:Pg:database=redmine;host=127.0.0.1" 
     RedmineDbUser "redmine" 
     RedmineDbPass "xxxxx" 

     RedmineGitSmartHttp yes
   </Location>
</VirtualHost>`

**Comment by tetoroa** [comment]
OK, I've figured it out (no thanx to the obscure error messages). I must be the only one who is using https!
Basically my virtual host configuration is missing 3 entries re SSL:
SSLEngine on
SSLCertificateFile
SSLCertificateKeyFile

Can the documentation on the website page http://redmine-git-hosting.io/how-to/install-addons/ be update to reflect this? It may help someone from pulling the hair out like I did :-)

**Comment by afinello** [comment]
Actually, you have to pass the right headers to redmine to support https besides just configuring it with Apache:

```
RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}
```

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
