### ISSUE TITLE
Plugin fails to determine git version

### ISSUE THREAD

**Issue by CMoH** [jbox-web/redmine_git_hosting#720]
Here is a shell conversation that I believe explains what's wrong:

```
redmine@dev ~ $ tail -n1 log/git_hosting.log 
2018-07-03 23:23:47 +0300 [ERROR] Can't retrieve Git version: Non-zero exit code pid 29467 exit 129 for `sudo -n -u git -i git --version --no-color`
redmine@dev ~ $ sudo -n -u git -i git --version --no-color
error: unknown option `no-color'
usage: git version [<options>]

    --build-options       also print build options

redmine@dev ~ $ sudo -n -u git -i git --version      
git version 2.16.4

```

**Comment by CMoH** [comment]
Is this due to the same problem?
![image](https://user-images.githubusercontent.com/663132/42425657-dd6d0e84-8328-11e8-9624-a5a071bd4aa5.png)

It would not bother me that much, except when I try to create a new repository I'm getting this thing, and the `Create` button is disable:
![image](https://user-images.githubusercontent.com/663132/42425679-145899ea-8329-11e8-9a64-2c99e0acbdf4.png)

What can I do?

**Comment by munzeitig** [comment]
Hello as regards the "error: unknown option `no-color'", this I have solved by upgrading Redmine to latest version and the error does not show up anymore.
(https://github.com/sameersbn/docker-redmine/issues/305)

Still I am having the issue with plugin not recognizing the git version for Xitolite. (neither at 
/settings/plugin/redmine_git_hosting)
Native Redmine git gets the version without problem.

**Comment by munzeitig** [comment]
Hello,
similar problem was discussed with the Redmine native "git".
See https://github.com/sameersbn/docker-redmine/issues/305

So I beleive you need to analogically edit
plugins/redmine_git_hosting/lib/redmine_git_hosting/commands/git.rb  and
plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb
and remove the "--no-color" parameter from there.

**Comment by munzeitig** [comment]
Just to confirmed, I have edited the 2 files mentioned above and it works fine now.

**Comment by CMoH** [comment]
Thank you. I applied your changes and now the plugin works. Maybe I can turn this into a PR which works on both git versions.

**Comment by devpap** [comment]
I got the problem mentioned by CMoH , but my versions are different. Even while I m using git version 2.11.0 I changed the files out of despair without any luck.
The log file looks good. No errors there. Got the same problems with the hooks. I m using nginx and puma.

Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [armv7l-linux-eabihf]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_bootstrap_kit          0.2.5
  redmine_git_hosting            1.2.3

**Comment by pva** [comment]
While it is correct to remove --no-color in git --version, it is bad idea to remove --no-color in xitolite_adapter.rb since log/diff/branch commands have this argument. So the only change that is needed is in ./lib/redmine_git_hosting/commands/git.rb.

**Comment by PowerKiKi** [comment]
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.
