### ISSUE TITLE
How to create key for "My public keys"

### ISSUE THREAD

**Issue by devacon** [jbox-web/redmine_git_hosting#721]
Hello,

how to create a public key which fits to Redmine "my public keys" section?
I tried some public keys made with putty, bt I got always the error: this key seems to be corrupted. 

Thx
EM

**Comment by porzione** [comment]
You have to use `ssh-keygen` from OpenSSH or [export keys from putty](https://stackoverflow.com/questions/2224066/how-to-convert-ssh-keypairs-generated-using-puttygenwindows-into-key-pairs-use).

**Comment by devacon** [comment]
Perfect...thank you
