### ISSUE TITLE
redmine_git_hosting:update_repositories generate empty commit on gitolite config GIT

### ISSUE THREAD

**Issue by sboisson** [jbox-web/redmine_git_hosting#728]

**Comment by sboisson** [comment]
When I perform the rake command, the configuration is not updated.
I tried on a empty config file and the repos config are not restored

**Comment by sboisson** [comment]
When I perform the Rescue > Resync all projects, the config is updated.
Is there a way to have the same behavior in command line?

**Comment by alexandermeindl** [comment]
Hi @sboisson 

thanks for reporting this! With my last push I made a change to force a resync with rake task _update_repositories_. Let me know, if this works for you.

**Comment by alexandermeindl** [comment]
As I already wrote, this should work with https://github.com/jbox-web/redmine_git_hosting/commit/f9086b16e9c348ae10a206d716eed0100eef0bc0. If you have problems with the latest version, please reopen this issue.
