### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by n-rodriguez** [jbox-web/redmine_git_hosting#732]
Hi!

I'm looking for maintainers to help me on this project. I'm the only one with `commit` permission and it blocks development. So if you know a little bit of Ruby, Rails and Redmine please ask me to add you as a contributor :+1: 
Thank you!

**Comment by PowerKiKi** [comment]
hi, my Ruby knowledge is limited, but I would like to help, to finalize the Redmine 4 support by:

- merging devel into master
- make a propre release
- closing all issues regarding Redmine 3 and older

Would you add me to the project ?
