### ISSUE TITLE
Fresh install and it doesn't work

### ISSUE THREAD

**Issue by mrPsycho** [jbox-web/redmine_git_hosting#741]
Hello, 
i already created two tickets while i was trying install this plugin.. and they are mostly for documentation..

so maybe this one depends on it, but nowhere written.

when i add public key on redmine UI, key don't get in authorized_keys file for `git` user. also, no projects are being created under /home/git/repositories.... 
on logs i see this error: 
```
2019-12-07 21:00:48 +0300 [ERROR] Git exited with non-zero status : 128 : 'sudo' '-n' '-u' 'git' '-i' 'git' '--git-dir' 'repositories/inet/
qwe.git' '-c' 'core.quotepath=false' '-c' 'log.decorate=no' 'branch' '--no-color' '--verbose' '--no-abbrev'
```
but, from `redmine` i can do this command

what to check?

**Comment by pulecp** [comment]
Hi @mrPsycho,

make sure that your test page is green at first

https://redmine.example.com/settings/plugin/redmine_git_hosting?tab=gitolite_config_test

**Comment by mrPsycho** [comment]
It is green: 
![redmine](https://user-images.githubusercontent.com/883964/79909964-83052e80-8426-11ea-9182-6c048c00d3f0.png)

**Comment by PowerKiKi** [comment]
Assuming this is either resolved or obsolete.
