### ISSUE TITLE
Unable to access to plugin admin

### ISSUE THREAD

**Issue by TheAtlantis** [jbox-web/redmine_git_hosting#743]
Hi, 

I have installed **redmine 4.0.6** on **Centos 8** with git **hosting plugin 4.0.0**.
When I try to access to plugin administration (settings/plugin/redmine_git_hosting), I have a 500 server internal error on brower.

Error present in production.log :

> Started GET "/settings/plugin/redmine_git_hosting" for 192.168.1.18 at 2020-01-23 14:11:19 +0100
> 
> Processing by SettingsController#plugin as HTML
>   Parameters: {"id"=>"redmine_git_hosting"}
>   Current user: admin (id=1)
>   Rendering settings/plugin.html.erb within layouts/admin
>   Rendered plugins/redmine_git_hosting/app/views/common/_git_hosting_js_headers.html.slim (3.2ms)
>   Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_ssh.html.slim (1.2ms)
>   Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_storage.html.slim (1.2ms)
>   Rendered plugins/redmine_git_hosting/app/views/settings/redmine_git_hosting/_gitolite_config_file.html.slim (32.0ms)
>   Rendered common/_tabs.html.erb (40.5ms)
>   Rendered plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.slim (45.6ms)
>   Rendered settings/plugin.html.erb within layouts/admin (47.1ms)
> Completed 500 Internal Server Error in 58ms (ActiveRecord: 3.5ms)
> 
> ActionView::Template::Error (No such file or directory - pandoc):
> 

My environement : 

> Environment:
>   Redmine version                4.0.6.stable
>   Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux]
>   Rails version                  5.2.4.1
>   Environment                    production
>   Database adapter               Mysql2
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> SCM:
>   Git                            2.18.2
>   Filesystem                     
>   Xitolite                       2.18.2
> Redmine plugins:
>   additionals                    2.0.22-1
>   redmine_base_deface            1.5.3
>   redmine_ckeditor               1.2.2
>   redmine_git_hosting            4.0.0
>   redmine_lightbox2              0.5.1
>   redmine_pandoc_formatter       1.0

Have you an idee to solve that ?

Thank you for your work

**Comment by Luckyvb** [comment]
debian
redmine 4.1.1

**Comment by Luckyvb** [comment]
sudo apt install pandoc
and reload web service help me.
not any one of requirements say about this :(

**Comment by alexandermeindl** [comment]
Hi @Luckyvb,
you use a plugin called redmine_pandoc_formatter. I suppose this requires pandoc.
This package is not required for redmine_git_hosting.
