### ISSUE TITLE
NameError: uninitialized constant RSpec

### ISSUE THREAD

**Issue by n0rvik** [jbox-web/redmine_git_hosting#749]
### rake aborted!

Hi

### I updated redmine 4.0.5 -> 4.1.0.

I get an error while running the command

`"bundle exec rake generate_secret_token".`

<pre>
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Mercurial                      5.2.2
  Bazaar                         2.5.1
  Git                            2.9.3
  Filesystem                     
  Xitolite                       2.9.3
Redmine plugins:
  additionals                    2.0.23
  progressive_projects_list      4.0.0
  redmine_git_hosting            4.0.1
  redmine_issue_badge            0.1.3
  redmine_tags                   4.0.0
</pre>

---

<pre>
[~/redmine]$ bundle exec rake generate_secret_token
rake aborted!
NameError: uninitialized constant RSpec
/mnt/storage/opt/redmine/redmine/plugins/redmine_git_hosting/lib/tasks/ci_tools.rake:4:in `block (2 levels) in <top (required)>'
/mnt/storage/opt/redmine/redmine/plugins/redmine_git_hosting/lib/tasks/ci_tools.rake:2:in `block in <top (required)>'
/mnt/storage/opt/redmine/redmine/plugins/redmine_git_hosting/lib/tasks/ci_tools.rake:1:in `<top (required)>'
/mnt/storage/opt/redmine/redmine/lib/tasks/redmine.rake:202:in `load'
/mnt/storage/opt/redmine/redmine/lib/tasks/redmine.rake:202:in `block in <top (required)>'
/mnt/storage/opt/redmine/redmine/lib/tasks/redmine.rake:202:in `each'
/mnt/storage/opt/redmine/redmine/lib/tasks/redmine.rake:202:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `load'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `block in run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `each'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:515:in `run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:459:in `load_tasks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/railtie.rb:190:in `public_send'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/railtie.rb:190:in `method_missing'
/mnt/storage/opt/redmine/redmine/Rakefile:7:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

</pre>

---

<pre>
[~/redmine/plugins/redmine_git_hosting]$ git branch
* (HEAD detached at 4.0.1)
  devel
</pre>

---

<pre>  
~/redmine/plugins]$ ll
drwxr-xr-x 11 redmine redmine 4096 Feb 28 11:43 additionals
drwxr-xr-x  7 redmine redmine  118 Feb 28 11:39 progressive_projects_list
drwxr-xr-x 11 redmine redmine  306 Feb 28 11:57 redmine_git_hosting
drwxr-xr-x 13 redmine redmine 4096 Feb 28 12:36 redmine_issue_badge
drwxr-xr-x  9 redmine redmine  261 Feb 28 11:39 redmine_tags
</pre>

**Comment by EvilBMP** [comment]
Any news here? I am still on `ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-linux]` but I have the same issue when I want to run rake commands.

**Comment by n0rvik** [comment]
### rake aborted!
NameError: uninitialized constant RSpec
  

ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

Rails 5.2.4.2

Redmine 4.1.1


`
[~/redmine-4.1.1/plugins/redmine_git_hosting]$ git branch
* (HEAD detached at 4.0.1)
  devel

$ bundle exec rake tmp:cache:clear  tmp:sockets:clear
rake aborted!
NameError: uninitialized constant RSpec
/mnt/storage/opt/redmine/redmine-4.1.1/plugins/redmine_git_hosting/lib/tasks/ci_tools.rake:4:in `block (2 levels) in <top (required)>'
/mnt/storage/opt/redmine/redmine-4.1.1/plugins/redmine_git_hosting/lib/tasks/ci_tools.rake:2:in `block in <top (required)>'
/mnt/storage/opt/redmine/redmine-4.1.1/plugins/redmine_git_hosting/lib/tasks/ci_tools.rake:1:in `<top (required)>'
/mnt/storage/opt/redmine/redmine-4.1.1/lib/tasks/redmine.rake:202:in `load'
/mnt/storage/opt/redmine/redmine-4.1.1/lib/tasks/redmine.rake:202:in `block in <top (required)>'
/mnt/storage/opt/redmine/redmine-4.1.1/lib/tasks/redmine.rake:202:in `each'
/mnt/storage/opt/redmine/redmine-4.1.1/lib/tasks/redmine.rake:202:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:656:in `load'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:656:in `block in run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:656:in `each'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:656:in `run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/application.rb:515:in `run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/engine.rb:459:in `load_tasks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/railtie.rb:190:in `public_send'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.2/lib/rails/railtie.rb:190:in `method_missing'
/mnt/storage/opt/redmine/redmine-4.1.1/Rakefile:7:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
`

**Comment by n0rvik** [comment]
Like this. This is how it works:

<pre>
bundle exec rake tmp:cache:clear  tmp:sockets:clear RAILS_ENV=production
</pre>

**Comment by PowerKiKi** [comment]
Assuming this is either resolved or obsolete.

**Comment by picman** [comment]
Yes, the problem is in the missing RAILS_ENV variable:
```bash
bundle exec rake generate_secret_token
rake aborted!
NameError: uninitialized constant RSpec
```
```bash
bundle exec rake generate_secret_token RAILS_ENV=production
````

**Comment by picman** [comment]
A part of the code responsible for the error is in _lib/tasks/c_tool.rake_. I think that this is wrong.
```ruby
unless Rails.env.production?
    RSpec::Core::RakeTask.new do |task|
      task.rspec_opts = '--pattern plugins/redmine_git_hosting/spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --color'
    end
  end
```
