### ISSUE TITLE
Gemfile still missing rdoc dependency

### ISSUE THREAD

**Issue by kevinpowell** [jbox-web/redmine_git_hosting#750]
new install on redmine 4.0.x  -- 'bundle exec rake' step fails because of missing rdoc dependency.

**Comment by alexandermeindl** [comment]
rdoc has been removed from Gemfile of redmine with https://www.redmine.org/projects/redmine/repository/revisions/17706. If you have same problems with redmine_git_hosting plugin 5.0.0 or newer, feel free and reopen this issue.
