### ISSUE TITLE
"View differences" tab reporting 500 error

### ISSUE THREAD

**Issue by rchady** [jbox-web/redmine_git_hosting#751]
Have an issue where clicking on the "View differences" tab in a repository is returning a 500 error.  The log shows:

```2020-04-02 12:31:55 -0400 [ERROR] DB Adapter : could not insert in cache, this is the error : 'Mysql2::Error: MySQL client is not connected: ROLLBACK'```

and

```app/models/repository/git.rb:92:in `find_changeset_by_name'
plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:150:in `diff_with_options'
plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:51:in `diff'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'```

Everything else seems to be working fine before and after, it just is that one link that seems to be broken.

I am running 4.0.0 on Redmine 4.0.6.

**Comment by alexandermeindl** [comment]
Hi @rchady.

can you try with our latest release 5.0.0 again? Let me know, if the problem still exists.

**Comment by alexandermeindl** [comment]
Please reopen this issue, if you have this problem with our latest version.
