### ISSUE TITLE
get_started does not work

### ISSUE THREAD

**Issue by MaxP69** [jbox-web/redmine_git_hosting#754]
Hi! 
I've got a error at bundle install --without development test

[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rubocop (~> 0.76.0) and rubocop (>= 0). Bundler cannot continue.
```

 #  from /usr/share/redmine/plugins/redmine_git_hosting/Gemfile:46
 #  -------------------------------------------
 #  
 >    gem 'rubocop', require: false
 #    gem 'rubocop-rspec'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /usr/share/redmine/Gemfile:101
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------

```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.4.2

Is 4.1.1 unsupported ?

**Comment by madc** [comment]
As a workaround (hack), we removed the following line from the plugins `Gemfile`:
https://github.com/jbox-web/redmine_git_hosting/blob/devel/Gemfile#L45-L46

It seems to work.

**Comment by madc** [comment]
This PR seems to have an even better solution:
https://github.com/jbox-web/redmine_git_hosting/pull/759/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478L45-L46

**Comment by n0rvik** [comment]
put it in a file Gemfile

<pre>
...
  #gem 'rubocop', require: false
</pre>

**Comment by alexandermeindl** [comment]
Rubocop has been removed from Gemfile in release 5.0.0. This problem should be solved with it.
