### ISSUE TITLE
Why is "additionals" plugin required in latest version?

### ISSUE THREAD

**Issue by EvilBMP** [jbox-web/redmine_git_hosting#755]
We've been using redmine_git_hosting for a long time already, but after migrating Redmine to version 4.1 and updating redmine_git_hosting as well, I was wondering why the "additionals" Plugin has been put as a requirement for redmine_git_hosting. The "additionals" Plugin offers way to much features, we actually don't need and it's also not possible to disable some of them.

So is this hard dependency between these two plugins really necessary? IMHO they have nothing to do with each other...

**Comment by PowerKiKi** [comment]
See 55cf8f48bbb49ae1e901aa985cd0cf414736d3d8, https://github.com/jbox-web/redmine_git_hosting/pull/727#issuecomment-502940120 and https://github.com/jbox-web/redmine_git_hosting/blob/master/CHANGELOG.md#400 for hints as to why it is a hard requirement.
