### ISSUE TITLE
UI-Problem rendering diff view: observeAutocompleteField is not defined

### ISSUE THREAD

**Issue by sseide** [jbox-web/redmine_git_hosting#763]
Currently we heave sometimes the strange behaviour that viewing the diff between git revisions the page inside the browser only displays  pure text black on white - no graphics colors and so on. Looks like a pure text page without any JS/CSS/...
For these diffs it seems reproducable.

Opening the Javascript console from the browsers it says
```
ReferenceError: observeAutocompleteField is not defined`
<anonym> https://redmine.myserver.de/myproject/projects/myrepo/revisions/a97a60b95df1d19d5d1044b0639cf6e6d7857aa6/diff/server.js:53
```
Checking the HTML source code has a script tag it seems it cannot resolv:
```
<script>
//<![CDATA[
observeAutocompleteField('issue_id', '/issues/auto_complete?project_id=myproject&scope=all')
//]]>
</script>
```

As i said - its not happening often, just sometimes. Most of the diff views are right. And i cannot really tell why its happening for these files. Reloading the page when this happens does not solve it. Going back, view other diffs its working and than back to the file above - no rendered HTML again and this error.

Redmine "production.log" no error:
```
Started GET "/projects/myproject/repository/myrepo/revisions/a97a60b95df1d19d5d1044b0639cf6e6d7857aa6/diff/server.js" for 93.253.7.200 at 2020-06-26 16:36:55 +0200
Processing by RepositoriesController#diff as JS
  Parameters: {"id"=>"nomad-web-application-2-0", "repository_id"=>"myrepo", "rev"=>"a97a60b95df1d19d5d1044b0639cf6e6d7857aa6", "path"=>"server.js"}
  Current user: myuser (id=3)
  Rendering repositories/diff.html.erb
  Rendered repositories/_related_issues.html.erb (2.3ms)
  Rendered common/_tabs.html.erb (0.3ms)
  Rendered repositories/_changeset.html.erb (9.9ms)
  Rendered repositories/diff.html.erb (12.7ms)
Completed 200 OK in 37ms (Views: 10.9ms | ActiveRecord: 18.9ms)
```
NGinx and redmine_git_hosting logs do not show any errors too.

Someone has an idea? Maybe incomplete quoted source code? Something else to check?

Redmine 4.0.7
Redmine Git Hosting 4.0.1
Browsers: Firefox ESR 8LLinux), Safari, Chrome (MacOs), others not testet

Thanks in advance,
Stefan

**Comment by n-rodriguez** [comment]
Hi!

There are 2 things to consider :

* either Redmine JS lib has evolved and `observeAutocompleteField` is no longer available
* or you're on *BSD and you run Redmine with a unix socket. This can cause errors like this one because BSD sockets behave differently than on Linux. Switch to `ip:port` and see if it's improving.

**Comment by sseide** [comment]
Hi,

thanks for the fast response.

First - `observeAutocompleteField` is there, already checked. Its part of Redmines application.js file
And second one  - I am on Debian Linux 10 using Redmine from Debian Backports  (Version: `4.0.7-1~bpo10+1`)
And Redmine itself is run with Passenger (`1:6.0.5-1~buster1`) inside NGinx using mod-http-passenger from Phusions debian repo.

And its not happening for all diff view. Most files from a git commit i can click on `myfile.js (diff)` behind the file name and its displayed fine. Only some files do not work. And its reproducible on this "some" files, All clients checked have this problems with `observeAutocompleteField` on this specific diffs.

Here is one of the not working ones (no matter what OS/browser used, reproducible)

![diff_not_working](https://user-images.githubusercontent.com/5168949/85902173-ade37880-b803-11ea-9059-91b95285af73.png)

And here one example where its working for all. Just another file from the same commit. And most diffs look like this

![diff_working](https://user-images.githubusercontent.com/5168949/85902175-af14a580-b803-11ea-8267-f7afd0446c0e.png)

I can freely change between them - working/not working stays the same... Seems to be something of the content inside the diff? Another ideas?

**Comment by n-rodriguez** [comment]
> Seems to be something of the content inside the diff?

Maybe...

**Comment by sseide** [comment]
If its a client side problem i can attach a javascrit debugger and have a look? But need some help where its best to place breakpoints.

**Comment by return1** [comment]
this has been fixed in Redmine Version 4.1.1 and 4.0.7, see https://www.redmine.org/issues/32449

**Comment by sseide** [comment]
thanks for the hint.

As i'm already at Redmine 4.0.7 (Debian backports 4.0.7-1~bpo10+1) the file mentioned at the Redmine issue already contains this fix.
But as i understand the `redmine_git_hosting` pugin is patching this file with its own code. And this code does not contain this patch as of now...

https://github.com/jbox-web/redmine_git_hosting/blob/079e2442cbed0c95539f606d3a8caa761c9e210e/lib/redmine_git_hosting/patches/repositories_controller_patch.rb#L150-L153

Patch from https://www.redmine.org/issues/32449 should be applied here too?

The problem i see is very similar to the one in the original Redmine issue. Happens for JS files and no base template seems to be used (HTML code returned starts with a `<div>` Tag instead of `<html>`).

**Comment by sseide** [comment]
adding the change from comment 4 (https://www.redmine.org/issues/32449#note-4) to the file `redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb` line 153 seems to fix the problem. Diff view is now rendered correctly.

**Comment by alexandermeindl** [comment]
Hi @sseide 
thanks for your feedback and your test. I fixed it with my last commit.

Thank you for your contribution!
