### ISSUE TITLE
Remove devel branch

### ISSUE THREAD

**Issue by PowerKiKi** [jbox-web/redmine_git_hosting#764]
@n-rodriguez could you please consider removing the branch `devel` and replacing the default branch with `master` ?

As it is now, `devel` brings no value, but only more maintenance work. Development already happens in dedicated branches via PR, without affecting stability of master. Stability of master is ensured via CI. And having to merge devel into master periodically only make us do more work, with a possibility of mistake (or forgetting to do it entirely).

**Comment by n-rodriguez** [comment]
done!

**Comment by PowerKiKi** [comment]
Thanks ! all PR have been rebased to master, and devel has been deleted entirely.
