### ISSUE TITLE
Question - Redmine repo settings - can "git" be disabled after plugin installation

### ISSUE THREAD

**Issue by sseide** [jbox-web/redmine_git_hosting#766]
Hello,

after installation of the "redmine_git_hosting" plugin there is a new Type of Repository "Xitolite" at "Adminstration -> "Settings" -> "Repositories".

Can "Git" be disabled here and "Xitolite" is enough? Or does disabling "Git" break some things.
Having booth enabled may lead to errors for project manager creating new repositories inside their projects as there are "Git" and "Gitolite" types available and its easy to use the wrong one here...

I did not have found any information regarding that inside the docs, only the explanation for the name "Xitolite" within the Admin area.

Thanks,
Stefan Seide

**Comment by n-rodriguez** [comment]
> Can "Git" be disabled here and "Xitolite" is enough?

yes

**Comment by sseide** [comment]
Thanks.

Would be good to add this as a remark to step 9 from http://redmine-git-hosting.io/get_started/ i think.
