### ISSUE TITLE
Failed to open TCP connection to localhost:3000 (Connection refused - connect(2).. when pushing changes to repository

### ISSUE THREAD

**Issue by theblackraven** [jbox-web/redmine_git_hosting#775]
Hi,

i'm using a lxc container with debian-buster image running  on a proxmox server.
i installed redmine, how it is explained in this installation guide : http://redmine-git-hosting.io/how-to/install-redmine/

then i installed the redmine_git_hosting plugin, with this installation guide:  http://redmine-git-hosting.io/get_started/

I had to add this step, when i created the ssh-key for the redmine user : 
`ssh-keygen -p -m PEM -f ssh_keys/redmine_gitolite_admin_id_rsa`    (issue : [https://github.com/jbox-web/redmine_git_hosting/issues/747#issuecomment-586971796](https://github.com/jbox-web/redmine_git_hosting/issues/747#issuecomment-586971796))

i think, that everything is installed correctly, inlcuding hooks etc. I can commit and clone to the repository and add a new repository to redmine projects. The only problem is, that the commits are not visible in Redmine.

I can push changes to the repository, but i get following error, when i push the changes:
```
remote: [1GNotifying Redmine about changes to this repository : 'laserplotter-eleksmaker/eleksmaker' ...        
remote: [1GHTTP_ERROR : Failed to open TCP connection to localhost:3000 (Connection refused - connect(2) for "localhost" port 3000)        
remote: [1G        
remote: [1GCalling additional post-receive hooks...        
remote: [1G  - Executing extra hook 'hooks/post-receive.d/mail_notifications'        
remote: [1G    multimailhook is disabled        

```

Redmine Environment
```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.20.1
  Filesystem                     
  Xitolite                       2.20.1
Redmine plugins:
  additionals                    2.0.24
  redmine_agile                  1.5.4
  redmine_checklists             3.1.18
  redmine_git_hosting            4.0.2
  redmine_issue_templates        1.1.0
  redmine_resources              1.0.4
  redmineup_tags                 2.0.8

```
[
![gitolite_config_test](https://user-images.githubusercontent.com/9560037/97297576-8274a700-1852-11eb-8e70-be5e0344c283.jpg)
](url)

**Comment by n-rodriguez** [comment]
check Hooks url (This url will be called by our Gitolite hook to trigger repository view refresh so be sure it’s callable)

**Comment by theblackraven** [comment]
how can i check, if this url is callable? 
the current hooks url is: http://localhost:3000/githooks/post-receive/redmine. That was the default value. If i try to connect with the browser to http://192.168.1.35:3000/githooks/post-receive/redmine the connection is rejected.
it's the first time i set up a git hosting system and i newer used hooks before :(

**Comment by n-rodriguez** [comment]
> If i try to connect with the browser to http://192.168.1.35:3000/githooks/post-receive/redmine the connection is rejected.

Yes, because it only responds to 'POST' requests (if my memory is good). Try with 192.1681.35, maybe it's an IPv6 issue (localhost resolve to `::1` and you're listening on `127.0.0.1`)

**Comment by theblackraven** [comment]
still the same problem: HTTP_ERROR : Failed to open TCP connection to 192.168.1.35:3000 (Connection refused - connect(2) for "192.168.1.35" port 3000)

**Comment by n-rodriguez** [comment]
Does Redmine respond on http://192.168.1.35:3000/ ?

**Comment by theblackraven** [comment]
i'm such an idiot :) 
http://127.0.0.1 is working. The problem was the port 3000

**Comment by theblackraven** [comment]
Thanks for helping and your great project

**Comment by n-rodriguez** [comment]
great :)
