### ISSUE TITLE
uninitialized constant Journald issue

### ISSUE THREAD

**Issue by scarab** [jbox-web/redmine_git_hosting#778]
Installed plugin 5.0.0. version as described in "Getting started" documentation on Debian 10.
Installed Thin as web server.
After any request got this error in Thin's logs:

/srv/redmine-4.1.1/plugins/redmine_git_hosting/lib/redmine_git_hosting/journal_logger.rb:3:in `<module:RedmineGitHosting>': uninitialized constant Journald (NameError)
        from /srv/redmine-4.1.1/plugins/redmine_git_hosting/lib/redmine_git_hosting/journal_logger.rb:1:in `<top (required)>'
        from /var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `each'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `block in eager_load!'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `each'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `eager_load!'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:356:in `eager_load!'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `each'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
        from /srv/redmine/config/environment.rb:16:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /srv/redmine/config.ru:3:in `block in <main>'
        from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `instance_eval'
        from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `initialize'
        from /srv/redmine/config.ru:1:in `new'
        from /srv/redmine/config.ru:1:in `<main>'
        from /usr/lib/ruby/vendor_ruby/rack/adapter/loader.rb:33:in `eval'
        from /usr/lib/ruby/vendor_ruby/rack/adapter/loader.rb:33:in `load'
        from /usr/lib/ruby/vendor_ruby/rack/adapter/loader.rb:42:in `for'
        from /usr/lib/ruby/vendor_ruby/thin/controllers/controller.rb:170:in `load_adapter'
        from /usr/lib/ruby/vendor_ruby/thin/controllers/controller.rb:74:in `start'
        from /usr/lib/ruby/vendor_ruby/thin/runner.rb:203:in `run_command'
        from /usr/lib/ruby/vendor_ruby/thin/runner.rb:159:in `run!'
        from /usr/bin/thin:6:in `<main>'

**Comment by alexandermeindl** [comment]
See #776
