### ISSUE TITLE
http_helper.rb:38: warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by tomhub** [jbox-web/redmine_git_hosting#784]
This a warning users gets when pushes into server:
```
Notifying Redmine about changes to this repository : 'gitolite-test-project/test' ...
remote: /var/lib/gitolite/local/hooks/common/lib/git_hosting/http_helper.rb:38: warning: URI.escape is obsolete
```
Server:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by alexandermeindl** [comment]
Hi @tomhub 

this looks like you have installed old hook scripts. You can update it, if you go to /settings/plugin/redmine_git_hosting?tab=gitolite_config_hooks and use the link "install hooks". This should solve your problem.

**Comment by tomhub** [comment]
I tried this - I even removed manually hooks from gitolite location, re-installed them through redmine, still the same..

**Comment by alexandermeindl** [comment]
Hi @tomhub 

you are right. I fixed it with my last commit to master branch. It would be great, if you test it.

**Comment by tomhub** [comment]
Hi Alexander
Thanks for quick update. It seems I cannot update to latest redmine_git_hosting: it expects additionals 3.0.2 version, but I only see 3.0.1: https://github.com/AlphaNodes/additionals/tags

**Comment by alexandermeindl** [comment]
Hi @tomhub 
additionals 3.0.2 should be released in the next 2 hours. Stay tuned ;)

**Comment by tomhub** [comment]
Seems fine now, thanks!
