### ISSUE TITLE
Broken links in howto

### ISSUE THREAD

**Issue by fairf4x** [jbox-web/redmine_git_hosting#794]
I have noticed that there are broken links in [howto](http://redmine-git-hosting.io/how-to/install-redmine/) instructions for installing redmine.
In particular:

- [puma config script](https://github.com/jbox-web/redmine_git_hosting/blob/devel/contrib/scripts/puma.rb)
- [puma start script](https://github.com/jbox-web/redmine_git_hosting/blob/devel/contrib/scripts/server_puma.sh)
- [debian init script](https://github.com/jbox-web/redmine_git_hosting/blob/devel/contrib/scripts/redmine)

I have figured out that all files can be found [here](https://github.com/jbox-web/redmine_git_hosting/tree/master/contrib/scripts) but the instructions might need some revision.

**Comment by alexandermeindl** [comment]
Hi @fairf4x 

thanks for reporting it. It should be fixed now.
