### ISSUE TITLE
WARNING: Zeitwerk defines the constant CoreExt after the directory

### ISSUE THREAD

**Issue by tomhub** [jbox-web/redmine_git_hosting#814]
When running puma server, I get these warnings:
```
bundle-2.6[279]: WARNING: Zeitwerk defines the constant CoreExt after the directory
bundle-2.6[279]:     /usr/share/webapps/redmine/vendor/bundle/ruby/2.6.0/bundler/gems/gitolite-rugged-4d24e45f97f9/lib/core_ext
bundle-2.6[279]: To prevent that, please configure the loader to ignore it:
bundle-2.6[279]:     loader.ignore("#{__dir__}/core_ext")
bundle-2.6[279]: Otherwise, there is a flag to silence this warning:
bundle-2.6[279]:     Zeitwerk::Loader.for_gem(warn_on_extra_files: false)
```

Environment:
```
Environment:
  Redmine version                4.2.7.stable
  Ruby version                   2.6.8-p205 (2021-07-07) [x86_64-linux]
  Rails version                  5.2.8
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.36.1
  Filesystem                     
  Xitolite                       2.36.1
Redmine plugins:
  additionals                    3.0.5.2
  redmine_auditlog               0.0.5
  redmine_git_hosting            5.0.1-master
  redmine_privacy_terms          1.0.4
  redmine_spent_time             4.1.0
```

In addition, when browsing redmine, I get this:
```
bundle-2.6[279]: EscapeUtils.escape_html is deprecated. Use GCI.escapeHTML instead, it's faster
```
Not sure where this is coming from, might be outside redmine_git_hosting

**Comment by picman** [comment]
I think that the origin of the problem is in Gemfile here. The problem is that neither redmine_git_hosting nor gitolite-rugged are compatible with Rails 6 (Zeitwerk).
```
# Gitolite Admin repository management
gem 'gitolite-rugged', git: 'https://github.com/jbox-web/gitolite-rugged.git', tag: '1.4.0'
```

**Comment by prahal** [comment]
@tomhub how comes your autoloader is zeitwerk with rails 5.2.8?
Zeitwerk is Rails 6.

Also you have
`  redmine_git_hosting            5.0.1-master`
the installation guide tells about checking out **5.0.0** in http://redmine-git-hosting.io/get_started/. Maybe you ended up with repository git master branch.


https://guides.rubyonrails.org/classic_to_zeitwerk_howto.html
From the very beginning, and up to Rails 5, Rails used an autoloader implemented in Active Support. This autoloader is known as classic and is still available in Rails 6.x. Rails 7 does not include this autoloader anymore.

Starting with Rails 6, Rails ships with a new and better way to autoload, which delegates to the [Zeitwerk](https://github.com/fxn/zeitwerk) gem. This is zeitwerk mode. By default, applications loading the 6.0 and 6.1 framework defaults run in zeitwerk mode, and this is the only mode available in Rails 7.

**Comment by tomhub** [comment]
I must have been using master branch, not 5.0.0. I will close this, as it seems development is moving forward to redmine 5 anyway.
