### ISSUE TITLE
error «Repository does not have "hooks.redmine_gitolite.key" set» (everything else works)

### ISSUE THREAD

**Issue by illwieckz** [jbox-web/redmine_git_hosting#92]
Hi, I get this strange message when pushing repository to gitolite:

> Repository does not have "hooks.redmine_gitolite.key" set. Skipping hook.

And redmine does not pull. However, everything seems to work

_**what works:**_

**redmine can sudo as gitolite and gitolite can sudo as redmine**

```
gitolite@myhost ~$ sudo -iu redmine "whoami"
redmine

redmine@myhost ~$ sudo -iu gitolite "whoami"
gitolite

redmine@myhost ~$ sudo -iu gitolite "sudo -iu redmine 'whoami'"
redmine
```

**redmine can write on gitolite repository (and does it)**

```
redmine@myhost ~$ ssh gitolite@myhost info
hello redmine, this is gitolite 2.3-1 (Debian) running on git 1.7.10.4
the gitolite config gives you the following access:
     R   W  gitolite-admin
```

**WEB Interface said me:**

on "Config Test" tab at https://myhost/redmine/settings/plugin/redmine_git_myhosting

> Required Permissions
> Git user is able to sudo to Redmine user? True
> Redmine user is able to sudo to Git user? True
> 
> PATH Directories
> /my/own/ruby/1.9.1/bin
> /usr/local/sbin
> /usr/local/bin
> /usr/sbin
> /usr/bin
> /sbin
> /bin
> 
> Gitolite Version : 2
> hello redmine, this is gitolite 2.3-1 (Debian) running on git 1.7.10.4
> 
> the gitolite config gives you the following access:
>     R   W     gitolite-admin

**Redmine push modifications**

If I create a repo and assign an user, the repo config and the user key is pushed to gitolite

If I pull gitolite-admin, I get what redmine has pushed.

**User push modifications**

An user created in redmine can push modification to Gitolite

_**What does'not works**_

If I pushed gitolite-admin (by example), I get that:

> remote: Repository does not have "hooks.redmine_gitolite.key" set. Skipping hook.

And redmine does not pull.

If I create a repo and assign an user, the user can push to gitolite, but I get that :

> remote: Repository does not have "hooks.redmine_gitolite.key" set. Skipping hook.

And redmine does not pull and said me "Repository is empty. Get started by following the instructions below."

If i do that:

```
gitolite@myhost:~ $ ~/.gitolite/hooks/common/post-receive
```

I get that.

> Repository does not have "hooks.redmine_gitolite.key" set. Skipping hook.

Is this a bug, or what I could forget?

Thanks for all you've done!

**Comment by psyclone241** [comment]
We recently updated to the latest version of this plugin. We had issues surrounding the renaming of all the keys for users, the application was keeping both the old format 'without redmine@' in the name. After deleting all the old keys and letting them regenerate, this was fixed.  Now we are experiencing the issue referred to in this article, however only on new repositories (new being since the updated plugin) we can push and pull successfully to all new repositories as well.  This message (Repository does not have "hooks.redmine_gitolite.key" set. Skipping hook) gets thrown up on screen upon pushing to a repository.
